<!DOCTYPE html>
<html lang="en"><head>
<link href="../../favicon.png" rel="icon" type="image/png">
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-bb62276ab45c84d9efd712f51ff97b5a.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.10.18">

  <meta name="author" content="Bill Perry">
  <meta name="dcterms.date" content="2026-10-09">
  <title>UMD DAta Science Biology – Lecture 11 — Linear Regression</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: 1.5em;}
    div.column{flex: auto;}
    @media screen {
    div.columns{gap: min(4vw, 1.5em);}
    div.column{overflow-x: auto;}
    }
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #24292e;  }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #24292e; } /* Normal */
    code span.al { color: #ff5555; font-weight: bold; } /* Alert */
    code span.an { color: #6a737d; } /* Annotation */
    code span.at { color: #d73a49; } /* Attribute */
    code span.bn { color: #005cc5; } /* BaseN */
    code span.bu { color: #d73a49; } /* BuiltIn */
    code span.cf { color: #d73a49; } /* ControlFlow */
    code span.ch { color: #032f62; } /* Char */
    code span.cn { color: #005cc5; } /* Constant */
    code span.co { color: #6a737d; } /* Comment */
    code span.cv { color: #6a737d; } /* CommentVar */
    code span.do { color: #6a737d; } /* Documentation */
    code span.dt { color: #d73a49; } /* DataType */
    code span.dv { color: #005cc5; } /* DecVal */
    code span.er { color: #ff5555; text-decoration: underline; } /* Error */
    code span.ex { color: #d73a49; font-weight: bold; } /* Extension */
    code span.fl { color: #005cc5; } /* Float */
    code span.fu { color: #6f42c1; } /* Function */
    code span.im { color: #032f62; } /* Import */
    code span.in { color: #6a737d; } /* Information */
    code span.kw { color: #d73a49; } /* Keyword */
    code span.op { color: #24292e; } /* Operator */
    code span.ot { color: #6f42c1; } /* Other */
    code span.pp { color: #d73a49; } /* Preprocessor */
    code span.re { color: #6a737d; } /* RegionMarker */
    code span.sc { color: #005cc5; } /* SpecialChar */
    code span.ss { color: #032f62; } /* SpecialString */
    code span.st { color: #032f62; } /* String */
    code span.va { color: #e36209; } /* Variable */
    code span.vs { color: #032f62; } /* VerbatimString */
    code span.wa { color: #ff5555; } /* Warning */
  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-dd7628516666e5f82eb94bcf304ed6a3.css">
  <link rel="stylesheet" href="../../css/main.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
<meta property="og:title" content="Lecture 11 — Linear Regression – UMD DAta Science Biology">
<meta property="og:description" content="Fitting a linear regression with lm(), reading the summary() output, checking the residuals, and using the slope to turn a tracing mass into a leaf area.">
<meta property="og:site_name" content="UMD DAta Science Biology">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Lecture 11 — Linear Regression</h1>
  <p class="subtitle">Using one measurement to predict another (Whitlock &amp; Schluter Ch. 17)</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Bill Perry
</div>
</div>
</div>

  <p class="date">2026-10-09</p>
</section>
<section id="where-we-left-off-lectures-0910" class="title-slide slide level1 center">
<h1>Where we left off (Lectures 09–10)</h1>
<ul>
<li><strong>Five steps</strong> — hypotheses → check normality → check variance → run the test → interpret and report</li>
<li><strong>Welch’s t-test</strong> compares the <strong>means of two groups</strong></li>
<li><strong>Pseudoreplication</strong> — average up to the thing you actually sampled before you test</li>
<li><strong>Our leaves</strong> — mean leaf <strong>mass</strong> did not differ between the shady and sunny sides</li>
<li><strong>Our sugar maples</strong> — shady-side leaves were significantly <strong>larger in area</strong> than sunny-side leaves on the same tree</li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ Where today comes in</strong></p>
<ul>
<li>A t-test compares two <strong>groups</strong>.</li>
<li>Today we ask a different question:
<ul>
<li>can one <strong>number</strong> predict another number?</li>
<li>we weighed our leaf tracings, but what we actually want is <strong>leaf area in cm²</strong></li>
</ul></li>
</ul>
</div>
</div>
</div>
</section>

<section id="goals-for-today" class="title-slide slide level1 center">
<h1>Goals for Today</h1>
<div class="columns">
<div class="column" style="width:60%;">
<ul>
<li><strong>Understand</strong> what a linear regression does: fit a straight line, <span class="math inline">\(\hat{Y} = a + bX\)</span></li>
<li><strong>See</strong> what a <strong>residual</strong> is, in a real plot</li>
<li><strong>Fit</strong> a model with <code>lm()</code></li>
<li><strong>Read and interpret</strong> the <code>summary()</code> output — slope, <em>p</em>-value, R²</li>
<li><strong>Check</strong> the residuals the way R shows them to you</li>
<li><strong>Use</strong> the slope to turn a tracing mass into a leaf area</li>
<li><strong>Report</strong> the result in a standard sentence</li>
</ul>
</div><div class="column" style="width:40%;">
<ul>
<li><strong>Tools today:</strong>
<ul>
<li><code>lm()</code> — fit the line</li>
<li><code>summary()</code> — read the result</li>
<li><code>plot(model)</code> — check the residuals</li>
<li>reading <code>7.660e-03</code> as 0.007660</li>
<li><code>geom_smooth(method = "lm")</code> — draw the line</li>
</ul></li>
<li><strong>Reading:</strong>
<ul>
<li>📖 Whitlock &amp; Schluter, Ch. 17 — <em>Regression</em>
<ul>
<li>§17.1 Linear regression</li>
<li>§17.3 Testing the slope</li>
<li>§17.4 R²</li>
<li>§17.5 Assumptions</li>
</ul></li>
</ul></li>
<li><strong>Today’s naming:</strong>
<ul>
<li>models → <code>_model</code></li>
<li>plots → <code>_plot</code></li>
</ul></li>
</ul>
</div></div>
</section>

<section id="chunk-1-of-3-what-regression-does" class="title-slide slide level1 center">
<h1>🧩 Chunk 1 of 3 · What Regression Does</h1>
<ul>
<li><p><strong>We will cover:</strong></p></li>
<li><p>the question regression answers,</p></li>
<li><p>the equation <span class="math inline">\(\hat{Y} = a + bX\)</span>,</p></li>
<li><p>what a <strong>residual</strong> is,</p></li>
<li><p>what <strong>R²</strong> tells you,</p></li>
<li><p>and the assumptions.</p></li>
<li><p>No code in this chunk — just the idea.</p></li>
</ul>
</section>

<section id="what-is-linear-regression" class="title-slide slide level1 center">
<h1>What Is Linear Regression?</h1>
<div class="columns">
<div class="column" style="width:58%;">
<p><strong>Linear regression</strong> fits the best straight line through a cloud of points so you can <strong>predict</strong> one number (Y) from another number (X).</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Role</th>
<th>Variable</th>
<th>On the plot</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Explanatory (X)</strong></td>
<td>what you can measure easily</td>
<td>x-axis</td>
</tr>
<tr class="even">
<td><strong>Response (Y)</strong></td>
<td>what you actually want to know</td>
<td>y-axis</td>
</tr>
</tbody>
</table>
<p>X is usually the <strong>easy</strong> measurement. Y is the <strong>expensive</strong> one. Regression gives you an equation that converts X into Y.</p>
<p>📖 W&amp;S §17.1 p.&nbsp;540–541</p>
</div><div class="column" style="width:42%;">
<p><strong>Regression vs.&nbsp;the t-test:</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Test</th>
<th>The question</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>t-test</td>
<td>Do two <strong>groups</strong> have different means?</td>
</tr>
<tr class="even">
<td>Regression</td>
<td>Does X <strong>predict</strong> Y?</td>
</tr>
</tbody>
</table>
<p><strong>Use regression when:</strong></p>
<ul>
<li>both variables are <strong>numeric</strong></li>
<li>X could reasonably predict Y</li>
<li>you want an <strong>equation</strong>, not just a yes/no</li>
</ul>
</div></div>
</section>

<section id="a-real-example-from-the-textbook" class="title-slide slide level1 center">
<h1>A Real Example from the Textbook</h1>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="regression_lecture_files/figure-revealjs/lion-scatter-1.png" alt="Scatter plot of lion age in years against the proportion of the nose that is black, for 32 lions, with an upward-sloping least-squares line through the points. The points scatter noticeably around the line."></p>
</figure>
</div>
</div>
</div>
<p><strong>W&amp;S Example 17.1 — “the lion’s nose.”</strong> 32 male lions of known age.</p>
</div><div class="column" style="width:45%;">
<p>Aging a wild lion is hard — you have to have watched it since it was a cub.</p>
<p>But a male lion’s nose <strong>darkens as it ages</strong>, and you can photograph a nose from a truck.</p>
<ul>
<li><strong>X</strong> = proportion of the nose that is black — <em>easy</em></li>
<li><strong>Y</strong> = age in years — <em>what you want</em></li>
</ul>
<p>Fit the line once on lions of known age, and from then on you can <strong>estimate</strong> a lion’s age from a photograph.</p>
<p>📖 W&amp;S §17.1, Example 17.1</p>
</div></div>
</section>

<section id="our-version-of-the-same-problem" class="title-slide slide level1 center scrollable">
<h1>Our Version of the Same Problem</h1>
<div class="columns">
<div class="column" style="width:58%;">
<p><strong>The problem:</strong> we want <strong>leaf area in cm²</strong>, but we don’t have a leaf-area meter. We have a balance.</p>
<p><strong>The fix — a calibration curve:</strong></p>
<ol type="1">
<li>Cut paper squares of <strong>known area</strong> (1, 4, 16 … 567 cm²)</li>
<li><strong>Weigh</strong> each square</li>
<li>Fit the line: <strong>area ~ mass</strong></li>
<li>Trace a leaf onto the <strong>same paper</strong> and weigh the tracing</li>
<li>Put the tracing mass into the equation → <strong>predicted leaf area</strong></li>
</ol>
<p><strong>Why it works:</strong> paper from one stock has a constant <strong>area per gram</strong>, so mass and area move together almost perfectly.</p>
</div><div class="column" style="width:42%;">
<table class="caption-top">
<thead>
<tr class="header">
<th>Known area (cm²)</th>
<th>Squares weighed</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>25</td>
</tr>
<tr class="even">
<td>4</td>
<td>32</td>
</tr>
<tr class="odd">
<td>16</td>
<td>24</td>
</tr>
<tr class="even">
<td>36</td>
<td>3</td>
</tr>
<tr class="odd">
<td>64</td>
<td>7</td>
</tr>
<tr class="even">
<td>100</td>
<td>14</td>
</tr>
<tr class="odd">
<td>225–567</td>
<td>13</td>
</tr>
</tbody>
</table>
<p><strong>118 paper squares in all.</strong></p>
<p>Remember <code>paper_mass_g</code> in our leaf data? That is the tracing mass. By the end of today it becomes an <strong>area</strong>.</p>
</div></div>
</section>

<section id="the-regression-equation" class="title-slide slide level1 center">
<h1>The Regression Equation</h1>
<div class="columns">
<div class="column" style="width:55%;">
<p><span class="math display">\[\hat{Y} = a + bX\]</span></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Symbol</th>
<th>Name</th>
<th>What it means</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\hat{Y}\)</span></td>
<td>predicted Y</td>
<td>what the line says Y should be</td>
</tr>
<tr class="even">
<td><em>a</em></td>
<td><strong>intercept</strong></td>
<td>Y when X = 0 — where the line crosses</td>
</tr>
<tr class="odd">
<td><em>b</em></td>
<td><strong>slope</strong></td>
<td>how much Y changes per 1 unit of X</td>
</tr>
</tbody>
</table>
<p><strong>Ours will read:</strong></p>
<p><span class="math display">\[\widehat{\text{area}} = a + b \times \text{mass}\]</span></p>
<p>📖 W&amp;S §17.1 pp.&nbsp;543–545</p>
</div><div class="column" style="width:45%;">
<p><strong>The slope is the useful one.</strong></p>
<blockquote>
<p><em>b</em> = the extra cm² you get for each extra gram of paper</p>
</blockquote>
<p>That is just the <strong>area density</strong> of the paper stock — and it is the number that does the converting.</p>
<p><strong>The intercept is a bookkeeping number.</strong></p>
<blockquote>
<p><em>a</em> = the predicted area of a piece of paper weighing nothing</p>
</blockquote>
<p>Physically that should be 0. A small value near zero is fine; it is measurement noise, not biology.</p>
</div></div>
</section>

<section id="what-is-a-residual" class="title-slide slide level1 center">
<h1>What Is a Residual?</h1>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="regression_lecture_files/figure-revealjs/lion-residuals-1.png" alt="The same lion scatter plot with the least-squares line, plus a vertical red segment drawn from every point to the line. Segments above the line are longer for a few lions; most are short. The plot shows the residual as the vertical gap between the observed point and the line."></p>
</figure>
</div>
</div>
</div>
<p><strong>Red = the residuals</strong> for the lion data.</p>
</div><div class="column" style="width:45%;">
<p>A <strong>residual</strong> is one point’s miss:</p>
<p><span class="math display">\[\text{residual} = \text{observed} - \text{predicted}\]</span></p>
<ul>
<li>A point <strong>above</strong> the line → <strong>positive</strong> residual (that lion was older than its nose suggested)</li>
<li>A point <strong>below</strong> the line → <strong>negative</strong> residual</li>
<li>A point <strong>on</strong> the line → residual of 0</li>
</ul>
<p><strong>The line R gives you is the one that makes those red segments as small as possible overall.</strong> That is all “least squares” means — and R does the work.</p>
<p>📖 W&amp;S §17.1 p.&nbsp;542</p>
</div></div>
</section>

<section id="r²-how-tight-is-the-fit" class="title-slide slide level1 center">
<h1>R² — How Tight Is the Fit?</h1>
<div class="columns">
<div class="column" style="width:62%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="regression_lecture_files/figure-revealjs/r2-comparison-1.png" alt="Two scatter plots side by side. Left: lion age against nose blackness with a fitted line and clearly scattered points, labelled R-squared equals 0.62. Right: paper area against paper mass with a fitted line and points sitting almost exactly on it, labelled R-squared equals 0.9999."></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:38%;">
<p><strong>R² runs from 0 to 1.</strong> It is the fraction of the variation in Y that the line accounts for.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>R²</th>
<th>Reads as</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1.00</td>
<td>points sit <strong>on</strong> the line</td>
</tr>
<tr class="even">
<td>0.62</td>
<td>X explains <strong>62%</strong> of the variation</td>
</tr>
<tr class="odd">
<td>0.00</td>
<td>the line tells you nothing</td>
</tr>
</tbody>
</table>
<p><strong>Both of these are good regressions.</strong> Nose blackness really does predict a lion’s age — just with scatter, because lions vary. Paper is manufactured to be uniform, so it has almost none.</p>
<p>In biology, <strong>R² of 0.3–0.7 is normal and useful</strong>. Don’t expect 0.99.</p>
<p>📖 W&amp;S §17.4 p.&nbsp;555</p>
</div></div>
</section>

<section id="r²-and-the-p-value-answer-different-questions" class="title-slide slide level1 center">
<h1>R² and the <em>p</em>-value Answer Different Questions</h1>
<div class="columns">
<div class="column" style="width:52%;">
<table class="caption-top">
<colgroup>
<col style="width: 34%">
<col style="width: 65%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>The question it answers</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong><em>p</em>-value</strong></td>
<td>Is there <strong>really</strong> a relationship, or could this slope be chance?</td>
</tr>
<tr class="even">
<td><strong>R²</strong></td>
<td><strong>How tightly</strong> do the points follow the line?</td>
</tr>
</tbody>
</table>
<p>You can have a <strong>significant slope with a low R²</strong> — a real relationship with a lot of scatter. That is most of ecology.</p>
</div><div class="column" style="width:48%;">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>The slope is the hypothesis test.</strong></p>
<p><strong>H₀:</strong> the slope is 0 — X does not predict Y</p>
<p><strong>Hₐ:</strong> the slope is not 0 — X does predict Y</p>
<p><code>summary()</code> gives you the <em>p</em>-value for exactly that test, and we will find it on the next few slides.</p>
</div>
</div>
</div>
<p>📖 W&amp;S §17.3 pp.&nbsp;551–553</p>
</div></div>
</section>

<section id="assumptions-of-regression" class="title-slide slide level1 center">
<h1>Assumptions of Regression</h1>
<div class="columns">
<div class="column" style="width:58%;">
<p>Four things need to be roughly true for the <em>p</em>-value and the intervals to mean anything (W&amp;S §17.5):</p>
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 40%">
<col style="width: 34%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Assumption</th>
<th>How you check it</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td><strong>Linear</strong> — Y really does follow a straight line</td>
<td>the scatter plot, then <code>plot(model)</code> panel 1</td>
</tr>
<tr class="even">
<td>2</td>
<td><strong>Independent</strong> — one observation doesn’t depend on another</td>
<td>your study design</td>
</tr>
<tr class="odd">
<td>3</td>
<td><strong>Equal variance</strong> — the scatter is about the same all the way along</td>
<td><code>plot(model)</code> panels 1 and 3</td>
</tr>
<tr class="even">
<td>4</td>
<td><strong>Normal residuals</strong> — the misses are bell-shaped</td>
<td><code>plot(model)</code> panel 2</td>
</tr>
</tbody>
</table>
</div><div class="column" style="width:42%;">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>Check the residuals, not the raw data.</strong></p>
<p>Normality here is about the <strong>misses</strong> — the red segments — not about Y itself. Y is <em>supposed</em> to go up with X; of course it isn’t bell-shaped.</p>
<p>The good news: once you have a fitted model, <code>plot()</code> draws all of these for you. No extra code.</p>
</div>
</div>
</div>
<p>Same habit as the t-test: <strong>check → decide → report.</strong></p>
<p>📖 W&amp;S §17.5 pp.&nbsp;557–560</p>
</div></div>
</section>

<section id="chunk-2-of-3-fit-it-and-read-it" class="title-slide slide level1 center">
<h1>🧩 Chunk 2 of 3 · Fit It and Read It</h1>
<p><strong>We will cover:</strong> loading the paper data, the scatter plot, fitting with <code>lm()</code>, and reading the <code>summary()</code> output line by line.</p>
<div class="activitybanner">
<p><strong>🛑 After this chunk: Activity Parts 1–3</strong> (the study, load, plot, fit, read the summary).</p>
</div>
</section>

<section id="load-libraries-and-data" class="title-slide slide level1 center">
<h1>Load Libraries and Data</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a aria-label="1"></a><span class="co"># Load packages at the top ------------------------------</span></span>
<span id="cb1-2"><a aria-label="2"></a><span class="fu">library</span>(readxl) <span class="co"># read Excel files</span></span>
<span id="cb1-3"><a aria-label="3"></a><span class="fu">library</span>(tidyverse) <span class="co"># dplyr + ggplot2</span></span>
<span id="cb1-4"><a aria-label="4"></a><span class="fu">library</span>(janitor) <span class="co"># clean_names()</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a aria-label="1"></a><span class="co"># Load the paper calibration data ----------------------</span></span>
<span id="cb2-2"><a aria-label="2"></a>paper_df <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"data/paper_area_weights.xlsx"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Two columns, 118 rows: <code>area_cm2</code> is the <strong>known</strong> area of each square, <code>mass_g</code> is what it weighed.</p>
</section>

<section id="always-plot-it-first" class="title-slide slide level1 center">
<h1>Always Plot It First</h1>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a aria-label="1"></a><span class="co"># Scatter plot of mass against known area --------------</span></span>
<span id="cb3-2"><a aria-label="2"></a>scatter_plot <span class="ot">&lt;-</span> paper_df <span class="sc">%&gt;%</span></span>
<span id="cb3-3"><a aria-label="3"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> area_cm2, <span class="at">y =</span> mass_g)) <span class="sc">+</span></span>
<span id="cb3-4"><a aria-label="4"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb3-5"><a aria-label="5"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>)</span>
<span id="cb3-6"><a aria-label="6"></a>scatter_plot</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="regression_lecture_files/figure-revealjs/scatter-11-1.png" alt="Scatter plot of paper mass in grams against known paper area in square centimetres. The points form a tight straight line rising from the bottom left to the top right."></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:45%;">
<p><strong>Three plain lines.</strong> <code>aes(x = , y = )</code> puts the variable you <strong>set</strong> on x and the one you <strong>measured</strong> on y, and <code>geom_point()</code> draws the dots.</p>
<p><strong>What you are looking for:</strong></p>
<ul>
<li><strong>Straight?</strong> → a line is the right tool</li>
<li><strong>Scatter the same all the way along?</strong></li>
<li><strong>Any point way off on its own?</strong></li>
</ul>
<p>Here: straight, tight, nothing strange. Fit the line.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Never fit a regression you haven’t looked at. A curve, a funnel, or one wild point all change what you should do next.</p>
</div>
</div>
</div>
</div></div>
</section>

<section id="fit-the-model-with-lm" class="title-slide slide level1 center">
<h1>Fit the Model with <code>lm()</code></h1>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a aria-label="1"></a><span class="co"># Fit the regression line ------------------------------</span></span>
<span id="cb4-2"><a aria-label="2"></a>paper_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(mass_g <span class="sc">~</span> area_cm2, <span class="at">data =</span> paper_df)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Nothing prints. <code>lm()</code> hands back a <strong>model object</strong> that is holding the answer — <code>summary()</code> is what shows it to you.</p>
</div><div class="column" style="width:45%;">
<p><strong>The formula is the whole trick:</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a aria-label="1"></a><span class="fu">lm</span>(Y <span class="sc">~</span> X, <span class="at">data =</span> df)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li><strong>Y</strong> — the response — goes on the <strong>left</strong> of <code>~</code></li>
<li><strong>X</strong> — the explanatory variable — goes on the <strong>right</strong></li>
<li><code>~</code> reads as <strong>“is predicted by”</strong></li>
</ul>
<p>So <code>mass_g ~ area_cm2</code> is “mass is predicted by area.”</p>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p><strong>⚠️ Which way round?</strong> We <strong>cut</strong> the areas and <strong>measured</strong> the masses, so <strong>mass</strong> is the response. <code>lm(area_cm2 ~ mass_g)</code> runs fine too — it just asks R to treat ten areas we chose on purpose as if they were the noisy measurement.</p>
</div>
</div>
</div>
</div></div>
</section>

<section id="summary-the-whole-output" class="title-slide slide level1 center scrollable">
<h1><code>summary()</code> — the Whole Output</h1>
<div class="cell columns column-output-location">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a aria-label="1"></a><span class="co"># Read the model ---------------------------------------</span></span>
<span id="cb6-2"><a aria-label="2"></a><span class="fu">summary</span>(paper_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mass_g ~ area_cm2, data = paper_df)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.066548 -0.001774  0.000907  0.002267  0.056127 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -2.058e-03  1.389e-03  -1.481    0.141    
area_cm2     7.660e-03  8.646e-06 885.964   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.01351 on 116 degrees of freedom
Multiple R-squared:  0.9999,    Adjusted R-squared:  0.9999 
F-statistic: 7.849e+05 on 1 and 116 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div></div>
<p>There are only <strong>four numbers</strong> in here that you need, and we will take them one at a time:</p>
<ol type="1">
<li>the <strong>slope</strong> (<code>area_cm2</code> → <code>Estimate</code>)</li>
<li>the <strong>intercept</strong> (<code>(Intercept)</code> → <code>Estimate</code>)</li>
<li>the slope’s <strong><em>p</em>-value</strong> (<code>area_cm2</code> → <code>Pr(&gt;|t|)</code>)</li>
<li>the <strong>R²</strong> (<code>Multiple R-squared</code>)</li>
</ol>
</section>

<section id="reading-it-1.-the-coefficients-table" class="title-slide slide level1 center">
<h1>Reading It — 1. The Coefficients Table</h1>
<div class="columns">
<div class="column" style="width:52%;">
<pre><code>Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)
(Intercept) -2.058e-03  1.389e-03  -1.481    0.141
area_cm2     7.660e-03  8.646e-06 885.964   &lt;2e-16</code></pre>
<p><strong>The <code>Estimate</code> column is the equation.</strong></p>
<ul>
<li><code>(Intercept)</code> = <strong>-0.002058</strong> → that is <em>a</em></li>
<li><code>area_cm2</code> = <strong>0.007660</strong> → that is <em>b</em>, the slope</li>
</ul>
<p><strong><code>7.660e-03</code> means 7.660 × 10⁻³</strong> — move the decimal point three places left.</p>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>Prefer plain decimals? <code>options(scipen = 999)</code> turns scientific notation off and <code>options(scipen = 0)</code> turns it back on. We leave it on — with it off, <em>p</em> prints as <code>&lt;0.0000000000000002</code>.</p>
</div>
</div>
</div>
<p>So the fitted line is:</p>
<p><span class="math display">\[\widehat{\text{mass}} = -0.0021 + 0.00766 \times \text{area}\]</span></p>
</div><div class="column" style="width:48%;">
<p><strong>Say the slope out loud, with units:</strong></p>
<blockquote>
<p>Every extra <strong>1 cm²</strong> of this paper weighs another <strong>0.00766 g</strong>.</p>
</blockquote>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>×10,000 → 76.6 g/m²</strong> — the paper’s <strong>grammage</strong>, the number on the side of the ream. Copy paper is sold at 75–80 g/m², so the slope is a property you can go and check.</p>
</div>
</div>
</div>
<p><strong>The other three columns, in one line each:</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Column</th>
<th>What it is</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>Std. Error</code></td>
<td>how uncertain that estimate is</td>
</tr>
<tr class="even">
<td><code>t value</code></td>
<td>Estimate ÷ Std. Error</td>
</tr>
<tr class="odd">
<td><code>Pr(&gt;|t|)</code></td>
<td>the <strong><em>p</em>-value</strong> for that row</td>
</tr>
</tbody>
</table>
<p>📖 W&amp;S §17.3 p.&nbsp;551</p>
</div></div>
</section>

<section id="reading-it-2.-the-two-p-values" class="title-slide slide level1 center">
<h1>Reading It — 2. The Two <em>p</em>-Values</h1>
<div class="columns">
<div class="column" style="width:52%;">
<pre><code>(Intercept) -2.058e-03  ...   0.141
area_cm2     7.660e-03  ...  &lt;2e-16</code></pre>
<p><strong>The slope row is the one that matters.</strong> <code>Pr(&gt;|t|)</code> for <code>area_cm2</code> is <code>&lt;2e-16</code> — R’s way of writing “smaller than I can print.”</p>
<ul>
<li><strong>H₀:</strong> the slope is 0 → area tells you nothing about mass</li>
<li><em>p</em> &lt; 0.001 → <strong>reject H₀</strong>. Area predicts mass.</li>
</ul>
<p><strong>The intercept row:</strong> <em>p</em> = 0.141, so the intercept is <strong>not</strong> distinguishable from 0 — exactly what physics says it should be. A piece of paper with no area has no mass.</p>
</div><div class="column" style="width:48%;">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>Which <em>p</em>-value do I report?</strong></p>
<p>The <strong>slope’s</strong>. That is the biological question. Nobody reports the intercept’s <em>p</em>-value unless zero means something special.</p>
</div>
</div>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>Never write <em>p</em> = 0.</strong> When R prints <code>&lt;2e-16</code>, you write <strong><em>p</em></strong> <strong>&lt; 0.001</strong>.</p>
</div>
</div>
</div>
</div></div>
</section>

<section id="reading-it-3.-r²-and-the-bottom-line" class="title-slide slide level1 center">
<h1>Reading It — 3. R² and the Bottom Line</h1>
<div class="columns">
<div class="column" style="width:52%;">
<pre><code>Residual standard error: 0.01351 on 116 degrees of freedom
Multiple R-squared:  0.9999, Adjusted R-squared:  0.9999
F-statistic: 7.849e+05 on 1 and 116 DF,  p-value: &lt; 2.2e-16</code></pre>
<ul>
<li><strong>Multiple R-squared = 0.9999</strong> → area explains <strong>99.99%</strong> of the variation in mass. That is manufactured paper, not biology.</li>
<li><strong>F-statistic</strong> with <strong>1 and 116 DF</strong>, <em>p</em> &lt; 2.2e-16 → the overall test of the model. With one X it tells you the same thing as the slope’s <em>p</em>-value.</li>
<li><strong>Residual standard error = 0.0135 g</strong> → a typical miss is about 13 mg.</li>
</ul>
</div><div class="column" style="width:48%;">
<p><strong>Where the df come from:</strong></p>
<ul>
<li><strong>1</strong> = one explanatory variable</li>
<li><strong>116</strong> = 118 squares − 2 numbers we estimated (<em>a</em> and <em>b</em>)</li>
</ul>
<p><strong>Use <code>Adjusted R-squared</code></strong> once you have more than one X; with a single X, report <code>Multiple R-squared</code>.</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>R² = 0.9999 does not mean “everything is fine.”</strong> It means the points are close to the line. Whether the <em>assumptions</em> hold is a separate question — and we check it two slides from now.</p>
</div>
</div>
</div>
</div></div>
</section>

<section id="activity-11-parts-13-now" class="title-slide slide level1 center">
<h1>→ ACTIVITY 11 Parts 1–3 now</h1>
<div class="activitybanner">
<p><strong>🛑 Do Activity Parts 1–3 now</strong></p>
<p>Load the paper data, make the scatter plot, fit <code>lm(mass_g ~ area_cm2)</code>, and read the slope, the <em>p</em>-value and R² <strong>off the summary output</strong>.</p>
</div>
</section>

<section id="chunk-3-of-3-plot-it-check-it-use-it" class="title-slide slide level1 center">
<h1>🧩 Chunk 3 of 3 · Plot It, Check It, Use It</h1>
<p><strong>We will cover:</strong> drawing the fitted line, reading <code>plot(model)</code>, converting the whole column of tracings, averaging away the pseudoreplication, and the paired <em>t</em>-tests.</p>
<div class="activitybanner">
<p><strong>🛑 After this chunk: Activity Parts 4–7</strong> (check the residuals, convert, average, paired <em>t</em>-tests).</p>
</div>
</section>

<section id="draw-the-line" class="title-slide slide level1 center">
<h1>Draw the Line</h1>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a aria-label="1"></a><span class="co"># Scatter plot with the fitted line --------------------</span></span>
<span id="cb11-2"><a aria-label="2"></a>calibration_plot <span class="ot">&lt;-</span> paper_df <span class="sc">%&gt;%</span></span>
<span id="cb11-3"><a aria-label="3"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> area_cm2, <span class="at">y =</span> mass_g)) <span class="sc">+</span></span>
<span id="cb11-4"><a aria-label="4"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb11-5"><a aria-label="5"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>)</span>
<span id="cb11-6"><a aria-label="6"></a>calibration_plot</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="regression_lecture_files/figure-revealjs/calibration-plain-11-1.png" alt="Scatter plot of paper mass against known paper area with a straight fitted regression line and a narrow grey confidence band through the points."></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:45%;">
<p><strong>One extra line.</strong> <code>geom_smooth(method = "lm")</code> fits the same regression again, just for drawing, and adds:</p>
<ul>
<li>the <strong>fitted line</strong></li>
<li>a grey <strong>95% confidence band</strong> around it</li>
</ul>
<p><strong>The band is narrowest in the middle</strong> of the data and flares at the ends — the line is pinned down best where you have the most data. Here it is so narrow you can barely see it.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><code>geom_smooth()</code> defaults to a wiggly curve. <strong><code>method = "lm"</code> is what makes it a straight regression line.</strong></p>
</div>
</div>
</div>
</div></div>
</section>

<section id="the-same-plot-dressed-up" class="title-slide slide level1 center">
<h1>The Same Plot, Dressed Up</h1>
<div class="columns">
<div class="column" style="width:55%;">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a aria-label="1"></a><span class="co"># The publication version — for reference ---------------</span></span>
<span id="cb12-2"><a aria-label="2"></a>calibration_plot <span class="ot">&lt;-</span> paper_df <span class="sc">%&gt;%</span></span>
<span id="cb12-3"><a aria-label="3"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> area_cm2, <span class="at">y =</span> mass_g)) <span class="sc">+</span></span>
<span id="cb12-4"><a aria-label="4"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb12-5"><a aria-label="5"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>) <span class="sc">+</span></span>
<span id="cb12-6"><a aria-label="6"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Paper area (cm²)"</span>,</span>
<span id="cb12-7"><a aria-label="7"></a>       <span class="at">y =</span> <span class="st">"Paper mass (g)"</span>) <span class="sc">+</span></span>
<span id="cb12-8"><a aria-label="8"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb12-9"><a aria-label="9"></a>calibration_plot</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="regression_lecture_files/figure-revealjs/calibration-dressed-11-1.png" alt="The same paper calibration scatter plot with the fitted line, now with axis labels reading Paper area in square centimetres and Paper mass in grams, on a minimal theme."></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:45%;">
<p><strong>This is the version you’d put in a report</strong> — and it is only two additions to the plot you already made:</p>
<ul>
<li><code>labs()</code> — real axis labels with units</li>
<li><code>theme_minimal()</code> — drop the grey background</li>
</ul>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>Don’t type this today.</strong> Get the plain <code>geom_point() + geom_smooth(method = "lm")</code> working first. Labels and themes are the last thing you add, once you know the plot is right.</p>
</div>
</div>
</div>
</div></div>
</section>

<section id="check-the-residuals-plotmodel" class="title-slide slide level1 center">
<h1>Check the Residuals — <code>plot(model)</code></h1>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a aria-label="1"></a><span class="co"># All four residual plots in one call ------------------</span></span>
<span id="cb13-2"><a aria-label="2"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb13-3"><a aria-label="3"></a><span class="fu">plot</span>(paper_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="regression_lecture_files/figure-revealjs/diagnostic-plots-11-1.png" alt="Four base R diagnostic plots for the paper calibration model in a two by two grid: residuals versus fitted values showing a clear funnel that widens to the right, a normal Q-Q plot with points curving away at both ends, a scale-location plot rising to the right, and residuals versus leverage."></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<p><code>par(mfrow = c(2, 2))</code> just says “put the next four plots in a 2×2 grid.”</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Panel</th>
<th>Name</th>
<th>Checks</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Residuals vs Fitted</td>
<td>linear? equal scatter?</td>
</tr>
<tr class="even">
<td>2</td>
<td>Normal Q-Q</td>
<td>residuals bell-shaped?</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Scale-Location</td>
<td>equal scatter again</td>
</tr>
<tr class="even">
<td>4</td>
<td>Residuals vs Leverage</td>
<td>any one point running the show</td>
</tr>
</tbody>
</table>
<p><strong>Panel 1 is the one to look at first.</strong></p>
<ul>
<li>✅ <strong>Good:</strong> a flat, shapeless cloud around 0</li>
<li>❌ <strong>Curved:</strong> the relationship isn’t straight</li>
<li>❌ <strong>Funnel:</strong> the scatter grows as Y grows</li>
</ul>
</div></div>
</section>

<section id="what-our-residual-plot-is-telling-us" class="title-slide slide level1 center">
<h1>What Our Residual Plot Is Telling Us</h1>
<div class="columns">
<div class="column" style="width:52%;">
<p>Look at panel 1 again. The points <strong>fan out</strong> — a 1 cm² square misses by hundredths of a cm², a 567 cm² square misses by several cm².</p>
<p>That is a <strong>funnel</strong>: assumption 3 (equal variance) does not hold.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a aria-label="1"></a><span class="co"># How big are the misses at each square size? ---------</span></span>
<span id="cb14-2"><a aria-label="2"></a>paper_df <span class="sc">%&gt;%</span></span>
<span id="cb14-3"><a aria-label="3"></a>  <span class="fu">mutate</span>(<span class="at">residual =</span> <span class="fu">residuals</span>(paper_model)) <span class="sc">%&gt;%</span></span>
<span id="cb14-4"><a aria-label="4"></a>  <span class="fu">group_by</span>(area_cm2) <span class="sc">%&gt;%</span></span>
<span id="cb14-5"><a aria-label="5"></a>  <span class="fu">summarize</span>(<span class="at">biggest_miss =</span> <span class="fu">round</span>(<span class="fu">max</span>(<span class="fu">abs</span>(residual)), <span class="dv">2</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 2
   area_cm2 biggest_miss
      &lt;dbl&gt;        &lt;dbl&gt;
 1        1         0   
 2        4         0   
 3       16         0   
 4       36         0.01
 5       64         0.01
 6      100         0.02
 7      225         0.02
 8      400         0.06
 9      500         0.06
10      567         0.07</code></pre>
</div>
</div>
</div><div class="column" style="width:48%;">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>A great R² and a bad residual plot can live together.</strong> R² says the points are near the line. The residual plot says the <em>size of the miss</em> depends on how big the square is — which it does, because a balance has percentage error, not fixed error.</p>
</div>
</div>
</div>
<p><strong>So what do we do?</strong></p>
<ul>
<li>For <strong>predicting a leaf tracing</strong> (0.1–0.4 g) we are down in the tight end of the line, where a typical miss is a fraction of a cm². The calibration is fine for the job.</li>
<li>The <strong>confidence intervals</strong> at the big-square end are the part you shouldn’t trust.</li>
<li>The proper fix — fitting on a log scale, or weighting the points — is a <strong>graduate</strong> topic. Knowing to look, and saying what you saw, is the undergraduate job.</li>
</ul>
</div></div>
</section>

<section id="from-tracing-mass-to-leaf-area" class="title-slide slide level1 center">
<h1>From Tracing Mass to Leaf Area</h1>
<div class="columns">
<div class="column" style="width:52%;">
<p>The model says</p>
<p><span class="math display">\[\text{mass} = a + b \times \text{area}\]</span></p>
<p>We have the <strong>mass</strong> and want the <strong>area</strong>, so rearrange:</p>
<p><span class="math display">\[\text{area} = \frac{\text{mass} - a}{b}\]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a aria-label="1"></a><span class="co"># Typed off the summary(), out of sci notation --------</span></span>
<span id="cb16-2"><a aria-label="2"></a>intercept <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">0.002058</span>   <span class="co"># from -2.058e-03</span></span>
<span id="cb16-3"><a aria-label="3"></a>slope     <span class="ot">&lt;-</span>  <span class="fl">0.007660</span>   <span class="co"># from  7.660e-03</span></span>
<span id="cb16-4"><a aria-label="4"></a></span>
<span id="cb16-5"><a aria-label="5"></a><span class="co"># 1 m2 = 10000 cm2</span></span>
<span id="cb16-6"><a aria-label="6"></a>slope <span class="sc">*</span> <span class="dv">10000</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 76.6</code></pre>
</div>
</div>
</div><div class="column" style="width:48%;">
<ul>
<li><strong>Type the two numbers in.</strong> They are right there in the Coefficients table, and the arithmetic stays in plain sight</li>
<li>Rounding to six decimals changes <strong>nothing</strong> — same <em>t</em>, df and <em>p</em> at the end</li>
<li>Or let R hand them to you: <strong><code>coef(paper_model)</code></strong>, then <code>[1]</code> and <code>[2]</code> — and it prints plain decimals</li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>×10,000 → 76.6 g/m²</strong> — the paper’s <strong>grammage</strong>, the number on the side of the ream. Copy paper is sold at 75–80 g/m², so the slope is a property you can <strong>check against the label</strong>.</p>
</div>
</div>
</div>
<p>A tracing weighing 0.138 g is</p>
<p><span class="math display">\[\frac{0.138 - (-0.002058)}{0.007660} = 18.3 \text{ cm}^2\]</span></p>
</div></div>
</section>

<section id="convert-a-whole-column-of-tracings" class="title-slide slide level1 center">
<h1>Convert a Whole Column of Tracings</h1>
<div class="columns">
<div class="column" style="width:58%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a aria-label="1"></a><span class="co"># Load our leaf data ----------------------------------</span></span>
<span id="cb18-2"><a aria-label="2"></a>leaf_df <span class="ot">&lt;-</span></span>
<span id="cb18-3"><a aria-label="3"></a>  <span class="fu">read_excel</span>(<span class="st">"data/2026_09_03_data_sci_leaf_area.xlsx"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb18-4"><a aria-label="4"></a>  <span class="fu">clean_names</span>()</span>
<span id="cb18-5"><a aria-label="5"></a></span>
<span id="cb18-6"><a aria-label="6"></a><span class="co"># Every tracing mass becomes an area ------------------</span></span>
<span id="cb18-7"><a aria-label="7"></a>leaf_df <span class="ot">&lt;-</span> leaf_df <span class="sc">%&gt;%</span></span>
<span id="cb18-8"><a aria-label="8"></a>  <span class="fu">mutate</span>(<span class="at">area_cm2 =</span> (paper_mass_g <span class="sc">-</span> intercept) <span class="sc">/</span> slope)</span>
<span id="cb18-9"><a aria-label="9"></a></span>
<span id="cb18-10"><a aria-label="10"></a>leaf_df <span class="sc">%&gt;%</span></span>
<span id="cb18-11"><a aria-label="11"></a>  <span class="fu">select</span>(teams, shade, mass_g, paper_mass_g, area_cm2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 53 × 5
   teams shade mass_g paper_mass_g area_cm2
   &lt;chr&gt; &lt;chr&gt;  &lt;dbl&gt;        &lt;dbl&gt;    &lt;dbl&gt;
 1 12345 sunny   0.4          0.21     27.7
 2 12345 sunny   0.48         0.21     27.7
 3 12345 sunny   0.34         0.21     27.7
 4 12345 sunny   0.65         0.24     31.6
 5 12345 sunny   0.27         0.15     19.9
 6 12345 sunny   0.43         0.34     44.7
 7 12345 shady   0.39         0.29     38.1
 8 12345 shady   0.45         0.25     32.9
 9 12345 shady   0.6          0.23     30.3
10 12345 shady   0.57         0.28     36.8
# ℹ 43 more rows</code></pre>
</div>
</div>
</div><div class="column" style="width:42%;">
<p><strong>This is the payoff.</strong> <code>paper_mass_g</code> was the mass of each leaf’s tracing — now every leaf has an <strong><code>area_cm2</code></strong>.</p>
<ul>
<li>One line of arithmetic, all 53 rows at once</li>
<li>No new function to learn</li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>The <code>NA</code>s are honest.</strong> One team never weighed their tracings, so those leaves have no area. R keeps the gap instead of inventing a number.</p>
</div>
</div>
</div>
</div></div>
</section>

<section id="one-value-per-team-per-side" class="title-slide slide level1 center">
<h1>One Value per Team per Side</h1>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a aria-label="1"></a><span class="co"># Average away the pseudoreplication ------------------</span></span>
<span id="cb20-2"><a aria-label="2"></a>team_df <span class="ot">&lt;-</span> leaf_df <span class="sc">%&gt;%</span></span>
<span id="cb20-3"><a aria-label="3"></a>  <span class="fu">group_by</span>(teams, shade) <span class="sc">%&gt;%</span></span>
<span id="cb20-4"><a aria-label="4"></a>  <span class="fu">summarize</span>(<span class="at">area_cm2 =</span> <span class="fu">mean</span>(area_cm2, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb20-5"><a aria-label="5"></a>            <span class="at">mass_g   =</span> <span class="fu">mean</span>(mass_g,   <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb20-6"><a aria-label="6"></a>            <span class="at">.groups  =</span> <span class="st">"drop"</span>)</span>
<span id="cb20-7"><a aria-label="7"></a></span>
<span id="cb20-8"><a aria-label="8"></a>team_df</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 4
   teams              shade area_cm2 mass_g
   &lt;chr&gt;              &lt;chr&gt;    &lt;dbl&gt;  &lt;dbl&gt;
 1 12345              shady     34.0  0.448
 2 12345              sunny     29.9  0.428
 3 Oscar_Karl         shady    NaN    0.400
 4 Oscar_Karl         sunny    NaN    0.339
 5 fighting_mongooses shady     35.7  0.653
 6 fighting_mongooses sunny     32.2  0.544
 7 leaf_oglers        shady     36.3  0.588
 8 leaf_oglers        sunny     37.4  0.599
 9 still_loading      shady     42.5  0.526
10 still_loading      sunny     53.7  0.789</code></pre>
</div>
</div>
</div><div class="column" style="width:45%;">
<ul>
<li>Six leaves off one branch are <strong>not six independent measurements</strong></li>
<li>Using all 53 is <strong>pseudoreplication</strong> — it makes <em>p</em> look better than the study earned</li>
<li>Averaging gives each team <strong>one</strong> sunny and <strong>one</strong> shady value</li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>You met this in T-Tests II. Same tree, same pairing — now in <strong>cm²</strong> instead of grams.</p>
</div>
</div>
</div>
</div></div>
</section>

<section id="paired-t-tests-on-area-and-mass" class="title-slide slide level1 center">
<h1>Paired <em>t</em>-Tests on Area and Mass</h1>
<div class="columns">
<div class="column" style="width:55%;">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a aria-label="1"></a><span class="co"># One row per team ------------------------------------</span></span>
<span id="cb22-2"><a aria-label="2"></a>wide_df <span class="ot">&lt;-</span> team_df <span class="sc">%&gt;%</span></span>
<span id="cb22-3"><a aria-label="3"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> shade,</span>
<span id="cb22-4"><a aria-label="4"></a>              <span class="at">values_from =</span> <span class="fu">c</span>(area_cm2, mass_g))</span>
<span id="cb22-5"><a aria-label="5"></a></span>
<span id="cb22-6"><a aria-label="6"></a><span class="fu">t.test</span>(wide_df<span class="sc">$</span>area_cm2_shady,</span>
<span id="cb22-7"><a aria-label="7"></a>       wide_df<span class="sc">$</span>area_cm2_sunny, <span class="at">paired =</span> <span class="cn">TRUE</span>)</span>
<span id="cb22-8"><a aria-label="8"></a></span>
<span id="cb22-9"><a aria-label="9"></a><span class="fu">t.test</span>(wide_df<span class="sc">$</span>mass_g_shady,</span>
<span id="cb22-10"><a aria-label="10"></a>       wide_df<span class="sc">$</span>mass_g_sunny, <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column" style="width:45%;">
<p>Each team measured <strong>both</strong> sides, so the team is the <strong>pair</strong>.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th>mean diff</th>
<th><em>t</em></th>
<th>df</th>
<th><em>p</em></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>area</td>
<td>−1.2 cm²</td>
<td>−0.34</td>
<td>3</td>
<td>0.76</td>
</tr>
<tr class="even">
<td>mass</td>
<td>−0.016 g</td>
<td>−0.25</td>
<td>4</td>
<td>0.81</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>Neither is significant</strong> — with 5 teams there is not much power</li>
<li>The <strong>area</strong> test has df = 3: one team never traced their leaves</li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>A real answer of “we could not detect a difference” is still an answer.</p>
</div>
</div>
</div>
</div></div>
</section>

<section id="how-to-report-a-regression" class="title-slide slide level1 center">
<h1>How to Report a Regression</h1>
<div class="columns">
<div class="column" style="width:52%;">
<p><strong>The template — fill in from your <code>summary()</code> output:</strong></p>
<blockquote>
<p><em>[What predicted what] (linear regression: F(df₁, df₂) = ___, p ___, R² = ___). The fitted equation was Y = ___ + ___ × X.</em></p>
</blockquote>
<p><strong>Ours:</strong></p>
<blockquote>
<p><em>Paper area was a very strong predictor of paper mass (linear regression: F(1, 116) = 784,900, p &lt; 0.001, R² = 0.9999). The calibration equation was mass = −0.0021 + 0.00766 × area, equivalent to 76.6 g/m². Residual scatter increased with square size, so the largest squares are the least well described.</em></p>
</blockquote>
</div><div class="column" style="width:48%;">
<p><strong>Where every number comes from:</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>In the sentence</th>
<th>In <code>summary()</code></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>F and both df</td>
<td>the <code>F-statistic:</code> line</td>
</tr>
<tr class="even">
<td><em>p</em></td>
<td>that same line</td>
</tr>
<tr class="odd">
<td>R²</td>
<td><code>Multiple R-squared</code></td>
</tr>
<tr class="even">
<td>intercept</td>
<td><code>(Intercept)</code> → <code>Estimate</code></td>
</tr>
<tr class="odd">
<td>slope</td>
<td><code>area_cm2</code> → <code>Estimate</code></td>
</tr>
</tbody>
</table>
<p><strong>Always include:</strong> the test name, F with both df, <em>p</em>, R², and <strong>the equation</strong>. Add a line about the assumptions you checked.</p>
<p>📖 W&amp;S §17.3 p.&nbsp;553</p>
</div></div>
</section>

<section id="activity-11-parts-47-now" class="title-slide slide level1 center">
<h1>→ ACTIVITY 11 Parts 4–7 now</h1>
<div class="activitybanner">
<p><strong>🛑 Do Activity Parts 4–7 now</strong></p>
<ul>
<li>Run <code>plot(model)</code> and say whether the assumptions are met</li>
<li>Convert the whole <code>paper_mass_g</code> column into areas</li>
<li>Average to one value per team per side, then run both paired <em>t</em>-tests</li>
<li>Your <strong>four answers</strong> in the script are what you hand in</li>
</ul>
</div>
</section>

<section id="what-we-learned-today" class="title-slide slide level1 center">
<h1>What We Learned Today</h1>
<div class="columns">
<div class="column" style="width:58%;">
<p><strong>The ideas:</strong></p>
<ul>
<li>Regression fits a line so you can <strong>predict Y from X</strong></li>
<li><span class="math inline">\(\hat{Y} = a + bX\)</span> — the <strong>slope</strong> converts X into Y</li>
<li>A <strong>residual</strong> is one point’s miss: observed − predicted</li>
<li><strong>R²</strong> = how tight the fit is; <strong><em>p</em></strong> = whether the slope is real</li>
<li>Check the <strong>residuals</strong> — and say what you saw</li>
</ul>
<p><strong>The code:</strong></p>
<ul>
<li><code>lm(Y ~ X, data = df)</code> — fit it</li>
<li><code>summary(model)</code> — slope, intercept, <em>p</em>, R²</li>
<li><code>geom_smooth(method = "lm")</code> — draw it</li>
<li><code>plot(model)</code> — check it</li>
<li><code>7.660e-03</code> = 0.007660 — reading scientific notation</li>
</ul>
</div><div class="column" style="width:42%;">
<ul>
<li><strong>Hand in:</strong> your finished <code>scripts/11_regression.R</code> — the code is given; your <strong>answers</strong> are graded</li>
</ul>
<p><strong>📖 W&amp;S Ch. 17:</strong></p>
<ul>
<li>§17.1 Linear regression · §17.2 Prediction</li>
<li>§17.3 Testing the slope · §17.4 R²</li>
<li>§17.5 Assumptions</li>
</ul>
<p><strong>Up next — Lecture 12:</strong></p>
<ul>
<li>Pulling real climate data into R with <code>GSODR</code></li>
<li>Summarizing daily weather into yearly values</li>
<li>The <strong>same <code>lm()</code></strong> — temperature predicted by date
<ul>
<li>the slope becomes a rate of change per year</li>
<li>and you write that regression yourself</li>
</ul></li>
</ul>
</div></div>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': true,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        // Bounds for smallest/largest possible scale to apply to content
        minScale: 0.2,

        maxScale: 2,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/wlperry\.github\.io\/umd_datasci");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>