{
  "hash": "f40fa43b4f2e04b3a7c9b5035d15fdcb",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lecture 17 - Principal Component Analysis (PCA)\"\nauthor: \"Bill Perry\"\n\nformat:\n  html:\n    output-file: \"17_01_lecture_powerpoint_html.html\"\n    downloads: [docx, pptx, typst]  # This creates download links for all three\n  revealjs:\n    output-file: \"17_01_lecture_powerpoint_slides.html\"\n  docx:\n    output-file: \"17_01_lecture_powerpoint.docx\"\n  pptx:\n    output-file: \"17_01_lecture_powerpoint.pptx\"\n---\n\n\n\n# Lecture 16: Review\n\n::::: columns\n::: {.column width=\"60%\"}\n## Review\n\n-   Multivariate data\n-   Multivariate statistics in ecology: overview\n-   Eigenvectors, eigenvalues, components\n-   Distance and dissimilarity in MV space\n-   Data standardization\n-   Graphics\n-   Screening MV data\n-   MANOVA\n:::\n\n::: {.column width=\"40%\"}\n![](images/clipboard-2539526410.png){width=\"500\"}\n:::\n:::::\n\n# Review: Eigenvectors and Components\n\nEigenvectors, eigenvalues and components\n\n-   Common goal of MV analysis is variable reduction: can we derive new\n    variables (based on linear combinations of \"original\" variables)\n    that explain variation in data?\n\n-   For data set with i= 1 to n objects and j = 1 to p original\n    variables we seek new variables (principal components) using the\n    equation:\n\n### $$z_{ik} = c_1y_{i1} + c_2y_{i2} + \\cdots c_jy_{ij} + \\cdots + c_py_{ip}$$\n\n# Review: Component Interpretation\n\n-   zik is value of new variable k for object I\n-   yi1- yip are values of original variables for object i\n-   c1-cp are coefficients that show importance of the original\n    variables to new derived variable\n\n### $$z_{ik} = c_1y_{i1} + c_2y_{i2} + \\cdots c_jy_{ij} + \\cdots + c_py_{ip}$$\n\n# Review: Component Properties\n\n::::: columns\n::: {.column width=\"60%\"}\nEigenvectors, eigenvalues and components\n\nDerived variables are found so that:\n\n-   First derived variable explains most of the variation in the data\n-   Second most of the remaining variation\n-   And so on…\n-   As many derived variables as original variables (p)\n-   Derived variables are uncorrelated with each other\n:::\n\n::: {.column width=\"40%\"}\n![](images/clipboard-2044711521.png){width=\"500\"}\n:::\n:::::\n\n# Review: Eigenvalues and Eigenvectors\n\nEigenvectors, eigenvalues and components\n\n-   Eigenvalues (latent roots) represent amount of variation in data\n    explained by the new k= 1 to p derived variables (λ1, λ2 …λp).\n-   Eigenvalues are population parameters and are estimated using ML to\n    get sample statistics (l1, l2…lp)\n-   Eigenvectors are lists of coefficients (c) that show contribution of\n    original variables to new, derived variables\n-   Each new variable has an eigenvalue and an eigenvector\n-   New variables (components) are derived from a p x p covariance or\n    correlation matrix of original variables\n\n# Lecture 17: PCA Goals and Introduction\n\n-   Common goals of MV data analysis are variable reduction (finding\n    derived variables that summarize data) and exploration of patterns\n    in data (scaling/ordination)\n-   Can use association (correlation/ covariance) matrices (PCA) or\n    dissimilarity measures (MDS)\n-   In PCA: take p old variables and transform them into p \"new/derived\"\n    uncorrelated variables (principal components)\n\n# Data for PCA Analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load the iris dataset\niris_df <- iris %>% clean_names() %>% mutate(ind = row_number()) %>% \n  mutate(species_ind = paste(species, ind, sep=\"_\"))\n\n# get values only\niris_data <- iris_df  %>% select(-species, -ind, -species_ind)\n\n# Keep species for later visualization\niris_species <- iris_df  %>% select(species, ind, species_ind)\n\n# pivot to long formt for viewing\niris_long_df <- iris_df %>%\n  pivot_longer(\n    cols = -c(species, ind, species_ind),\n    names_to = \"variable\",\n    values_to = \"values\")\n \niris_df \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    sepal_length sepal_width petal_length petal_width    species ind\n1            5.1         3.5          1.4         0.2     setosa   1\n2            4.9         3.0          1.4         0.2     setosa   2\n3            4.7         3.2          1.3         0.2     setosa   3\n4            4.6         3.1          1.5         0.2     setosa   4\n5            5.0         3.6          1.4         0.2     setosa   5\n6            5.4         3.9          1.7         0.4     setosa   6\n7            4.6         3.4          1.4         0.3     setosa   7\n8            5.0         3.4          1.5         0.2     setosa   8\n9            4.4         2.9          1.4         0.2     setosa   9\n10           4.9         3.1          1.5         0.1     setosa  10\n11           5.4         3.7          1.5         0.2     setosa  11\n12           4.8         3.4          1.6         0.2     setosa  12\n13           4.8         3.0          1.4         0.1     setosa  13\n14           4.3         3.0          1.1         0.1     setosa  14\n15           5.8         4.0          1.2         0.2     setosa  15\n16           5.7         4.4          1.5         0.4     setosa  16\n17           5.4         3.9          1.3         0.4     setosa  17\n18           5.1         3.5          1.4         0.3     setosa  18\n19           5.7         3.8          1.7         0.3     setosa  19\n20           5.1         3.8          1.5         0.3     setosa  20\n21           5.4         3.4          1.7         0.2     setosa  21\n22           5.1         3.7          1.5         0.4     setosa  22\n23           4.6         3.6          1.0         0.2     setosa  23\n24           5.1         3.3          1.7         0.5     setosa  24\n25           4.8         3.4          1.9         0.2     setosa  25\n26           5.0         3.0          1.6         0.2     setosa  26\n27           5.0         3.4          1.6         0.4     setosa  27\n28           5.2         3.5          1.5         0.2     setosa  28\n29           5.2         3.4          1.4         0.2     setosa  29\n30           4.7         3.2          1.6         0.2     setosa  30\n31           4.8         3.1          1.6         0.2     setosa  31\n32           5.4         3.4          1.5         0.4     setosa  32\n33           5.2         4.1          1.5         0.1     setosa  33\n34           5.5         4.2          1.4         0.2     setosa  34\n35           4.9         3.1          1.5         0.2     setosa  35\n36           5.0         3.2          1.2         0.2     setosa  36\n37           5.5         3.5          1.3         0.2     setosa  37\n38           4.9         3.6          1.4         0.1     setosa  38\n39           4.4         3.0          1.3         0.2     setosa  39\n40           5.1         3.4          1.5         0.2     setosa  40\n41           5.0         3.5          1.3         0.3     setosa  41\n42           4.5         2.3          1.3         0.3     setosa  42\n43           4.4         3.2          1.3         0.2     setosa  43\n44           5.0         3.5          1.6         0.6     setosa  44\n45           5.1         3.8          1.9         0.4     setosa  45\n46           4.8         3.0          1.4         0.3     setosa  46\n47           5.1         3.8          1.6         0.2     setosa  47\n48           4.6         3.2          1.4         0.2     setosa  48\n49           5.3         3.7          1.5         0.2     setosa  49\n50           5.0         3.3          1.4         0.2     setosa  50\n51           7.0         3.2          4.7         1.4 versicolor  51\n52           6.4         3.2          4.5         1.5 versicolor  52\n53           6.9         3.1          4.9         1.5 versicolor  53\n54           5.5         2.3          4.0         1.3 versicolor  54\n55           6.5         2.8          4.6         1.5 versicolor  55\n56           5.7         2.8          4.5         1.3 versicolor  56\n57           6.3         3.3          4.7         1.6 versicolor  57\n58           4.9         2.4          3.3         1.0 versicolor  58\n59           6.6         2.9          4.6         1.3 versicolor  59\n60           5.2         2.7          3.9         1.4 versicolor  60\n61           5.0         2.0          3.5         1.0 versicolor  61\n62           5.9         3.0          4.2         1.5 versicolor  62\n63           6.0         2.2          4.0         1.0 versicolor  63\n64           6.1         2.9          4.7         1.4 versicolor  64\n65           5.6         2.9          3.6         1.3 versicolor  65\n66           6.7         3.1          4.4         1.4 versicolor  66\n67           5.6         3.0          4.5         1.5 versicolor  67\n68           5.8         2.7          4.1         1.0 versicolor  68\n69           6.2         2.2          4.5         1.5 versicolor  69\n70           5.6         2.5          3.9         1.1 versicolor  70\n71           5.9         3.2          4.8         1.8 versicolor  71\n72           6.1         2.8          4.0         1.3 versicolor  72\n73           6.3         2.5          4.9         1.5 versicolor  73\n74           6.1         2.8          4.7         1.2 versicolor  74\n75           6.4         2.9          4.3         1.3 versicolor  75\n76           6.6         3.0          4.4         1.4 versicolor  76\n77           6.8         2.8          4.8         1.4 versicolor  77\n78           6.7         3.0          5.0         1.7 versicolor  78\n79           6.0         2.9          4.5         1.5 versicolor  79\n80           5.7         2.6          3.5         1.0 versicolor  80\n81           5.5         2.4          3.8         1.1 versicolor  81\n82           5.5         2.4          3.7         1.0 versicolor  82\n83           5.8         2.7          3.9         1.2 versicolor  83\n84           6.0         2.7          5.1         1.6 versicolor  84\n85           5.4         3.0          4.5         1.5 versicolor  85\n86           6.0         3.4          4.5         1.6 versicolor  86\n87           6.7         3.1          4.7         1.5 versicolor  87\n88           6.3         2.3          4.4         1.3 versicolor  88\n89           5.6         3.0          4.1         1.3 versicolor  89\n90           5.5         2.5          4.0         1.3 versicolor  90\n91           5.5         2.6          4.4         1.2 versicolor  91\n92           6.1         3.0          4.6         1.4 versicolor  92\n93           5.8         2.6          4.0         1.2 versicolor  93\n94           5.0         2.3          3.3         1.0 versicolor  94\n95           5.6         2.7          4.2         1.3 versicolor  95\n96           5.7         3.0          4.2         1.2 versicolor  96\n97           5.7         2.9          4.2         1.3 versicolor  97\n98           6.2         2.9          4.3         1.3 versicolor  98\n99           5.1         2.5          3.0         1.1 versicolor  99\n100          5.7         2.8          4.1         1.3 versicolor 100\n101          6.3         3.3          6.0         2.5  virginica 101\n102          5.8         2.7          5.1         1.9  virginica 102\n103          7.1         3.0          5.9         2.1  virginica 103\n104          6.3         2.9          5.6         1.8  virginica 104\n105          6.5         3.0          5.8         2.2  virginica 105\n106          7.6         3.0          6.6         2.1  virginica 106\n107          4.9         2.5          4.5         1.7  virginica 107\n108          7.3         2.9          6.3         1.8  virginica 108\n109          6.7         2.5          5.8         1.8  virginica 109\n110          7.2         3.6          6.1         2.5  virginica 110\n111          6.5         3.2          5.1         2.0  virginica 111\n112          6.4         2.7          5.3         1.9  virginica 112\n113          6.8         3.0          5.5         2.1  virginica 113\n114          5.7         2.5          5.0         2.0  virginica 114\n115          5.8         2.8          5.1         2.4  virginica 115\n116          6.4         3.2          5.3         2.3  virginica 116\n117          6.5         3.0          5.5         1.8  virginica 117\n118          7.7         3.8          6.7         2.2  virginica 118\n119          7.7         2.6          6.9         2.3  virginica 119\n120          6.0         2.2          5.0         1.5  virginica 120\n121          6.9         3.2          5.7         2.3  virginica 121\n122          5.6         2.8          4.9         2.0  virginica 122\n123          7.7         2.8          6.7         2.0  virginica 123\n124          6.3         2.7          4.9         1.8  virginica 124\n125          6.7         3.3          5.7         2.1  virginica 125\n126          7.2         3.2          6.0         1.8  virginica 126\n127          6.2         2.8          4.8         1.8  virginica 127\n128          6.1         3.0          4.9         1.8  virginica 128\n129          6.4         2.8          5.6         2.1  virginica 129\n130          7.2         3.0          5.8         1.6  virginica 130\n131          7.4         2.8          6.1         1.9  virginica 131\n132          7.9         3.8          6.4         2.0  virginica 132\n133          6.4         2.8          5.6         2.2  virginica 133\n134          6.3         2.8          5.1         1.5  virginica 134\n135          6.1         2.6          5.6         1.4  virginica 135\n136          7.7         3.0          6.1         2.3  virginica 136\n137          6.3         3.4          5.6         2.4  virginica 137\n138          6.4         3.1          5.5         1.8  virginica 138\n139          6.0         3.0          4.8         1.8  virginica 139\n140          6.9         3.1          5.4         2.1  virginica 140\n141          6.7         3.1          5.6         2.4  virginica 141\n142          6.9         3.1          5.1         2.3  virginica 142\n143          5.8         2.7          5.1         1.9  virginica 143\n144          6.8         3.2          5.9         2.3  virginica 144\n145          6.7         3.3          5.7         2.5  virginica 145\n146          6.7         3.0          5.2         2.3  virginica 146\n147          6.3         2.5          5.0         1.9  virginica 147\n148          6.5         3.0          5.2         2.0  virginica 148\n149          6.2         3.4          5.4         2.3  virginica 149\n150          5.9         3.0          5.1         1.8  virginica 150\n       species_ind\n1         setosa_1\n2         setosa_2\n3         setosa_3\n4         setosa_4\n5         setosa_5\n6         setosa_6\n7         setosa_7\n8         setosa_8\n9         setosa_9\n10       setosa_10\n11       setosa_11\n12       setosa_12\n13       setosa_13\n14       setosa_14\n15       setosa_15\n16       setosa_16\n17       setosa_17\n18       setosa_18\n19       setosa_19\n20       setosa_20\n21       setosa_21\n22       setosa_22\n23       setosa_23\n24       setosa_24\n25       setosa_25\n26       setosa_26\n27       setosa_27\n28       setosa_28\n29       setosa_29\n30       setosa_30\n31       setosa_31\n32       setosa_32\n33       setosa_33\n34       setosa_34\n35       setosa_35\n36       setosa_36\n37       setosa_37\n38       setosa_38\n39       setosa_39\n40       setosa_40\n41       setosa_41\n42       setosa_42\n43       setosa_43\n44       setosa_44\n45       setosa_45\n46       setosa_46\n47       setosa_47\n48       setosa_48\n49       setosa_49\n50       setosa_50\n51   versicolor_51\n52   versicolor_52\n53   versicolor_53\n54   versicolor_54\n55   versicolor_55\n56   versicolor_56\n57   versicolor_57\n58   versicolor_58\n59   versicolor_59\n60   versicolor_60\n61   versicolor_61\n62   versicolor_62\n63   versicolor_63\n64   versicolor_64\n65   versicolor_65\n66   versicolor_66\n67   versicolor_67\n68   versicolor_68\n69   versicolor_69\n70   versicolor_70\n71   versicolor_71\n72   versicolor_72\n73   versicolor_73\n74   versicolor_74\n75   versicolor_75\n76   versicolor_76\n77   versicolor_77\n78   versicolor_78\n79   versicolor_79\n80   versicolor_80\n81   versicolor_81\n82   versicolor_82\n83   versicolor_83\n84   versicolor_84\n85   versicolor_85\n86   versicolor_86\n87   versicolor_87\n88   versicolor_88\n89   versicolor_89\n90   versicolor_90\n91   versicolor_91\n92   versicolor_92\n93   versicolor_93\n94   versicolor_94\n95   versicolor_95\n96   versicolor_96\n97   versicolor_97\n98   versicolor_98\n99   versicolor_99\n100 versicolor_100\n101  virginica_101\n102  virginica_102\n103  virginica_103\n104  virginica_104\n105  virginica_105\n106  virginica_106\n107  virginica_107\n108  virginica_108\n109  virginica_109\n110  virginica_110\n111  virginica_111\n112  virginica_112\n113  virginica_113\n114  virginica_114\n115  virginica_115\n116  virginica_116\n117  virginica_117\n118  virginica_118\n119  virginica_119\n120  virginica_120\n121  virginica_121\n122  virginica_122\n123  virginica_123\n124  virginica_124\n125  virginica_125\n126  virginica_126\n127  virginica_127\n128  virginica_128\n129  virginica_129\n130  virginica_130\n131  virginica_131\n132  virginica_132\n133  virginica_133\n134  virginica_134\n135  virginica_135\n136  virginica_136\n137  virginica_137\n138  virginica_138\n139  virginica_139\n140  virginica_140\n141  virginica_141\n142  virginica_142\n143  virginica_143\n144  virginica_144\n145  virginica_145\n146  virginica_146\n147  virginica_147\n148  virginica_148\n149  virginica_149\n150  virginica_150\n```\n\n\n:::\n:::\n\n\n# Step 1: Explore the Iris Dataset\n\n::::: columns\n::: {.column width=\"60%\"}\nAs in every case you should be looking at the data first - every time...\n\nRight is the data on iris from a long dataframe\n:::\n\n::: {.column width=\"40%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\noverview_plot <- iris_long_df %>% \n  ggplot(aes(species, values, color=species)) + \n  geom_boxplot() +\n  facet_wrap(~variable, scales = \"free\")\noverview_plot\n```\n\n::: {.cell-output-display}\n![](17_01_lecture_powerpoint_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n:::\n:::::\n\n# What is PCA? Goals and Overview\n\n::::: columns\n::: {.column width=\"40%\"}\n## Principal Component Analysis Goals:\n\n-   **Variable Reduction**: Transform many correlated variables into\n    fewer uncorrelated components\n-   **Data Exploration**: Visualize patterns and relationships in\n    high-dimensional data\n-   **Noise Reduction**: Focus on the most important sources of\n    variation\n-   **Dimension Reduction**: Make complex datasets easier to analyze and\n    interpret\n\n**Today's Example**: Iris flower measurements - can we reduce 4\nmeasurements to 2-3 components that capture most variation?\n:::\n\n::: {.column width=\"60%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](17_01_lecture_powerpoint_files/figure-html/correaltions-1.png){width=672}\n:::\n:::\n\n:::\n:::::\n\n# High-Dimensional Data Visualization\n\n::::: columns\n::: {.column width=\"40%\"}\n## Principal Component Analysis Goals:\n\n-   **Variable Reduction**: Transform many correlated variables into\n    fewer uncorrelated components\n-   **Data Exploration**: Visualize patterns and relationships in\n    high-dimensional data\n-   **Noise Reduction**: Focus on the most important sources of\n    variation\n-   **Dimension Reduction**: Make complex datasets easier to analyze and\n    interpret\n\n**Today's Example**: Iris flower measurements - can we reduce 4\nmeasurements to fewer components that capture most variation?\n:::\n\n::: {.column width=\"60%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-71ef1b733f72a2438995\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-71ef1b733f72a2438995\">{\"x\":{\"visdat\":{\"160ce7194a1c2\":[\"function () \",\"plotlyVisDat\"]},\"cur_data\":\"160ce7194a1c2\",\"attrs\":{\"160ce7194a1c2\":{\"x\":{},\"y\":{},\"z\":{},\"mode\":\"markers\",\"marker\":{\"size\":5,\"opacity\":0.80000000000000004},\"text\":{},\"hoverinfo\":\"text\",\"color\":{},\"colors\":[\"#E41A1C\",\"#377EB8\",\"#4DAF4A\"],\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"type\":\"scatter3d\"}},\"layout\":{\"margin\":{\"b\":40,\"l\":60,\"t\":25,\"r\":10},\"scene\":{\"xaxis\":{\"title\":\"\",\"showgrid\":false,\"showline\":false,\"showticklabels\":false,\"zeroline\":false,\"showspikes\":false},\"yaxis\":{\"title\":\"\",\"showgrid\":false,\"showline\":false,\"showticklabels\":false,\"zeroline\":false,\"showspikes\":false},\"zaxis\":{\"title\":\"\",\"showgrid\":false,\"showline\":false,\"showticklabels\":false,\"zeroline\":false,\"showspikes\":false},\"bgcolor\":\"white\",\"camera\":{\"eye\":{\"x\":1.5,\"y\":1.5,\"z\":1.5}}},\"paper_bgcolor\":\"white\",\"showlegend\":true,\"hovermode\":\"closest\"},\"source\":\"A\",\"config\":{\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"data\":[{\"x\":[5.0999999999999996,4.9000000000000004,4.7000000000000002,4.5999999999999996,5,5.4000000000000004,4.5999999999999996,5,4.4000000000000004,4.9000000000000004,5.4000000000000004,4.7999999999999998,4.7999999999999998,4.2999999999999998,5.7999999999999998,5.7000000000000002,5.4000000000000004,5.0999999999999996,5.7000000000000002,5.0999999999999996,5.4000000000000004,5.0999999999999996,4.5999999999999996,5.0999999999999996,4.7999999999999998,5,5,5.2000000000000002,5.2000000000000002,4.7000000000000002,4.7999999999999998,5.4000000000000004,5.2000000000000002,5.5,4.9000000000000004,5,5.5,4.9000000000000004,4.4000000000000004,5.0999999999999996,5,4.5,4.4000000000000004,5,5.0999999999999996,4.7999999999999998,5.0999999999999996,4.5999999999999996,5.2999999999999998,5],\"y\":[3.5,3,3.2000000000000002,3.1000000000000001,3.6000000000000001,3.8999999999999999,3.3999999999999999,3.3999999999999999,2.8999999999999999,3.1000000000000001,3.7000000000000002,3.3999999999999999,3,3,4,4.4000000000000004,3.8999999999999999,3.5,3.7999999999999998,3.7999999999999998,3.3999999999999999,3.7000000000000002,3.6000000000000001,3.2999999999999998,3.3999999999999999,3,3.3999999999999999,3.5,3.3999999999999999,3.2000000000000002,3.1000000000000001,3.3999999999999999,4.0999999999999996,4.2000000000000002,3.1000000000000001,3.2000000000000002,3.5,3.6000000000000001,3,3.3999999999999999,3.5,2.2999999999999998,3.2000000000000002,3.5,3.7999999999999998,3,3.7999999999999998,3.2000000000000002,3.7000000000000002,3.2999999999999998],\"z\":[5.379999999999999,5.0299999999999994,4.96,4.9999999999999991,5.379999999999999,6.04,5.1299999999999999,5.3499999999999996,4.7299999999999995,5.0999999999999996,5.7000000000000002,5.3199999999999994,4.9299999999999997,4.4699999999999998,5.8399999999999999,6.3000000000000007,5.7600000000000007,5.4299999999999997,6.0899999999999999,5.6499999999999995,5.6899999999999995,5.6500000000000004,4.8999999999999995,5.6399999999999988,5.5299999999999994,5.2199999999999998,5.5200000000000005,5.4999999999999991,5.379999999999999,5.1699999999999999,5.1699999999999999,5.6500000000000004,5.75,5.9299999999999988,5.1499999999999995,5.0399999999999991,5.5099999999999998,5.2799999999999994,4.71,5.3999999999999995,5.3100000000000005,4.46,4.8099999999999996,5.6699999999999999,5.9799999999999995,5.0300000000000002,5.669999999999999,4.9799999999999995,5.6499999999999995,5.2299999999999995],\"mode\":\"markers\",\"marker\":{\"color\":\"rgba(228,26,28,1)\",\"size\":5,\"opacity\":0.80000000000000004,\"line\":{\"color\":\"rgba(228,26,28,1)\"}},\"text\":[\"Sepal Length: 5.1 <br> Sepal Width: 3.5 <br> Petal Length: 1.4 <br> Petal Width: 0.2\",\"Sepal Length: 4.9 <br> Sepal Width: 3 <br> Petal Length: 1.4 <br> Petal Width: 0.2\",\"Sepal Length: 4.7 <br> Sepal Width: 3.2 <br> Petal Length: 1.3 <br> Petal Width: 0.2\",\"Sepal Length: 4.6 <br> Sepal Width: 3.1 <br> Petal Length: 1.5 <br> Petal Width: 0.2\",\"Sepal Length: 5 <br> Sepal Width: 3.6 <br> Petal Length: 1.4 <br> Petal Width: 0.2\",\"Sepal Length: 5.4 <br> Sepal Width: 3.9 <br> Petal Length: 1.7 <br> Petal Width: 0.4\",\"Sepal Length: 4.6 <br> Sepal Width: 3.4 <br> Petal Length: 1.4 <br> Petal Width: 0.3\",\"Sepal Length: 5 <br> Sepal Width: 3.4 <br> Petal Length: 1.5 <br> Petal Width: 0.2\",\"Sepal Length: 4.4 <br> Sepal Width: 2.9 <br> Petal Length: 1.4 <br> Petal Width: 0.2\",\"Sepal Length: 4.9 <br> Sepal Width: 3.1 <br> Petal Length: 1.5 <br> Petal Width: 0.1\",\"Sepal Length: 5.4 <br> Sepal Width: 3.7 <br> Petal Length: 1.5 <br> Petal Width: 0.2\",\"Sepal Length: 4.8 <br> Sepal Width: 3.4 <br> Petal Length: 1.6 <br> Petal Width: 0.2\",\"Sepal Length: 4.8 <br> Sepal Width: 3 <br> Petal Length: 1.4 <br> Petal Width: 0.1\",\"Sepal Length: 4.3 <br> Sepal Width: 3 <br> Petal Length: 1.1 <br> Petal Width: 0.1\",\"Sepal Length: 5.8 <br> Sepal Width: 4 <br> Petal Length: 1.2 <br> Petal Width: 0.2\",\"Sepal Length: 5.7 <br> Sepal Width: 4.4 <br> Petal Length: 1.5 <br> Petal Width: 0.4\",\"Sepal Length: 5.4 <br> Sepal Width: 3.9 <br> Petal Length: 1.3 <br> Petal Width: 0.4\",\"Sepal Length: 5.1 <br> Sepal Width: 3.5 <br> Petal Length: 1.4 <br> Petal Width: 0.3\",\"Sepal Length: 5.7 <br> Sepal Width: 3.8 <br> Petal Length: 1.7 <br> Petal Width: 0.3\",\"Sepal Length: 5.1 <br> Sepal Width: 3.8 <br> Petal Length: 1.5 <br> Petal Width: 0.3\",\"Sepal Length: 5.4 <br> Sepal Width: 3.4 <br> Petal Length: 1.7 <br> Petal Width: 0.2\",\"Sepal Length: 5.1 <br> Sepal Width: 3.7 <br> Petal Length: 1.5 <br> Petal Width: 0.4\",\"Sepal Length: 4.6 <br> Sepal Width: 3.6 <br> Petal Length: 1 <br> Petal Width: 0.2\",\"Sepal Length: 5.1 <br> Sepal Width: 3.3 <br> Petal Length: 1.7 <br> Petal Width: 0.5\",\"Sepal Length: 4.8 <br> Sepal Width: 3.4 <br> Petal Length: 1.9 <br> Petal Width: 0.2\",\"Sepal Length: 5 <br> Sepal Width: 3 <br> Petal Length: 1.6 <br> Petal Width: 0.2\",\"Sepal Length: 5 <br> Sepal Width: 3.4 <br> Petal Length: 1.6 <br> Petal Width: 0.4\",\"Sepal Length: 5.2 <br> Sepal Width: 3.5 <br> Petal Length: 1.5 <br> Petal Width: 0.2\",\"Sepal Length: 5.2 <br> Sepal Width: 3.4 <br> Petal Length: 1.4 <br> Petal Width: 0.2\",\"Sepal Length: 4.7 <br> Sepal Width: 3.2 <br> Petal Length: 1.6 <br> Petal Width: 0.2\",\"Sepal Length: 4.8 <br> Sepal Width: 3.1 <br> Petal Length: 1.6 <br> Petal Width: 0.2\",\"Sepal Length: 5.4 <br> Sepal Width: 3.4 <br> Petal Length: 1.5 <br> Petal Width: 0.4\",\"Sepal Length: 5.2 <br> Sepal Width: 4.1 <br> Petal Length: 1.5 <br> Petal Width: 0.1\",\"Sepal Length: 5.5 <br> Sepal Width: 4.2 <br> Petal Length: 1.4 <br> Petal Width: 0.2\",\"Sepal Length: 4.9 <br> Sepal Width: 3.1 <br> Petal Length: 1.5 <br> Petal Width: 0.2\",\"Sepal Length: 5 <br> Sepal Width: 3.2 <br> Petal Length: 1.2 <br> Petal Width: 0.2\",\"Sepal Length: 5.5 <br> Sepal Width: 3.5 <br> Petal Length: 1.3 <br> Petal Width: 0.2\",\"Sepal Length: 4.9 <br> Sepal Width: 3.6 <br> Petal Length: 1.4 <br> Petal Width: 0.1\",\"Sepal Length: 4.4 <br> Sepal Width: 3 <br> Petal Length: 1.3 <br> Petal Width: 0.2\",\"Sepal Length: 5.1 <br> Sepal Width: 3.4 <br> Petal Length: 1.5 <br> Petal Width: 0.2\",\"Sepal Length: 5 <br> Sepal Width: 3.5 <br> Petal Length: 1.3 <br> Petal Width: 0.3\",\"Sepal Length: 4.5 <br> Sepal Width: 2.3 <br> Petal Length: 1.3 <br> Petal Width: 0.3\",\"Sepal Length: 4.4 <br> Sepal Width: 3.2 <br> Petal Length: 1.3 <br> Petal Width: 0.2\",\"Sepal Length: 5 <br> Sepal Width: 3.5 <br> Petal Length: 1.6 <br> Petal Width: 0.6\",\"Sepal Length: 5.1 <br> Sepal Width: 3.8 <br> Petal Length: 1.9 <br> Petal Width: 0.4\",\"Sepal Length: 4.8 <br> Sepal Width: 3 <br> Petal Length: 1.4 <br> Petal Width: 0.3\",\"Sepal Length: 5.1 <br> Sepal Width: 3.8 <br> Petal Length: 1.6 <br> Petal Width: 0.2\",\"Sepal Length: 4.6 <br> Sepal Width: 3.2 <br> Petal Length: 1.4 <br> Petal Width: 0.2\",\"Sepal Length: 5.3 <br> Sepal Width: 3.7 <br> Petal Length: 1.5 <br> Petal Width: 0.2\",\"Sepal Length: 5 <br> Sepal Width: 3.3 <br> Petal Length: 1.4 <br> Petal Width: 0.2\"],\"hoverinfo\":[\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\"],\"type\":\"scatter3d\",\"name\":\"setosa\",\"textfont\":{\"color\":\"rgba(228,26,28,1)\"},\"error_y\":{\"color\":\"rgba(228,26,28,1)\"},\"error_x\":{\"color\":\"rgba(228,26,28,1)\"},\"line\":{\"color\":\"rgba(228,26,28,1)\"},\"frame\":null},{\"x\":[7,6.4000000000000004,6.9000000000000004,5.5,6.5,5.7000000000000002,6.2999999999999998,4.9000000000000004,6.5999999999999996,5.2000000000000002,5,5.9000000000000004,6,6.0999999999999996,5.5999999999999996,6.7000000000000002,5.5999999999999996,5.7999999999999998,6.2000000000000002,5.5999999999999996,5.9000000000000004,6.0999999999999996,6.2999999999999998,6.0999999999999996,6.4000000000000004,6.5999999999999996,6.7999999999999998,6.7000000000000002,6,5.7000000000000002,5.5,5.5,5.7999999999999998,6,5.4000000000000004,6,6.7000000000000002,6.2999999999999998,5.5999999999999996,5.5,5.5,6.0999999999999996,5.7999999999999998,5,5.5999999999999996,5.7000000000000002,5.7000000000000002,6.2000000000000002,5.0999999999999996,5.7000000000000002],\"y\":[3.2000000000000002,3.2000000000000002,3.1000000000000001,2.2999999999999998,2.7999999999999998,2.7999999999999998,3.2999999999999998,2.3999999999999999,2.8999999999999999,2.7000000000000002,2,3,2.2000000000000002,2.8999999999999999,2.8999999999999999,3.1000000000000001,3,2.7000000000000002,2.2000000000000002,2.5,3.2000000000000002,2.7999999999999998,2.5,2.7999999999999998,2.8999999999999999,3,2.7999999999999998,3,2.8999999999999999,2.6000000000000001,2.3999999999999999,2.3999999999999999,2.7000000000000002,2.7000000000000002,3,3.3999999999999999,3.1000000000000001,2.2999999999999998,3,2.5,2.6000000000000001,3,2.6000000000000001,2.2999999999999998,2.7000000000000002,3,2.8999999999999999,2.8999999999999999,2.5,2.7999999999999998],\"z\":[9.0899999999999981,8.6999999999999993,9.1799999999999997,7.3499999999999996,8.620000000000001,8.0499999999999989,8.8900000000000006,6.46,8.6199999999999992,7.3799999999999999,6.4500000000000002,8.1400000000000006,7.3999999999999995,8.4900000000000002,7.4199999999999999,8.6799999999999997,8.1999999999999993,7.6199999999999992,8.0999999999999996,7.3299999999999992,8.8100000000000005,7.8999999999999995,8.5800000000000001,8.3399999999999999,8.3100000000000005,8.5800000000000001,8.8599999999999994,9.1999999999999993,8.3499999999999996,7.1000000000000005,7.1600000000000001,7.04,7.5799999999999992,8.7199999999999989,8.0999999999999996,8.6500000000000004,8.9399999999999995,8.0299999999999994,7.8199999999999994,7.4500000000000002,7.7299999999999995,8.4699999999999989,7.5999999999999996,6.46,7.7400000000000002,7.8899999999999988,7.8899999999999997,8.2099999999999991,6.4499999999999993,7.7699999999999996],\"mode\":\"markers\",\"marker\":{\"color\":\"rgba(55,126,184,1)\",\"size\":5,\"opacity\":0.80000000000000004,\"line\":{\"color\":\"rgba(55,126,184,1)\"}},\"text\":[\"Sepal Length: 7 <br> Sepal Width: 3.2 <br> Petal Length: 4.7 <br> Petal Width: 1.4\",\"Sepal Length: 6.4 <br> Sepal Width: 3.2 <br> Petal Length: 4.5 <br> Petal Width: 1.5\",\"Sepal Length: 6.9 <br> Sepal Width: 3.1 <br> Petal Length: 4.9 <br> Petal Width: 1.5\",\"Sepal Length: 5.5 <br> Sepal Width: 2.3 <br> Petal Length: 4 <br> Petal Width: 1.3\",\"Sepal Length: 6.5 <br> Sepal Width: 2.8 <br> Petal Length: 4.6 <br> Petal Width: 1.5\",\"Sepal Length: 5.7 <br> Sepal Width: 2.8 <br> Petal Length: 4.5 <br> Petal Width: 1.3\",\"Sepal Length: 6.3 <br> Sepal Width: 3.3 <br> Petal Length: 4.7 <br> Petal Width: 1.6\",\"Sepal Length: 4.9 <br> Sepal Width: 2.4 <br> Petal Length: 3.3 <br> Petal Width: 1\",\"Sepal Length: 6.6 <br> Sepal Width: 2.9 <br> Petal Length: 4.6 <br> Petal Width: 1.3\",\"Sepal Length: 5.2 <br> Sepal Width: 2.7 <br> Petal Length: 3.9 <br> Petal Width: 1.4\",\"Sepal Length: 5 <br> Sepal Width: 2 <br> Petal Length: 3.5 <br> Petal Width: 1\",\"Sepal Length: 5.9 <br> Sepal Width: 3 <br> Petal Length: 4.2 <br> Petal Width: 1.5\",\"Sepal Length: 6 <br> Sepal Width: 2.2 <br> Petal Length: 4 <br> Petal Width: 1\",\"Sepal Length: 6.1 <br> Sepal Width: 2.9 <br> Petal Length: 4.7 <br> Petal Width: 1.4\",\"Sepal Length: 5.6 <br> Sepal Width: 2.9 <br> Petal Length: 3.6 <br> Petal Width: 1.3\",\"Sepal Length: 6.7 <br> Sepal Width: 3.1 <br> Petal Length: 4.4 <br> Petal Width: 1.4\",\"Sepal Length: 5.6 <br> Sepal Width: 3 <br> Petal Length: 4.5 <br> Petal Width: 1.5\",\"Sepal Length: 5.8 <br> Sepal Width: 2.7 <br> Petal Length: 4.1 <br> Petal Width: 1\",\"Sepal Length: 6.2 <br> Sepal Width: 2.2 <br> Petal Length: 4.5 <br> Petal Width: 1.5\",\"Sepal Length: 5.6 <br> Sepal Width: 2.5 <br> Petal Length: 3.9 <br> Petal Width: 1.1\",\"Sepal Length: 5.9 <br> Sepal Width: 3.2 <br> Petal Length: 4.8 <br> Petal Width: 1.8\",\"Sepal Length: 6.1 <br> Sepal Width: 2.8 <br> Petal Length: 4 <br> Petal Width: 1.3\",\"Sepal Length: 6.3 <br> Sepal Width: 2.5 <br> Petal Length: 4.9 <br> Petal Width: 1.5\",\"Sepal Length: 6.1 <br> Sepal Width: 2.8 <br> Petal Length: 4.7 <br> Petal Width: 1.2\",\"Sepal Length: 6.4 <br> Sepal Width: 2.9 <br> Petal Length: 4.3 <br> Petal Width: 1.3\",\"Sepal Length: 6.6 <br> Sepal Width: 3 <br> Petal Length: 4.4 <br> Petal Width: 1.4\",\"Sepal Length: 6.8 <br> Sepal Width: 2.8 <br> Petal Length: 4.8 <br> Petal Width: 1.4\",\"Sepal Length: 6.7 <br> Sepal Width: 3 <br> Petal Length: 5 <br> Petal Width: 1.7\",\"Sepal Length: 6 <br> Sepal Width: 2.9 <br> Petal Length: 4.5 <br> Petal Width: 1.5\",\"Sepal Length: 5.7 <br> Sepal Width: 2.6 <br> Petal Length: 3.5 <br> Petal Width: 1\",\"Sepal Length: 5.5 <br> Sepal Width: 2.4 <br> Petal Length: 3.8 <br> Petal Width: 1.1\",\"Sepal Length: 5.5 <br> Sepal Width: 2.4 <br> Petal Length: 3.7 <br> Petal Width: 1\",\"Sepal Length: 5.8 <br> Sepal Width: 2.7 <br> Petal Length: 3.9 <br> Petal Width: 1.2\",\"Sepal Length: 6 <br> Sepal Width: 2.7 <br> Petal Length: 5.1 <br> Petal Width: 1.6\",\"Sepal Length: 5.4 <br> Sepal Width: 3 <br> Petal Length: 4.5 <br> Petal Width: 1.5\",\"Sepal Length: 6 <br> Sepal Width: 3.4 <br> Petal Length: 4.5 <br> Petal Width: 1.6\",\"Sepal Length: 6.7 <br> Sepal Width: 3.1 <br> Petal Length: 4.7 <br> Petal Width: 1.5\",\"Sepal Length: 6.3 <br> Sepal Width: 2.3 <br> Petal Length: 4.4 <br> Petal Width: 1.3\",\"Sepal Length: 5.6 <br> Sepal Width: 3 <br> Petal Length: 4.1 <br> Petal Width: 1.3\",\"Sepal Length: 5.5 <br> Sepal Width: 2.5 <br> Petal Length: 4 <br> Petal Width: 1.3\",\"Sepal Length: 5.5 <br> Sepal Width: 2.6 <br> Petal Length: 4.4 <br> Petal Width: 1.2\",\"Sepal Length: 6.1 <br> Sepal Width: 3 <br> Petal Length: 4.6 <br> Petal Width: 1.4\",\"Sepal Length: 5.8 <br> Sepal Width: 2.6 <br> Petal Length: 4 <br> Petal Width: 1.2\",\"Sepal Length: 5 <br> Sepal Width: 2.3 <br> Petal Length: 3.3 <br> Petal Width: 1\",\"Sepal Length: 5.6 <br> Sepal Width: 2.7 <br> Petal Length: 4.2 <br> Petal Width: 1.3\",\"Sepal Length: 5.7 <br> Sepal Width: 3 <br> Petal Length: 4.2 <br> Petal Width: 1.2\",\"Sepal Length: 5.7 <br> Sepal Width: 2.9 <br> Petal Length: 4.2 <br> Petal Width: 1.3\",\"Sepal Length: 6.2 <br> Sepal Width: 2.9 <br> Petal Length: 4.3 <br> Petal Width: 1.3\",\"Sepal Length: 5.1 <br> Sepal Width: 2.5 <br> Petal Length: 3 <br> Petal Width: 1.1\",\"Sepal Length: 5.7 <br> Sepal Width: 2.8 <br> Petal Length: 4.1 <br> Petal Width: 1.3\"],\"hoverinfo\":[\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\"],\"type\":\"scatter3d\",\"name\":\"versicolor\",\"textfont\":{\"color\":\"rgba(55,126,184,1)\"},\"error_y\":{\"color\":\"rgba(55,126,184,1)\"},\"error_x\":{\"color\":\"rgba(55,126,184,1)\"},\"line\":{\"color\":\"rgba(55,126,184,1)\"},\"frame\":null},{\"x\":[6.2999999999999998,5.7999999999999998,7.0999999999999996,6.2999999999999998,6.5,7.5999999999999996,4.9000000000000004,7.2999999999999998,6.7000000000000002,7.2000000000000002,6.5,6.4000000000000004,6.7999999999999998,5.7000000000000002,5.7999999999999998,6.4000000000000004,6.5,7.7000000000000002,7.7000000000000002,6,6.9000000000000004,5.5999999999999996,7.7000000000000002,6.2999999999999998,6.7000000000000002,7.2000000000000002,6.2000000000000002,6.0999999999999996,6.4000000000000004,7.2000000000000002,7.4000000000000004,7.9000000000000004,6.4000000000000004,6.2999999999999998,6.0999999999999996,7.7000000000000002,6.2999999999999998,6.4000000000000004,6,6.9000000000000004,6.7000000000000002,6.9000000000000004,5.7999999999999998,6.7999999999999998,6.7000000000000002,6.7000000000000002,6.2999999999999998,6.5,6.2000000000000002,5.9000000000000004],\"y\":[3.2999999999999998,2.7000000000000002,3,2.8999999999999999,3,3,2.5,2.8999999999999999,2.5,3.6000000000000001,3.2000000000000002,2.7000000000000002,3,2.5,2.7999999999999998,3.2000000000000002,3,3.7999999999999998,2.6000000000000001,2.2000000000000002,3.2000000000000002,2.7999999999999998,2.7999999999999998,2.7000000000000002,3.2999999999999998,3.2000000000000002,2.7999999999999998,3,2.7999999999999998,3,2.7999999999999998,3.7999999999999998,2.7999999999999998,2.7999999999999998,2.6000000000000001,3,3.3999999999999999,3.1000000000000001,3,3.1000000000000001,3.1000000000000001,3.1000000000000001,2.7000000000000002,3.2000000000000002,3.2999999999999998,3,2.5,3,3.3999999999999999,3],\"z\":[10.25,8.7699999999999996,10.23,9.4199999999999999,9.9100000000000001,10.970000000000001,7.6999999999999993,10.41,9.5600000000000005,10.92,9.4199999999999999,9.2099999999999991,9.8000000000000007,8.5999999999999996,9.0699999999999985,9.6600000000000001,9.5,11.539999999999999,11.130000000000001,8.3499999999999996,10.190000000000001,8.629999999999999,10.94,8.8300000000000001,10.040000000000001,10.300000000000001,8.7599999999999998,8.879999999999999,9.5700000000000003,9.9600000000000009,10.319999999999999,11.33,9.6199999999999992,8.8699999999999992,8.9699999999999989,10.77,9.9699999999999989,9.5,8.7599999999999998,9.8300000000000001,10.02,9.7200000000000006,8.7699999999999996,10.280000000000001,10.24,9.6400000000000006,8.8499999999999996,9.3900000000000006,9.7300000000000004,8.9199999999999999],\"mode\":\"markers\",\"marker\":{\"color\":\"rgba(77,175,74,1)\",\"size\":5,\"opacity\":0.80000000000000004,\"line\":{\"color\":\"rgba(77,175,74,1)\"}},\"text\":[\"Sepal Length: 6.3 <br> Sepal Width: 3.3 <br> Petal Length: 6 <br> Petal Width: 2.5\",\"Sepal Length: 5.8 <br> Sepal Width: 2.7 <br> Petal Length: 5.1 <br> Petal Width: 1.9\",\"Sepal Length: 7.1 <br> Sepal Width: 3 <br> Petal Length: 5.9 <br> Petal Width: 2.1\",\"Sepal Length: 6.3 <br> Sepal Width: 2.9 <br> Petal Length: 5.6 <br> Petal Width: 1.8\",\"Sepal Length: 6.5 <br> Sepal Width: 3 <br> Petal Length: 5.8 <br> Petal Width: 2.2\",\"Sepal Length: 7.6 <br> Sepal Width: 3 <br> Petal Length: 6.6 <br> Petal Width: 2.1\",\"Sepal Length: 4.9 <br> Sepal Width: 2.5 <br> Petal Length: 4.5 <br> Petal Width: 1.7\",\"Sepal Length: 7.3 <br> Sepal Width: 2.9 <br> Petal Length: 6.3 <br> Petal Width: 1.8\",\"Sepal Length: 6.7 <br> Sepal Width: 2.5 <br> Petal Length: 5.8 <br> Petal Width: 1.8\",\"Sepal Length: 7.2 <br> Sepal Width: 3.6 <br> Petal Length: 6.1 <br> Petal Width: 2.5\",\"Sepal Length: 6.5 <br> Sepal Width: 3.2 <br> Petal Length: 5.1 <br> Petal Width: 2\",\"Sepal Length: 6.4 <br> Sepal Width: 2.7 <br> Petal Length: 5.3 <br> Petal Width: 1.9\",\"Sepal Length: 6.8 <br> Sepal Width: 3 <br> Petal Length: 5.5 <br> Petal Width: 2.1\",\"Sepal Length: 5.7 <br> Sepal Width: 2.5 <br> Petal Length: 5 <br> Petal Width: 2\",\"Sepal Length: 5.8 <br> Sepal Width: 2.8 <br> Petal Length: 5.1 <br> Petal Width: 2.4\",\"Sepal Length: 6.4 <br> Sepal Width: 3.2 <br> Petal Length: 5.3 <br> Petal Width: 2.3\",\"Sepal Length: 6.5 <br> Sepal Width: 3 <br> Petal Length: 5.5 <br> Petal Width: 1.8\",\"Sepal Length: 7.7 <br> Sepal Width: 3.8 <br> Petal Length: 6.7 <br> Petal Width: 2.2\",\"Sepal Length: 7.7 <br> Sepal Width: 2.6 <br> Petal Length: 6.9 <br> Petal Width: 2.3\",\"Sepal Length: 6 <br> Sepal Width: 2.2 <br> Petal Length: 5 <br> Petal Width: 1.5\",\"Sepal Length: 6.9 <br> Sepal Width: 3.2 <br> Petal Length: 5.7 <br> Petal Width: 2.3\",\"Sepal Length: 5.6 <br> Sepal Width: 2.8 <br> Petal Length: 4.9 <br> Petal Width: 2\",\"Sepal Length: 7.7 <br> Sepal Width: 2.8 <br> Petal Length: 6.7 <br> Petal Width: 2\",\"Sepal Length: 6.3 <br> Sepal Width: 2.7 <br> Petal Length: 4.9 <br> Petal Width: 1.8\",\"Sepal Length: 6.7 <br> Sepal Width: 3.3 <br> Petal Length: 5.7 <br> Petal Width: 2.1\",\"Sepal Length: 7.2 <br> Sepal Width: 3.2 <br> Petal Length: 6 <br> Petal Width: 1.8\",\"Sepal Length: 6.2 <br> Sepal Width: 2.8 <br> Petal Length: 4.8 <br> Petal Width: 1.8\",\"Sepal Length: 6.1 <br> Sepal Width: 3 <br> Petal Length: 4.9 <br> Petal Width: 1.8\",\"Sepal Length: 6.4 <br> Sepal Width: 2.8 <br> Petal Length: 5.6 <br> Petal Width: 2.1\",\"Sepal Length: 7.2 <br> Sepal Width: 3 <br> Petal Length: 5.8 <br> Petal Width: 1.6\",\"Sepal Length: 7.4 <br> Sepal Width: 2.8 <br> Petal Length: 6.1 <br> Petal Width: 1.9\",\"Sepal Length: 7.9 <br> Sepal Width: 3.8 <br> Petal Length: 6.4 <br> Petal Width: 2\",\"Sepal Length: 6.4 <br> Sepal Width: 2.8 <br> Petal Length: 5.6 <br> Petal Width: 2.2\",\"Sepal Length: 6.3 <br> Sepal Width: 2.8 <br> Petal Length: 5.1 <br> Petal Width: 1.5\",\"Sepal Length: 6.1 <br> Sepal Width: 2.6 <br> Petal Length: 5.6 <br> Petal Width: 1.4\",\"Sepal Length: 7.7 <br> Sepal Width: 3 <br> Petal Length: 6.1 <br> Petal Width: 2.3\",\"Sepal Length: 6.3 <br> Sepal Width: 3.4 <br> Petal Length: 5.6 <br> Petal Width: 2.4\",\"Sepal Length: 6.4 <br> Sepal Width: 3.1 <br> Petal Length: 5.5 <br> Petal Width: 1.8\",\"Sepal Length: 6 <br> Sepal Width: 3 <br> Petal Length: 4.8 <br> Petal Width: 1.8\",\"Sepal Length: 6.9 <br> Sepal Width: 3.1 <br> Petal Length: 5.4 <br> Petal Width: 2.1\",\"Sepal Length: 6.7 <br> Sepal Width: 3.1 <br> Petal Length: 5.6 <br> Petal Width: 2.4\",\"Sepal Length: 6.9 <br> Sepal Width: 3.1 <br> Petal Length: 5.1 <br> Petal Width: 2.3\",\"Sepal Length: 5.8 <br> Sepal Width: 2.7 <br> Petal Length: 5.1 <br> Petal Width: 1.9\",\"Sepal Length: 6.8 <br> Sepal Width: 3.2 <br> Petal Length: 5.9 <br> Petal Width: 2.3\",\"Sepal Length: 6.7 <br> Sepal Width: 3.3 <br> Petal Length: 5.7 <br> Petal Width: 2.5\",\"Sepal Length: 6.7 <br> Sepal Width: 3 <br> Petal Length: 5.2 <br> Petal Width: 2.3\",\"Sepal Length: 6.3 <br> Sepal Width: 2.5 <br> Petal Length: 5 <br> Petal Width: 1.9\",\"Sepal Length: 6.5 <br> Sepal Width: 3 <br> Petal Length: 5.2 <br> Petal Width: 2\",\"Sepal Length: 6.2 <br> Sepal Width: 3.4 <br> Petal Length: 5.4 <br> Petal Width: 2.3\",\"Sepal Length: 5.9 <br> Sepal Width: 3 <br> Petal Length: 5.1 <br> Petal Width: 1.8\"],\"hoverinfo\":[\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\"],\"type\":\"scatter3d\",\"name\":\"virginica\",\"textfont\":{\"color\":\"rgba(77,175,74,1)\"},\"error_y\":{\"color\":\"rgba(77,175,74,1)\"},\"error_x\":{\"color\":\"rgba(77,175,74,1)\"},\"line\":{\"color\":\"rgba(77,175,74,1)\"},\"frame\":null}],\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n:::\n:::::\n\n# PCA Assumptions - Critical to Check First!\n\n## Key Assumptions:\n\n1.  **Linear relationships** between variables\n2.  **No extreme outliers** (can distort results)\n3.  **Variables should be correlated** (if not, PCA won't reduce\n    dimensions)\n4.  **Adequate sample size** (generally n \\> 50, preferably n \\> 100)\n5.  **No missing data** (complete cases only)\n6.  **Consider standardization** when variables have different scales\n\n**Important**: PCA works best when original variables are moderately to\nhighly correlated!\n\n**Let's check these assumptions with our iris data...**\n\n# Step 2: Check PCA Assumptions - Correlations\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Correlation Matrix:\"\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             sepal_length sepal_width petal_length petal_width\nsepal_length        1.000      -0.118        0.872       0.818\nsepal_width        -0.118       1.000       -0.428      -0.366\npetal_length        0.872      -0.428        1.000       0.963\npetal_width         0.818      -0.366        0.963       1.000\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](17_01_lecture_powerpoint_files/figure-html/check_correlations-1.png){width=672}\n:::\n:::\n\n\n# Step 2: Check PCA Assumptions - Linearity\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](17_01_lecture_powerpoint_files/figure-html/check_linearity-1.png){width=672}\n:::\n:::\n\n\n# Step 2: Check PCA Assumptions - Outliers\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](17_01_lecture_powerpoint_files/figure-html/check_outliers-1.png){width=672}\n:::\n:::\n\n\n# Step 3: Standardize the Data\n\n## STANDARDIZATION: Making all variables comparable\n\n::::: columns\n::: {.column width=\"60%\"}\nWhy standardize?\n\nOur measurements have different units and scales:\n\n-   Sepal length: ranges from \\~4-8 cm\n-   Sepal width: ranges from \\~2-4 cm\n-   Petal length: ranges from \\~1-7 cm\n-   Petal width: ranges from \\~0.1-2.5 cm\n\nWithout standardization, PCA would be dominated by variables with larger\nnumbers (like petal length) simply because they have bigger values, not\nbecause they're more important biologically\n\nWhat does standardization do?\n\n-   Converts each variable to have:\n    -   Mean = 0 (centered at zero)\n    -   Standard deviation = 1 (same spread)\n    -   This gives all variables equal weight in the analysis\n\nHow to interpret standardized values: Example: A sepal length of 5.1 cm\nmight become -0.9 after standardization, meaning it's 0.9 standard\ndeviations below the average sepal length\n:::\n\n::: {.column width=\"40%\"}\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Means after standardization (should be ~0):\"\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsepal_length  sepal_width petal_length  petal_width \n           0            0            0            0 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Standard deviations after standardization (should be 1):\"\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsepal_length  sepal_width petal_length  petal_width \n           1            1            1            1 \n```\n\n\n:::\n:::\n\n:::\n:::::\n\n# Step 4: Perform PCA - The Mathematics\n\n::::: columns\n::: {.column width=\"60%\"}\n## What is PCA doing?\n\nPrincipal Component Analysis finds new variables (called components)\nthat capture the most variation in your data. Think of it as finding the\n\"best viewing angles\" to see differences between flowers.\n\n## The mathematics (simplified):\n\n-   PCA rotates your data to find the direction with maximum spread\n    (PC1)\n-   Then finds the next direction with maximum spread perpendicular to\n    PC1 (PC2)\n-   Continues until it has as many components as original variables (4\n    in our case)\n\n## Why center = FALSE and scale = FALSE?\n\nWe already standardized our data in Step 3, so we tell R not to do it\nagain: - center = FALSE: Don't subtract the mean (we already did) -\nscale = FALSE: Don't divide by standard deviation (we already did)\n\n## What the summary shows:\n\n-   **Standard deviation**: How much variation each component captures\n-   **Proportion of Variance**: Percentage of total variation explained\n    by each component\n-   **Cumulative Proportion**: Running total of variance explained\n:::\n\n::: {.column width=\"40%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\n# Perform PCA on standardized data\niris_pca <- prcomp(iris_scaled, center = FALSE, scale. = FALSE)\n# Note: center and scale are FALSE because we already standardized\n\n# Alternative using vegan package\niris_pca_vegan <- rda(iris_scaled)\n\n# Summary of PCA results\nsummary(iris_pca)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nImportance of components:\n                          PC1    PC2     PC3     PC4\nStandard deviation     1.7084 0.9560 0.38309 0.14393\nProportion of Variance 0.7296 0.2285 0.03669 0.00518\nCumulative Proportion  0.7296 0.9581 0.99482 1.00000\n```\n\n\n:::\n:::\n\n:::\n:::::\n\n# Deriving Components: 2D Visualization\n\n::::: columns\n::: {.column width=\"60%\"}\nHow are new uncorrelated components derived? One way to think it is in\nterms of axis rotation Consider a 2-variable dataset:\n:::\n\n::: {.column width=\"40%\"}\n![](images/clipboard-1945433117.png){width=\"500\"}\n:::\n:::::\n\n# Component Derivation: Axis Rotation\n\n::::: columns\n::: {.column width=\"60%\"}\nGoal is to \"rotate the axes\" around center of the data \"cloud\" in such a\nway that most of the variation lies along the first axis Then find\nsecond axis that explains the second-most variation AND is orthogonal to\nfirst axis\n:::\n\n::: {.column width=\"40%\"}\n![](images/clipboard-369995082.png){width=\"500\"}\n:::\n:::::\n\n# Component Derivation: Multivariate Extension\n\n::::: columns\n::: {.column width=\"60%\"}\nEasy to picture in 2D (or even 3D), but harder in multivariate space\nPractically, components are \"extracted\" from a covariance of correlation\nmatrix among original variables Will extract as many principal\ncomponents as original variables\n:::\n\n::: {.column width=\"40%\"}\n![](images/clipboard-1512013712.png){width=\"500\"}\n:::\n:::::\n\n# Component Information: Eigenvalues and Eigenvectors\n\n-   Get two important pieces of information from PCA: eigenvectors and\n    eigenvalues\n-   Eigenvalues (latent roots)- how much of the variation is explained\n    by each component?\n-   Eigenvectors- list of coefficients for original variables. There are\n    p coefficients in an eigenvector and p eigenvectors\n-   Correlation bw original variables will result in fewer components\n    explaining more variance; variable reduction will fail if original\n    variables are not correlated\n\n# Step 4: Understanding Eigenvalues and Variance\n\n::::: columns\n::: {.column width=\"60%\"}\n## Understanding Eigenvalues and Variance\n\n### What are eigenvalues?\n\n-   Eigenvalues tell us how much variation each principal component\n    captures.\n-   Larger eigenvalues = more important components.\n\n### Key terms explained:\n\n-   **Eigenvalue**: The amount of variance captured by each component\n    (always positive)\n-   **Proportion of Variance**: What percentage of total variation this\n    component explains\n-   **Cumulative Variance**: Running total - helps us decide how many\n    components we need\n\n### How to read the results:\n\n-   If PC1 has eigenvalue = 2.9, it captures 2.9 \"units\" of variance\n-   If Prop_Variance = 0.728, PC1 explains 72.8% of all variation in the\n    data\n-   If Cumsum_Variance = 0.959 at PC2, the first 2 components together\n    explain 95.9% of variation\n\n### Why this matters:\n\nThis table helps us decide how many components to keep.\n\n-   If 2 components explain 95% of variance, we've successfully reduced\n    4 variables to 2\n-   We only lose 5% of information without including the other\n    variables!\n:::\n\n::: {.column width=\"40%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract eigenvalues (variance explained by each component)\neigenvalues <- iris_pca$sdev^2\nprop_variance <- eigenvalues / sum(eigenvalues)\ncumsum_variance <- cumsum(prop_variance)\n\n# Create a summary table\npca_summary <- data.frame(\n  Component = paste0(\"PC\", 1:length(eigenvalues)),\n  Eigenvalue = eigenvalues,\n  Prop_Variance = prop_variance,\n  Cumsum_Variance = cumsum_variance\n)\n\nprint(\"PCA Summary:\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"PCA Summary:\"\n```\n\n\n:::\n\n```{.r .cell-code}\nkable(pca_summary, digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|Component | Eigenvalue| Prop_Variance| Cumsum_Variance|\n|:---------|----------:|-------------:|---------------:|\n|PC1       |      2.918|         0.730|           0.730|\n|PC2       |      0.914|         0.229|           0.958|\n|PC3       |      0.147|         0.037|           0.995|\n|PC4       |      0.021|         0.005|           1.000|\n\n\n:::\n:::\n\n:::\n:::::\n\n# Step 5: Determine Number of Components - Scree Plot\n\n::::: columns\n::: {.column width=\"60%\"}\n## What is a Scree Plot?\n\nA scree plot shows how much variance each component explains, helping us\ndecide how many components we need. The name comes from the geological\nterm \"scree\" - loose rocks at the base of a cliff - because the plot\noften looks like a steep cliff followed by rubble.\n\n## How to read a Scree Plot:\n\n-   **Y-axis**: Percentage of variance explained by each component\n-   **X-axis**: Component number (PC1, PC2, etc.)\n-   **The pattern**: Usually shows a steep drop followed by a leveling\n    off\n\n## The \"Elbow Method\":\n\nLook for where the line \"bends\" or forms an elbow:\n\n-   Components before the elbow = important (steep slope)\n-   Components after the elbow = less important (gentle slope)\n-   Keep components up to and including the elbow\n\n## What to look for in our plot:\n\n-   If PC1 explains 70% and PC2 explains 20%, but PC3 only explains 5%,\n    the elbow is at PC2\n-   This suggests keeping the first 2 components\n-   The dramatic drop from PC1 to PC2, then gentle decline after,\n    confirms our dimension reduction worked well\n:::\n\n::: {.column width=\"40%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](17_01_lecture_powerpoint_files/figure-html/scree_plot-1.png){width=672}\n:::\n:::\n\n:::\n:::::\n\n# Step 5: Component Selection Rules\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Eigenvalue > 1 rule (Kaiser criterion)\ncomponents_to_keep <- sum(eigenvalues > 1)\nprint(paste(\"Components with eigenvalue > 1:\", components_to_keep))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Components with eigenvalue > 1: 1\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# Components explaining at least 80% of variance\ncomponents_80_percent <- which(cumsum_variance >= 0.80)[1]\nprint(paste(\"Components needed for 80% variance:\", components_80_percent))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Components needed for 80% variance: 2\"\n```\n\n\n:::\n:::\n\n\n# Step 6: Interpret the Components - Loadings\n\n::::: columns\n::: {.column width=\"60%\"}\n## What are Component Loadings\n\nLoadings tell us how much each original variable contributes to each\nprincipal component. Think of them as \"recipes\" that show how to mix\nyour original measurements to create the new components.\n\n## How to read the loadings table\n\n-   **Values range from -1 to +1** (like correlations)\n-   **Large positive values** (e.g., 0.8): This variable contributes\n    strongly in the positive direction\n-   **Large negative values** (e.g., -0.8): This variable contributes\n    strongly in the negative direction\n-   **Values near 0**: This variable doesn't contribute much to this\n    component\n\n## Interpreting the patterns:\n\n-   **If all loadings have similar signs**: Component represents overall\n    size (all measurements increase/decrease together)\n-   **If loadings have mixed signs**: Component represents shape or\n    proportions (some measurements increase while others decrease)\n-   **Dominant variables**: Variables with the largest absolute loadings\n    drive that component's meaning\n\n## Example interpretation:\n\nIf PC1 has all negative loadings around -0.5, it means:\n\n-   Flowers with high PC1 scores have small values for ALL measurements\n-   This component captures \"overall flower size\"\n-   The negative sign just indicates direction (could flip signs and\n    interpretation)\n:::\n\n::: {.column width=\"40%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\n# Component loadings (how much each original variable contributes)\nloadings_df <- data.frame(\n  Variable = rownames(iris_pca$rotation),\n  PC1 = iris_pca$rotation[, 1],\n  PC2 = iris_pca$rotation[, 2],\n  PC3 = iris_pca$rotation[, 3],\n  PC4 = iris_pca$rotation[, 4]\n)\n\nprint(\"Component Loadings:\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Component Loadings:\"\n```\n\n\n:::\n\n```{.r .cell-code}\nloadings_df\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 Variable        PC1         PC2        PC3        PC4\nsepal_length sepal_length  0.5210659 -0.37741762  0.7195664  0.2612863\nsepal_width   sepal_width -0.2693474 -0.92329566 -0.2443818 -0.1235096\npetal_length petal_length  0.5804131 -0.02449161 -0.1421264 -0.8014492\npetal_width   petal_width  0.5648565 -0.06694199 -0.6342727  0.5235971\n```\n\n\n:::\n:::\n\n:::\n:::::\n\n# Step 6: Eigenvector Properties\n\n### Key properties of eigenvectors/loadings:\n\n-   **Unit length**: Each eigenvector has length 1 (sum of squares = 1)\n-   **Orthogonal**: Eigenvectors are perpendicular to each other (dot\n    product = 0)\n-   **Ordered by importance**: First eigenvector (PC1) explains most\n    variance\n\n### The complete picture:\n\n-   **Eigenvectors** = The directions (loadings)\n-   **Eigenvalues** = The importance of each direction (variance\n    explained)\n-   Together they fully describe the PCA transformation\n\n# Step 6b: Visualization of Component Loadings\n\n::::: columns\n::: {.column width=\"60%\"}\nWhat does this plot show?\n\nThis is a visual representation of the loadings table, showing how each\noriginal variable contributes to PC1 and PC2. It's like a map of how\nyour original measurements relate to the new principal components.\n\nHow to read the plot:\n\n-   Arrows represent your original variables (sepal_length, sepal_width,\n    etc.)\n-   Arrow direction shows which PC the variable contributes to\n-   Arrow length indicates the strength of contribution (longer =\n    stronger)\n-   Arrow color shows the overall contribution magnitude (red = highest,\n    blue = lowest)\n-   The circle represents the maximum possible contribution\n\nKey interpretations from this plot:\n\n-   PC1 (horizontal axis, 73% variance):\n    -   All arrows point roughly left (negative direction)\n    -   All variables contribute almost equally to PC1\n    -   This confirms PC1 represents \"overall flower size\"\n\nPC2 (vertical axis, 22.9% variance):\n\n-   Sepal_width points down (negative)\n-   Other variables point slightly up (positive)\n-   This creates a contrast: sepal width vs. everything else\n-   PC2 captures \"flower shape\" - wide sepals vs. long petals\n:::\n\n::: {.column width=\"40%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](17_01_lecture_powerpoint_files/figure-html/loading_visualization-1.png){width=672}\n:::\n:::\n\n:::\n:::::\n\n# Loading Plot Interpretation\n\nWhat the arrow positions tell us:\n\n-   Variables pointing in same direction = positively correlated\n-   Variables at 90° angles = uncorrelated\n-   Variables pointing opposite directions = negatively correlated\n\nThe practical meaning:\n\n-   Flowers with high PC1 scores have large values for all measurements\n-   Flowers with high PC2 scores have narrow sepals but long/wide petals\n-   The plot confirms our dimension reduction worked - we've captured\n    95.9% of variation in just 2 dimensions!\n\n# Step 7: PCA Biplot - The Main Result\n\n::::: columns\n::: {.column width=\"60%\"}\n## Key insights from this biplot:\n\n### Species separation:\n\n-   **Setosa (blue)**: Clearly separated on the left (negative PC1)\n-   **Versicolor (yellow)**: In the middle\n-   **Virginica (red)**: On the right (positive PC1)\n-   PCA successfully separates species without being told about them!\n\n### Understanding flower characteristics:\n\n-   **Setosa flowers**: Small overall (negative PC1), relatively wide\n    sepals (positive PC2)\n-   **Virginica flowers**: Large overall (positive PC1), especially long\n    petals\n-   **Versicolor flowers**: Intermediate in most characteristics\n\n### Variable relationships:\n\n-   Petal measurements point together → highly correlated\n-   Sepal width points differently → captures different information\n-   All arrows point right → all measurements increase from setosa to\n    virginica\n:::\n\n::: {.column width=\"40%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](17_01_lecture_powerpoint_files/figure-html/pca_biplot_species-1.png){width=672}\n:::\n:::\n\n:::\n:::::\n\n# Step 7: PCA Scores Plot - Alternative Visualization\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Alternative scores plot\nggplot(pca_scores, aes(x = PC1, y = PC2, color = species)) +\n  geom_point(size = 3, alpha = 0.7) +\n  stat_ellipse(level = 0.68, linetype = 2) +  # Add ellipses\n  labs(title = \"PCA Scores Plot\",\n       subtitle = paste0(\"PC1 explains \", round(prop_variance[1]*100, 1), \n                        \"% of variance, PC2 explains \", round(prop_variance[2]*100, 1), \"%\"),\n       x = paste0(\"PC1 (\", round(prop_variance[1]*100, 1), \"%)\"),\n       y = paste0(\"PC2 (\", round(prop_variance[2]*100, 1), \"%)\"),\n       color = \"Species\") +\n  theme_minimal() +\n  scale_color_manual(values = c(\"#00AFBB\", \"#E7B800\", \"#FC4E07\"))\n```\n\n::: {.cell-output-display}\n![](17_01_lecture_powerpoint_files/figure-html/pca_scores_plot-1.png){width=672}\n:::\n:::\n\n\n# Step 8: Interpret PC1 Results\n\n### Understanding PC1 Loadings:\n\nThe loadings show how each original variable contributes to PC1:\n\n-   **Sepal length: 0.521** - Strong positive contribution\n-   **Sepal width: -0.269** - Moderate negative contribution\n-   **Petal length: 0.580** - Strong positive contribution\n-   **Petal width: 0.565** - Strong positive contribution\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# What does PC1 represent?\npc1_loadings <- iris_pca$rotation[, 1]\nprint(\"PC1 Loadings (all variables contribute similarly):\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"PC1 Loadings (all variables contribute similarly):\"\n```\n\n\n:::\n\n```{.r .cell-code}\nround(pc1_loadings, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsepal_length  sepal_width petal_length  petal_width \n       0.521       -0.269        0.580        0.565 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nPC1 Interpretation: Overall flower size\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nPC1 Interpretation: Overall flower size\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\n- All variables have similar negative loadings\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n- All variables have similar negative loadings\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\n- Higher PC1 values = smaller flowers overall\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n- Higher PC1 values = smaller flowers overall\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\n- Lower PC1 values = larger flowers overall\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n- Lower PC1 values = larger flowers overall\n```\n\n\n:::\n:::\n\n\n# PC1 Interpretation: Overall Flower Size\n\n### PC1 Interpretation: Overall flower size (with a twist)\n\nNote: The output says \"all variables have similar negative loadings\" but\nthe actual values show mostly positive loadings. This is likely due to a\nsign flip - PCA signs can be arbitrary. Let's interpret based on the\nactual values shown:\n\n-   **Three variables (sepal length, petal length, petal width) have\n    similar positive loadings** (\\~0.52-0.58)\n-   **Sepal width has a negative loading** (-0.269)\n-   This means PC1 captures flowers where length and width measurements\n    (except sepal width) vary together\n\n### What PC1 scores mean:\n\n-   **Higher PC1 values** = Longer petals, longer sepals, wider petals,\n    but narrower sepals\n-   **Lower PC1 values** = Shorter petals, shorter sepals, narrower\n    petals, but wider sepals\n-   PC1 essentially captures \"overall flower size except sepal width\n    goes opposite\"\n\n### Biological interpretation:\n\nPC1 distinguishes between:\n\n-   Small flowers with relatively wide sepals (negative PC1) - typical\n    of setosa\n-   Large flowers with relatively narrow sepals (positive PC1) - typical\n    of virginica\n\n# Step 8: Interpret PC2 Results\n\n### Understanding PC2 Loadings:\n\nThe loadings show how each original variable contributes to PC2:\n\n-   **Sepal length: -0.377** - Moderate negative contribution\n-   **Sepal width: -0.923** - Very strong negative contribution\n-   **Petal length: -0.024** - Almost no contribution\n-   **Petal width: -0.067** - Very small negative contribution\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# What does PC2 represent?\npc2_loadings <- iris_pca$rotation[, 2]\nprint(\"PC2 Loadings:\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"PC2 Loadings:\"\n```\n\n\n:::\n\n```{.r .cell-code}\nround(pc2_loadings, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsepal_length  sepal_width petal_length  petal_width \n      -0.377       -0.923       -0.024       -0.067 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nPC2 Interpretation: Flower shape contrast\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nPC2 Interpretation: Flower shape contrast\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\n- Positive loadings: sepal width\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n- Positive loadings: sepal width\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\n- Negative loadings: petal length and width, sepal length\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n- Negative loadings: petal length and width, sepal length\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\n- Higher PC2 = wider sepals relative to petal size\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n- Higher PC2 = wider sepals relative to petal size\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\n- Lower PC2 = longer/wider petals relative to sepal width\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n- Lower PC2 = longer/wider petals relative to sepal width\n```\n\n\n:::\n:::\n\n\n# PC2 Interpretation: Flower Shape Contrast\n\n### PC2 Interpretation: Correcting the output\n\nNote: The output says \"Positive loadings: sepal width\" but the actual\nvalue is -0.923 (negative). All loadings are actually negative, with\nsepal width being the most strongly negative.\n\n### What PC2 actually represents:\n\n-   **All variables have negative loadings**, but sepal width is\n    dominant (-0.923)\n-   **Petal measurements contribute very little** (-0.024 and -0.067)\n-   **This component is primarily driven by sepal width**, with some\n    contribution from sepal length\n\n### What PC2 scores mean:\n\n-   **Higher PC2 values** = Smaller measurements overall, especially\n    narrow sepals\n-   **Lower PC2 values** = Larger measurements overall, especially wide\n    sepals\n-   Since sepal width has the strongest loading, PC2 primarily captures\n    sepal width variation\n\n### Biological interpretation:\n\nPC2 helps distinguish:\n\n-   Flowers with narrow sepals and smaller overall size (positive PC2)\n-   Flowers with wide sepals and larger overall size (negative PC2)\n-   This dimension helps separate species that have similar PC1 scores\n    but different sepal proportions\n\n# Step 9: How Well Does PCA Work?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate total variance explained by first 2 components\nvariance_explained_2pc <- sum(prop_variance[1:2])\ncaption_pca <- paste(\"Variance explained by first 2 components:\", round(variance_explained_2pc * 100, 1), \"%\")\n\n# This means we reduced 4 variables to 2 components while retaining most information!\n\n# Create a summary plot showing dimension reduction success\ntibble(\n  Component = factor(paste0(\"PC\", 1:4), levels = paste0(\"PC\", 1:4)),\n  Variance = prop_variance * 100,\n  Cumulative = cumsum_variance * 100\n) %>% \n  ggplot(aes(x = Component)) +\n  geom_col(aes(y = Variance), fill = \"lightblue\", alpha = 0.7) +\n  geom_line(aes(y = Cumulative, group = 1), color = \"red\", size = 1) +\n  geom_point(aes(y = Cumulative), color = \"red\", size = 3) +\n  labs(title = \"PCA Dimension Reduction Success\",\n       subtitle = \"Blue bars = individual variance, Red line = cumulative variance\",\n       caption = caption_pca,\n       x = \"Principal Component\", \n       y = \"Percentage of Variance Explained\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](17_01_lecture_powerpoint_files/figure-html/pca_effectiveness-1.png){width=672}\n:::\n:::\n\n\n# Summary: What We Learned\n\n## Key Findings:\n\n1.  **Successful dimension reduction**: 4 variables → 2 components\n    explaining \\~96% of variance\n\n2.  **PC1 (72.8% variance)**: Overall flower size\n\n    -   All measurements contribute similarly\n    -   Separates large from small flowers\n\n3.  **PC2 (23.1% variance)**: Shape contrast\n\n    -   Sepal width vs. petal dimensions\n    -   Separates flower shape types\n\n4.  **Species separation**: PCA naturally groups the three iris species\n    based on their morphological differences\n\n## PCA Success Criteria Met:\n\n✓ Variables were correlated\\\n✓ Linear relationships\\\n✓ No major outliers\\\n✓ Adequate sample size\\\n✓ Clear dimension reduction\\\n✓ Interpretable components\n\n# When to Use PCA vs. Other Methods\n\n## Use PCA when:\n\n-   Variables are **continuous and correlated**\n-   Goal is **dimension reduction** or **data exploration**\n-   Linear relationships between variables\n-   Want to **remove redundancy** in measurements\n\n## Consider alternatives when:\n\n-   Variables are categorical → use MCA (Multiple Correspondence\n    Analysis)\n-   Focus on **species composition** → use ordination methods like NMDS\n-   Want to **classify/predict** → use discriminant analysis or machine\n    learning\n\n**PCA is excellent for exploring patterns in biological measurements\nlike morphology, physiology, or environmental variables!**\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/htmltools-fill-0.5.9/fill.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"../../site_libs/plotly-binding-4.12.0/plotly.js\"></script>\n<script src=\"../../site_libs/typedarray-0.1/typedarray.min.js\"></script>\n<script src=\"../../site_libs/jquery-3.5.1/jquery.min.js\"></script>\n<link href=\"../../site_libs/crosstalk-1.2.2/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/crosstalk-1.2.2/js/crosstalk.min.js\"></script>\n<link href=\"../../site_libs/plotly-htmlwidgets-css-2.25.2/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/plotly-main-2.25.2/plotly-latest.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}