project:
  type: website
  output-dir: docs

website:
  title: "UMD Biostatistics"
  site-url: "https://your-site-url.github.io"

  sidebar:
    logo: "images/course-hex.png"
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Course Information"
        contents:
          - href: index.qmd
            text: "Schedule"
          - href: syllabus.qmd
            text: "Syllabus"
          - href: overview.qmd
            text: "Overview"
          - href: links.qmd
            text: "Helpful Links"
            
      - section: "Course Materials"
        contents:
          - href: lectures/index.qmd 
            text: "Lectures"
          - href: activities/index.qmd
            text: "Activities"
          - href: homeworks/index.qmd
            text: "Homeworks"
          - href: assingments/index.qmd
            text: "Assignments"
          - href: vignettes/index.qmd
            text: "Vignettes"
           
  open-graph: true

  page-footer:
    left: "© 2026 UMD Biostatistics"
    right: 
      - icon: github
        href: https://github.com/wlperry
      - icon: envelope-heart-fill
        href: mailto:wlperry@d.umn.edu

format:
  html:
    theme: css/theme.scss
    css: styles.css  # Fixed! Removed css/ since the file is in your main directory
    toc: true