project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Ecological Statistics 2026"
  description: "Homepage for Ecostats ### - University of Minnesota-Duluth, Fall 2026."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

open-graph: true

page-footer:
  right: "This page is built with Positron and [Quarto](https://quarto.org/)."
  left: "&copy; Copyright 2026, Bill Perry"
  background: "#D9E3E4"

sidebar:
    background: "#D9E3E4"
    logo: "images/course-hex.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/wlperry/ecostats_2026
        text: "GitHub class"
      - icon: github
        href: https://canvas.umn.edu/
        text: "Canvas"
      - icon: person-fill
        text: "stuff to add"
        menu:
            - text: Bills Page
              href: https://wlperry.github.io/index.html


style: "docked"
search: true
collapse-level: 1
contents:
  - section: "Course information"
    contents:
      - href: index.qmd
        text: Schedule
      - href: overview.qmd
        text: Overview
      - href: syllabus.qmd
        text: Syllabus
      - href: links.qmd
        text: Useful links
  - section: "Vignettes"
    contents:
      - href: vignettes/slr-derivations.qmd
        text: Vignettes

execute:
  freeze: auto
  cache: true
  echo: true
  keep-md: true
  message: true
  warning: true
  paged-print: false

format:
  html:
    theme:
      light: [cosmo, css/theme.scss]
      dark: [cosmo, css/theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true
    css: css/activity.css # Global CSS for all HTML pages

editor: visual