---
title: "UMD Biostatistics: Schedule"
page-layout: full
---

This page contains the schedule and links for lectures, activities, homework, and common_code for Data Science Fall 2026. I am currently working on updating the lectures and intro specifically so we have more trianing for using R to facilitate doing the statistics easier.

::::::::::::::::::: column-screen-inset-right
### Week 1: Foundations

::: {layout-ncol="2"}
#### 01 - Introduction - Start with R

- [🖥️ Lecture](lectures/lecture_01/01_lecture_powerpoint.qmd)
- [📋 Activity](activities/lecture_01/01_class_activity.qmd)
- [💻 Homework](homeworks/hw_01/01_homework.qmd)

#### 02 - Project Design and Graphing data

- [🖥️ Lecture](lectures/lecture_02/02_lecture_powerpoint.qmd)
- [📋 Activity](activities/lecture_02/02_class_activity.qmd)
:::

------------------------------------------------------------------------

### Week 2:

::: {layout-ncol="2"}
#### 03 -

- [🖥️ Lecture](lectures/lecture_03/03_lecture_powerpoint.qmd)
- [📋 Activity](activities/lecture_03/03_class_activity.qmd)
- [💻 Homework](homeworks/hw_03/03_homework.qmd)

#### 04 -

- [🖥️ Lecture](lectures/lecture_04/04_lecture_powerpoint.qmd)
- [📋 Activity](activities/lecture_04/04_class_activity.qmd)
:::

------------------------------------------------------------------------

### Week 3:

::: {layout-ncol="2"}
#### 05 -

- [🖥️ Lecture](lectures/lecture_05/05_lecture_powerpoint.qmd)
- [📋 Activity](activities/lecture_05/05_class_activity.qmd)
- [💻 Homework](homeworks/hw_05/05_homework.qmd)

#### 06 -

- [🖥️ Lecture](lectures/lecture_06/06_lecture_powerpoint.qmd)
- [📋 Activity](activities/lecture_06/06_class_activity.qmd)
:::

------------------------------------------------------------------------

### Week 4:

::: {layout-ncol="2"}
#### 07 -

- [🖥️ Lecture](lectures/lecture_07/07_lecture_powerpoint.qmd)
- [📋 Activity](activities/lecture_07/07_class_activity.qmd)
- [💻 Homework](homeworks/hw_07/07_homework.qmd)

#### 08 -

- [🖥️ Lecture](lectures/lecture_08/08_lecture_powerpoint.qmd)
- [📋 Activity](activities/lecture_08/08_class_activity.qmd)
:::

------------------------------------------------------------------------

### Week 5:

::: {layout-ncol="1"}
#### 09 -

- [🖥️ Lecture](lectures/lecture_09/09_lecture_powerpoint.qmd)
- [📋 Activity](activities/lecture_09/09_class_activity.qmd)
- [💻 Homework](homeworks/hw_09/09_homework.qmd)

#### 10 -

- [🖥️ Lecture](lectures/lecture_10/10_lecture_powerpoint.qmd)
- [📋 Activity](activities/lecture_10/10_class_activity.qmd)
:::

------------------------------------------------------------------------

### Week 6:

::: {layout-ncol="2"}
#### 11 -

- [🖥️ Lecture](lectures/lecture_11/11_lecture_powerpoint.qmd)
- [📋 Activity](activities/lecture_11/11_class_activity.qmd)
- [💻 Homework](homeworks/hw_11/11_homework.qmd)

#### 12 -

- [🖥️ Lecture](lectures/lecture_12/12_lecture_powerpoint.qmd)
- [📋 Activity](activities/lecture_12/12_class_activity.qmd)
- 📖 Common Code: *(Coming Soon)*
:::

------------------------------------------------------------------------

### Week 7:

::: {layout-ncol="2"}
#### 13 -

- [🖥️ Lecture](lectures/lecture_13/13_lecture_powerpoint.qmd)
- [📋 Activity](activities/lecture_13/13_class_activity.qmd)
- [💻 Homework](homeworks/hw_13/13_homework.qmd)

#### 14 -

- [🖥️ Lecture](lectures/lecture_14/14_lecture_powerpoint.qmd)
- [📋 Activity](activities/lecture_14/14_class_activity.qmd)
- 📖 Common Code: *(Coming Soon)*
:::

------------------------------------------------------------------------

### Week 8:

::: {layout-ncol="2"}
#### 15 -

- [🖥️ Lecture](lectures/lecture_15/15_lecture_powerpoint.qmd)
- [📋 Activity](activities/lecture_15/15_class_activity.qmd)
- [💻 Homework](homeworks/hw_15/15_homework.qmd)

#### 16 -

- [🖥️ Lecture](lectures/lecture_16/16_lecture_powerpoint.qmd)
- [📋 Activity](activities/lecture_16/16_class_activity.qmd)
- 📖 Common Code: *(Coming Soon)*
:::

------------------------------------------------------------------------

### Week 9:

::: {layout-ncol="2"}
#### 17 -

- [🖥️ Lecture](lectures/lecture_17/17_lecture_powerpoint.qmd)
- [📋 Activity](activities/lecture_17/17_class_activity.qmd)
- [💻 Homework](homeworks/hw_17/17_homework.qmd)

#### 18 -

- [🖥️ Lecture](lectures/lecture_18/18_lecture_powerpoint.qmd)
- [📋 Activity](activities/lecture_18/18_class_activity.qmd)
:::

------------------------------------------------------------------------

### Week 10:

::: {layout-ncol="2"}
#### 19 - Review

- [🖥️ Lecture](lectures/lecture_19/19_lecture_powerpoint.qmd)

#### 20 -

- [🖥️ Lecture](lectures/lecture_20/20_lecture_powerpoint.qmd)
:::

------------------------------------------------------------------------

### Week 11:

::: {layout-ncol="2"}
#### 21 -

- [🖥️ Lecture](lectures/lecture_21/21_lecture_powerpoint.qmd)

#### 22 -

- [🖥️ Lecture](lectures/lecture_22/22_lecture_powerpoint.qmd)
:::

------------------------------------------------------------------------

### Week 12:

::: {layout-ncol="2"}
#### 23 -

- [🖥️ Lecture](lectures/lecture_23/23_lecture_powerpoint.qmd)

#### 24 -

- [🖥️ Lecture](lectures/lecture_24/24_lecture_powerpoint.qmd)
:::

------------------------------------------------------------------------

### Week 13:

::: {layout-ncol="2"}
#### 25 -

- [🖥️ Lecture](lectures/lecture_25/25_lecture_powerpoint.qmd)

#### 26 -

- [🖥️ Lecture](lectures/lecture_26/26_lecture_powerpoint.qmd)
:::

------------------------------------------------------------------------

### Week 14:

::: {layout-ncol="2"}
#### 27 -

- [🖥️ Lecture](lectures/lecture_27/27_lecture_powerpoint.qmd)

#### 28 -

- [🖥️ Lecture](lectures/lecture_28/28_lecture_powerpoint.qmd)
:::

------------------------------------------------------------------------

### Week 15:

::: {layout-ncol="2"}
#### 29 -

- [🖥️ Lecture](lectures/lecture_29/29_lecture_powerpoint.qmd)

#### 30 -

- [🖥️ Lecture](lectures/lecture_30/30_lecture_powerpoint.qmd)
:::

### Common Code you might reference

::: {layout-ncol="2"}
#### - Libraries

- [📖 Common Code: libraries](common_code/01_libraries/01_libraries.qmd) \#### - Reading and writng files
- [📖 Common Code: Reading and writing files](common_code/02_reading_writing/02_reading_writing.qmd) \#### - GGPlot basics
- [📖 Common Code: GGPlot](common_code/03_ggplot/03_ggplot.qmd) \#### - Filtering and selecting data
- [📖 Common Code: filter_select](common_code/04_filter_select/04_filter_select.qmd) \#### - Mutating data
- [📖 Common Code: Mutate](common_code/05_mutate/05_mutate.qmd) \#### - Advanced Plotting
- [📖 Common Code: Advanced Plotting and Themes](common_code/06_advanced_plotting_themes/06_advanced_plotting_themes.qmd) \#### - Themes
- [📖 Common Code: Advanced Plotting and Themes](common_code/07_themes/07_themes.qmd) \#### - Descriptive Statistics
- [📖 Common Code: Advanced Plotting and Themes](common_code/08_descriptive_stats/08_desc_stats.qmd) \#### - T Tests
- [📖 Common Code: Advanced Plotting and Themes](common_code/09_ttest/09_ttest.qmd) \#### - Correlations and Regressions
- [📖 Common Code: Advanced Plotting and Themes](common_code/10_correlation_regression/10_correlation_regression.qmd) \#### - One Way Anova
- [📖 Common Code: Advanced Plotting and Themes](common_code/11_anova/11_anova.qmd)
:::
:::::::::::::::::::