---
title: "Syllabus"
format: 
  html:
    toc: false
    toc-depth: 3
  docx:
    default: true
    toc: false
    toc-depth: 3
    number-sections: false
    highlight-style: github
    reference-doc: ms_templates/custom-reference.docx
    css: css/msword.css
    embed-resources: true
about:
  template: marquee
  links:
    - icon: github
      href: https://github.com/wlperry
    - icon: envelope-heart-fill
      href: mailto:wlperry@d.umn.edu
---

# This is the tentative set of course policies 

| Semester - Fall 2026 | Instructor: Bill Perry |
|----|----|
| **When**: Tuesday and Thursday 9:30 - 10:45 | **Email**: wlperry\@d.umn.edu |
| **Where**: SSB 115 | **Assistant**: NONE |
| **How**: Mostly working through datascience topics in class with associated lectures but mosly doing data science rather than leccturing about it.  | **Assistant email**:  wlperry\@d.umn.edu |
| **Required materials**: The textbook and a laptop that is functional | **Office hours**: 13 SSB - TBD and by appointment or walk in |

## **Aim and Scope:**

Welcome to DAta Scinece! This is a practical course that will introduce you to the topics of data scinece and how to work wiht larger data sets using R and other scripting programs. We will use code rather than Excel to explore the data and will focus on developing your skills to code and analyze data extending your statistical background. The goal of the course is to enable you to explore data and tell a story from the data.  We will learn about common statistical approaches and datascience approachs used in ecology . Additionally, this course will provide opportunities for students to practice scientific writing and presentation skills.

## **Student learning outcomes:**

Learn some useful data skills and organizaiton and statistical methods and R skills.

## **Course Structure:**

The course will be taught in a combined lecture and laboratory format with mostly hands on activities assuming you have read the materials. Some of our meetings will take a primarily lecture and discussion format, others a primarily computer lab format, but most will have elements of both. Lecture portions will be dedicated to taking up homework questions, going over course concepts and discussing examples. Computer laboratory elements will be dedicated to using the R statistical computing package for data analysis and visualization.

Materials such as lecture slides, computer laboratories, homework, and assignments will be distributed through the course Canvas site or on this website. There will be no textbook for the course but we will usetilize many online tutorials and work through of them is some detail. THe primary books we will use are: 

- [**R Companion**](https://rcompanion.org/handbook/) - this is a great stats site with a lot of well done tests

- [**R4DataScience**](https://r4ds.hadley.nz/) - this is the book by Grolemund and Whickham that is really good

-   **A Compendium of Clean Graphs in R** (<http://shinyapps.org/apps/RGraphCompendium/index.php>)

## **Evaluation scheme:**

Your grade will be based on **homework**, **in-class quizzes on paper!**, **take-home assignments**, and **presentation and poster**:

I will be making this out of points as we get there

|                                          |       |
|------------------------------------------|-------|
|  Homework                                |  20%  | 
|  Quizzes                                 |  20%  |
|  In-class activities                     |  20%  |
|  Take-home assignments                   |  30%  |
|  Presentation and poster                 |  10%  |

## **Quizzes:** 

There will be paper quizzes - yes paper - that assess your ability to interpret code and illustrate the output, troubleshoot code that may or may not work and how to fix it and how to write simple lines of code to do a task that was the focus of the prior class.

## **Homework:**  

You are required to read the class readings (see ‘course schedule’) ahead of each class. Homework questions based on the readings will also need to be completed ahead of many classes. Homework questions will be assigned one class meeting before they are due and will need to be submitted before the start of class. We will spend the portions class taking up and discussing homework questions. I will cold-call students to present and explain their answers to the rest of the class. Homework assignments will receive one of four possible grades: 100% (A) for work that meets or exceeds expectations, 85% (B) for work that meets most expectations, 65% (D) for work that misses most expectations or 0% (F) for work deemed unacceptable.

## **In-class activities:** 

most computer lab exercises will be accompanied by in-class questions and disucssion. You will submit answers to these questions and your functional R code for the exercise by the end of the day of each exercise. In-class activities will be submitted as simple R files or **Quaerto Markdown Files**. In-class activities will be graded on the same scale as homework.

**Take-home assignments:** 4? assignments will be completed outside of class. Each assignment will involve the independent analysis, presentation and interpretation of a dataset. The written report will include 3 sections: **abstract**, **statistical** **materials and methods** and **results** (statistical results and figures/ tables), prepared to “publication quality” standards. Assignments will be graded out of 100% and assessed on metrics including data literacy (performing analyses correctly), graphical presentation of data, adherence to correct statistical reporting norms, grammar and the quality/functionality of the accompanying R code. The assignments will comprise 70% of your final grade; A1 will be worth 10% of the final grade, A2 15%, A3 20%, and A4 25%.

## **Final letter grades** 

will be assigned on a straight 10% scale, with 90-100% receiving some form of A, 80-89% some form of B, etc. + and – grades will fall on the upper (\>X7) and lower (\<X4) end of the ranges, respectively. Percentage grades below 50% are equivalent to an ‘F’ letter grade.

## **Late/missed assignment policy:** 

10% of total possible grade will be deducted per day late in absence of valid excuse. A grade of 0 will be given for assignments that are more than 3 days late.

## **Valid excuses:**

Valid excuses for missed class or late work consist of subpoenas, jury duty, military duty, religious observances, illness, bereavement for immediate family and NCAA varsity intercollegiate athletics. Conflicts with work, vacations, weddings, travel, or some other private situation that was foreseen will not be accommodated.  For further information on excused absences see https://evcaa.d.umn.edu/excused-absences

## **Academic Integrity:**

I take plagiarism and academic dishonesty very seriously and will invoke the full weight of UMD-approved sanctions at the first instance of plagiarism. I am happy to answer questions on what is considered a violation of academic integrity in this class. Please also refer to UMD’s academic integrity policy at: <https://evcaa.d.umn.edu/student-academic-integrity>

## **Student Conduct Code:**

I will enforce, and expect you to follow the University's Student Code of Conduct. Appropriate classroom conduct promotes an environment of academic achievement and integrity. Disruptive classroom behaviour that substantially or repeatedly interrupts either the instructor's ability to teach, or student learning, is prohibited. Disruptive behaviour includes inappropriate use of technology in the classroom. Examples include ringing cell phones, text-messaging, watching videos of funny cats (and other videos), playing computer games, doing email, or surfing the Internet on your computer instead of note-taking or other instructor-sanctioned activities. See more here: <https://regents.umn.edu/sites/regents.umn.edu/files/2022-07/policy_student_conduct_code.pdf>

## **Access for Students with Disabilities:**

Individuals who have any disability, either permanent or temporary, which might affect their ability to perform in this course are encouraged to inform the instructor at the start of the quarter. Methods, materials or testing may be modified to provide for equitable participation.

## **Promotion of Bias-free Instruction:**

The University of Minnesota is committed to the policy that all of its students shall have equal educational opportunities. The University expressly forbids discrimination on the basis of race, color, gender, sexual orientation, disability, veteran's status, ethnicity, religion, creed, national origin or marital status. If you believe that your Ecology instructor has not followed this policy, you are invited to bring this to the attention of the Biology Department Head (207 Swenson Science Building; 218-726-8123). Your conference will be kept confidential.

You may review **other relevant UMD policy statements** at: https://evcaa.d.umn.edu/recommended-syllabi-policy-statements
