<!DOCTYPE html>
<html lang="en"><head>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.36">

  <meta name="author" content="Bill Perry">
  <title>UMD Biostatistics – Principal Component Analysis (PCA)</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-b88c2fe81f1ff78e74849ca62ba99059.css">
  <link rel="stylesheet" href="../../css/lecture.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <link href="../../site_libs/htmltools-fill-0.5.9/fill.css" rel="stylesheet">
  <script src="../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
  <script src="../../site_libs/plotly-binding-4.12.0/plotly.js"></script>
  <script src="../../site_libs/typedarray-0.1/typedarray.min.js"></script>
  <script src="../../site_libs/jquery-3.5.1/jquery.min.js"></script>
  <link href="../../site_libs/crosstalk-1.2.2/css/crosstalk.min.css" rel="stylesheet">
  <script src="../../site_libs/crosstalk-1.2.2/js/crosstalk.min.js"></script>
  <link href="../../site_libs/plotly-htmlwidgets-css-2.25.2/plotly-htmlwidgets.css" rel="stylesheet">
  <script src="../../site_libs/plotly-main-2.25.2/plotly-latest.min.js"></script>
<meta property="og:title" content="Principal Component Analysis (PCA) – UMD Biostatistics">
<meta property="og:description" content="Understanding Multivariate Data with Darlingtonia californica">
<meta property="og:site_name" content="UMD Biostatistics">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Principal Component Analysis (PCA)</h1>
  <p class="subtitle">Understanding Multivariate Data with <em>Darlingtonia californica</em></p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Bill Perry 
</div>
</div>
</div>

</section>
<section>
<section id="introduction-to-multivariate-analysis" class="title-slide slide level1 center">
<h1>Introduction to Multivariate Analysis</h1>

</section>
<div class="columns">
<div class="column" style="width:60%;">
<h3 id="why-study-multivariate-data">Why Study Multivariate Data?</h3>
<ul>
<li>In ecology, often measure many variables on the same organisms:
<ul>
<li><strong>Plant morphology</strong>: height, width, leaf size, flower size</li>
<li><strong>Environmental conditions</strong>: temperature, pH, nutrients</li>
<li><strong>Species composition</strong>: presence/absence, abundance</li>
</ul></li>
<li><strong>Challenge</strong>: How do we make sense of all these variables at once?</li>
<li><strong>PCA helps by</strong>:
<ul>
<li>Reducing many correlated variables to a few key dimensions</li>
<li>Visualizing patterns in high-dimensional data</li>
<li>Identifying the most important sources of variation</li>
</ul></li>
</ul>
</div><div class="column" style="width:40%;">
<p>Darlingtonia californica (Cobra Lily)</p>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/clipboard-3752708543.png" width="335"></p>
<figcaption>image of a cobra lily Darlingtonia californica</figcaption>
</figure>
</div>
</div>
</div></section>
<section>
<section id="our-study-system-darlingtonia" class="title-slide slide level1 center">
<h1>Our Study System: Darlingtonia</h1>

</section>
<div class="columns">
<div class="column" style="width:60%;">
<h3 id="the-cobra-lily-dataset">The Cobra Lily Dataset</h3>
<ul>
<li>Analyze morphological measurements from 89 individual <em>Darlingtonia californica</em> plants collected from <strong>4 sites</strong> in the Siskiyou Mountains of Oregon.</li>
<li><strong>Variables measured</strong> (10 total):
<ul>
<li><strong>Morphological measurements (mm)</strong>:
<ul>
<li>height - Height of pitcher</li>
<li>mouth_diam - Mouth diameter</li>
<li>tube_diam - Tube diameter</li>
<li>keel_diam - Keel diameter</li>
<li>wing1_length, wing2_length</li>
<li>Wing lengths (2 measurements)</li>
<li>wingsprea - Wing spread</li>
</ul></li>
<li><strong>Biomass measurements (g)</strong>:
<ul>
<li><p>hoodmass_g - Hood mass</p></li>
<li><p>tubemass_g - Tube mass</p></li>
<li><p>wingmass_g - Wing mass</p></li>
</ul></li>
</ul></li>
</ul>
</div><div class="column" style="width:40%;">
<pre><code>![Darlingtonia pitcher structure showing measured features\]</code></pre>
<p><img data-src="images/clipboard-4005369252.png" width="211"></p>
<ul>
<li>**Sites**:</li>
<li>TJH: T.J. Howell’s Fen</li>
<li>DG: Day’s Gulch</li>
<li>LEH: L.E. Hunter’s Fen</li>
<li>HD: High Divide</li>
</ul>
</div>
</div></section>
<section>
<section id="loading-the-data" class="title-slide slide level1 center">
<h1>Loading the Data</h1>

</section>
<h3 id="step-1-import-and-prepare-the-data">Step 1: Import and Prepare the Data</h3>
<div class="panel">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a></a><span class="co"># Load the data</span></span>
<span id="cb2-2"><a></a>darlingtonia <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"darlingtonia.csv"</span>)</span>
<span id="cb2-3"><a></a></span>
<span id="cb2-4"><a></a><span class="co"># View the structure</span></span>
<span id="cb2-5"><a></a><span class="fu">head</span>(darlingtonia)</span>
<span id="cb2-6"><a></a><span class="do">## # A tibble: 6 × 11</span></span>
<span id="cb2-7"><a></a><span class="do">##   site  height mouth_diam tube_diam keel_diam wing1_length wing2_length</span></span>
<span id="cb2-8"><a></a><span class="do">##   &lt;chr&gt;  &lt;dbl&gt;      &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;        &lt;dbl&gt;        &lt;dbl&gt;</span></span>
<span id="cb2-9"><a></a><span class="do">## 1 TJH      654       38.4      16.6       6.4           85           76</span></span>
<span id="cb2-10"><a></a><span class="do">## 2 TJH      413       22.2      17.2       5.9           55           26</span></span>
<span id="cb2-11"><a></a><span class="do">## 3 TJH      610       31.2      19.9       6.7           62           60</span></span>
<span id="cb2-12"><a></a><span class="do">## 4 TJH      546       34.4      20.8       6.3           84           79</span></span>
<span id="cb2-13"><a></a><span class="do">## 5 TJH      665       30.5      20.4       6.6           60           51</span></span>
<span id="cb2-14"><a></a><span class="do">## 6 TJH      665       33.6      19.5       6.6           84           66</span></span>
<span id="cb2-15"><a></a><span class="do">## # ℹ 4 more variables: wingsprea &lt;dbl&gt;, hoodmass_g &lt;dbl&gt;, tubemass_g &lt;dbl&gt;,</span></span>
<span id="cb2-16"><a></a><span class="do">## #   wingmass_g &lt;dbl&gt;</span></span>
<span id="cb2-17"><a></a></span>
<span id="cb2-18"><a></a>darlingtonia <span class="sc">%&gt;%</span></span>
<span id="cb2-19"><a></a>  <span class="fu">count</span>(site, <span class="at">name =</span> <span class="st">"n_plants"</span>)</span>
<span id="cb2-20"><a></a><span class="do">## # A tibble: 4 × 2</span></span>
<span id="cb2-21"><a></a><span class="do">##   site  n_plants</span></span>
<span id="cb2-22"><a></a><span class="do">##   &lt;chr&gt;    &lt;int&gt;</span></span>
<span id="cb2-23"><a></a><span class="do">## 1 DG          25</span></span>
<span id="cb2-24"><a></a><span class="do">## 2 HD          12</span></span>
<span id="cb2-25"><a></a><span class="do">## 3 LEH         25</span></span>
<span id="cb2-26"><a></a><span class="do">## 4 TJH         25</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div></section>
<section>
<section id="exploring-the-raw-data" class="title-slide slide level1 center">
<h1>Exploring the Raw Data</h1>

</section>
<div class="columns">
<div class="column" style="width:60%;">
<section id="initial-data-exploration" class="slide level2">
<h2>Initial Data Exploration</h2>
<p>Before any analysis, we should <strong>always look at our data</strong>:</p>
<ul>
<li>Check for outliers</li>
<li>Examine distributions</li>
<li>Look for patterns by site</li>
<li>Understand variable scales</li>
</ul>
<p><strong>Key observations</strong>:</p>
<ul>
<li>Variables measured in different units (mm vs.&nbsp;g)</li>
<li>Different ranges: height (hundreds) vs.&nbsp;biomass (fractions)</li>
<li>Need to standardize before PCA!</li>
</ul>
</section>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="16_01_lecture_powerpoint_files/figure-revealjs/explore_data-1.png" width="768"></p>
</figure>
</div>
</div>
</div>
</div>
</div></section>
<section>
<section id="the-problem-of-different-scales" class="title-slide slide level1 center">
<h1>The Problem of Different Scales</h1>

</section>
<div class="columns">
<div class="column" style="width:60%;">
<h3 id="why-standardization-matters">Why Standardization Matters</h3>
<ul>
<li><strong>Without standardization</strong>:
<ul>
<li>Variables with larger values (like height in mm) would dominate the analysis over variables with smaller values (like biomass in g).</li>
</ul></li>
<li><strong>Example from data</strong>:
<ul>
<li>Height: mean ≈ 600 mm, range 322-845 mm -</li>
<li>Wing mass: mean ≈ 0.16 g, range 0.02-5.00 g</li>
</ul></li>
<li>calculated distances without standardizing, height would have 1000× more influence than wing mass!</li>
<li><strong>Solution: Z-score standardization</strong>
<ul>
<li><span class="math inline">\(Z = \frac{(Y_i - \bar{Y})}{s}\)</span></li>
</ul></li>
<li>transforms each variable to:
<ul>
<li>Mean = 0</li>
<li>Standard deviation = 1</li>
<li>Units: “standard deviations from the mean”</li>
</ul></li>
</ul>
</div><div class="column" style="width:40%;">
<ul>
<li><strong>Before standardization:</strong> - Height dominates (larger scale)</li>
<li><strong>After standardization:</strong>
<ul>
<li>All variables contribute equally</li>
<li>Measured in “standard deviations”</li>
</ul></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a></a><span class="co"># Example: standardize height</span></span>
<span id="cb3-2"><a></a>darlingtonia <span class="sc">%&gt;%</span></span>
<span id="cb3-3"><a></a>  <span class="fu">summarize</span>(</span>
<span id="cb3-4"><a></a>    <span class="at">mean_height =</span> <span class="fu">mean</span>(height),</span>
<span id="cb3-5"><a></a>    <span class="at">sd_height =</span> <span class="fu">sd</span>(height),</span>
<span id="cb3-6"><a></a>    <span class="at">mean_wingmass =</span> <span class="fu">mean</span>(wingmass_g),</span>
<span id="cb3-7"><a></a>    <span class="at">sd_wingmass =</span> <span class="fu">sd</span>(wingmass_g)</span>
<span id="cb3-8"><a></a>  )</span>
<span id="cb3-9"><a></a><span class="do">## # A tibble: 1 × 4</span></span>
<span id="cb3-10"><a></a><span class="do">##   mean_height sd_height mean_wingmass sd_wingmass</span></span>
<span id="cb3-11"><a></a><span class="do">##         &lt;dbl&gt;     &lt;dbl&gt;         &lt;dbl&gt;       &lt;dbl&gt;</span></span>
<span id="cb3-12"><a></a><span class="do">## 1        616.      101.         0.154       0.102</span></span>
<span id="cb3-13"><a></a></span>
<span id="cb3-14"><a></a><span class="co"># After standardization, both will have:</span></span>
<span id="cb3-15"><a></a><span class="co"># mean = 0, sd = 1</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div></section>
<section>
<section id="measuring-multivariate-distance" class="title-slide slide level1 center">
<h1>Measuring Multivariate Distance</h1>

</section>
<div class="columns">
<div class="column" style="width:60%;">
<h3 id="euclidean-distance-between-individuals">Euclidean Distance Between Individuals</h3>
<ul>
<li>How different are two plants?
<ul>
<li>For two plants measured on multiple variables, calculate <strong>Euclidean distance</strong>:
<ul>
<li><p><strong>For 2 variables</strong> (height and spread):</p>
<ul>
<li><span class="math inline">\(d_{i,j} = \sqrt{(y_{i,1} - y_{j,1})^2 + (y_{i,2} - y_{j,2})^2}\)</span></li>
</ul></li>
<li><p><strong>For n variables</strong>:</p>
<ul>
<li><span class="math inline">\(d_{i,j} = \sqrt{\sum_{k=1}^{n}(y_{i,k} - y_{j,k})^2}\)</span></li>
</ul></li>
<li><p>Pythagorean theorem extended to many dimensions!</p></li>
<li><p><strong>Key point</strong>: Distance should use <em>standardized</em> values so all variables contribute equally</p></li>
</ul></li>
</ul></li>
</ul>
</div><div class="column" style="width:40%;">
<div class="cell">
<pre><code>## 
## Distance between plants 1 and 2 (standardized):
##  3.53 standard deviations
## 
##  
## Note: Standardization uses mean and SD from ALL plants,
##  not just these two plants!</code></pre>
</div>
</div>
</div></section>
<section>
<section id="standardizing-the-data" class="title-slide slide level1 center">
<h1>Standardizing the Data</h1>

</section>
<div class="columns">
<div class="column" style="width:60%;">
<h3 id="step-2-z-score-transformation">Step 2: Z-score Transformation</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="16_01_lecture_powerpoint_files/figure-revealjs/standardize-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:40%;">
<h3 id="visualizing-standardized-data">Visualizing Standardized Data</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="16_01_lecture_powerpoint_files/figure-revealjs/scaled_comparison-1.png" width="480"></p>
</figure>
</div>
</div>
</div>
</div>
</div></section>
<section>
<section id="understanding-correlations" class="title-slide slide level1 center">
<h1>Understanding Correlations</h1>

</section>
<div class="columns">
<div class="column" style="width:60%;">
<h3 id="why-correlations-matter-for-pca">Why Correlations Matter for PCA</h3>
<ul>
<li>PCA works best when variables are <strong>correlated</strong>:
<ul>
<li>If variables are uncorrelated → PCA provides no benefit</li>
<li>If variables are highly correlated → PCA can reduce dimensions effectively</li>
</ul></li>
<li><strong>In data</strong>, expect correlations because:
<ul>
<li>Larger plants have larger measurements overall</li>
<li>Wing dimensions likely correlate with each other</li>
<li>Mass measurements correlate with size measurements</li>
</ul></li>
<li><strong>The correlation matrix</strong> shows relationships between all pairs of variables.</li>
<li>Strong correlations (positive or negative) suggest PCA will be useful!</li>
</ul>
</div><div class="column" style="width:40%;">
<p><strong>Strong positive correlations</strong> (dark blue) suggest variables measure similar aspects of plant size/shape.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="16_01_lecture_powerpoint_files/figure-revealjs/correlation_plot-1.png" width="576"></p>
</figure>
</div>
</div>
</div>
</div>
</div></section>
<section>
<section id="correlation-matrix-details" class="title-slide slide level1 center">
<h1>Correlation Matrix Details</h1>

</section>
<h3 id="examining-variable-relationships">Examining Variable Relationships</h3>
<div class="panel">
<div class="cell">
<pre><code>##              height mouth_diam tube_diam keel_diam wing1_length wing2_length
## height         1.00       0.61      0.24     -0.06         0.28         0.29
## mouth_diam     0.61       1.00     -0.05     -0.39         0.57         0.44
## tube_diam      0.24      -0.05      1.00      0.65        -0.09         0.01
## keel_diam     -0.06      -0.39      0.65      1.00        -0.35        -0.24
## wing1_length   0.28       0.57     -0.09     -0.35         1.00         0.84
## wing2_length   0.29       0.44      0.01     -0.24         0.84         1.00
## wingsprea      0.12       0.25      0.10     -0.19         0.64         0.71
## hoodmass_g     0.49       0.76     -0.11     -0.34         0.61         0.49
## tubemass_g     0.84       0.72      0.10     -0.24         0.44         0.36
## wingmass_g     0.40       0.62     -0.16     -0.36         0.76         0.69
##              wingsprea hoodmass_g tubemass_g wingmass_g
## height            0.12       0.49       0.84       0.40
## mouth_diam        0.25       0.76       0.72       0.62
## tube_diam         0.10      -0.11       0.10      -0.16
## keel_diam        -0.19      -0.34      -0.24      -0.36
## wing1_length      0.64       0.61       0.44       0.76
## wing2_length      0.71       0.49       0.36       0.69
## wingsprea         1.00       0.25       0.16       0.39
## hoodmass_g        0.25       1.00       0.76       0.80
## tubemass_g        0.16       0.76       1.00       0.63
## wingmass_g        0.39       0.80       0.63       1.00</code></pre>
</div>
</div></section>
<section id="key-observations" class="title-slide slide level1 center">
<h1>Key Observations</h1>
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li><strong>Highly correlated variables</strong>:
<ul>
<li>Height with tube area (r=0.89)
<ul>
<li>Wing lengths with each other (r=0.80)</li>
<li>Wing area with wing spread (r=0.81)</li>
</ul></li>
</ul></li>
<li>These correlations indicate <strong>redundancy</strong></li>
<li>multiple variables measuring similar things.</li>
</ul>
</div><div class="column" style="width:50%;">
<ul>
<li><strong>Moderate correlations</strong>:
<ul>
<li>Most morphological variables</li>
<li>Mass measurements with size</li>
</ul></li>
<li><strong>Lower correlations</strong>:
<ul>
<li>Some specific features like keel diameter</li>
</ul></li>
<li><strong>PCA will help</strong> by combining correlated variables into fewer components!</li>
</ul>
</div></div>
</section>

<section>
<section id="what-is-principal-component-analysis" class="title-slide slide level1 center">
<h1>What is Principal Component Analysis?</h1>

</section>
<div class="columns">
<div class="column" style="width:60%;">
<h3 id="the-concept-of-pca">The Concept of PCA</h3>
<ul>
<li>PCA creates new variables (components) that are:
<ul>
<li><strong>Linear combinations</strong> of original variables</li>
<li><strong>Uncorrelated</strong> with each other</li>
<li><strong>Ordered by importance</strong> (amount of variance explained)</li>
</ul></li>
<li><strong>The mathematical idea</strong>:
<ul>
<li>For each plant <em>i</em> and component <em>k</em>:</li>
<li><span class="math inline">\(Z_{ik} = a_{i1}Y_1 + a_{i2}Y_2 + ... + a_{in}Y_n\)</span></li>
</ul></li>
<li>Where:
<ul>
<li><span class="math inline">\(Z_{ik}\)</span> = score on principal component <em>k</em></li>
<li><span class="math inline">\(Y_j\)</span> = standardized value of original variable <em>j</em></li>
<li><span class="math inline">\(a_{ij}\)</span> = loading (weight) of variable <em>j</em> on component <em>i</em></li>
</ul></li>
<li><strong>Goal</strong>: Find loadings that maximize variance in first component, then second, etc.</li>
</ul>
</div><div class="column" style="width:40%;">
<p><img data-src="images/clipboard-2517015273.png" width="246" alt="https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/GaussianScatterPCA.svg/500px-GaussianScatterPCA.svg.png"><br>
Conceptual diagram of PCA: reducing 2 variables to 1 principal axis</p>
<ul>
<li><strong>The first principal axis</strong> passes through maximum variance.</li>
<li><strong>Key properties</strong>: - As many components as variables - First components explain most variation - Later components explain residual variation</li>
</ul>
</div>
</div></section>
<section>
<section id="principal-components-properties" class="title-slide slide level1 center">
<h1>Principal Components: Properties</h1>

</section>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="understanding-components-are">Understanding Components are:</h3>
<ul>
<li><strong>1. Orthogonal (perpendicular)</strong>
<ul>
<li>Components are uncorrelated</li>
<li>Each captures independent information</li>
</ul></li>
<li><strong>2. Ordered by variance</strong>
<ul>
<li>PC1 explains the most variance</li>
<li>PC2 explains second most (of remaining variance)</li>
<li>And so on…</li>
</ul></li>
<li><strong>3. Linear combinations</strong>
<ul>
<li>Each component is a weighted sum of original variables</li>
<li>Weights (loadings) show variable importance</li>
</ul></li>
</ul>
</div><div class="column" style="width:50%;">
<h3 id="why-this-matters">Why this matters:</h3>
<ul>
<li><strong>Dimension reduction</strong>:
<ul>
<li>Start with 10 correlated variables</li>
<li>End with 2-3 uncorrelated components</li>
<li>Retain most information with fewer dimensions</li>
</ul></li>
<li><strong>Easier interpretation</strong>:
<ul>
<li>PC1 might represent “overall size”</li>
<li>PC2 might represent “shape”</li>
<li>Components often have biological meaning</li>
</ul></li>
<li><strong>Better for analysis</strong>:
<ul>
<li>Can use in regression, ANOVA</li>
<li>No multicollinearity problems</li>
<li>Variables are standardized</li>
</ul></li>
</ul>
</div>
</div></section>
<section>
<section id="performing-pca-in-r" class="title-slide slide level1 center">
<h1>Performing PCA in R</h1>

</section>
<h3 id="step-3-run-the-analysis">Step 3: Run the Analysis</h3>
<div class="panel">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a></a><span class="co"># Perform PCA using prcomp()</span></span>
<span id="cb6-2"><a></a><span class="co"># center = TRUE: center variables (mean = 0)</span></span>
<span id="cb6-3"><a></a><span class="co"># scale. = TRUE: scale variables (sd = 1)</span></span>
<span id="cb6-4"><a></a>pca_result <span class="ot">&lt;-</span> <span class="fu">prcomp</span>(darl_numeric, </span>
<span id="cb6-5"><a></a>                     <span class="at">center =</span> <span class="cn">TRUE</span>, </span>
<span id="cb6-6"><a></a>                     <span class="at">scale =</span> <span class="cn">TRUE</span>)</span>
<span id="cb6-7"><a></a></span>
<span id="cb6-8"><a></a><span class="co"># What's in the result?</span></span>
<span id="cb6-9"><a></a><span class="fu">names</span>(pca_result)</span>
<span id="cb6-10"><a></a><span class="do">## [1] "sdev"     "rotation" "center"   "scale"    "x"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div></section>
<section id="understanding-the-output" class="title-slide slide level1 center">
<h1>Understanding the Output</h1>
<div class="panel">
<div class="cell">
<pre><code>## Importance of components:
##                           PC1    PC2    PC3     PC4     PC5     PC6     PC7
## Standard deviation     2.2332 1.3288 1.2354 0.75701 0.59301 0.51062 0.46177
## Proportion of Variance 0.4987 0.1766 0.1526 0.05731 0.03517 0.02607 0.02132
## Cumulative Proportion  0.4987 0.6753 0.8279 0.88521 0.92038 0.94645 0.96777
##                           PC8     PC9    PC10
## Standard deviation     0.3768 0.33982 0.25457
## Proportion of Variance 0.0142 0.01155 0.00648
## Cumulative Proportion  0.9820 0.99352 1.00000</code></pre>
</div>
<ul>
<li><strong>Output components</strong>:</li>
<li><code>sdev</code>: standard deviations of each PC (square root of eigenvalues)</li>
<li><code>rotation</code>: loadings matrix (how variables load on PCs)</li>
<li><code>x</code>: PC scores for each observation</li>
<li><code>center</code>: variable means</li>
<li><code>scale</code>: variable standard deviations</li>
</ul>
</div>
</section>

<section>
<section id="eigenvalues-and-variance-explained" class="title-slide slide level1 center">
<h1>Eigenvalues and Variance Explained</h1>

</section>
<div class="columns">
<div class="column" style="width:60%;">
<h3 id="how-much-variance-does-each-pc-explain">How Much Variance Does Each PC Explain?</h3>
<ul>
<li><strong>Eigenvalues</strong> (<span class="math inline">\(\lambda\)</span>) measure variance explained by each component.</li>
<li>The proportion of variance for PC <em>j</em> is:
<ul>
<li><span class="math inline">\(\text{Proportion}_j = \frac{\lambda_j}{\sum_{k=1}^{n}\lambda_k}\)</span></li>
</ul></li>
<li><strong>In practice</strong>:
<ul>
<li><p>PC1 always explains the most variance</p></li>
<li><p>We want the first few PCs to explain most (&gt;70%) of total variance</p></li>
<li><p>allows dimension reduction</p></li>
</ul></li>
</ul>
</div><div class="column" style="width:40%;">
<div class="cell">
<pre><code>## # A tibble: 10 × 4
##    PC    Eigenvalue Proportion Cumulative
##    &lt;chr&gt;      &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;
##  1 PC1        4.99       0.499      0.499
##  2 PC2        1.77       0.177      0.675
##  3 PC3        1.53       0.153      0.828
##  4 PC4        0.573      0.057      0.885
##  5 PC5        0.352      0.035      0.92 
##  6 PC6        0.261      0.026      0.946
##  7 PC7        0.213      0.021      0.968
##  8 PC8        0.142      0.014      0.982
##  9 PC9        0.115      0.012      0.994
## 10 PC10       0.065      0.006      1</code></pre>
</div>
</div>
</div></section>
<section>
<section id="scree-plot-choosing-components" class="title-slide slide level1 center">
<h1>Scree Plot: Choosing Components</h1>

</section>
<div class="columns">
<div class="column" style="width:60%;">
<h3 id="how-many-components-to-use">How Many Components to Use?</h3>
<ul>
<li>A <strong>scree plot</strong> shows variance explained by each component.</li>
<li><strong>How to read it</strong>:
<ul>
<li>Look for an “elbow” - sharp change in slope</li>
<li>Keep components before the elbow</li>
<li>Discard components in the “scree” (rubble)</li>
</ul></li>
<li><strong>In this data</strong>:
<ul>
<li>PC1 explains 49.9% of variance</li>
<li>PC2 explains 17.7%</li>
<li>PC3 explains 15.3%</li>
<li><strong>First 3 PCs explain 77.3% of variance</strong></li>
</ul></li>
<li><strong>Decision</strong>: Use PC1, PC2, and PC3 for interpretation.</li>
<li>remaining 7 components explain 17.1% (mostly noise).</li>
</ul>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="16_01_lecture_powerpoint_files/figure-revealjs/scree_plot-1.png" width="576"></p>
</figure>
</div>
</div>
</div>
</div>
</div></section>
<section>
<section id="understanding-loadings" class="title-slide slide level1 center">
<h1>Understanding Loadings</h1>

</section>
<div class="columns">
<div class="column" style="width:60%;">
<h3 id="what-are-loadings">What are Loadings?</h3>
<ul>
<li><strong>Loadings</strong> are the weights (<span class="math inline">\(a_{ij}\)</span>) that show how each original variable contributes to each principal component.</li>
<li><strong>For PC1</strong>:
<ul>
<li><span class="math inline">\(Z_1 = a_{11}Y_1 + a_{12}Y_2 + ... + a_{1p}Y_p\)</span></li>
</ul></li>
<li><strong>Interpreting loadings</strong>:
<ul>
<li><strong>Large positive loading</strong>: variable increases with PC</li>
<li><strong>Large negative loading</strong>: variable decreases with PC</li>
<li><strong>Near-zero loading</strong>: variable unimportant for PC</li>
</ul></li>
<li><strong>Guidelines</strong>:
<ul>
<li>Loadings &gt; 0.3 or &lt; -0.3 are worth considering</li>
<li>Loadings &gt; 0.5 or &lt; -0.5 are important</li>
<li>Sign (+ or -) can flip; patterns matter more</li>
</ul></li>
</ul>
</div><div class="column" style="width:40%;">
<ul>
<li><strong>PC1 loadings</strong>:
<ul>
<li>Most variables have similar positive values</li>
<li>All ~0.31 to 0.40 except keel (-0.18) and tube (-0.002)</li>
<li>Suggests PC1 measures “overall size”</li>
</ul></li>
</ul>
<div class="cell">
<pre><code>##                 PC1    PC2    PC3
## height       -0.278 -0.449  0.198
## mouth_diam   -0.369 -0.110  0.214
## tube_diam     0.040 -0.602 -0.390
## keel_diam     0.202 -0.491 -0.328
## wing1_length -0.375  0.171 -0.280
## wing2_length -0.342  0.131 -0.415
## wingsprea    -0.239  0.156 -0.549
## hoodmass_g   -0.385 -0.057  0.185
## tubemass_g   -0.355 -0.320  0.263
## wingmass_g   -0.393  0.080 -0.007</code></pre>
</div>
</div>
</div></section>
<section id="interpreting-pc1-overall-size" class="title-slide slide level1 center">
<h1>Interpreting PC1: Overall Size</h1>
<div class="columns">
<div class="column" style="width:60%;">
<ul>
<li>PC1 Interpretation - Looking at PC1 loadings:</li>
<li><strong>Key patterns</strong>:</li>
<li>Most variables load positively and similarly: - Height: 0.310 - Mouth diameter: 0.400
<ul>
<li>Wing lengths: 0.386, 0.372</li>
<li>Wing spread: 0.256</li>
<li>Biomass: 0.397, 0.380, 0.230</li>
</ul></li>
<li><strong>Exception</strong>: Keel diameter (-0.177) and tube diameter (~0)</li>
<li><strong>Biological meaning</strong>: PC1 represents <strong>overall plant size</strong>
<ul>
<li>most measurements scale together (bigger plants have bigger everything).</li>
</ul></li>
</ul>
<div class="cell">
<pre><code>## # A tibble: 10 × 2
##    Variable     Loading
##    &lt;chr&gt;          &lt;dbl&gt;
##  1 wingmass_g   -0.393 
##  2 hoodmass_g   -0.385 
##  3 wing1_length -0.375 
##  4 mouth_diam   -0.369 
##  5 tubemass_g   -0.355 
##  6 wing2_length -0.342 
##  7 height       -0.278 
##  8 wingsprea    -0.239 
##  9 keel_diam     0.202 
## 10 tube_diam     0.0402</code></pre>
</div>
</div><div class="column" style="width:40%;">
<ul>
<li>High PC1 → large plants</li>
<li>Low PC1 → small plants</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="16_01_lecture_powerpoint_files/figure-revealjs/pc1_loading_plot-1.png" width="384"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>

<section>
<section id="interpreting-pc2-shape-contrast" class="title-slide slide level1 center">
<h1>Interpreting PC2: Shape Contrast</h1>

</section>
<div class="columns">
<div class="column" style="width:60%;">
<h3 id="pc2-interpretation">PC2 Interpretation</h3>
<ul>
<li>Looking at PC2 loadings:</li>
<li><strong>Key patterns</strong>:
<ul>
<li>Height: -0.419 (negative, moderate)</li>
<li>Mouth: -0.250 (negative, moderate)</li>
<li>Wing measurements: positive (0.275-0.434)</li>
<li>Wing spread: 0.434 (positive, strong)</li>
<li>Biomass: mostly negative</li>
</ul></li>
<li><strong>Biological meaning</strong>: PC2 represents <strong>shape trade-offs</strong>
<ul>
<li>tall narrow pitchers vs.&nbsp;short wide pitchers with large wings.</li>
</ul></li>
</ul>
<div class="cell">
<pre><code>## # A tibble: 10 × 2
##    Variable     Loading
##    &lt;chr&gt;          &lt;dbl&gt;
##  1 tube_diam    -0.602 
##  2 keel_diam    -0.491 
##  3 height       -0.449 
##  4 tubemass_g   -0.320 
##  5 wing1_length  0.171 
##  6 wingsprea     0.156 
##  7 wing2_length  0.131 
##  8 mouth_diam   -0.110 
##  9 wingmass_g    0.0800
## 10 hoodmass_g   -0.0575</code></pre>
</div>
</div><div class="column" style="width:40%;">
<ul>
<li>High PC2 → short plants with large wings</li>
<li>Low PC2 → tall narrow plants</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="16_01_lecture_powerpoint_files/figure-revealjs/pc2_loading_plot-1.png" width="480"></p>
</figure>
</div>
</div>
</div>
</div>
</div></section>
<section>
<section id="interpreting-pc3" class="title-slide slide level1 center">
<h1>Interpreting PC3</h1>

</section>
<div class="columns">
<div class="column" style="width:60%;">
<h3 id="pc3-interpretation">PC3 Interpretation</h3>
<ul>
<li>Looking at PC3 loadings:</li>
<li><strong>Key patterns</strong>:</li>
<li>Dominated by:
<ul>
<li>Tube diameter: 0.743 (very strong positive)</li>
<li>Keel diameter: 0.576 (strong positive)</li>
<li>Most other variables near zero</li>
</ul></li>
<li><strong>Biological meaning</strong>: PC3 represents <strong>tube girth</strong>
<ul>
<li>width/diameter of tube structure independent of height or wing size.</li>
<li>Plants with high PC3 scores = <strong>fat tubes</strong>, allowing to trap larger prey?</li>
</ul></li>
</ul>
<div class="cell">
<pre><code>## # A tibble: 10 × 2
##    Variable      Loading
##    &lt;chr&gt;           &lt;dbl&gt;
##  1 wingsprea    -0.549  
##  2 wing2_length -0.415  
##  3 tube_diam    -0.390  
##  4 keel_diam    -0.328  
##  5 wing1_length -0.280  
##  6 tubemass_g    0.263  
##  7 mouth_diam    0.214  
##  8 height        0.198  
##  9 hoodmass_g    0.185  
## 10 wingmass_g   -0.00743</code></pre>
</div>
</div><div class="column" style="width:40%;">
<ul>
<li>High PC3 → fat tubes</li>
<li>Low PC3 → skinny tubes</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="16_01_lecture_powerpoint_files/figure-revealjs/pc3_loading_plot-1.png" width="480"></p>
</figure>
</div>
</div>
</div>
</div>
</div></section>
<section>
<section id="principal-component-scores" class="title-slide slide level1 center">
<h1>Principal Component Scores</h1>

</section>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="what-are-pc-scores">What are PC Scores?</h3>
<ul>
<li><strong>PC scores</strong> are values of each principal component for each obs./plant</li>
<li>Each plant gets a score on each PC:
<ul>
<li>PC1 score = measure of size</li>
<li>PC2 score = measure of shape</li>
<li>PC3 score = measure of tube girth</li>
</ul></li>
<li><strong>How they’re calculated</strong>:</li>
<li>For plant <em>i</em> on PC1:
<ul>
<li><span class="math inline">\(\text{PC1}_i = 0.31×height_i + 0.40×mouth_i + ...\)</span></li>
<li>Using the standardized values and loadings we saw earlier.</li>
</ul></li>
</ul>
</div><div class="column" style="width:50%;">
<div class="cell">
<pre><code>## # A tibble: 10 × 5
##    plant_id site     PC1     PC2    PC3
##       &lt;int&gt; &lt;chr&gt;  &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;
##  1        1 TJH   -1.92   0.0772  1.53 
##  2        2 TJH    3.35   1.53    0.755
##  3        3 TJH    0.918 -0.0320  0.248
##  4        4 TJH   -0.983  0.236  -0.242
##  5        5 TJH    1.15  -1.02    1.54 
##  6        6 TJH   -1.37  -0.613   0.847
##  7        7 TJH   -1.50  -1.63    0.693
##  8        8 TJH   -0.651  0.121  -0.412
##  9        9 TJH    2.48  -0.0786 -0.260
## 10       10 TJH   -1.11  -1.27    2.27</code></pre>
</div>
</div>
</div></section>
<section>
<section id="visualizing-pca-results-scores-plot" class="title-slide slide level1 center">
<h1>Visualizing PCA Results: Scores Plot</h1>

</section>
<div class="columns">
<div class="column" style="width:60%;">
<h3 id="ordination-of-sites">Ordination of Sites</h3>
<ul>
<li>We can plot PC scores to visualize:
<ul>
<li>How plants are distributed in PC space</li>
<li>Whether sites differ in morphology</li>
<li>Patterns and groupings</li>
</ul></li>
<li><strong>In this plot</strong>:
<ul>
<li>Each point = one plant</li>
<li>Position determined by PC1 and PC2 scores</li>
<li>Colors indicate collection site</li>
</ul></li>
<li><strong>Observations</strong>:
<ul>
<li>Sites show some separation</li>
<li>HD (orange) plants have lower PC1 (smaller)</li>
<li>TJH (pink) plants variable but lower PC2</li>
<li>Some overlap among sites</li>
</ul></li>
<li>This is called <strong>ordination</strong> - ordering objects along axes.</li>
</ul>
</div><div class="column" style="width:40%;">
<p>The ordination</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="16_01_lecture_powerpoint_files/figure-revealjs/scores_plot_basic-1.png" width="576"></p>
</figure>
</div>
</div>
</div>
</div>
</div></section>
<section id="different-visualization-of-pca-scores" class="title-slide slide level1 center">
<h1>Different visualization of PCA Scores</h1>
<div class="panel">
<div class="cell">
<div class="cell-output-display">
<div class="plotly html-widget html-fill-item" id="htmlwidget-75420fd3acaef9812fa4" style="width:960px;height:480px;"></div>
<script type="application/json" data-for="htmlwidget-75420fd3acaef9812fa4">{"x":{"visdat":{"3bb03cdee3e8":["function () ","plotlyVisDat"]},"cur_data":"3bb03cdee3e8","attrs":{"3bb03cdee3e8":{"x":{},"y":{},"z":{},"mode":"markers","color":{},"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter3d"}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"scene":{"xaxis":{"title":"PC1"},"yaxis":{"title":"PC2"},"zaxis":{"title":"PC3"}},"hovermode":"closest","showlegend":true},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"x":[-2.2417084302101471,-3.1488111996745194,-0.031357247571229777,-1.629226205483864,0.17864887947362329,-2.8137205962749716,-1.5136271507468295,0.48047835290602409,-2.4235581558893076,-2.4207859653813832,-1.7134269393451564,-2.836543931789175,1.2828622649504529,-0.67781996575422787,-2.3395163552335601,-1.9577431510255812,1.1390722661876604,-1.1455578611843447,-1.3783995382486087,0.10266145762430659,0.51843584966760059,1.3830217303046743,-0.094323016367073104,-0.92431846827749786,-1.4055358982329349],"y":[-0.09583126511955524,-0.17938019412960229,-1.2637405550382301,0.12719197448843936,0.68120234770657284,-1.2201747859334831,0.15017946717123248,1.9063329825517352,-0.65192516841892734,1.9405292592885268,0.83075710209431686,-0.061505549807052806,1.0450338094306302,1.575728764276918,-2.111589479608059,2.3799587171442398,0.60251064373720209,0.75510383660089508,2.186558546903056,0.78706210460312631,0.9738371677156481,2.1720231459760204,1.2321344985110778,0.9609507941585228,0.37764596968802638],"z":[0.098742836455033053,-1.034346133503032,2.0761936135999326,0.74632879266233787,0.41890583932227732,-0.30478111450845841,0.44104000807534677,-0.81898748834020418,1.5251514698526025,-0.49142084414175274,-0.23363784478466745,-0.040276923734023376,-0.72612091951923852,-0.83338789604054175,2.8846790041299251,0.56426987795404071,-0.50888350106630131,0.18713023961205363,1.4029812725704285,1.3836929474690494,1.23050024494273,2.2340039565314482,0.91352421351709834,1.6198246243563499,0.8148089638927386],"mode":"markers","type":"scatter3d","name":"DG","marker":{"color":"rgba(102,194,165,1)","line":{"color":"rgba(102,194,165,1)"}},"textfont":{"color":"rgba(102,194,165,1)"},"error_y":{"color":"rgba(102,194,165,1)"},"error_x":{"color":"rgba(102,194,165,1)"},"line":{"color":"rgba(102,194,165,1)"},"frame":null},{"x":[3.0695543372075611,2.5698291790774679,3.4152914347624499,1.5250888497266184,1.6546722227528461,3.6137024574162826,1.6087835605716005,2.9781234964510683,3.3834367255909426,3.7796218062665554,1.664711961337906,2.2522500324053358],"y":[-1.0747707829442734,-1.916299100291202,0.90516782805261708,-4.2391205309431097,-0.66142974558611312,-1.1577323280075973,0.1877317931392771,-1.4975315584230366,-0.54356104351226175,-1.3005775081041901,-0.6206374277052199,1.5636573250450552],"z":[-1.3691542016650271,-1.4902359590376695,-0.84073587601482735,-0.43420286112158585,-2.5204942170235283,-2.9843543192027706,-2.4998667474295142,-1.3830146500820601,-1.4497714496960936,0.46288596754746492,-0.68468238939608272,0.065482850202376333],"mode":"markers","type":"scatter3d","name":"HD","marker":{"color":"rgba(252,141,98,1)","line":{"color":"rgba(252,141,98,1)"}},"textfont":{"color":"rgba(252,141,98,1)"},"error_y":{"color":"rgba(252,141,98,1)"},"error_x":{"color":"rgba(252,141,98,1)"},"line":{"color":"rgba(252,141,98,1)"},"frame":null},{"x":[3.3893861534747325,0.32951405185554217,0.080752236782147227,-2.25927531678219,-2.9118986242159339,-1.7227211355727985,0.030878093641676787,0.7999834169250537,-0.18106883719102101,-1.1378224537895201,-0.11528437599363446,0.20649941380454398,3.5783094953764873,0.40358824121884163,1.1328890334867501,1.6902086874735263,-0.23799959809853669,2.3465745379848815,0.17780660427383924,-0.7578615384730174,0.22733493991378573,-4.1956970001066161,-5.9251916806860763,-7.0006379895354138,-4.4201288004318666],"y":[0.31187931289457943,-0.57846014965785786,-0.58292140027887596,1.7483418286793233,1.4511768294798169,-0.23976890403647311,-0.027181811234005527,0.82575778335349559,-1.3156607250662957,-0.28511180925329765,0.5652689262401247,-2.1016207483400065,2.9157078187512524,-0.36433496097997536,0.58249871502575845,3.1893384058039476,-2.0520950294853235,0.92397660743579124,0.79459254413788183,0.69339765095368933,0.021499730336819046,0.61700649686652842,1.1290868542094119,-0.58144928437060617,-3.7682581555512771],"z":[0.29110352965563191,0.62313754959789958,1.4972708501513399,-0.62260520991658341,-1.5334043272083977,0.76303017903470904,1.5970137288248001,0.47311858257850542,-1.9360968667375285,-0.3080653560327557,-0.71780570926704468,-0.30165404405928603,-0.14834176675419605,-0.38756479256775239,-1.5089943923020748,0.23138974544181987,-1.4989137648530448,-1.271537290404636,-1.0987584815992129,-1.1516321867704016,-1.1530050289500637,0.26291950309547796,-3.1047473327126514,-2.0740832353846144,-0.80305585146951075],"mode":"markers","type":"scatter3d","name":"LEH","marker":{"color":"rgba(141,160,203,1)","line":{"color":"rgba(141,160,203,1)"}},"textfont":{"color":"rgba(141,160,203,1)"},"error_y":{"color":"rgba(141,160,203,1)"},"error_x":{"color":"rgba(141,160,203,1)"},"line":{"color":"rgba(141,160,203,1)"},"frame":null},{"x":[-1.9215219426413912,3.3499988030811836,0.91827709837975502,-0.98257870519661428,1.1500885487363428,-1.3714136655991702,-1.5044504781464787,-0.65128080835888069,2.4769129137958559,-1.1086700213034903,2.8785450826012284,-1.8186796099754226,-3.8769412473540279,-0.98706777065364215,0.89125024275521114,2.3898893935763699,-0.88544150326496052,0.7355665825724641,1.8933598123170239,0.40339776062422567,-0.45273522722207948,1.6260513886731713,3.3702739742634948,2.0179804628088385,2.0267845722053019],"y":[0.077198456418082428,1.5308406216093509,-0.032013230717069546,0.23616046666696494,-1.0237391318751694,-0.61295599331081574,-1.6319655460983491,0.12102596107119343,-0.078642920265714816,-1.2739075321409794,0.24118629629930766,0.10930924058571079,-0.75802845023592647,-0.75638619559834408,-0.34953006493302008,1.1803608638928484,-0.37077628525753165,0.63643038793810947,-0.13498245826379696,-0.35793578837779866,-0.18311125105099926,-1.6899541093453001,-2.792649991926734,0.56695837770330837,-1.2710493034129666],"z":[1.5264877253014526,0.75470164647235638,0.24750403494827142,-0.24238412638514892,1.5372036163838703,0.84661071258278875,0.69262951931477945,-0.41170574097695545,-0.26039969437698463,2.270291384348829,0.81350601338027162,-0.54076718980083704,-0.24119783839284614,1.5041223875831562,1.3644732863094269,1.4471270444656921,1.1607980074510724,-0.86373545579863853,0.12636711095476841,0.64144935990648644,0.30557502071889925,0.025175590948726984,1.7186316449569992,-0.53991037678088316,1.5769368987081724],"mode":"markers","type":"scatter3d","name":"TJH","marker":{"color":"rgba(231,138,195,1)","line":{"color":"rgba(231,138,195,1)"}},"textfont":{"color":"rgba(231,138,195,1)"},"error_y":{"color":"rgba(231,138,195,1)"},"error_x":{"color":"rgba(231,138,195,1)"},"line":{"color":"rgba(231,138,195,1)"},"frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
</div>
</section>

<section>
<section id="pca-biplot-combining-scores-and-loadings" class="title-slide slide level1 center">
<h1>PCA Biplot: Combining Scores and Loadings</h1>

</section>
<div class="columns">
<div class="column" style="width:60%;">
<h3 id="reading-a-biplot">Reading a Biplot</h3>
<ul>
<li>A <strong>biplot</strong> shows both:
<ul>
<li><strong>Points</strong> = plants (PC scores)</li>
<li><strong>Arrows</strong> = original variables (loadings)</li>
</ul></li>
<li><strong>How to interpret arrows</strong>:</li>
<li><strong>Length</strong> = how important the variable is</li>
<li><strong>Direction</strong> = how the variable relates to PCs</li>
<li><strong>Angle between arrows</strong> = correlation
<ul>
<li>Small angle = positively correlated</li>
<li>90° = uncorrelated</li>
<li>180° = negatively correlated</li>
</ul></li>
<li><strong>How to interpret points</strong>:
<ul>
<li>Plants in the direction of an arrow are high in that variable</li>
<li>Plants opposite an arrow are low in that variable</li>
</ul></li>
</ul>
</div><div class="column" style="width:40%;">
<p>The plot</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="16_01_lecture_powerpoint_files/figure-revealjs/biplot-1.png" width="576"></p>
</figure>
</div>
</div>
</div>
</div>
</div></section>
<section>
<section id="biplot-interpretation" class="title-slide slide level1 center">
<h1>Biplot Interpretation</h1>

</section>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="key-patterns-in-the-biplot">Key Patterns in the Biplot</h3>
<ul>
<li><strong>Variable relationships</strong>:
<ul>
<li>Most morphological and biomass variables point together (right and slightly down):
<ul>
<li><p>Height, mouth, masses - These are highly correlated</p></li>
<li><p>All contribute to PC1 (size)</p></li>
</ul></li>
</ul></li>
<li>Wing variables (wing1_length, wing2_length, wingspread) point more upward:
<ul>
<li>Contribute positively to PC2
<ul>
<li>Represent the “wing dimension” of shape</li>
</ul></li>
</ul></li>
<li><strong>Site separation</strong>:
<ul>
<li><p><strong>HD (blue)</strong>: Lower PC1, plants are smaller overall</p></li>
<li><p><strong>DG (orange)</strong>: Higher PC1, plants are larger</p></li>
<li><p><strong>TJH (yellow)</strong> and <strong>LEH (green)</strong>: Intermediate and variable</p></li>
</ul></li>
</ul>
</div><div class="column" style="width:50%;">
<h3 id="biological-interpretation">Biological Interpretation</h3>
<ul>
<li><strong>What determines plant morphology?</strong>
<ul>
<li><strong>Size</strong> (PC1, 45.8% variance)
<ul>
<li><p>Primary source of variation</p></li>
<li><p>Most measurements scale together</p></li>
<li><p>May reflect resource availability or age</p></li>
</ul></li>
<li><strong>Shape trade-offs</strong> (PC2, 16.7% variance)
<ul>
<li>Tall narrow vs.&nbsp;short wide with large wings</li>
<li>May reflect different trapping strategies</li>
<li>Or developmental/environmental constraints</li>
</ul></li>
<li><strong>Tube dimensions</strong> (PC3, 14.8% variance)
<ul>
<li>Independent aspect of morphology</li>
<li>May affect prey capture efficiency</li>
</ul></li>
<li><strong>Sites differ</strong> primarily in overall size, with some shape variation.</li>
</ul></li>
</ul>
</div>
</div></section>
<section>
<section id="testing-site-differences-with-anova" class="title-slide slide level1 center">
<h1>Testing Site Differences with ANOVA</h1>

</section>
<h3 id="step-4-statistical-analysis">Step 4: Statistical Analysis</h3>
<ul>
<li>Now that we have PC scores, we can test if sites differ:
<ul>
<li><strong>Result</strong>: Sites differ significantly in PC1 (F = 9.26, P &lt; 0.001)</li>
</ul></li>
</ul>
<div class="panel">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a></a><span class="co"># Test for site differences on PC1 (size)</span></span>
<span id="cb14-2"><a></a>anova_pc1 <span class="ot">&lt;-</span> <span class="fu">aov</span>(PC1 <span class="sc">~</span> site, <span class="at">data =</span> pc_scores)</span>
<span id="cb14-3"><a></a><span class="fu">summary</span>(anova_pc1)</span>
<span id="cb14-4"><a></a><span class="do">##             Df Sum Sq Mean Sq F value   Pr(&gt;F)    </span></span>
<span id="cb14-5"><a></a><span class="do">## site         3  124.3   41.44   11.29 2.75e-06 ***</span></span>
<span id="cb14-6"><a></a><span class="do">## Residuals   83  304.6    3.67                     </span></span>
<span id="cb14-7"><a></a><span class="do">## ---</span></span>
<span id="cb14-8"><a></a><span class="do">## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span>
<span id="cb14-9"><a></a></span>
<span id="cb14-10"><a></a><span class="co"># Calculate means by site</span></span>
<span id="cb14-11"><a></a>pc_scores <span class="sc">%&gt;%</span></span>
<span id="cb14-12"><a></a>  <span class="fu">group_by</span>(site) <span class="sc">%&gt;%</span></span>
<span id="cb14-13"><a></a>  <span class="fu">summarize</span>(</span>
<span id="cb14-14"><a></a>    <span class="at">mean_PC1 =</span> <span class="fu">mean</span>(PC1),</span>
<span id="cb14-15"><a></a>    <span class="at">sd_PC1 =</span> <span class="fu">sd</span>(PC1),</span>
<span id="cb14-16"><a></a>    <span class="at">n =</span> <span class="fu">n</span>()</span>
<span id="cb14-17"><a></a>  )</span>
<span id="cb14-18"><a></a><span class="do">## # A tibble: 4 × 4</span></span>
<span id="cb14-19"><a></a><span class="do">##   site  mean_PC1 sd_PC1     n</span></span>
<span id="cb14-20"><a></a><span class="do">##   &lt;chr&gt;    &lt;dbl&gt;  &lt;dbl&gt; &lt;int&gt;</span></span>
<span id="cb14-21"><a></a><span class="do">## 1 DG      -1.02   1.38     25</span></span>
<span id="cb14-22"><a></a><span class="do">## 2 HD       2.63   0.857    12</span></span>
<span id="cb14-23"><a></a><span class="do">## 3 LEH     -0.659  2.61     25</span></span>
<span id="cb14-24"><a></a><span class="do">## 4 TJH      0.423  1.90     25</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div></section>
<section>
<section id="anova-for-pc2-and-pc3" class="title-slide slide level1 center">
<h1>ANOVA for PC2 and PC3</h1>

</section>
<h3 id="testing-shape-and-tube-differences">Testing Shape and Tube Differences</h3>
<ul>
<li><strong>Results</strong>:
<ul>
<li>PC2 (shape): F = 5.36, P = 0.002 (significant)
<ul>
<li>PC3 (tube girth): F = 1.45, P = 0.234 (not significant)</li>
</ul></li>
</ul></li>
</ul>
<div class="panel">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a></a><span class="co"># Test for site differences on PC2 (shape)</span></span>
<span id="cb15-2"><a></a>anova_pc2 <span class="ot">&lt;-</span> <span class="fu">aov</span>(PC2 <span class="sc">~</span> site, <span class="at">data =</span> pc_scores)</span>
<span id="cb15-3"><a></a><span class="fu">summary</span>(anova_pc2)</span>
<span id="cb15-4"><a></a><span class="do">##             Df Sum Sq Mean Sq F value  Pr(&gt;F)   </span></span>
<span id="cb15-5"><a></a><span class="do">## site         3  21.63   7.209   4.595 0.00502 **</span></span>
<span id="cb15-6"><a></a><span class="do">## Residuals   83 130.22   1.569                   </span></span>
<span id="cb15-7"><a></a><span class="do">## ---</span></span>
<span id="cb15-8"><a></a><span class="do">## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span>
<span id="cb15-9"><a></a><span class="co"># Test for site differences on PC3 (tube girth)</span></span>
<span id="cb15-10"><a></a>anova_pc3 <span class="ot">&lt;-</span> <span class="fu">aov</span>(PC3 <span class="sc">~</span> site, <span class="at">data =</span> pc_scores)</span>
<span id="cb15-11"><a></a><span class="fu">summary</span>(anova_pc3)</span>
<span id="cb15-12"><a></a><span class="do">##             Df Sum Sq Mean Sq F value  Pr(&gt;F)    </span></span>
<span id="cb15-13"><a></a><span class="do">## site         3  43.68  14.561    13.8 2.2e-07 ***</span></span>
<span id="cb15-14"><a></a><span class="do">## Residuals   83  87.58   1.055                    </span></span>
<span id="cb15-15"><a></a><span class="do">## ---</span></span>
<span id="cb15-16"><a></a><span class="do">## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span>
<span id="cb15-17"><a></a><span class="co"># Summary statistics</span></span>
<span id="cb15-18"><a></a>pc_scores <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(site) <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(<span class="at">mean_PC2 =</span> <span class="fu">mean</span>(PC2),<span class="at">mean_PC3 =</span> <span class="fu">mean</span>(PC3))</span>
<span id="cb15-19"><a></a><span class="do">## # A tibble: 4 × 3</span></span>
<span id="cb15-20"><a></a><span class="do">##   site  mean_PC2 mean_PC3</span></span>
<span id="cb15-21"><a></a><span class="do">##   &lt;chr&gt;    &lt;dbl&gt;    &lt;dbl&gt;</span></span>
<span id="cb15-22"><a></a><span class="do">## 1 DG       0.604    0.542</span></span>
<span id="cb15-23"><a></a><span class="do">## 2 HD      -0.863   -1.26 </span></span>
<span id="cb15-24"><a></a><span class="do">## 3 LEH      0.155   -0.555</span></span>
<span id="cb15-25"><a></a><span class="do">## 4 TJH     -0.345    0.618</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div></section>
<section>
<section id="visualizing-site-differences" class="title-slide slide level1 center">
<h1>Visualizing Site Differences</h1>

</section>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="box-plots-of-pc-scores">Box Plots of PC Scores</h3>
<p><strong>HD plants are significantly smaller</strong> than plants at other sites.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="16_01_lecture_powerpoint_files/figure-revealjs/boxplots_pc1-1.png" width="576"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<ul>
<li><p><strong>TJH plants have different shapes</strong></p>
<ul>
<li>taller and narrower with smaller wings.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="16_01_lecture_powerpoint_files/figure-revealjs/boxplots_pc2-1.png" width="576"></p>
</figure>
</div>
</div>
</div></li>
</ul>
</div>
</div></section>
<section>
<section id="post-hoc-comparisons" class="title-slide slide level1 center">
<h1>Post-hoc Comparisons</h1>

</section>
<h3 id="which-sites-differ">Which Sites Differ?</h3>
<div class="panel">
<div class="cell">
<pre><code>##  contrast  estimate    SE df t.ratio p.value
##  DG - HD     -3.651 0.673 83  -5.427 &lt;0.0001
##  DG - LEH    -0.366 0.542 83  -0.675  0.9064
##  DG - TJH    -1.447 0.542 83  -2.671  0.0442
##  HD - LEH     3.285 0.673 83   4.883 &lt;0.0001
##  HD - TJH     2.204 0.673 83   3.276  0.0082
##  LEH - TJH   -1.082 0.542 83  -1.996  0.1977
## 
## P value adjustment: tukey method for comparing a family of 4 estimates
##  site emmean    SE df lower.CL upper.CL .group
##  DG   -1.024 0.383 83   -1.786   -0.262  a    
##  LEH  -0.659 0.383 83   -1.421    0.103  ab   
##  TJH   0.423 0.383 83   -0.339    1.185   b   
##  HD    2.626 0.553 83    1.526    3.726    c  
## 
## Confidence level used: 0.95 
## P value adjustment: tukey method for comparing a family of 4 estimates 
## significance level used: alpha = 0.05 
## NOTE: If two or more means share the same grouping symbol,
##       then we cannot show them to be different.
##       But we also did not show them to be the same.</code></pre>
</div>
</div></section>
<section>
<section id="distance-between-sites" class="title-slide slide level1 center">
<h1>Distance Between Sites</h1>

</section>
<div class="columns">
<div class="column" style="width:60%;">
<h3 id="calculating-euclidean-distance-between-groups">Calculating Euclidean Distance Between Groups</h3>
<ul>
<li>Calculate the distance between site centroids (mean PC scores):
<ul>
<li><span class="math inline">\(d_{k,j} = \sqrt{\sum_{i=1}^{p}(\bar{Z}_{i,k} - \bar{Z}_{i,j})^2}\)</span></li>
<li>Where <span class="math inline">\(\bar{Z}_{i,k}\)</span> is the mean of PC <em>i</em> for site <em>k</em>.</li>
</ul></li>
<li><strong>Using all PCs</strong> preserves the true Euclidean distance from the original data.</li>
<li><strong>Using just PC1-PC3</strong> (77% of variance) gives approximate distances.</li>
</ul>
</div><div class="column" style="width:40%;">
<p><strong>HD is most different</strong> from other sites (smallest plants).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a></a><span class="co"># Calculate site centroids (means)</span></span>
<span id="cb17-2"><a></a>site_means <span class="ot">&lt;-</span> pc_scores <span class="sc">%&gt;%</span></span>
<span id="cb17-3"><a></a>  <span class="fu">group_by</span>(site) <span class="sc">%&gt;%</span></span>
<span id="cb17-4"><a></a>  <span class="fu">summarize</span>(<span class="fu">across</span>(PC1<span class="sc">:</span>PC3, mean))</span>
<span id="cb17-5"><a></a></span>
<span id="cb17-6"><a></a>site_means</span>
<span id="cb17-7"><a></a><span class="do">## # A tibble: 4 × 4</span></span>
<span id="cb17-8"><a></a><span class="do">##   site     PC1    PC2    PC3</span></span>
<span id="cb17-9"><a></a><span class="do">##   &lt;chr&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;</span></span>
<span id="cb17-10"><a></a><span class="do">## 1 DG    -1.02   0.604  0.542</span></span>
<span id="cb17-11"><a></a><span class="do">## 2 HD     2.63  -0.863 -1.26 </span></span>
<span id="cb17-12"><a></a><span class="do">## 3 LEH   -0.659  0.155 -0.555</span></span>
<span id="cb17-13"><a></a><span class="do">## 4 TJH    0.423 -0.345  0.618</span></span>
<span id="cb17-14"><a></a></span>
<span id="cb17-15"><a></a><span class="co"># Calculate distance matrix</span></span>
<span id="cb17-16"><a></a>site_dist <span class="ot">&lt;-</span> site_means <span class="sc">%&gt;%</span></span>
<span id="cb17-17"><a></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(PC1, PC2, PC3) <span class="sc">%&gt;%</span></span>
<span id="cb17-18"><a></a>  <span class="fu">dist</span>() <span class="sc">%&gt;%</span></span>
<span id="cb17-19"><a></a>  <span class="fu">round</span>(<span class="dv">3</span>)</span>
<span id="cb17-20"><a></a>site_dist</span>
<span id="cb17-21"><a></a><span class="do">##       1     2     3</span></span>
<span id="cb17-22"><a></a><span class="do">## 2 4.328            </span></span>
<span id="cb17-23"><a></a><span class="do">## 3 1.241 3.511      </span></span>
<span id="cb17-24"><a></a><span class="do">## 4 1.732 2.942 1.672</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div></section>
<section id="visualization-of-the-distances" class="title-slide slide level1 center">
<h1>Visualization of the distances</h1>
<div class="panel">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a></a><span class="co"># 1. Prepare PC Scores with Site</span></span>
<span id="cb18-2"><a></a>pc_scores_for_dist <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(pca_result<span class="sc">$</span>x) <span class="sc">%&gt;%</span></span>
<span id="cb18-3"><a></a>  <span class="fu">mutate</span>(<span class="at">site =</span> darlingtonia<span class="sc">$</span>site)</span>
<span id="cb18-4"><a></a></span>
<span id="cb18-5"><a></a><span class="co"># 2. Calculate the mean PC scores for each site (the site "centroids")</span></span>
<span id="cb18-6"><a></a>site_centroids <span class="ot">&lt;-</span> pc_scores_for_dist <span class="sc">%&gt;%</span></span>
<span id="cb18-7"><a></a>  <span class="fu">group_by</span>(site) <span class="sc">%&gt;%</span></span>
<span id="cb18-8"><a></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">starts_with</span>(<span class="st">"PC"</span>), mean)) <span class="sc">%&gt;%</span></span>
<span id="cb18-9"><a></a>  <span class="fu">ungroup</span>()</span>
<span id="cb18-10"><a></a></span>
<span id="cb18-11"><a></a><span class="co"># 3. Set site names as row names BEFORE calculating distances</span></span>
<span id="cb18-12"><a></a>site_centroids_matrix <span class="ot">&lt;-</span> site_centroids <span class="sc">%&gt;%</span></span>
<span id="cb18-13"><a></a>  <span class="fu">column_to_rownames</span>(<span class="st">"site"</span>)  <span class="co"># This keeps site names as row names</span></span>
<span id="cb18-14"><a></a></span>
<span id="cb18-15"><a></a><span class="co"># 4. Calculate the Euclidean distance matrix between site centroids</span></span>
<span id="cb18-16"><a></a>dist_matrix <span class="ot">&lt;-</span> <span class="fu">dist</span>(site_centroids_matrix, <span class="at">method =</span> <span class="st">"euclidean"</span>)</span>
<span id="cb18-17"><a></a></span>
<span id="cb18-18"><a></a><span class="co"># Display the distance matrix</span></span>
<span id="cb18-19"><a></a>dist_matrix</span>
<span id="cb18-20"><a></a><span class="do">##           DG       HD      LEH</span></span>
<span id="cb18-21"><a></a><span class="do">## HD  4.346434                  </span></span>
<span id="cb18-22"><a></a><span class="do">## LEH 1.621198 3.659711         </span></span>
<span id="cb18-23"><a></a><span class="do">## TJH 1.843120 3.021386 1.960547</span></span>
<span id="cb18-24"><a></a></span>
<span id="cb18-25"><a></a><span class="co"># Visualize the distance matrix</span></span>
<span id="cb18-26"><a></a><span class="fu">fviz_dist</span>(dist_matrix, </span>
<span id="cb18-27"><a></a>          <span class="at">gradient =</span> <span class="fu">list</span>(<span class="at">low =</span> <span class="st">"#00AFBB"</span>, <span class="at">high =</span> <span class="st">"#FC4E07"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="16_01_lecture_powerpoint_files/figure-revealjs/euclidian distances-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</section>

<section>
<section id="summary-pca-results-for-darlingtonia" class="title-slide slide level1 center">
<h1>Summary: PCA Results for Darlingtonia</h1>

</section>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="what-we-learned">What We Learned</h3>
<ul>
<li>Dimension Reduction Success
<ul class="task-list">
<li><label><input type="checkbox" checked=""><strong>Started with</strong>: 10 correlated variables<br>
</label></li>
<li><label><input type="checkbox" checked=""><strong>Reduced to</strong>: 3 principal components<br>
</label></li>
<li><label><input type="checkbox" checked=""><strong>Retained</strong>: 77.3% of variance</label></li>
</ul></li>
<li>This makes data <strong>easier to visualize, interpret, and analyze</strong>.</li>
<li>Biological Insights - <strong>Three major axes of morphological variation</strong>: - <strong>PC1 (45.8%)</strong>: Overall size
<ul>
<li>Larger vs.&nbsp;smaller plants</li>
<li>HD site has smallest plants - <strong>PC2 (16.7%)</strong>: Shape contrast</li>
<li>Tall/narrow vs.&nbsp;short/wide with large wings</li>
<li>TJH site has taller, narrower plants - <strong>PC3 (14.8%)</strong>: Tube girth</li>
<li>Fat vs.&nbsp;skinny tubes</li>
<li>No significant site differences</li>
</ul></li>
</ul>
</div><div class="column" style="width:50%;">
<ul>
<li>Statistical Findings
<ul>
<li><strong>Sites differ significantly</strong> in size (PC1)</li>
<li><strong>Sites differ significantly</strong> in shape (PC2)</li>
<li><strong>Sites do not differ</strong> in tube girth (PC3)</li>
</ul></li>
<li>PCA Advantages
<ul class="task-list">
<li><label><input type="checkbox" checked="">Reduced 10 dimensions to 3<br>
</label></li>
<li><label><input type="checkbox" checked="">Created uncorrelated variables<br>
</label></li>
<li><label><input type="checkbox" checked="">Revealed biological patterns<br>
</label></li>
<li><label><input type="checkbox" checked="">Enabled statistical testing<br>
</label></li>
<li><label><input type="checkbox" checked="">Simplified visualization</label></li>
</ul></li>
<li>Key Take-Home Messages
<ul>
<li>PCA good for <strong>exploratory analysis</strong> of multivariate data</li>
<li>Always <strong>standardize</strong> when different units/scales</li>
<li><strong>Loadings</strong> reveal variables contributions to each component</li>
<li><strong>Scores</strong> used in subsequent analyses (ANOVA, regression)</li>
<li><strong>Biplots</strong> visualize both samples and variables simultaneously</li>
</ul></li>
</ul>
</div>
</div></section>
<section id="when-to-use-pca" class="title-slide slide level1 center">
<h1>When to Use PCA</h1>
<ul>
<li>PCA is Appropriate When:
<ul class="task-list">
<li><label><input type="checkbox" checked="">Variables are <strong>continuous</strong> (not categorical)</label></li>
<li><label><input type="checkbox" checked="">Variables are <strong>correlated</strong> (redundancy exists) + <strong>Linear relationships</strong></label></li>
<li><label><input type="checkbox" checked="">Goal is <strong>dimension reduction</strong> or <strong>data exploration</strong></label></li>
<li><label><input type="checkbox" checked=""><strong>Sample size</strong> adequate (at least 3× number of variables)</label></li>
</ul></li>
<li>PCA Assumptions:
<ul>
<li><strong>Linearity</strong>: relationships between variables are linear</li>
<li><strong>Adequate correlation</strong>: variables must be correlated</li>
<li><strong>No severe outliers</strong>: can distort results</li>
<li><strong>Sample size</strong>: need enough observations</li>
</ul></li>
<li>Always Check:
<ul>
<li>Correlation matrix (are variables correlated?)</li>
<li>Scree plot (how many components needed?)</li>
<li>Loadings (biological interpretation makes sense?)</li>
<li>Outliers (check scores plots)</li>
</ul></li>
</ul>
</section>

<section id="when-to-consider-alternatives" class="title-slide slide level1 center">
<h1>When to <strong>Consider Alternatives:</strong></h1>
<ul>
<li><strong>Different data types</strong>:
<ul>
<li>Categorical variables → MCA (Multiple</li>
<li>Correspondence Analysis) - Species composition data → CA (Correspondence Analysis)</li>
<li>Distance/dissimilarity matrices → PCoA (Principal Coordinates Analysis)</li>
</ul></li>
<li><strong>Different goals</strong>: - Classification → Discriminant Analysis
<ul>
<li>Non-linear patterns → NMDS (Non-metric Multidimensional Scaling)</li>
<li>Hypothesis testing → MANOVA</li>
</ul></li>
<li><strong>Problems with PCA</strong>:
<ul>
<li>Strong outliers present</li>
<li>Non-linear relationships</li>
<li>Variables are uncorrelated</li>
<li>Many zeros in data</li>
</ul></li>
<li><strong>PCA works best</strong> for morphological, physiological, and environmental variables!</li>
</ul>
</section>

<section>
<section id="additional-pca-diagnostics" class="title-slide slide level1 center">
<h1>Additional PCA Diagnostics</h1>

</section>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="checking-assumptions-and-quality">Checking Assumptions and Quality</h3>
<ol type="1">
<li>Sampling Adequacy</li>
</ol>
<ul>
<li><strong>Kaiser-Meyer-Olkin (KMO) Test</strong>:</li>
<li>Measures sampling adequacy</li>
<li>Values &gt; 0.6 = acceptable</li>
<li>Values &gt; 0.8 = good</li>
</ul>
<p>Our overall KMO = 0.80 (good!)</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a></a><span class="co"># KMO test requires psych package</span></span>
<span id="cb19-2"><a></a><span class="fu">KMO</span>(<span class="fu">cor</span>(darl_numeric))</span>
<span id="cb19-3"><a></a><span class="do">## Kaiser-Meyer-Olkin factor adequacy</span></span>
<span id="cb19-4"><a></a><span class="do">## Call: KMO(r = cor(darl_numeric))</span></span>
<span id="cb19-5"><a></a><span class="do">## Overall MSA =  0.76</span></span>
<span id="cb19-6"><a></a><span class="do">## MSA for each item = </span></span>
<span id="cb19-7"><a></a><span class="do">##       height   mouth_diam    tube_diam    keel_diam wing1_length wing2_length </span></span>
<span id="cb19-8"><a></a><span class="do">##         0.64         0.84         0.47         0.61         0.85         0.80 </span></span>
<span id="cb19-9"><a></a><span class="do">##    wingsprea   hoodmass_g   tubemass_g   wingmass_g </span></span>
<span id="cb19-10"><a></a><span class="do">##         0.76         0.78         0.72         0.86</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div><div class="column" style="width:50%;">
<h3 id="outlier-detection">2. Outlier Detection</h3>
<p>Check for influential observations:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="16_01_lecture_powerpoint_files/figure-revealjs/outliers-1.png" width="576"></p>
</figure>
</div>
</div>
</div>
</div>
</div></section>
<section>
<section id="pca-vs.-other-ordination-methods" class="title-slide slide level1 center">
<h1>PCA vs.&nbsp;Other Ordination Methods</h1>

</section>
<section id="comparison-table" class="slide level2">
<h2>Comparison Table</h2>
<table class="caption-top">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Method</th>
<th>Data Type</th>
<th>Distance/Similarity</th>
<th>Linear?</th>
<th>Eigenanalysis?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>PCA</strong></td>
<td>Continuous, correlated</td>
<td>Euclidean (correlation)</td>
<td>Yes</td>
<td>Yes</td>
</tr>
<tr class="even">
<td><strong>CA</strong></td>
<td>Count data, species</td>
<td>Chi-square</td>
<td>No</td>
<td>Yes</td>
</tr>
<tr class="odd">
<td><strong>PCoA</strong></td>
<td>Any (via distance matrix)</td>
<td>Any distance metric</td>
<td>N/A</td>
<td>Yes</td>
</tr>
<tr class="even">
<td><strong>NMDS</strong></td>
<td>Any (via distance matrix)</td>
<td>Any distance metric</td>
<td>No</td>
<td>No</td>
</tr>
<tr class="odd">
<td><strong>DCA</strong></td>
<td>Species abundance</td>
<td>Weighted averaging</td>
<td>No</td>
<td>Yes</td>
</tr>
</tbody>
</table>
</section></section>
<section>
<section id="advanced-topics-in-pca" class="title-slide slide level1 center">
<h1>Advanced Topics in PCA</h1>

</section>
<div class="columns">
<div class="column" style="width:50%;">
<section id="topics-we-havent-covered" class="slide level2">
<h2>Topics We Haven’t Covered</h2>
<ul>
<li><strong>Factor Analysis</strong>: - Similar to PCA but with different goals - Assumes latent “factors” cause observed variables - Uses rotation to improve interpretation - More common in social sciences</li>
<li><strong>Robust PCA</strong>: - Less sensitive to outliers - Uses robust covariance estimators - Useful with messy ecological data</li>
<li><strong>Sparse PCA</strong>: - Forces many loadings to exactly zero - Easier to interpret - Better for very high-dimensional data</li>
</ul>
</section>
</div><div class="column" style="width:50%;">
<ul>
<li><strong>Functional PCA</strong>: - For time series or spatial data - Treats curves as observations - Common in physiology</li>
<li><strong>Probabilistic PCA</strong>: - Includes uncertainty estimation - Can handle missing data - Maximum likelihood framework</li>
<li><strong>Kernel PCA</strong>: - Handles non-linear relationships - Uses kernel trick from machine learning - More flexible but harder to interpret<br>
</li>
<li>These are beyond our scope but worth knowing exist!</li>
</ul>
</div>
</div></section>
<section>
<section id="practical-tips-for-pca" class="title-slide slide level1 center">
<h1>Practical Tips for PCA</h1>

</section>
<section id="best-practices" class="slide level2">
<h2>Best Practices</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="before-pca">Before PCA:</h3>
<ol type="1">
<li><strong>Explore your data</strong>
<ul>
<li>Check distributions</li>
<li>Identify outliers</li>
<li>Understand variable scales</li>
</ul></li>
<li><strong>Check correlations</strong>
<ul>
<li>Make correlation plot</li>
<li>Ensure variables are correlated</li>
<li>Consider removing redundant variables</li>
</ul></li>
<li><strong>Standardize appropriately</strong>
<ul>
<li>Use <code>scale = TRUE</code> for different units</li>
<li>Consider centering only for same units</li>
</ul></li>
<li><strong>Check sample size</strong>
<ul>
<li>Need at least 3× variables</li>
<li>More is better (50+ ideal)</li>
</ul></li>
</ol>
</div><div class="column" style="width:50%;">
<h3 id="during-pca">During PCA:</h3>
<ol type="1">
<li><strong>Examine scree plot</strong>
<ul>
<li>Look for elbow</li>
<li>Consider cumulative variance</li>
<li>Usually keep 2-5 components</li>
</ul></li>
<li><strong>Interpret loadings</strong>
<ul>
<li>Look for patterns</li>
<li>Consider biological meaning</li>
<li>Ignore very small loadings</li>
</ul></li>
<li><strong>Check scores plots</strong>
<ul>
<li>Look for outliers</li>
<li>Identify patterns/groups</li>
<li>Consider site/treatment effects</li>
</ul></li>
</ol>
<h3 id="after-pca">After PCA:</h3>
<ol type="1">
<li><strong>Report clearly</strong>
<ul>
<li>State why you used PCA</li>
<li>Report variance explained</li>
<li>Describe component interpretation</li>
</ul></li>
<li><strong>Use results appropriately</strong>
<ul>
<li>PC scores can go into other analyses</li>
<li>Don’t over-interpret small components</li>
<li>Remember: exploratory tool!</li>
</ul></li>
</ol>
</div></div>
</section></section>
<section>
<section id="reporting-pca-results" class="title-slide slide level1 center">
<h1>Reporting PCA Results</h1>

</section>
<section id="what-to-include-in-paperstheses" class="slide level2">
<h2>What to Include in Papers/Theses</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="methods-section">Methods Section:</h3>
<p>“We performed principal component analysis (PCA) on 10 morphological and biomass variables measured on 89 <em>Darlingtonia californica</em> plants from four sites. Variables were standardized (mean = 0, SD = 1) prior to analysis to account for different measurement scales. PCA was conducted using the <code>prcomp()</code> function in R. We retained principal components with eigenvalues &gt; 1 and that cumulatively explained &gt;70% of variance.”</p>
<h3 id="results-section">Results Section:</h3>
<p>“The first three principal components explained 77.3% of variance (PC1: 45.8%, PC2: 16.7%, PC3: 14.8%). PC1 represented overall plant size, with high positive loadings for most morphological and biomass variables…”</p>
</div><div class="column" style="width:50%;">
<h3 id="essential-figures">Essential Figures:</h3>
<ol type="1">
<li><strong>Scree plot</strong> - shows variance explained</li>
<li><strong>Loadings plot</strong> - shows variable contributions</li>
<li><strong>Scores plot</strong> or <strong>biplot</strong> - shows samples in PC space</li>
</ol>
<h3 id="essential-tables">Essential Tables:</h3>
<ol type="1">
<li><strong>Variance explained</strong> by each PC</li>
<li><strong>Loadings</strong> for retained PCs (usually PC1-PC3)</li>
<li><strong>ANOVA results</strong> if testing groups</li>
</ol>
<h3 id="dont-report">Don’t Report:</h3>
<ul>
<li>All 10 PCs if only 3 are meaningful</li>
<li>Tiny loadings (&lt; 0.3)</li>
<li>Every individual PC score</li>
<li>Raw eigenvalues (report % variance instead)</li>
</ul>
</div></div>
</section></section>
<section>
<section id="common-pca-mistakes-to-avoid" class="title-slide slide level1 center">
<h1>Common PCA Mistakes to Avoid</h1>

</section>
<div class="columns">
<div class="column" style="width:50%;">
<section id="mistakes-students-make" class="slide level2">
<h2>Mistakes Students Make:</h2>
<p>❌ <strong>Not standardizing</strong> data with different units<br>
→ ✓ Always use <code>scale = TRUE</code> for different units</p>
<p>❌ <strong>Forgetting to check correlations</strong><br>
→ ✓ Make correlation plot first</p>
<p>❌ <strong>Using too many components</strong><br>
→ ✓ Use scree plot, keep components above elbow</p>
<p>❌ <strong>Over-interpreting small loadings</strong><br>
→ ✓ Focus on loadings &gt; |0.3|</p>
<p>❌ <strong>Ignoring signs on loadings</strong><br>
→ ✓ Sign can flip; look at patterns</p>
<p>❌ <strong>Treating PC scores as original data</strong><br>
→ ✓ Remember PCs are derived variables</p>
</section>
</div><div class="column" style="width:50%;">
<p>❌ <strong>Using PCA on categorical data</strong><br>
→ ✓ Use appropriate method (CA, MCA)</p>
<p>❌ <strong>Not checking for outliers</strong><br>
→ ✓ Plot scores, check for extreme values</p>
<p>❌ <strong>Assuming PCs have biological meaning</strong><br>
→ ✓ Interpret carefully, components are mathematical</p>
<p>❌ <strong>Using PCA with too few samples</strong><br>
→ ✓ Need n &gt; 3p (preferably n &gt; 50)</p>
<p>❌ <strong>Not reporting variance explained</strong><br>
→ ✓ Always report % variance for each PC</p>
<p>❌ <strong>Forgetting that PCA is exploratory</strong><br>
→ ✓ Use for patterns, not hypothesis testing</p>
</div>
</div></section>
<section>
<section id="practice-exercise" class="title-slide slide level1 center">
<h1>Practice Exercise</h1>

</section>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="exercise-1-subset-analysis">Exercise 1: Subset Analysis</h3>
<p>Try running PCA on just the <strong>morphological variables</strong> (exclude biomass):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a></a><span class="co"># Select only morphological variables</span></span>
<span id="cb20-2"><a></a>darl_morph <span class="ot">&lt;-</span> darlingtonia <span class="sc">%&gt;%</span></span>
<span id="cb20-3"><a></a>  <span class="fu">select</span>(height, mouth_diam, tube_diam, </span>
<span id="cb20-4"><a></a>         keel_diam, wing1_length, </span>
<span id="cb20-5"><a></a>         wing2_length, wingsprea)</span>
<span id="cb20-6"><a></a></span>
<span id="cb20-7"><a></a><span class="co"># Run PCA</span></span>
<span id="cb20-8"><a></a>pca_morph <span class="ot">&lt;-</span> <span class="fu">prcomp</span>(darl_morph, </span>
<span id="cb20-9"><a></a>                    <span class="at">scale. =</span> <span class="cn">TRUE</span>)</span>
<span id="cb20-10"><a></a></span>
<span id="cb20-11"><a></a><span class="co"># Examine results</span></span>
<span id="cb20-12"><a></a><span class="fu">summary</span>(pca_morph)</span>
<span id="cb20-13"><a></a></span>
<span id="cb20-14"><a></a><span class="co"># How do results differ from full PCA?</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div><div class="column" style="width:50%;">
<h3 id="exercise-2-site-specific-pca">Exercise 2: Site-Specific PCA</h3>
<p>Run PCA on just one site (e.g., DG):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a></a><span class="co"># Filter to one site</span></span>
<span id="cb21-2"><a></a>darl_dg <span class="ot">&lt;-</span> darlingtonia <span class="sc">%&gt;%</span></span>
<span id="cb21-3"><a></a>  <span class="fu">filter</span>(site <span class="sc">==</span> <span class="st">"DG"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb21-4"><a></a>  <span class="fu">select</span>(<span class="sc">-</span>site)</span>
<span id="cb21-5"><a></a></span>
<span id="cb21-6"><a></a><span class="co"># Run PCA</span></span>
<span id="cb21-7"><a></a>pca_dg <span class="ot">&lt;-</span> <span class="fu">prcomp</span>(darl_dg, </span>
<span id="cb21-8"><a></a>                 <span class="at">scale. =</span> <span class="cn">TRUE</span>)</span>
<span id="cb21-9"><a></a></span>
<span id="cb21-10"><a></a><span class="co"># Compare to overall PCA</span></span>
<span id="cb21-11"><a></a><span class="fu">summary</span>(pca_dg)</span>
<span id="cb21-12"><a></a></span>
<span id="cb21-13"><a></a><span class="co"># Do the same patterns emerge?</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<h3 id="exercise-3-interpretation">Exercise 3: Interpretation</h3>
<ol type="1">
<li>What does PC1 represent in each analysis?</li>
<li>How much variance is explained?</li>
<li>Do you see the same patterns?</li>
</ol>
</div>
</div></section>
<section id="some-other-ways" class="title-slide slide level1 center">
<h1>Some other ways</h1>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="16_01_lecture_powerpoint_files/figure-revealjs/unnamed-chunk-3-1.png" width="960"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="16_01_lecture_powerpoint_files/figure-revealjs/unnamed-chunk-3-2.png" width="960"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="16_01_lecture_powerpoint_files/figure-revealjs/unnamed-chunk-4-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="16_01_lecture_powerpoint_files/figure-revealjs/unnamed-chunk-5-1.png" width="960"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="16_01_lecture_powerpoint_files/figure-revealjs/unnamed-chunk-5-2.png" width="960"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="16_01_lecture_powerpoint_files/figure-revealjs/unnamed-chunk-6-1.png" width="960"></p>
</figure>
</div>
</div>
<pre><code>## Permutation test for adonis under reduced model
## Permutation: free
## Number of permutations: 999
## 
## adonis2(formula = darl_scaled ~ site, data = darlingtonia, permutations = 999, method = "euclidean")
##          Df SumOfSqs      R2      F Pr(&gt;F)    
## Model     3   189.72 0.24512 8.9836  0.001 ***
## Residual 83   584.28 0.75488                  
## Total    86   774.00 1.00000                  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="16_01_lecture_powerpoint_files/figure-revealjs/unnamed-chunk-7-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<pre><code>## $parent_call
## [1] "darl_scaled ~ site , strata = Null , permutations 999"
## 
## $TJH_vs_DG
##          Df SumOfSqs      R2      F Pr(&gt;F)    
## Model     1   32.602 0.10636 5.7128  0.001 ***
## Residual 48  273.930 0.89364                  
## Total    49  306.532 1.00000                  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## $TJH_vs_LEH
##          Df SumOfSqs      R2      F Pr(&gt;F)   
## Model     1    47.72 0.10517 5.6414  0.002 **
## Residual 48   406.06 0.89483                 
## Total    49   453.78 1.00000                 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## $TJH_vs_HD
##          Df SumOfSqs      R2      F Pr(&gt;F)    
## Model     1   69.308 0.25135 11.751  0.001 ***
## Residual 35  206.432 0.74865                  
## Total    36  275.740 1.00000                  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## $DG_vs_LEH
##          Df SumOfSqs      R2      F Pr(&gt;F)  
## Model     1    26.24 0.06493 3.3333  0.016 *
## Residual 48   377.85 0.93507                
## Total    49   404.09 1.00000                
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## $DG_vs_HD
##          Df SumOfSqs      R2      F Pr(&gt;F)    
## Model     1   131.09 0.42382 25.745  0.001 ***
## Residual 35   178.22 0.57618                  
## Total    36   309.31 1.00000                  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## $LEH_vs_HD
##          Df SumOfSqs     R2      F Pr(&gt;F)    
## Model     1   101.69 0.2468 11.468  0.001 ***
## Residual 35   310.35 0.7532                  
## Total    36   412.04 1.0000                  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## attr(,"class")
## [1] "pwadstrata" "list"</code></pre>
</div>
<div class="cell">
<pre><code>## 
##  Pairwise comparisons using permutation MANOVAs on a distance matrix 
## 
## data:  vegdist(darl_scaled, method = "euclidean") by darlingtonia$site
## 999 permutations 
## 
##     DG    HD    LEH  
## HD  0.006 -     -    
## LEH 0.108 0.006 -    
## TJH 0.006 0.006 0.018
## 
## P value adjustment method: bonferroni</code></pre>
</div>
<p>results come from different statistical tests being used. Let me break down what each is doing: 1. pairwise.adonis2() - PERMANOVA on subsets What it does: For each pair, it subsets the data to just those 2 sites and runs a separate PERMANOVA Results: All p-values ≤ 0.016 (5 of 6 are p = 0.001) Interpretation: Tests if centroids (mean positions) differ between site pairs 2. pairwise.perm.manova() - Different test entirely What it does: Uses a MANOVA-based approach with permutations on the full distance matrix Results: More conservative - DG vs LEH now p = 0.078 (not significant) Interpretation: Also tests centroid differences but uses a different statistical framework</p>
<p>Why the differences matter: Location (Centroid) Tests:</p>
<p>pairwise.adonis2() and pairwise.perm.manova() both test if site means differ They give slightly different p-values due to different algorithms, but similar conclusions Use these to answer: “Are sites morphologically different?”</p>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/your-site-url\.github\.io");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>