<!DOCTYPE html>
<html lang="en"><head>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.36">

  <meta name="author" content="Bill Perry">
  <title>UMD Biostatistics – Lecture 13 - Nested ANOVA</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-b88c2fe81f1ff78e74849ca62ba99059.css">
  <link rel="stylesheet" href="../../css/lecture.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
<meta property="og:title" content="Lecture 13 - Nested ANOVA – UMD Biostatistics">
<meta property="og:site_name" content="UMD Biostatistics">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Lecture 13 - Nested ANOVA</h1>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Bill Perry 
</div>
</div>
</div>

</section>
<section id="lecture-12-review" class="title-slide slide level1 center">
<h1>Lecture 12: Review</h1>
<div class="columns">
<div class="column" style="width:60%;">
<ul>
<li>Two Factor ANOVA
<ul>
<li><p>Example</p></li>
<li><p>Linear model</p></li>
<li><p>Analysis of variance</p></li>
<li><p>Null hypotheses</p></li>
<li><p>Interactions and main effects</p></li>
<li><p>Unequal sample size</p></li>
<li><p>Assumptions</p></li>
</ul></li>
</ul>
</div><div class="column" style="width:40%;">
<p><img data-src="images/clipboard-1642768928.png" style="width:75.0%"></p>
</div></div>
</section>

<section id="lecture-12-2-factor-or-2-way-anova" class="title-slide slide level1 center">
<h1>Lecture 12: 2 Factor or 2 Way ANOVA</h1>
<div class="columns">
<div class="column" style="width:60%;">
<ul>
<li>Often consider more than 1 factor (independent categorical variables):
<ul>
<li>reduce unexplained variance</li>
<li>look at interactions</li>
</ul></li>
<li>2-factor designs (2-way ANOVA) very common in ecology</li>
<li>Can have more factors (e.g., 3-way ANOVA)
<ul>
<li>interpretation tricky…</li>
</ul></li>
<li>Most tests are multifactor designs:
<ul>
<li>factorial</li>
<li>nested</li>
<li>mixed</li>
</ul></li>
</ul>
</div><div class="column" style="width:40%;">
<p><img data-src="images/clipboard-1173869376.png" style="width:75.0%"></p>
</div></div>
</section>

<section id="factorial-versus-nested-designs" class="title-slide slide level1 center">
<h1>Factorial Versus Nested Designs</h1>
<div class="columns">
<div class="column" style="width:60%;">
<ul>
<li>Consider two factors: A and B
<ul>
<li><p>Factorial/crossed: every level of B in every level of A</p></li>
<li><p>Nested/hierarchical: levels of B occur only in 1 level of A</p>
<ul>
<li>both can be fixed - rare</li>
<li>one fixed one random</li>
<li>both random - rare in ecology common in genetics</li>
</ul></li>
</ul></li>
</ul>
</div><div class="column" style="width:40%;">
<p><img data-src="images/clipboard-758019042.png" style="width:75.0%"></p>
</div></div>
</section>

<section id="factorial-designs-overview" class="title-slide slide level1 center">
<h1>Factorial Designs Overview</h1>
<div class="columns">
<div class="column" style="width:40%;">
<ul>
<li>Factorial Designs:
<ul>
<li>Both factors typically fixed (but not always)</li>
</ul></li>
</ul>
</div><div class="column" style="width:60%;">
<p><img data-src="images/clipboard-723648250.png" style="width:100.0%"></p>
</div></div>
</section>

<section id="factorial-design-example-seedling-growth" class="title-slide slide level1 center">
<h1>Factorial Design Example: Seedling Growth</h1>
<div class="columns">
<div class="column" style="width:40%;">
<ul>
<li>Effects of light level on growth of seedlings of different size:
<ul>
<li><p>3 light levels (factor A)</p></li>
<li><p>3 size classes (factor B)</p></li>
<li><p>5 replicate seeding in each cell</p></li>
</ul></li>
</ul>
</div><div class="column" style="width:60%;">
<p><img data-src="images/clipboard-1057376698.png" style="width:100.0%"></p>
</div></div>
</section>

<section id="factorial-design-example-salamander-growth" class="title-slide slide level1 center">
<h1>Factorial Design Example: Salamander Growth</h1>
<div class="columns">
<div class="column" style="width:40%;">
<ul>
<li>Effects of food level and tadpole presence on larval salamander growth
<ul>
<li><p>2 food levels (factor A)</p></li>
<li><p>presence/absence of tadpoles (factor B)</p></li>
<li><p>8 replicates in each cell</p></li>
</ul></li>
</ul>
</div><div class="column" style="width:60%;">
<p><img data-src="images/clipboard-3697840818.png" style="width:100.0%"></p>
</div></div>
</section>

<section id="factorial-design-example-limpet-fecundity" class="title-slide slide level1 center">
<h1>Factorial Design Example: Limpet Fecundity</h1>
<div class="columns">
<div class="column" style="width:40%;">
<ul>
<li>Effect of season and density on limpet fecundity.
<ul>
<li><p>2 seasons (factor A)</p></li>
<li><p>4 density treatments (factor B)</p></li>
<li><p>3 replicates in each cell</p></li>
</ul></li>
</ul>
</div><div class="column" style="width:60%;">
<p><img data-src="images/clipboard-1223732443.png" style="width:100.0%"></p>
</div></div>
</section>

<section id="nested-designs-overview" class="title-slide slide level1 center">
<h1>Nested Designs Overview</h1>
<div class="columns">
<div class="column" style="width:40%;">
<ul>
<li>Nested design examples
<ul>
<li>Nested designs</li>
<li>Linear model</li>
<li>Analysis of variance</li>
<li>Null hypotheses</li>
<li>Unbalanced designs</li>
<li>Assumptions</li>
<li>mixed model ANOVA</li>
</ul></li>
<li>Nested Designs:
<ul>
<li>Factor A usually fixed</li>
<li>Factor B usually random</li>
</ul></li>
</ul>
</div><div class="column" style="width:60%;">
<p><img data-src="images/clipboard-3125256618.png" style="width:100.0%"></p>
</div></div>
</section>

<section id="nested-design-example-limpet-growth" class="title-slide slide level1 center">
<h1>Nested Design Example: Limpet Growth</h1>
<div class="columns">
<div class="column" style="width:40%;">
<ul>
<li>Study on effects of enclosure size on limpet growth:
<ul>
<li><p>2 enclosure sizes (factor A)</p></li>
<li><p>5 replicate enclosures (factor B)</p></li>
<li><p>5 replicate limpets per enclosure</p></li>
</ul></li>
</ul>
</div><div class="column" style="width:60%;">
<p><img data-src="images/clipboard-1867917958.png" style="width:100.0%"></p>
</div></div>
</section>

<section id="nested-design-example-reef-fish" class="title-slide slide level1 center">
<h1>Nested Design Example: Reef Fish</h1>
<div class="columns">
<div class="column" style="width:40%;">
<ul>
<li>Study on reef fish recruitment:
<ul>
<li><p>5 sites (factor A)</p></li>
<li><p>6 transects at each site (factor B)</p></li>
<li><p>replicate observations along each transect</p></li>
</ul></li>
</ul>
</div><div class="column" style="width:60%;">
<p><img data-src="images/clipboard-1621781711.png" style="width:100.0%"></p>
</div></div>
</section>

<section id="nested-design-example-sea-urchin-grazing" class="title-slide slide level1 center">
<h1>Nested Design Example: Sea Urchin Grazing</h1>
<div class="columns">
<div class="column" style="width:40%;">
<p>Effects of sea urchin grazing on biomass of filamentous algae:</p>
<ul>
<li>4 levels of urchin grazing: none, L, M, H</li>
<li>4 patches of rocky bottom (3-4 m2) nested in each level of grazing</li>
<li>5 replicate quadrats per patch</li>
</ul>
</div><div class="column" style="width:60%;">
<p><img data-src="images/clipboard-3570106410.png" style="width:100.0%"></p>
</div></div>
</section>

<section id="nested-design-linear-model-structure" class="title-slide slide level1 center">
<h1>Nested Design: Linear Model Structure</h1>
<div class="columns">
<div class="column" style="width:40%;">
<ul>
<li>Consider a nested design with:
<ul>
<li><p>p levels of factor A (i= 1…p) (e.g., 4 grazing levels)</p></li>
<li><p>q levels of factor B (j= 1…q), nested within each level of A (e.g., 4 - diff. patches per grazing level)</p></li>
<li><p>n replicates (k= 1…n) in each combination of A and B (5 replicate - quadrats in each patch in each grazing level)</p></li>
</ul></li>
</ul>
</div><div class="column" style="width:60%;">
<p><img data-src="images/clipboard-2460153431.png"></p>
</div></div>
</section>

<section id="calculating-means-in-nested-design" class="title-slide slide level1 center">
<h1>Calculating Means in Nested Design</h1>
<div class="columns">
<div class="column" style="width:40%;">
<ul>
<li>Can calculate several means:
<ul>
<li>overall mean (across all levels of A and B)= ȳ;</li>
<li>a mean for each level of A (across all levels of B in that A)= ȳi;</li>
<li>a mean for each level of B within each A= ȳj(i)</li>
</ul></li>
</ul>
</div><div class="column" style="width:60%;">
<p><img data-src="images/clipboard-2098022400.png" style="width:100.0%"></p>
</div></div>
</section>

<section id="nested-design-means-visualization" class="title-slide slide level1 center">
<h1>Nested Design Means Visualization</h1>
<div class="panel" data-column="screen">
<p><img data-src="images/clipboard-1474611051.png" style="width:100.0%"></p>
</div>
</section>

<section>
<section id="nested-design-linear-model" class="title-slide slide level1 center">
<h1>Nested Design Linear Model</h1>
<p>The linear model for a nested design is:</p>
</section>
<h3 id="y_ijk-mu-alpha_i-beta_ji-varepsilon_ijk"><span class="math display">\[y_{ijk} = \mu + \alpha_i + \beta_{j(i)} + \varepsilon_{ijk}\]</span></h3>
<ul>
<li>Where:
<ul>
<li><span class="math inline">\(y_{ijk}\)</span> is the response variable
<ul>
<li>value of the k-th replicate in j-th level of B in the i-th level of A</li>
<li>(algal biomass in 3rd quadrat, in 2nd patch in low grazing treatment)</li>
</ul></li>
<li><span class="math inline">\(\mu\)</span> is the overall mean
<ul>
<li>(overall average algal biomass)</li>
</ul></li>
</ul></li>
</ul></section>
<section>
<section id="fixed-effects-in-nested-model" class="title-slide slide level1 center">
<h1>Fixed Effects in Nested Model</h1>
<p>The linear model for a nested design is:</p>
</section>
<h3 id="y_ijk-mu-alpha_i-beta_ji-varepsilon_ijk-1"><span class="math display">\[y_{ijk} = \mu + \alpha_i + \beta_{j(i)} + \varepsilon_{ijk}\]</span></h3>
<ul>
<li><span class="math inline">\(\alpha_i\)</span> is the fixed effect of factor <span class="math inline">\(i\)</span></li>
<li>(difference between average biomass in all low grazing level quadrats and overall mean)</li>
<li><span class="math inline">\(\beta_{j(i)}\)</span> is the random effect of factor <span class="math inline">\(j\)</span> nested within factor <span class="math inline">\(i\)</span></li>
<li>usually random variable, measuring variance among all possible levels of B within each level of A</li>
<li>(variance among all possible patches that may have been used in the low grazing treatment)</li>
</ul></section>
<section>
<section id="error-term-in-nested-model" class="title-slide slide level1 center">
<h1>Error Term in Nested Model</h1>

</section>
<h3 id="the-linear-model-for-a-nested-design-is">The linear model for a nested design is:</h3>
<h3 id="y_ijk-mu-alpha_i-beta_ji-varepsilon_ijk-2"><span class="math inline">\(y_{ijk} = \mu + \alpha_i + \beta_{j(i)} + \varepsilon_{ijk}\)</span></h3>
<ul>
<li>where:
<ul>
<li><span class="math inline">\(\varepsilon_{ijk}\)</span> is the error term</li>
<li>αi: is the effect of the ith level of A: µi- µ</li>
<li>unexplained variance associated with the kth replicate in jth level of B in the ith level of A</li>
<li>(difference bw observed algal biomass in 3rd quadrat in 2nd patch in low grazing treatment and predicted biomass - average biomass in 2nd patch in low grazing treatment)</li>
</ul></li>
</ul></section>
<section id="analysis-of-variance-residual-and-total" class="title-slide slide level1 center">
<h1>Analysis of Variance: Residual and Total</h1>
<div class="columns">
<div class="column" style="width:40%;">
<ul>
<li>SSresid is difference bw each observation and mean for its level of factor B, summed over all observations</li>
<li>SStotal = SSA + SSB + SSresid</li>
<li>SS can be turned into MS by dividing by appropriate df</li>
</ul>
</div><div class="column" style="width:60%;">
<p><img data-src="images/clipboard-2357756170.png" style="width:100.0%"></p>
</div></div>
</section>

<section id="analysis-of-variance-ssa" class="title-slide slide level1 center">
<h1>Analysis of Variance: SSA</h1>
<div class="columns">
<div class="column" style="width:40%;">
<p>As before, partition the variance in the response variable using SS SSA is SS of differences between means in each level of A and overall mean</p>
</div><div class="column" style="width:60%;">
<p><img data-src="images/clipboard-1219870939.png" style="width:100.0%"></p>
</div></div>
</section>

<section id="analysis-of-variance-ssb" class="title-slide slide level1 center">
<h1>Analysis of Variance: SSB</h1>
<div class="columns">
<div class="column" style="width:40%;">
<p>SSB is SS of difference between means in each level of B and the mean of corresponding level of A summed across levels of A</p>
</div><div class="column" style="width:60%;">
<p><img data-src="images/clipboard-2467119661.png" style="width:100.0%"></p>
</div></div>
</section>

<section id="analysis-of-variance-table" class="title-slide slide level1 center">
<h1>Analysis of Variance Table</h1>
<div class="panel" data-column="screen">
<p><img data-src="images/clipboard-449121940.png" style="width:100.0%"></p>
</div>
</section>

<section id="null-hypotheses-factor-a" class="title-slide slide level1 center">
<h1>Null Hypotheses: Factor A</h1>
<div class="columns">
<div class="column" style="width:40%;">
<p>Two hypotheses tested on values of MS:</p>
<ol type="1">
<li>no effects of factor A</li>
</ol>
<ul>
<li>Assuming A is fixed:</li>
<li>Ho(A): µ1= µ2= µ3=…. µi= µ</li>
<li>Same as in 1-factor ANOVA, using means from B factors nested within each - level of A</li>
<li>(no difference in algal biomass across all levels of grazing: µnone= - µlow= µmed= µhigh)</li>
</ul>
</div><div class="column" style="width:60%;">
<p><img data-src="images/clipboard-1310685300.png" style="width:100.0%"></p>
</div></div>
</section>

<section id="null-hypotheses-factor-b" class="title-slide slide level1 center">
<h1>Null Hypotheses: Factor B</h1>
<div class="columns">
<div class="column" style="width:40%;">
<p>Two hypotheses tested on values of MS:</p>
<ol start="2" type="1">
<li>No effects of factor B nested in A</li>
</ol>
<ul>
<li>Assuming B is random:</li>
<li>Ho(B): σβ2= 0 (no variance added due to differences between all possible - levels of B)</li>
<li>(no variance added due to differences between patches)</li>
</ul>
</div><div class="column" style="width:60%;">
<p><img data-src="images/clipboard-1310685300.png" style="width:100.0%"></p>
</div></div>
</section>

<section id="conclusions-from-analysis" class="title-slide slide level1 center">
<h1>Conclusions from Analysis</h1>
<div class="columns">
<div class="column" style="width:40%;">
<p><strong>Conclusions?</strong></p>
<p>“significant variation between replicate patches within each treatment, but no significant difference in amount of filamentous algae between treatments”</p>
</div><div class="column" style="width:60%;">
<p><img data-src="images/clipboard-3596669693.png" style="width:100.0%"></p>
</div></div>
</section>

<section id="unbalanced-nested-designs" class="title-slide slide level1 center">
<h1>Unbalanced Nested Designs</h1>
<div class="columns">
<div class="column" style="width:40%;">
<p>Unequal sample sizes can be because of:</p>
<ul>
<li>uneven number of B levels within each A</li>
<li>uneven number of replicates within each level of B</li>
</ul>
<p>Not a problem, unless have unequal variance or large deviation from - normality</p>
</div><div class="column" style="width:60%;">
<p><img data-src="images/clipboard-2098022400.png"></p>
</div></div>
</section>

<section id="nested-design-assumptions" class="title-slide slide level1 center">
<h1>Nested Design Assumptions</h1>
<ul>
<li>As usual, we assume
<ul>
<li>equal variance</li>
<li>normality</li>
<li>no outliers</li>
<li>independence of observations</li>
</ul></li>
<li>Equal variance + normality need to be assessed at both levels:
<ul>
<li>Since means for each level of B within each A are used for the H-test about A, need to assess whether those means meet normality and equal variance</li>
<li>Examine residuals for H-test about B</li>
<li>Transformations can be used</li>
</ul></li>
</ul>
</section>

<section id="lecture-13-the-nested-design-the-hard-way" class="title-slide slide level1 center">
<h1>Lecture 13: The nested design the hard way</h1>
<p>This analysis examines the effects of varying sea urchin densities on the percentage cover of filamentous algae. The experiment was designed with:</p>
<ul>
<li>four random patches</li>
<li>four urchin density treatments (
<ul>
<li>none = removed</li>
<li>low = control</li>
<li>medium = 33% of original density</li>
<li>high = 66% of original density)</li>
</ul></li>
<li>Five replicate quadrats were measured within each treatment-patch combination.</li>
</ul>
</section>

<section>
<section id="lecture-13-data-overview" class="title-slide slide level1 center">
<h1>Lecture 13: Data Overview</h1>

</section>
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li><p>The dataframe contains the following variables:</p>
<ul>
<li>patch: Random patches (1-16) where treatments were applied</li>
<li>treat: Urchin density treatment (None/Removed, Low/Control, Medium/33% Density, High/66% Density)</li>
<li>quad: Replicate quadrats within each treatment-patch combination</li>
<li>algae: Percentage cover of filamentous algae (response variable)</li>
</ul></li>
<li><p>Read data and make factors</p></li>
</ul>
</div><div class="column" style="width:50%;">
<div class="cell">
<pre><code>## Data
## # A tibble: 6 × 4
##   treat patch  quad algae
##   &lt;fct&gt; &lt;fct&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 high  1         1     0
## 2 high  1         2     0
## 3 high  1         3     0
## 4 high  1         4     6
## 5 high  1         5     2
## 6 high  2         1     0
## 
## 
## Treatment levels:
## [1] "none"   "low"    "medium" "high"</code></pre>
</div>
<section id="summary-statistics" class="slide level2">
<h2>Summary statistics</h2>
<div class="cell">
<pre><code>## Summary statistics by treatment:
## # A tibble: 4 × 7
##   treat      n  mean    sd    se   min   max
##   &lt;fct&gt;  &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 none      20  39.2 28.7  6.41      0    83
## 2 low       20  21.6 25.1  5.62      0    79
## 3 medium    20  19   25.7  5.74      0    71
## 4 high      20   1.3  3.18 0.711     0    13</code></pre>
</div>
</section>
</div>
</div></section>
<section id="plots" class="title-slide slide level1 center">
<h1>Plots</h1>
<div class="panel" data-column="screen">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="13_01_lecture_powerpoint_files/figure-revealjs/unnamed-chunk-1-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</section>

<section id="manual-nested-anova" class="title-slide slide level1 center">
<h1>Manual nested ANOVA</h1>
<div class="columns">
<div class="column" style="width:60%;">
<ul>
<li>In this experimental design,
<ul>
<li>patch is nested within treat because each patch received only one treatment level.</li>
<li>a hierarchical design where the effect of patches must be considered within each treatment.</li>
<li>in Quinn &amp; Keough (2002)</li>
</ul></li>
<li>we’ll use a traditional nested ANOVA
<ul>
<li>you could make this easy and take the averages of the response variable algae</li>
<li>do a one way anova
<ul>
<li>your power is significantly reduced</li>
<li>you don’t get estimates of variability of patches</li>
</ul></li>
</ul></li>
<li>This is really a regular factorial anova
<ul>
<li>really not appropriate as it is pseudoreplicated</li>
<li>also the F value for Treat is using the MSresid</li>
<li>should use MStreat:patch</li>
</ul></li>
</ul>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a></a><span class="co"># Full model for patch effect and residual - proper nesting notation</span></span>
<span id="cb3-2"><a></a><span class="co"># First, get the standard ANOVA table to extract MS values</span></span>
<span id="cb3-3"><a></a>u_fact_model <span class="ot">&lt;-</span> <span class="fu">aov</span>(algae <span class="sc">~</span> treat <span class="sc">+</span> treat<span class="sc">:</span>patch, <span class="at">data =</span> u_df)</span>
<span id="cb3-4"><a></a></span>
<span id="cb3-5"><a></a><span class="fu">cat</span>(<span class="st">"Factorial model summary:</span><span class="sc">\n\n</span><span class="st">"</span>)</span>
<span id="cb3-6"><a></a><span class="do">## Factorial model summary:</span></span>
<span id="cb3-7"><a></a><span class="fu">summary</span>(u_fact_model)</span>
<span id="cb3-8"><a></a><span class="do">##             Df Sum Sq Mean Sq F value       Pr(&gt;F)    </span></span>
<span id="cb3-9"><a></a><span class="do">## treat        3  14429    4810  16.108 0.0000000658 ***</span></span>
<span id="cb3-10"><a></a><span class="do">## treat:patch 12  21242    1770   5.928 0.0000008323 ***</span></span>
<span id="cb3-11"><a></a><span class="do">## Residuals   64  19110     299                         </span></span>
<span id="cb3-12"><a></a><span class="do">## ---</span></span>
<span id="cb3-13"><a></a><span class="do">## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div></div>
</section>

<section id="the-factorial-anova-is-not-correct" class="title-slide slide level1 center">
<h1>The factorial anova is not correct</h1>
<div class="columns">
<div class="column" style="width:40%;">
<ul>
<li>We can correct this by specifying the error term</li>
<li>The MS needed for the F value is really MS patch nested in treatments as those are the replicates</li>
<li>we can specify that
<ul>
<li>problem is that we can’t really handle unbalanced designs.</li>
</ul></li>
</ul>
</div><div class="column" style="width:60%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a></a><span class="co"># Explicitly specify the nesting</span></span>
<span id="cb4-2"><a></a><span class="co"># This will give you the correct F-test using patch within treat as error term</span></span>
<span id="cb4-3"><a></a>u_nested_model <span class="ot">&lt;-</span> <span class="fu">aov</span>(algae <span class="sc">~</span> treat <span class="sc">+</span> <span class="fu">Error</span>(treat<span class="sc">:</span>patch), <span class="at">data =</span> u_df)</span>
<span id="cb4-4"><a></a></span>
<span id="cb4-5"><a></a><span class="fu">cat</span>(<span class="st">"Correctly specified nested ANOVA:</span><span class="sc">\n\n</span><span class="st">"</span>)</span>
<span id="cb4-6"><a></a><span class="do">## Correctly specified nested ANOVA:</span></span>
<span id="cb4-7"><a></a><span class="fu">summary</span>(u_nested_model)</span>
<span id="cb4-8"><a></a><span class="do">## </span></span>
<span id="cb4-9"><a></a><span class="do">## Error: treat:patch</span></span>
<span id="cb4-10"><a></a><span class="do">##           Df Sum Sq Mean Sq F value Pr(&gt;F)  </span></span>
<span id="cb4-11"><a></a><span class="do">## treat      3  14429    4810   2.717 0.0913 .</span></span>
<span id="cb4-12"><a></a><span class="do">## Residuals 12  21242    1770                 </span></span>
<span id="cb4-13"><a></a><span class="do">## ---</span></span>
<span id="cb4-14"><a></a><span class="do">## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span>
<span id="cb4-15"><a></a><span class="do">## </span></span>
<span id="cb4-16"><a></a><span class="do">## Error: Within</span></span>
<span id="cb4-17"><a></a><span class="do">##           Df Sum Sq Mean Sq F value Pr(&gt;F)</span></span>
<span id="cb4-18"><a></a><span class="do">## Residuals 64  19110   298.6</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div></div>
</section>

<section id="what-to-do-if-it-is-unbalanced-design" class="title-slide slide level1 center">
<h1>What to do if it is unbalanced design</h1>
<div class="columns">
<div class="column" style="width:50%;">
<p>And you are from the 80’s and had big hair</p>
<p><img data-src="images/clipboard-3990741592.png" width="311"></p>
<p><strong>Bon Jovi</strong></p>
<p><img data-src="images/clipboard-1147189835.png" width="323"></p>
<p>David Bowie</p>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a></a><span class="co"># Using afex package (recommended for unbalanced designs)</span></span>
<span id="cb5-2"><a></a><span class="co"># The afex package is specifically designed for ANOVA with </span></span>
<span id="cb5-3"><a></a><span class="co"># Type III SS and handles nested designs pretty well:</span></span>
<span id="cb5-4"><a></a></span>
<span id="cb5-5"><a></a><span class="fu">options</span>(<span class="at">contrasts =</span> <span class="fu">c</span>(<span class="st">"contr.sum"</span>, <span class="st">"contr.poly"</span>))</span>
<span id="cb5-6"><a></a></span>
<span id="cb5-7"><a></a><span class="co"># This works and gives you the correct answer</span></span>
<span id="cb5-8"><a></a>u_afex_model <span class="ot">&lt;-</span> <span class="fu">aov_car</span>(algae <span class="sc">~</span> treat <span class="sc">+</span> <span class="fu">Error</span>(patch), </span>
<span id="cb5-9"><a></a>                     <span class="at">data =</span> u_df,</span>
<span id="cb5-10"><a></a>                     <span class="at">fun_aggregate =</span> mean)</span>
<span id="cb5-11"><a></a></span>
<span id="cb5-12"><a></a><span class="fu">cat</span>(<span class="st">"AFEX nested ANOVA results:</span><span class="sc">\n\n</span><span class="st">"</span>)</span>
<span id="cb5-13"><a></a><span class="do">## AFEX nested ANOVA results:</span></span>
<span id="cb5-14"><a></a><span class="fu">summary</span>(u_afex_model)</span>
<span id="cb5-15"><a></a><span class="do">## Anova Table (Type 3 tests)</span></span>
<span id="cb5-16"><a></a><span class="do">## </span></span>
<span id="cb5-17"><a></a><span class="do">## Response: algae</span></span>
<span id="cb5-18"><a></a><span class="do">##       num Df den Df    MSE      F     ges  Pr(&gt;F)  </span></span>
<span id="cb5-19"><a></a><span class="do">## treat      3     12 354.03 2.7171 0.40451 0.09126 .</span></span>
<span id="cb5-20"><a></a><span class="do">## ---</span></span>
<span id="cb5-21"><a></a><span class="do">## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div></div>
</section>

<section id="the-modern-way---mixed-model-anova" class="title-slide slide level1 center">
<h1>The modern way - mixed model ANOVA</h1>
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li><p>Fit the model with treatment as fixed effect and patch nested within treatment as random lmer(algae ~ treat + (1|treat:patch), data = u_df, control = lmerControl(optimizer = “bobyqa”, optCtrl = list(maxfun = 2e5)))</p></li>
<li><p>BOBYQA (Bound Optimization BY Quadratic Approximation)</p>
<ul>
<li>optimization algorithm in mixed-effects modeling to find the best parameter values maximizing the likelihood function</li>
<li>Useful when fitting complex models like the ones you’re working with in your nested ANOVA analysis</li>
</ul></li>
<li><p>Notation we will get into later</p>
<ul>
<li>random intercept - fixed slope - (1|patch)</li>
<li>random intercept - random slope - (1|treat:patch)</li>
</ul></li>
</ul>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a></a><span class="co"># Fit the model with treatment as fixed effect and patch nested within treatment as random</span></span>
<span id="cb6-2"><a></a>u_lmer_model <span class="ot">&lt;-</span> <span class="fu">lmer</span>(algae <span class="sc">~</span> treat <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>treat<span class="sc">:</span>patch), <span class="at">data =</span> u_df,</span>
<span id="cb6-3"><a></a>                    <span class="at">control =</span> <span class="fu">lmerControl</span>(<span class="at">optimizer =</span> <span class="st">"bobyqa"</span>,</span>
<span id="cb6-4"><a></a>                                         <span class="at">optCtrl =</span> <span class="fu">list</span>(<span class="at">maxfun =</span> <span class="fl">2e5</span>)))</span>
<span id="cb6-5"><a></a></span>
<span id="cb6-6"><a></a><span class="co"># BOBYQA (Bound Optimization BY Quadratic Approximation) is an optimization algorithm used in mixed-effects modeling to find the best parameter values that maximize the likelihood function. It's especially useful when fitting complex models like the ones you're working with in your nested ANOVA analysis.</span></span>
<span id="cb6-7"><a></a></span>
<span id="cb6-8"><a></a><span class="fu">cat</span>(<span class="st">"Mixed model summary:</span><span class="sc">\n\n</span><span class="st">"</span>)</span>
<span id="cb6-9"><a></a><span class="do">## Mixed model summary:</span></span>
<span id="cb6-10"><a></a><span class="fu">summary</span>(u_lmer_model)</span>
<span id="cb6-11"><a></a><span class="do">## Linear mixed model fit by REML. t-tests use Satterthwaite's method [</span></span>
<span id="cb6-12"><a></a><span class="do">## lmerModLmerTest]</span></span>
<span id="cb6-13"><a></a><span class="do">## Formula: algae ~ treat + (1 | treat:patch)</span></span>
<span id="cb6-14"><a></a><span class="do">##    Data: u_df</span></span>
<span id="cb6-15"><a></a><span class="do">## Control: lmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 200000))</span></span>
<span id="cb6-16"><a></a><span class="do">## </span></span>
<span id="cb6-17"><a></a><span class="do">## REML criterion at convergence: 684.9</span></span>
<span id="cb6-18"><a></a><span class="do">## </span></span>
<span id="cb6-19"><a></a><span class="do">## Scaled residuals: </span></span>
<span id="cb6-20"><a></a><span class="do">##     Min      1Q  Median      3Q     Max </span></span>
<span id="cb6-21"><a></a><span class="do">## -1.9808 -0.3106 -0.1093  0.2831  2.5910 </span></span>
<span id="cb6-22"><a></a><span class="do">## </span></span>
<span id="cb6-23"><a></a><span class="do">## Random effects:</span></span>
<span id="cb6-24"><a></a><span class="do">##  Groups      Name        Variance Std.Dev.</span></span>
<span id="cb6-25"><a></a><span class="do">##  treat:patch (Intercept) 294.3    17.16   </span></span>
<span id="cb6-26"><a></a><span class="do">##  Residual                298.6    17.28   </span></span>
<span id="cb6-27"><a></a><span class="do">## Number of obs: 80, groups:  treat:patch, 16</span></span>
<span id="cb6-28"><a></a><span class="do">## </span></span>
<span id="cb6-29"><a></a><span class="do">## Fixed effects:</span></span>
<span id="cb6-30"><a></a><span class="do">##             Estimate Std. Error     df t value Pr(&gt;|t|)   </span></span>
<span id="cb6-31"><a></a><span class="do">## (Intercept)   20.262      4.704 12.000   4.308  0.00102 **</span></span>
<span id="cb6-32"><a></a><span class="do">## treat1        18.938      8.147 12.000   2.324  0.03846 * </span></span>
<span id="cb6-33"><a></a><span class="do">## treat2         1.288      8.147 12.000   0.158  0.87707   </span></span>
<span id="cb6-34"><a></a><span class="do">## treat3        -1.263      8.147 12.000  -0.155  0.87943   </span></span>
<span id="cb6-35"><a></a><span class="do">## ---</span></span>
<span id="cb6-36"><a></a><span class="do">## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span>
<span id="cb6-37"><a></a><span class="do">## </span></span>
<span id="cb6-38"><a></a><span class="do">## Correlation of Fixed Effects:</span></span>
<span id="cb6-39"><a></a><span class="do">##        (Intr) treat1 treat2</span></span>
<span id="cb6-40"><a></a><span class="do">## treat1  0.000              </span></span>
<span id="cb6-41"><a></a><span class="do">## treat2  0.000 -0.333       </span></span>
<span id="cb6-42"><a></a><span class="do">## treat3  0.000 -0.333 -0.333</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div></div>
</section>

<section id="the-modern-way---mixed-model-anova-1" class="title-slide slide level1 center">
<h1>The modern way - mixed model ANOVA</h1>
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li>METHOD 1 - the F-distribution with estimated degrees of freedom
<ul>
<li>Accounts for the uncertainty in variance component estimation</li>
<li>More conservative (higher p-values)</li>
<li>Better for small samples</li>
</ul></li>
</ul>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a></a><span class="co"># Type III ANOVA with F-statistics (not chi-square) using Satterthwaite's method</span></span>
<span id="cb7-2"><a></a>u_anova_result <span class="ot">&lt;-</span> <span class="fu">Anova</span>(u_lmer_model, <span class="at">type =</span> <span class="dv">3</span>, <span class="at">ddf =</span> <span class="st">"Satterthwaite"</span>,</span>
<span id="cb7-3"><a></a>                       <span class="at">test.statistic =</span> <span class="st">"F"</span>)</span>
<span id="cb7-4"><a></a></span>
<span id="cb7-5"><a></a><span class="fu">cat</span>(<span class="st">"Type III ANOVA with F test:</span><span class="sc">\n\n</span><span class="st">"</span>)</span>
<span id="cb7-6"><a></a><span class="do">## Type III ANOVA with F test:</span></span>
<span id="cb7-7"><a></a>u_anova_result</span>
<span id="cb7-8"><a></a><span class="do">## Analysis of Deviance Table (Type III Wald F tests with Kenward-Roger df)</span></span>
<span id="cb7-9"><a></a><span class="do">## </span></span>
<span id="cb7-10"><a></a><span class="do">## Response: algae</span></span>
<span id="cb7-11"><a></a><span class="do">##                   F Df Df.res   Pr(&gt;F)   </span></span>
<span id="cb7-12"><a></a><span class="do">## (Intercept) 18.5551  1     12 0.001018 **</span></span>
<span id="cb7-13"><a></a><span class="do">## treat        2.7171  3     12 0.091262 . </span></span>
<span id="cb7-14"><a></a><span class="do">## ---</span></span>
<span id="cb7-15"><a></a><span class="do">## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div></div>
</section>

<section id="the-modern-way---mixed-model-anova-2" class="title-slide slide level1 center">
<h1>The modern way - mixed model ANOVA</h1>
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li>METHOD 2 - the Chi Square
<ul>
<li>Assumes variance components are known (not estimated)</li>
<li>More liberal (lower p-values)</li>
<li>Assumes large samples</li>
</ul></li>
<li>Why Different Results?
<ul>
<li>relationship between these tests is:</li>
<li>Chi-square = F × numerator df</li>
</ul></li>
<li>The p-values differ because:
<ul>
<li>F-test accounts for denominator df (12 in your case) - reflects sample size</li>
<li>Chi-square assumes infinite denominator df - assumes large samples</li>
</ul></li>
<li><strong>Rule of Thumb</strong></li>
<li>under 100 observations or &lt; 20 random effect levels: Use F-test</li>
<li>over 500 observations and &gt; 50 random effect levels: Chi-square is okay</li>
<li>In between: F-test is safer</li>
</ul>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a></a><span class="co"># Alternative using car package with F-statistic</span></span>
<span id="cb8-2"><a></a>u_anova_f <span class="ot">&lt;-</span> <span class="fu">Anova</span>(u_lmer_model, <span class="at">type =</span> <span class="dv">3</span>, <span class="at">test.statistic =</span> <span class="st">"Chisq"</span>)</span>
<span id="cb8-3"><a></a></span>
<span id="cb8-4"><a></a><span class="fu">cat</span>(<span class="st">"Type III ANOVA with F test:</span><span class="sc">\n\n</span><span class="st">"</span>)</span>
<span id="cb8-5"><a></a><span class="do">## Type III ANOVA with F test:</span></span>
<span id="cb8-6"><a></a>u_anova_f</span>
<span id="cb8-7"><a></a><span class="do">## Analysis of Deviance Table (Type III Wald chisquare tests)</span></span>
<span id="cb8-8"><a></a><span class="do">## </span></span>
<span id="cb8-9"><a></a><span class="do">## Response: algae</span></span>
<span id="cb8-10"><a></a><span class="do">##               Chisq Df Pr(&gt;Chisq)    </span></span>
<span id="cb8-11"><a></a><span class="do">## (Intercept) 18.5551  1 0.00001651 ***</span></span>
<span id="cb8-12"><a></a><span class="do">## treat        8.1513  3    0.04299 *  </span></span>
<span id="cb8-13"><a></a><span class="do">## ---</span></span>
<span id="cb8-14"><a></a><span class="do">## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div></div>
</section>

<section id="the-modern-way---mixed-model-anova-3" class="title-slide slide level1 center">
<h1>The modern way - mixed model ANOVA</h1>
<div class="columns">
<div class="column" style="width:50%;">
<p>The nested ANOVA model is specified as:</p>
<p><span class="math inline">\(algae_{ijk} = \mu + \alpha_i + \beta_{j(i)} + \epsilon_{ijk}\)</span></p>
<p>Where:</p>
<ul>
<li><span class="math inline">\(\mu\)</span> is the overall mean<br>
</li>
<li><span class="math inline">\(\alpha_i\)</span> is the fixed effect of treatment <span class="math inline">\(i\)</span><br>
</li>
<li><span class="math inline">\(\beta_{j(i)}\)</span> is the random effect of patch <span class="math inline">\(j\)</span> nested within treatment <span class="math inline">\(i\)</span><br>
</li>
<li><span class="math inline">\(\epsilon_{ijk}\)</span> is the residual error for quadrat <span class="math inline">\(k\)</span> in patch <span class="math inline">\(j\)</span> within treatment <span class="math inline">\(i\)</span></li>
</ul>
</div><div class="column" style="width:50%;">
<div class="cell">
<pre><code>## Final ANOVA results:
## Analysis of Deviance Table (Type III Wald F tests with Kenward-Roger df)
## 
## Response: algae
##                   F Df Df.res   Pr(&gt;F)   
## (Intercept) 18.5551  1     12 0.001018 **
## treat        2.7171  3     12 0.091262 . 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div></div>
</section>

<section id="lecture-13-variance-components" class="title-slide slide level1 center">
<h1>Lecture 13: Variance Components</h1>
<div class="callout callout-important callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Interpretation of ANOVA Results The nested ANOVA reveals that there was no significant effect of urchin density treatment on algae cover (χ² = 8.1513, df = 3, p = 0.04306). The variance component for patches nested within treatments (294.3) indicates substantial spatial heterogeneity in algae cover, highlighting the importance of accounting for this spatial variation in the analysis.</p>
</div>
</div>
</div>
</section>

<section id="lecture-13-post-hoc-comparisons" class="title-slide slide level1 center">
<h1>Lecture 13: Post-hoc Comparisons</h1>
<p>Although the main effect of treatment was marginally significant in the nested ANOVA (p = 0.04306), we can examine the mean differences between treatments to understand patterns in the data.</p>
<div class="panel" data-column="screen">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a></a><span class="co"># Calculate estimated marginal means</span></span>
<span id="cb10-2"><a></a>u_emm <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(u_lmer_model, <span class="sc">~</span> treat)</span>
<span id="cb10-3"><a></a></span>
<span id="cb10-4"><a></a><span class="fu">cat</span>(<span class="st">"Estimated marginal means:</span><span class="sc">\n\n</span><span class="st">"</span>)</span>
<span id="cb10-5"><a></a><span class="do">## Estimated marginal means:</span></span>
<span id="cb10-6"><a></a>u_emm</span>
<span id="cb10-7"><a></a><span class="do">##  treat  emmean   SE df lower.CL upper.CL</span></span>
<span id="cb10-8"><a></a><span class="do">##  none     39.2 9.41 12    18.70     59.7</span></span>
<span id="cb10-9"><a></a><span class="do">##  low      21.6 9.41 12     1.05     42.0</span></span>
<span id="cb10-10"><a></a><span class="do">##  medium   19.0 9.41 12    -1.50     39.5</span></span>
<span id="cb10-11"><a></a><span class="do">##  high      1.3 9.41 12   -19.20     21.8</span></span>
<span id="cb10-12"><a></a><span class="do">## </span></span>
<span id="cb10-13"><a></a><span class="do">## Degrees-of-freedom method: kenward-roger </span></span>
<span id="cb10-14"><a></a><span class="do">## Confidence level used: 0.95</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</section>

<section id="lecture-13-tukey-pairwise-comparisons" class="title-slide slide level1 center">
<h1>Lecture 13: Tukey Pairwise Comparisons</h1>
<div class="panel" data-column="screen">
<div class="cell">
<pre><code>## Pairwise comparisons (Sidak adjusted):
##  contrast      estimate   SE df t.ratio p.value
##  none - low       17.65 13.3 12   1.327  0.7557
##  none - medium    20.20 13.3 12   1.518  0.6356
##  none - high      37.90 13.3 12   2.849  0.0848
##  low - medium      2.55 13.3 12   0.192  1.0000
##  low - high       20.25 13.3 12   1.522  0.6331
##  medium - high    17.70 13.3 12   1.330  0.7534
## 
## Degrees-of-freedom method: kenward-roger 
## P value adjustment: sidak method for 6 tests</code></pre>
</div>
</div>
</section>

<section id="lecture-13-letter-display" class="title-slide slide level1 center">
<h1>Lecture 13: Letter Display</h1>
<div class="panel" data-column="screen">
<div class="cell">
<pre><code>## Compact letter display:
##  treat  emmean   SE df lower.CL upper.CL .group
##  high      1.3 9.41 12   -19.20     21.8  a    
##  medium   19.0 9.41 12    -1.50     39.5  a    
##  low      21.6 9.41 12     1.05     42.0  a    
##  none     39.2 9.41 12    18.70     59.7  a    
## 
## Degrees-of-freedom method: kenward-roger 
## Confidence level used: 0.95 
## P value adjustment: tukey method for comparing a family of 4 estimates 
## significance level used: alpha = 0.05 
## NOTE: If two or more means share the same grouping symbol,
##       then we cannot show them to be different.
##       But we also did not show them to be the same.</code></pre>
</div>
</div>
<div class="callout callout-important callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Interpretation of Treatment Comparisons The mean algae cover shows a clear pattern with increasing urchin density: None/Removed (39.20%) &gt; Medium/33% Density (19.00%) &gt; High/66% Density (21.55%) &gt; Low/Control (1.30%). The pattern suggests an inverse relationship between urchin density and algae cover, with complete removal showing the highest algae cover. The high variability among patches within treatments contributed to the marginal statistical significance for the treatment effect.</p>
</div>
</div>
</div>
</section>

<section id="lecture-13-anova-assumptions-testing" class="title-slide slide level1 center">
<h1>Lecture 13: ANOVA Assumptions Testing</h1>
<ul>
<li>For valid inference from ANOVA, several assumptions must be met. We test these assumptions below.</li>
<li>Base R approach</li>
<li>Note that it does not work that well</li>
</ul>
<div class="panel" data-column="screen">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="13_01_lecture_powerpoint_files/figure-revealjs/diagnostic_plots-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</section>

<section id="lecture-13-levenes-test-for-homogeneity-of-variance" class="title-slide slide level1 center">
<h1>Lecture 13: Levenes Test for Homogeneity of Variance</h1>
<div class="columns">
<div class="column" style="width:50%;">
<p>Levenes test</p>
<div class="cell">
<pre><code>## Levene's test for homogeneity of variance:
## Levene's Test for Homogeneity of Variance (center = median)
##       Df F value     Pr(&gt;F)    
## group  3  8.1694 0.00008785 ***
##       76                       
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div><div class="column" style="width:50%;">
<p>Interpretation of Assumption Tests The Q-Q plot shows some deviation from normality, particularly in the tails, and Levene’s test indicates significant heterogeneity of variances across treatments (p = 0.00008785). As noted by Quinn &amp; Keough (2002), there were “large differences in within-cell variances” in this dataset, and transformations (including arcsin) did not improve variance homogeneity. However, ANOVA is generally robust to heteroscedasticity with balanced designs, which is why they chose to analyze untransformed data. The Residuals vs.&nbsp;fitted plot also shows a pattern of increasing variance with increasing fitted values, confirming the heteroscedasticity.</p>
</div></div>
</section>

<section id="lecture-13-visualization" class="title-slide slide level1 center">
<h1>Lecture 13: Visualization</h1>
<div class="panel" data-column="screen">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="13_01_lecture_powerpoint_files/figure-revealjs/boxplot-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</section>

<section id="lecture-13-means-plot" class="title-slide slide level1 center">
<h1>Lecture 13: Means Plot</h1>
<div class="panel" data-column="screen">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="13_01_lecture_powerpoint_files/figure-revealjs/means_plot-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</section>

<section id="lecture-13-discussion" class="title-slide slide level1 center">
<h1>Lecture 13: Discussion</h1>
<div class="callout callout-important callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Scientific Interpretation Our nested ANOVA analysis revealed substantial spatial heterogeneity in algae cover, with significant variation among patches within each treatment. The effect of urchin density treatments on filamentous algae cover was marginally significant at the α = 0.05 level (p = 0.043). The descriptive statistics show a clear pattern where algae cover increases as urchin density decreases, with None/Removed showing the highest cover (39.20%), followed by Medium/33% Density (19.00%), High/66% Density (21.55%), and Low/Control showing minimal algae cover (1.30%). This pattern demonstrates a density-dependent relationship between urchin grazing and algal abundance. The substantial variance component associated with patches nested within treatments (294.31, approximately 39.5% of total variance) underscores the importance of spatial heterogeneity in structuring algal communities. This finding highlights the necessity of accounting for spatial variability when designing and analyzing ecological field experiments. From an ecological perspective, these results suggest that sea urchins significantly influence algal communities through grazing, though local environmental factors and patch-specific conditions also play an important role in determining algae cover. This has important implications for ecosystem management, as it indicates that the effects of urchin density manipulations are context-dependent and influenced by local environmental conditions.</p>
</div>
</div>
</div>
</section>

<section id="we-can-do-this-manually" class="title-slide slide level1 center">
<h1>We can do this manually</h1>
<div class="columns">
<div class="column" style="width:50%;">
<p>But UGGGG who would EVER do this</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a></a><span class="co"># Method 1: Convert to dataframe with Source as a proper variable</span></span>
<span id="cb14-2"><a></a>u_man_model <span class="ot">&lt;-</span> <span class="fu">aov</span>(algae <span class="sc">~</span> treat <span class="sc">+</span> treat<span class="sc">:</span>patch, <span class="at">data =</span> u_df)</span>
<span id="cb14-3"><a></a>u_anova_summary <span class="ot">&lt;-</span> <span class="fu">summary</span>(u_man_model)[[<span class="dv">1</span>]]</span>
<span id="cb14-4"><a></a></span>
<span id="cb14-5"><a></a><span class="fu">cat</span>(<span class="st">"Standard ANOVA table:</span><span class="sc">\n\n</span><span class="st">"</span>)</span>
<span id="cb14-6"><a></a><span class="do">## Standard ANOVA table:</span></span>
<span id="cb14-7"><a></a>u_anova_summary</span>
<span id="cb14-8"><a></a><span class="do">##             Df Sum Sq Mean Sq F value        Pr(&gt;F)    </span></span>
<span id="cb14-9"><a></a><span class="do">## treat        3  14429  4809.7 16.1075 0.00000006579 ***</span></span>
<span id="cb14-10"><a></a><span class="do">## treat:patch 12  21242  1770.2  5.9282 0.00000083226 ***</span></span>
<span id="cb14-11"><a></a><span class="do">## Residuals   64  19110   298.6                          </span></span>
<span id="cb14-12"><a></a><span class="do">## ---</span></span>
<span id="cb14-13"><a></a><span class="do">## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a></a><span class="co"># Extract values by position (much simpler!)</span></span>
<span id="cb15-2"><a></a><span class="co"># Row 1 = treat, Row 2 = treat:patch, Row 3 = Residuals</span></span>
<span id="cb15-3"><a></a>u_MS_treat <span class="ot">&lt;-</span> u_anova_summary[<span class="dv">1</span>, <span class="st">"Mean Sq"</span>]      <span class="co"># Row 1, Mean Sq column</span></span>
<span id="cb15-4"><a></a>u_MS_patch <span class="ot">&lt;-</span> u_anova_summary[<span class="dv">2</span>, <span class="st">"Mean Sq"</span>]      <span class="co"># Row 2, Mean Sq column  </span></span>
<span id="cb15-5"><a></a>u_MS_residual <span class="ot">&lt;-</span> u_anova_summary[<span class="dv">3</span>, <span class="st">"Mean Sq"</span>]   <span class="co"># Row 3, Mean Sq column</span></span>
<span id="cb15-6"><a></a></span>
<span id="cb15-7"><a></a>u_df_treat <span class="ot">&lt;-</span> u_anova_summary[<span class="dv">1</span>, <span class="st">"Df"</span>]</span>
<span id="cb15-8"><a></a>u_df_patch <span class="ot">&lt;-</span> u_anova_summary[<span class="dv">2</span>, <span class="st">"Df"</span>] </span>
<span id="cb15-9"><a></a>u_df_residual <span class="ot">&lt;-</span> u_anova_summary[<span class="dv">3</span>, <span class="st">"Df"</span>]</span>
<span id="cb15-10"><a></a></span>
<span id="cb15-11"><a></a><span class="fu">cat</span>(<span class="st">"Extracted mean squares:</span><span class="sc">\n\n</span><span class="st">"</span>)</span>
<span id="cb15-12"><a></a><span class="do">## Extracted mean squares:</span></span>
<span id="cb15-13"><a></a><span class="fu">cat</span>(<span class="st">"MS Treatment:"</span>, u_MS_treat, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb15-14"><a></a><span class="do">## MS Treatment: 4809.712</span></span>
<span id="cb15-15"><a></a><span class="fu">cat</span>(<span class="st">"MS Patch(Treatment):"</span>, u_MS_patch, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb15-16"><a></a><span class="do">## MS Patch(Treatment): 1770.163</span></span>
<span id="cb15-17"><a></a><span class="fu">cat</span>(<span class="st">"MS Residual:"</span>, u_MS_residual, <span class="st">"</span><span class="sc">\n\n</span><span class="st">"</span>)</span>
<span id="cb15-18"><a></a><span class="do">## MS Residual: 298.6</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a></a><span class="co"># Calculate CORRECT F-ratios for nested design</span></span>
<span id="cb16-2"><a></a>u_F_treat_correct <span class="ot">&lt;-</span> u_MS_treat <span class="sc">/</span> u_MS_patch        <span class="co"># Treatment tested against patches</span></span>
<span id="cb16-3"><a></a>u_F_patch <span class="ot">&lt;-</span> u_MS_patch <span class="sc">/</span> u_MS_residual             <span class="co"># Patches tested against residual</span></span>
<span id="cb16-4"><a></a></span>
<span id="cb16-5"><a></a><span class="fu">cat</span>(<span class="st">"Corrected F-ratios:</span><span class="sc">\n\n</span><span class="st">"</span>)</span>
<span id="cb16-6"><a></a><span class="do">## Corrected F-ratios:</span></span>
<span id="cb16-7"><a></a><span class="fu">cat</span>(<span class="st">"F Treatment:"</span>, u_F_treat_correct, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb16-8"><a></a><span class="do">## F Treatment: 2.717102</span></span>
<span id="cb16-9"><a></a><span class="fu">cat</span>(<span class="st">"F Patch(Treatment):"</span>, u_F_patch, <span class="st">"</span><span class="sc">\n\n</span><span class="st">"</span>)</span>
<span id="cb16-10"><a></a><span class="do">## F Patch(Treatment): 5.928207</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a></a><span class="co"># Calculate correct p-values</span></span>
<span id="cb17-2"><a></a>u_p_treat_correct <span class="ot">&lt;-</span> <span class="fu">pf</span>(u_F_treat_correct, u_df_treat, u_df_patch, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span>
<span id="cb17-3"><a></a>u_p_patch <span class="ot">&lt;-</span> <span class="fu">pf</span>(u_F_patch, u_df_patch, u_df_residual, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span>
<span id="cb17-4"><a></a></span>
<span id="cb17-5"><a></a><span class="fu">cat</span>(<span class="st">"Corrected p-values:</span><span class="sc">\n\n</span><span class="st">"</span>)</span>
<span id="cb17-6"><a></a><span class="do">## Corrected p-values:</span></span>
<span id="cb17-7"><a></a><span class="fu">cat</span>(<span class="st">"p Treatment:"</span>, u_p_treat_correct, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb17-8"><a></a><span class="do">## p Treatment: 0.091262</span></span>
<span id="cb17-9"><a></a><span class="fu">cat</span>(<span class="st">"p Patch(Treatment):"</span>, u_p_patch, <span class="st">"</span><span class="sc">\n\n</span><span class="st">"</span>)</span>
<span id="cb17-10"><a></a><span class="do">## p Patch(Treatment): 0.0000008322613</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a></a><span class="co"># Create simple corrected table</span></span>
<span id="cb18-2"><a></a>u_corrected_table <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb18-3"><a></a>  <span class="at">Source =</span> <span class="fu">c</span>(<span class="st">"Treatment"</span>, <span class="st">"Patches(Treatment)"</span>, <span class="st">"Residual"</span>),</span>
<span id="cb18-4"><a></a>  <span class="at">Df =</span> <span class="fu">c</span>(u_df_treat, u_df_patch, u_df_residual),</span>
<span id="cb18-5"><a></a>  <span class="at">MS =</span> <span class="fu">round</span>(<span class="fu">c</span>(u_MS_treat, u_MS_patch, u_MS_residual), <span class="dv">1</span>),</span>
<span id="cb18-6"><a></a>  <span class="at">F =</span> <span class="fu">c</span>(<span class="fu">round</span>(u_F_treat_correct, <span class="dv">2</span>), <span class="fu">round</span>(u_F_patch, <span class="dv">2</span>), <span class="cn">NA</span>),</span>
<span id="cb18-7"><a></a>  <span class="at">p =</span> <span class="fu">c</span>(<span class="fu">ifelse</span>(u_p_treat_correct <span class="sc">&lt;</span> <span class="fl">0.001</span>, <span class="st">"&lt;0.001"</span>, <span class="fu">round</span>(u_p_treat_correct, <span class="dv">3</span>)),</span>
<span id="cb18-8"><a></a>        <span class="fu">ifelse</span>(u_p_patch <span class="sc">&lt;</span> <span class="fl">0.001</span>, <span class="st">"&lt;0.001"</span>, <span class="fu">round</span>(u_p_patch, <span class="dv">3</span>)), </span>
<span id="cb18-9"><a></a>        <span class="cn">NA</span>)</span>
<span id="cb18-10"><a></a>)</span>
<span id="cb18-11"><a></a></span>
<span id="cb18-12"><a></a><span class="fu">cat</span>(<span class="st">"Corrected ANOVA table:</span><span class="sc">\n\n</span><span class="st">"</span>)</span>
<span id="cb18-13"><a></a><span class="do">## Corrected ANOVA table:</span></span>
<span id="cb18-14"><a></a>u_corrected_table</span>
<span id="cb18-15"><a></a><span class="do">##               Source Df     MS    F      p</span></span>
<span id="cb18-16"><a></a><span class="do">## 1          Treatment  3 4809.7 2.72  0.091</span></span>
<span id="cb18-17"><a></a><span class="do">## 2 Patches(Treatment) 12 1770.2 5.93 &lt;0.001</span></span>
<span id="cb18-18"><a></a><span class="do">## 3           Residual 64  298.6   NA   &lt;NA&gt;</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div></div>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/your-site-url\.github\.io");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>