<!DOCTYPE html>
<html lang="en"><head>
<link href="../../favicon.png" rel="icon" type="image/png">
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-bb62276ab45c84d9efd712f51ff97b5a.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.10.18">

  <meta name="author" content="Bill Perry">
  <meta name="dcterms.date" content="2026-10-08">
  <title>UMD DAta Science Biology – Lecture 10 — T-Tests II: Two-Sample vs.&nbsp;Paired</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: 1.5em;}
    div.column{flex: auto;}
    @media screen {
    div.columns{gap: min(4vw, 1.5em);}
    div.column{overflow-x: auto;}
    }
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #24292e;  }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #24292e; } /* Normal */
    code span.al { color: #ff5555; font-weight: bold; } /* Alert */
    code span.an { color: #6a737d; } /* Annotation */
    code span.at { color: #d73a49; } /* Attribute */
    code span.bn { color: #005cc5; } /* BaseN */
    code span.bu { color: #d73a49; } /* BuiltIn */
    code span.cf { color: #d73a49; } /* ControlFlow */
    code span.ch { color: #032f62; } /* Char */
    code span.cn { color: #005cc5; } /* Constant */
    code span.co { color: #6a737d; } /* Comment */
    code span.cv { color: #6a737d; } /* CommentVar */
    code span.do { color: #6a737d; } /* Documentation */
    code span.dt { color: #d73a49; } /* DataType */
    code span.dv { color: #005cc5; } /* DecVal */
    code span.er { color: #ff5555; text-decoration: underline; } /* Error */
    code span.ex { color: #d73a49; font-weight: bold; } /* Extension */
    code span.fl { color: #005cc5; } /* Float */
    code span.fu { color: #6f42c1; } /* Function */
    code span.im { color: #032f62; } /* Import */
    code span.in { color: #6a737d; } /* Information */
    code span.kw { color: #d73a49; } /* Keyword */
    code span.op { color: #24292e; } /* Operator */
    code span.ot { color: #6f42c1; } /* Other */
    code span.pp { color: #d73a49; } /* Preprocessor */
    code span.re { color: #6a737d; } /* RegionMarker */
    code span.sc { color: #005cc5; } /* SpecialChar */
    code span.ss { color: #032f62; } /* SpecialString */
    code span.st { color: #032f62; } /* String */
    code span.va { color: #e36209; } /* Variable */
    code span.vs { color: #032f62; } /* VerbatimString */
    code span.wa { color: #ff5555; } /* Warning */
  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-dd7628516666e5f82eb94bcf304ed6a3.css">
  <link rel="stylesheet" href="../../css/main.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
<meta property="og:title" content="Lecture 10 — T-Tests II: Two-Sample vs.&nbsp;Paired – UMD DAta Science Biology">
<meta property="og:description" content="Reading and reporting t.test() output, then the sugar maple data: averaging pseudoreplicates, two-sample vs.&nbsp;paired t-tests (and why pairing adds power), and the rank-based partners Mann-Whitney U and Wilcoxon signed-rank.">
<meta property="og:site_name" content="UMD DAta Science Biology">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Lecture 10 — T-Tests II: Two-Sample vs.&nbsp;Paired</h1>
  <p class="subtitle">Reading the output, the power of pairing, and rank-based tests</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Bill Perry
</div>
</div>
</div>

  <p class="date">2026-10-08</p>
</section>
<section id="where-we-left-off-lecture-09-t-tests-i" class="title-slide slide level1 center">
<h1>Where we left off (Lecture 09 — T-Tests I)</h1>
<ul>
<li><strong>Five steps:</strong> hypotheses → normality → variance → run → report</li>
<li><strong>Normality:</strong> stacked histograms, box plot + <strong>QQ plot</strong>, Shapiro-Wilk</li>
<li><strong>Variance:</strong> Levene’s — we use <strong>Welch’s</strong> either way</li>
<li><strong>Leaf data:</strong> assumptions OK, ran Welch’s t-test — no significant difference</li>
<li><strong>Homework:</strong> checked the assumptions for the <strong>sugar maple</strong> leaves</li>
</ul>
<p><strong>Today we go back and ask a harder question: did we even have 53 leaves’ worth of information?</strong></p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ Key idea for today</strong></p>
<p>The <em>design</em> of a study decides which test is right. The same numbers can give two very different answers depending on whether you respect how they were collected.</p>
</div>
</div>
</div>
</section>

<section id="goals-for-today" class="title-slide slide level1 center">
<h1>Goals for Today</h1>
<div class="columns">
<div class="column" style="width:60%;">
<ul>
<li><strong>Read</strong> the <code>t.test()</code> output and make a decision (steps 4–5)</li>
<li><strong>Write</strong> a results sentence</li>
<li>Run a <strong>two-sample</strong> and a <strong>paired</strong> t-test on our leaf data</li>
<li>Spot <strong>pseudoreplication</strong> — and fix it with <strong>one <code>summarize()</code> at the top</strong>, then <strong>rerun the same code</strong></li>
<li>See how much the answer moves when you do</li>
<li><strong>Check the assumptions</strong>, then test the sugar maples the same way</li>
<li>See <strong>why pairing adds power</strong></li>
<li><strong>Plot</strong> a paired result</li>
<li>Know the <strong>rank-based</strong> backups: Mann-Whitney U and Wilcoxon signed-rank</li>
</ul>
</div><div class="column" style="width:40%;">
<p><strong>New tools today:</strong></p>
<ul>
<li><code>t.test(..., paired = TRUE)</code></li>
<li><code>pivot_wider()</code> — a sneak peek</li>
<li><code>row_number()</code> — numbering rows within a group</li>
<li><code>scales::pvalue()</code> — tidy p-values for plots</li>
<li><code>wilcox.test()</code> — rank-based tests</li>
</ul>
<p><strong>Reading:</strong></p>
<ul>
<li>📖 Whitlock &amp; Schluter, Ch. 12 — <em>Comparing two means</em></li>
<li>📖 Whitlock &amp; Schluter, Ch. 13 — <em>Handling violations of assumptions</em></li>
</ul>
</div></div>
</section>

<section id="load-libraries-and-data" class="title-slide slide level1 center">
<h1>Load Libraries and Data</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a aria-label="1"></a><span class="co"># Load all packages at the top ----------------------------</span></span>
<span id="cb1-2"><a aria-label="2"></a><span class="fu">library</span>(readxl)    <span class="co"># reading Excel files</span></span>
<span id="cb1-3"><a aria-label="3"></a><span class="fu">library</span>(tidyverse) <span class="co"># data manipulation + ggplot2</span></span>
<span id="cb1-4"><a aria-label="4"></a><span class="fu">library</span>(janitor)   <span class="co"># clean_names()</span></span>
<span id="cb1-5"><a aria-label="5"></a><span class="fu">library</span>(car)       <span class="co"># Levene's test</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a aria-label="1"></a><span class="co"># Load both data sets ------------------------------------</span></span>
<span id="cb2-2"><a aria-label="2"></a>leaf_df <span class="ot">&lt;-</span></span>
<span id="cb2-3"><a aria-label="3"></a>  <span class="fu">read_excel</span>(<span class="st">"data/2026_09_03_data_sci_leaf_area.xlsx"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb2-4"><a aria-label="4"></a>  <span class="fu">clean_names</span>()</span>
<span id="cb2-5"><a aria-label="5"></a></span>
<span id="cb2-6"><a aria-label="6"></a>maple_df <span class="ot">&lt;-</span></span>
<span id="cb2-7"><a aria-label="7"></a>  <span class="fu">read_excel</span>(<span class="st">"data/2026_09_02_sugar_maple_leaf_area.xlsx"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb2-8"><a aria-label="8"></a>  <span class="fu">clean_names</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>

<section id="chunk-1-of-2-the-t-test-code" class="title-slide slide level1 center">
<h1>🧩 Chunk 1 of 2 · The t-Test Code</h1>
<p><strong>We will cover:</strong> the <code>t.test()</code> code on the leaf data from last time — every line of the output, the decision, and a results sentence. Then we run the <strong>paired</strong> test on the same leaves, discover the data are <strong>pseudoreplicated</strong>, fix it with <strong>one <code>summarize()</code> at the top</strong>, and rerun the exact same code.</p>
<div class="activitybanner">
<p><strong>🛑 After this chunk: Activity Parts 1–6.</strong></p>
</div>
</section>

<section id="step-4-run-the-test-again" class="title-slide slide level1 center">
<h1>Step 4 — Run the Test (again)</h1>
<div class="columns">
<div class="column" style="width:60%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a aria-label="1"></a><span class="co"># Welch's two-sample t-test on the leaf data ------------</span></span>
<span id="cb3-2"><a aria-label="2"></a>leaf_model <span class="ot">&lt;-</span> <span class="fu">t.test</span>(mass_g <span class="sc">~</span> shade, <span class="at">data =</span> leaf_df,</span>
<span id="cb3-3"><a aria-label="3"></a>                     <span class="at">var.equal =</span> <span class="cn">FALSE</span>)</span>
<span id="cb3-4"><a aria-label="4"></a>leaf_model</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  mass_g by shade
t = 0.35579, df = 42.527, p-value = 0.7238
alternative hypothesis: true difference in means between group shady and group sunny is not equal to 0
95 percent confidence interval:
 -0.08392774  0.11987117
sample estimates:
mean in group shady mean in group sunny 
          0.5230357           0.5050640 </code></pre>
</div>
</div>
</div><div class="column" style="width:40%;">
<p><strong>Reading it top to bottom:</strong></p>
<table class="caption-top">
<colgroup>
<col style="width: 40%">
<col style="width: 60%">
</colgroup>
<thead>
<tr class="header">
<th>Line</th>
<th>What it tells you</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>t =</code></td>
<td>gap between means ÷ noise</td>
</tr>
<tr class="even">
<td><code>df =</code></td>
<td>degrees of freedom (Welch’s gives decimals — that’s normal)</td>
</tr>
<tr class="odd">
<td><code>p-value =</code></td>
<td>how often you’d see a gap this big if H₀ were true</td>
</tr>
<tr class="even">
<td><code>95 percent confidence interval</code></td>
<td>plausible range for the <strong>true difference</strong> in means</td>
</tr>
<tr class="odd">
<td><code>mean in group ...</code></td>
<td>the two group means</td>
</tr>
</tbody>
</table>
</div></div>
</section>

<section id="step-5-make-a-decision" class="title-slide slide level1 center">
<h1>Step 5 — Make a Decision</h1>
<div class="columns">
<div class="column" style="width:55%;">
<p><strong>The rule</strong> (set <em>before</em> the test): α = 0.05</p>
<table class="caption-top">
<colgroup>
<col style="width: 20%">
<col style="width: 30%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>If…</th>
<th>Decision</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><em>p</em> &lt; 0.05</td>
<td><strong>Reject</strong> H₀</td>
<td>the means differ</td>
</tr>
<tr class="even">
<td><em>p</em> ≥ 0.05</td>
<td><strong>Fail to reject</strong> H₀</td>
<td>no evidence the means differ</td>
</tr>
</tbody>
</table>
<p><strong>Leaf data:</strong> <em>p</em> is far above 0.05 → <strong>fail to reject H₀</strong>.</p>
<p>The confidence interval tells the same story: it runs from <strong>below zero to above zero</strong>, so “no difference” is a plausible value.</p>
</div><div class="column" style="width:45%;">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>“Fail to reject” is not “proved equal.”</strong></p>
<p>It means <em>this sample</em> did not give enough evidence of a difference. Maybe there is none — or maybe we had too few leaves, or too much noise, to see it.</p>
<p>Keep that second possibility in mind — it is the whole story of the next few slides.</p>
</div>
</div>
</div>
</div></div>
</section>

<section id="step-5-report-it" class="title-slide slide level1 center">
<h1>Step 5 — Report It</h1>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a aria-label="1"></a><span class="co"># Pull the numbers for the sentence out of the model ----</span></span>
<span id="cb5-2"><a aria-label="2"></a><span class="fu">tibble</span>(</span>
<span id="cb5-3"><a aria-label="3"></a>  <span class="at">t  =</span> leaf_model<span class="sc">$</span>statistic,</span>
<span id="cb5-4"><a aria-label="4"></a>  <span class="at">df =</span> leaf_model<span class="sc">$</span>parameter,</span>
<span id="cb5-5"><a aria-label="5"></a>  <span class="at">p  =</span> leaf_model<span class="sc">$</span>p.value</span>
<span id="cb5-6"><a aria-label="6"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
      t    df     p
  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 0.356  42.5 0.724</code></pre>
</div>
</div>
<p><code>leaf_model$statistic</code>, <code>$parameter</code>, <code>$p.value</code> — the <code>$</code> pulls one piece out of the result, so you never retype numbers by hand.</p>
</div><div class="column" style="width:45%;">
<p><strong>The template:</strong></p>
<blockquote>
<p><em>[Finding] (Welch’s t-test: t(df) = X.XX, p = X.XX).</em></p>
</blockquote>
<p><strong>Our leaves:</strong></p>
<blockquote>
<p><em>Mean leaf mass did not differ significantly between shady and sunny sides (Welch’s t-test: t(42.5) = 0.36, p = 0.72).</em></p>
</blockquote>
<ul>
<li>Test name, t, df, and exact <em>p</em></li>
<li>Never write “p = 0.000” — write “p &lt; 0.001”</li>
<li>A non-significant result is still a result — report it plainly</li>
</ul>
</div></div>
</section>

<section id="wait-where-did-these-leaves-come-from" class="title-slide slide level1 center">
<h1>Wait — Where Did These Leaves Come From?</h1>
<div class="columns">
<div class="column" style="width:52%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a aria-label="1"></a><span class="co"># How many leaves did each team turn in? ----------------</span></span>
<span id="cb7-2"><a aria-label="2"></a>leaf_df <span class="sc">%&gt;%</span></span>
<span id="cb7-3"><a aria-label="3"></a>  <span class="fu">count</span>(teams, shade) <span class="sc">%&gt;%</span></span>
<span id="cb7-4"><a aria-label="4"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> shade,</span>
<span id="cb7-5"><a aria-label="5"></a>              <span class="at">values_from =</span> n)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 3
  teams              shady sunny
  &lt;chr&gt;              &lt;int&gt; &lt;int&gt;
1 12345                  6     6
2 Oscar_Karl             6     6
3 fighting_mongooses     6     6
4 leaf_oglers            6     4
5 still_loading          4     3</code></pre>
</div>
</div>
</div><div class="column" style="width:48%;">
<ul>
<li><strong>5 teams</strong>, not 53 independent leaves</li>
<li>Each team went to <strong>one tree</strong> and picked leaves off the <strong>sunny</strong> side and the <strong>shady</strong> side of that tree</li>
<li>So every team contributes a sunny <em>and</em> a shady value — the two sides are <strong>matched within a team</strong></li>
</ul>
<p><strong>Two consequences.</strong> The data are <strong>paired</strong>, and they are <strong>pseudoreplicated</strong>. Let’s take them one at a time.</p>
</div></div>
</section>

<section id="the-pairing-hiding-in-the-leaf-data" class="title-slide slide level1 center">
<h1>The Pairing Hiding in the Leaf Data</h1>
<div class="columns">
<div class="column" style="width:55%;">
<p>A paired test needs the two groups <strong>side by side in one row</strong>, so we reshape:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a aria-label="1"></a><span class="co"># Number the leaves within each team and side ----------</span></span>
<span id="cb9-2"><a aria-label="2"></a>leaf_wide_df <span class="ot">&lt;-</span> leaf_df <span class="sc">%&gt;%</span></span>
<span id="cb9-3"><a aria-label="3"></a>  <span class="fu">group_by</span>(teams, shade) <span class="sc">%&gt;%</span></span>
<span id="cb9-4"><a aria-label="4"></a>  <span class="fu">mutate</span>(<span class="at">leaf_n =</span> <span class="fu">row_number</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb9-5"><a aria-label="5"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb9-6"><a aria-label="6"></a>  <span class="fu">select</span>(teams, leaf_n, shade, mass_g) <span class="sc">%&gt;%</span></span>
<span id="cb9-7"><a aria-label="7"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> shade,</span>
<span id="cb9-8"><a aria-label="8"></a>              <span class="at">values_from =</span> mass_g) <span class="sc">%&gt;%</span></span>
<span id="cb9-9"><a aria-label="9"></a>  <span class="fu">mutate</span>(<span class="at">diff =</span> shady <span class="sc">-</span> sunny)</span>
<span id="cb9-10"><a aria-label="10"></a></span>
<span id="cb9-11"><a aria-label="11"></a>leaf_wide_df <span class="sc">%&gt;%</span> <span class="fu">head</span>(<span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
  teams leaf_n sunny shady    diff
  &lt;chr&gt;  &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;
1 12345      1  0.4   0.39 -0.0100
2 12345      2  0.48  0.45 -0.0300
3 12345      3  0.34  0.6   0.26  
4 12345      4  0.65  0.57 -0.0800</code></pre>
</div>
</div>
</div><div class="column" style="width:45%;">
<ul>
<li><code>row_number()</code> numbers the leaves <strong>1, 2, 3…</strong> inside each team and side</li>
<li><code>pivot_wider()</code> then puts the shady and sunny leaf with the same number in the <strong>same row</strong></li>
<li><code>diff</code> is the shady − sunny gap for that row</li>
</ul>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>Look at what we just did.</strong> We paired shady leaf #1 with sunny leaf #1 because they happen to share a number. There is <strong>no reason</strong> those two leaves belong together — they’re just two leaves off the same tree.</p>
<p>Hold that thought.</p>
</div>
</div>
</div>
</div></div>
</section>

<section id="paired-t-test-on-every-leaf" class="title-slide slide level1 center">
<h1>Paired t-Test on Every Leaf</h1>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a aria-label="1"></a><span class="co"># Paired t-test on all the leaves ----------------------</span></span>
<span id="cb11-2"><a aria-label="2"></a>leaf_paired_model <span class="ot">&lt;-</span> <span class="fu">t.test</span>(leaf_wide_df<span class="sc">$</span>shady,</span>
<span id="cb11-3"><a aria-label="3"></a>                            leaf_wide_df<span class="sc">$</span>sunny,</span>
<span id="cb11-4"><a aria-label="4"></a>                            <span class="at">paired =</span> <span class="cn">TRUE</span>)</span>
<span id="cb11-5"><a aria-label="5"></a>leaf_paired_model</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  leaf_wide_df$shady and leaf_wide_df$sunny
t = 0.58003, df = 24, p-value = 0.5673
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
 -0.05746912  0.10239712
sample estimates:
mean difference 
       0.022464 </code></pre>
</div>
</div>
</div><div class="column" style="width:45%;">
<p><strong>R ran it without complaint.</strong></p>
<ul>
<li>It got <em>p</em> = 0.57 — no difference</li>
<li><code>df</code> = 24, so it thinks it has <strong>25 pairs</strong> of information</li>
</ul>
<blockquote>
<p>⚠️ <strong>Watch out!</strong> Two teams turned in <strong>uneven</strong> numbers of leaves (4 shady / 3 sunny). Those leftover leaves had no partner to pair with, so <code>t.test()</code> <strong>silently dropped 3 of them</strong>. It never warns you.</p>
</blockquote>
<p><strong>R will answer any question you ask it — including a meaningless one.</strong> Our job is to ask the right one.</p>
</div></div>
</section>

<section id="problem-pseudoreplication" class="title-slide slide level1 center">
<h1>Problem: Pseudoreplication</h1>
<div class="columns">
<div class="column" style="width:55%;">
<p>The 6 shady leaves from team <code>Oscar_Karl</code> all came off <strong>one tree</strong>. They share that tree’s soil, water, light, age, and genetics. They are <strong>not independent</strong> — they are closer to <strong>one measurement taken six times</strong>.</p>
<p>Treating all 53 leaves as independent is <strong>pseudoreplication</strong>: it pretends we have far more information than we collected.</p>
<p><strong>Count the real replicates.</strong> We did not sample 53 trees. We sampled <strong>5</strong>.</p>
<table class="caption-top">
<colgroup>
<col style="width: 28%">
<col style="width: 36%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>What the test used</th>
<th>What we actually have</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Two-sample</td>
<td>28 + 25 leaves, df = 42.5</td>
<td>5 + 5 teams</td>
</tr>
<tr class="even">
<td>Paired</td>
<td>25 “pairs”, df = 24</td>
<td>5 pairs</td>
</tr>
</tbody>
</table>
</div><div class="column" style="width:45%;">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>Why this is serious.</strong> <code>df</code> drives the <em>p</em>-value. Inflate your <code>df</code> and every <em>p</em>-value you report is too small — you will claim differences that your data cannot support.</p>
<p>Here both tests said “no difference,” so nothing went wrong <em>this time</em>. That is luck, not method.</p>
</div>
</div>
</div>
<p><strong>The fix is one line</strong>, and it is a line you already know: <code>group_by()</code> + <code>summarize()</code>.</p>
</div></div>
</section>

<section id="the-fix-one-summarize-at-the-top" class="title-slide slide level1 center">
<h1>The Fix: One <code>summarize()</code> at the Top</h1>
<div class="columns">
<div class="column" style="width:55%;">
<p>Go back to where you <strong>loaded</strong> the data and add the averaging step to the end of the chain. Keep the <strong>same name</strong>, <code>leaf_df</code>, and the <strong>same column name</strong>, <code>mass_g</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a aria-label="1"></a><span class="co"># Load the leaf data and average each team's side ------</span></span>
<span id="cb13-2"><a aria-label="2"></a>leaf_df <span class="ot">&lt;-</span></span>
<span id="cb13-3"><a aria-label="3"></a>  <span class="fu">read_excel</span>(<span class="st">"data/2026_09_03_data_sci_leaf_area.xlsx"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb13-4"><a aria-label="4"></a>  <span class="fu">clean_names</span>() <span class="sc">%&gt;%</span></span>
<span id="cb13-5"><a aria-label="5"></a>  <span class="fu">group_by</span>(teams, shade) <span class="sc">%&gt;%</span></span>
<span id="cb13-6"><a aria-label="6"></a>  <span class="fu">summarize</span>(<span class="at">mass_g =</span> <span class="fu">mean</span>(mass_g),</span>
<span id="cb13-7"><a aria-label="7"></a>            <span class="at">.groups =</span> <span class="st">"drop"</span>)</span>
<span id="cb13-8"><a aria-label="8"></a></span>
<span id="cb13-9"><a aria-label="9"></a>leaf_df</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 3
   teams              shade mass_g
   &lt;chr&gt;              &lt;chr&gt;  &lt;dbl&gt;
 1 12345              shady  0.448
 2 12345              sunny  0.428
 3 Oscar_Karl         shady  0.400
 4 Oscar_Karl         sunny  0.339
 5 fighting_mongooses shady  0.653
 6 fighting_mongooses sunny  0.544
 7 leaf_oglers        shady  0.588
 8 leaf_oglers        sunny  0.599
 9 still_loading      shady  0.526
10 still_loading      sunny  0.789</code></pre>
</div>
</div>
</div><div class="column" style="width:45%;">
<p><strong>One value per team per side. 10 rows — 5 teams × 2 sides.</strong></p>
<ul>
<li><code>group_by(teams, shade)</code> — two grouping columns, the pattern from Summary Statistics</li>
<li><code>mass_g = mean(mass_g)</code> — reusing the name means <strong>every line of code below keeps working</strong></li>
<li><code>.groups = "drop"</code> tidies up afterwards</li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ This is how real analysis works.</strong> You don’t write a new script. You go back to the top, fix how the data are built, and <strong>rerun everything</strong> — because the code below never cared how many rows came in.</p>
</div>
</div>
</div>
</div></div>
</section>

<section id="rerun-the-same-code" class="title-slide slide level1 center">
<h1>Rerun the Same Code</h1>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a aria-label="1"></a><span class="co"># Keep a copy of the pseudoreplicated results ----------</span></span>
<span id="cb15-2"><a aria-label="2"></a>pseudo_2s     <span class="ot">&lt;-</span> leaf_model</span>
<span id="cb15-3"><a aria-label="3"></a>pseudo_paired <span class="ot">&lt;-</span> leaf_paired_model</span>
<span id="cb15-4"><a aria-label="4"></a></span>
<span id="cb15-5"><a aria-label="5"></a><span class="co"># Exactly the same two-sample code as before -----------</span></span>
<span id="cb15-6"><a aria-label="6"></a>leaf_model <span class="ot">&lt;-</span> <span class="fu">t.test</span>(mass_g <span class="sc">~</span> shade, <span class="at">data =</span> leaf_df,</span>
<span id="cb15-7"><a aria-label="7"></a>                     <span class="at">var.equal =</span> <span class="cn">FALSE</span>)</span>
<span id="cb15-8"><a aria-label="8"></a></span>
<span id="cb15-9"><a aria-label="9"></a><span class="co"># Exactly the same reshape + paired code as before -----</span></span>
<span id="cb15-10"><a aria-label="10"></a>leaf_wide_df <span class="ot">&lt;-</span> leaf_df <span class="sc">%&gt;%</span></span>
<span id="cb15-11"><a aria-label="11"></a>  <span class="fu">group_by</span>(teams, shade) <span class="sc">%&gt;%</span></span>
<span id="cb15-12"><a aria-label="12"></a>  <span class="fu">mutate</span>(<span class="at">leaf_n =</span> <span class="fu">row_number</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb15-13"><a aria-label="13"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb15-14"><a aria-label="14"></a>  <span class="fu">select</span>(teams, leaf_n, shade, mass_g) <span class="sc">%&gt;%</span></span>
<span id="cb15-15"><a aria-label="15"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> shade,</span>
<span id="cb15-16"><a aria-label="16"></a>              <span class="at">values_from =</span> mass_g) <span class="sc">%&gt;%</span></span>
<span id="cb15-17"><a aria-label="17"></a>  <span class="fu">mutate</span>(<span class="at">diff =</span> shady <span class="sc">-</span> sunny)</span>
<span id="cb15-18"><a aria-label="18"></a></span>
<span id="cb15-19"><a aria-label="19"></a>leaf_paired_model <span class="ot">&lt;-</span> <span class="fu">t.test</span>(leaf_wide_df<span class="sc">$</span>shady,</span>
<span id="cb15-20"><a aria-label="20"></a>                            leaf_wide_df<span class="sc">$</span>sunny,</span>
<span id="cb15-21"><a aria-label="21"></a>                            <span class="at">paired =</span> <span class="cn">TRUE</span>)</span>
<span id="cb15-22"><a aria-label="22"></a></span>
<span id="cb15-23"><a aria-label="23"></a>leaf_wide_df</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 5
  teams              leaf_n shady sunny    diff
  &lt;chr&gt;               &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;
1 12345                   1 0.448 0.428  0.0200
2 Oscar_Karl              1 0.400 0.339  0.0612
3 fighting_mongooses      1 0.653 0.544  0.110 
4 leaf_oglers             1 0.588 0.599 -0.0102
5 still_loading           1 0.526 0.789 -0.263 </code></pre>
</div>
</div>
</div><div class="column" style="width:45%;">
<p><strong>Not one character of the test code changed.</strong> We only changed what <code>leaf_df</code> <em>is</em> — the two <code>pseudo_</code> lines just park the old results so we can put them side by side in a moment.</p>
<ul>
<li>Each team now has a single row per side, so <code>row_number()</code> is just 1 everywhere and <code>pivot_wider()</code> gives <strong>5 clean pairs</strong> — one per team</li>
<li>Nothing gets silently dropped now</li>
<li><code>diff</code> is finally a real quantity: <strong>this team’s shady side minus this team’s sunny side</strong></li>
</ul>
<p>Look at <code>still_loading</code>: a difference of <strong>−0.26 g</strong>, far bigger than anyone else’s.</p>
</div></div>
</section>

<section id="same-leaves-four-answers" class="title-slide slide level1 center">
<h1>Same Leaves, Four Answers</h1>
<div class="columns">
<div class="column" style="width:58%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a aria-label="1"></a><span class="co"># Pull all four results out of the four models ---------</span></span>
<span id="cb17-2"><a aria-label="2"></a><span class="fu">tibble</span>(</span>
<span id="cb17-3"><a aria-label="3"></a>  <span class="at">analysis =</span> <span class="fu">c</span>(<span class="st">"Two-sample, every leaf"</span>,</span>
<span id="cb17-4"><a aria-label="4"></a>               <span class="st">"Paired, every leaf"</span>,</span>
<span id="cb17-5"><a aria-label="5"></a>               <span class="st">"Two-sample, team means"</span>,</span>
<span id="cb17-6"><a aria-label="6"></a>               <span class="st">"Paired, team means"</span>),</span>
<span id="cb17-7"><a aria-label="7"></a>  <span class="at">t  =</span> <span class="fu">c</span>(pseudo_2s<span class="sc">$</span>statistic, pseudo_paired<span class="sc">$</span>statistic,</span>
<span id="cb17-8"><a aria-label="8"></a>         leaf_model<span class="sc">$</span>statistic, leaf_paired_model<span class="sc">$</span>statistic),</span>
<span id="cb17-9"><a aria-label="9"></a>  <span class="at">df =</span> <span class="fu">c</span>(pseudo_2s<span class="sc">$</span>parameter, pseudo_paired<span class="sc">$</span>parameter,</span>
<span id="cb17-10"><a aria-label="10"></a>         leaf_model<span class="sc">$</span>parameter, leaf_paired_model<span class="sc">$</span>parameter),</span>
<span id="cb17-11"><a aria-label="11"></a>  <span class="at">p  =</span> <span class="fu">c</span>(pseudo_2s<span class="sc">$</span>p.value, pseudo_paired<span class="sc">$</span>p.value,</span>
<span id="cb17-12"><a aria-label="12"></a>         leaf_model<span class="sc">$</span>p.value, leaf_paired_model<span class="sc">$</span>p.value)</span>
<span id="cb17-13"><a aria-label="13"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb17-14"><a aria-label="14"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(t<span class="sc">:</span>p, \(x) <span class="fu">round</span>(x, <span class="dv">3</span>)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
  analysis                    t    df     p
  &lt;chr&gt;                   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 Two-sample, every leaf  0.356 42.5  0.724
2 Paired, every leaf      0.58  24    0.567
3 Two-sample, team means -0.184  6.52 0.86 
4 Paired, team means     -0.254  4    0.812</code></pre>
</div>
</div>
</div><div class="column" style="width:42%;">
<p><strong>Two things to notice.</strong></p>
<p><strong>1. The <code>df</code> collapse.</strong> 42.5 → 6.5. We did not lose data; we stopped <strong>double-counting</strong> it.</p>
<p><strong>2. The difference changes sign.</strong> Shady leaves looked <em>heavier</em> (+0.018 g) with every leaf, and <em>lighter</em> (−0.016 g) once we averaged.</p>
<p>Why? Teams turned in <strong>uneven</strong> numbers of leaves. A team with 6 shady leaves counted six times in the raw mean, a team with 4 counted four times. Averaging first gives <strong>every team one equal vote</strong>.</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>Pseudoreplication does not just break your <em>p</em>-value — it can point the difference the wrong way.</strong></p>
</div>
</div>
</div>
</div></div>
</section>

<section id="activity-10-parts-16-now" class="title-slide slide level1 center">
<h1>→ ACTIVITY 10 Parts 1–6 now</h1>
<div class="activitybanner">
<p><strong>🛑 Do Activity Parts 1–6 now</strong></p>
<p>Run the two-sample and paired tests on every leaf, then add the <code>summarize()</code> to the top of your data-loading chain and rerun the same code. Compare the four answers.</p>
</div>
</section>

<section id="chunk-2-of-2-the-maple-test" class="title-slide slide level1 center">
<h1>🧩 Chunk 2 of 2 · The Maple Test</h1>
<p><strong>Same workflow, better data.</strong> We apply the same <code>summarize()</code> step to the sugar maple leaves, check the assumptions, run the <strong>two-sample</strong> and the <strong>paired</strong> t-test, see <strong>why pairing adds power</strong>, plot and report the paired result, and meet the rank-based backups.</p>
<div class="activitybanner">
<p><strong>🛑 After this chunk: Activity Parts 7–12, then Part B.</strong></p>
</div>
</section>

<section id="the-sugar-maple-design" class="title-slide slide level1 center">
<h1>The Sugar Maple Design</h1>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a aria-label="1"></a><span class="co"># How many leaves from each tree and side? --------------</span></span>
<span id="cb19-2"><a aria-label="2"></a>maple_df <span class="sc">%&gt;%</span></span>
<span id="cb19-3"><a aria-label="3"></a>  <span class="fu">count</span>(tree, side) <span class="sc">%&gt;%</span></span>
<span id="cb19-4"><a aria-label="4"></a>  <span class="fu">head</span>(<span class="dv">6</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
   tree side      n
  &lt;dbl&gt; &lt;chr&gt; &lt;int&gt;
1     1 shady     2
2     1 sunny     2
3     2 shady     2
4     2 sunny     2
5     3 shady     2
6     3 sunny     2</code></pre>
</div>
</div>
</div><div class="column" style="width:50%;">
<ul>
<li><strong>8 trees</strong></li>
<li>From <strong>each tree</strong>: 2 leaves from the <strong>sunny</strong> side and 2 from the <strong>shady</strong> side</li>
<li>32 leaves in total</li>
</ul>
<p>In class we test <strong>leaf area</strong> (<code>total_area_cm2</code>). Your hand-in does the same for <strong>leaf mass</strong>.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ Same structure as our leaf data — but designed on purpose.</strong></p>
<p>Leaves inside a tree-side, so it needs the <strong>same <code>summarize()</code> step</strong>. The difference: it is <strong>perfectly balanced</strong> — exactly 2 leaves everywhere, 8 trees, nothing uneven and nothing missing.</p>
<p>So no team gets an unfair vote, and the pairing is <strong>real</strong> by design: both sides come off the <strong>same tree</strong>.</p>
</div>
</div>
</div>
</div></div>
</section>

<section id="step-1-the-same-summarize-one-more-time" class="title-slide slide level1 center">
<h1>Step 1: The Same <code>summarize()</code>, One More Time</h1>
<div class="columns">
<div class="column" style="width:55%;">
<p>Two leaves off the sunny side of tree 3 share that tree’s soil, water, and light — <strong>not independent</strong>, exactly like our 6 leaves per team. So we start where we now always start: <strong>average up to the real replicate.</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a aria-label="1"></a><span class="co"># Average the 2 leaves per tree and side ---------------</span></span>
<span id="cb21-2"><a aria-label="2"></a>maple_tree_df <span class="ot">&lt;-</span> maple_df <span class="sc">%&gt;%</span></span>
<span id="cb21-3"><a aria-label="3"></a>  <span class="fu">group_by</span>(tree, side) <span class="sc">%&gt;%</span></span>
<span id="cb21-4"><a aria-label="4"></a>  <span class="fu">summarize</span>(<span class="at">area =</span> <span class="fu">mean</span>(total_area_cm2),</span>
<span id="cb21-5"><a aria-label="5"></a>            <span class="at">.groups =</span> <span class="st">"drop"</span>)</span>
<span id="cb21-6"><a aria-label="6"></a>maple_tree_df <span class="sc">%&gt;%</span> <span class="fu">head</span>(<span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
   tree side   area
  &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;
1     1 shady  136.
2     1 sunny  106.
3     2 shady  200.
4     2 sunny  159.</code></pre>
</div>
</div>
<p><strong>32 leaves → 16 rows.</strong> The real replicate is the <strong>tree</strong>, so we get 8 shady values and 8 sunny values.</p>
</div><div class="column" style="width:45%;">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ The habit, not the trick.</strong></p>
<p>Ask this of <strong>every</strong> data set before you test it:</p>
<blockquote>
<p><em>What is the thing I actually sampled, and is there exactly one row per one of those?</em></p>
</blockquote>
<p>Here: 8 trees sampled, so 8 values per side. Same two-column <code>group_by()</code>, same <code>summarize()</code>, same <code>.groups = "drop"</code>.</p>
</div>
</div>
</div>
<p>Because this design is <strong>balanced</strong>, averaging won’t flip anything the way it did for our leaves — every tree already had an equal say. Here averaging buys us something different: an <strong>honest <code>df</code></strong>, and a clean shot at the pairing.</p>
</div></div>
</section>

<section id="two-sample-test-check-the-assumptions-first" class="title-slide slide level1 center">
<h1>Two-Sample Test — Check the Assumptions First</h1>
<div class="columns">
<div class="column" style="width:55%;">
<p>Last lecture you checked all 32 leaves. We now test the <strong>tree means</strong>, so we check <em>those</em>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a aria-label="1"></a><span class="co"># Normality of each side (tree means) -------------------</span></span>
<span id="cb23-2"><a aria-label="2"></a>maple_tree_df <span class="sc">%&gt;%</span></span>
<span id="cb23-3"><a aria-label="3"></a>  <span class="fu">group_by</span>(side) <span class="sc">%&gt;%</span></span>
<span id="cb23-4"><a aria-label="4"></a>  <span class="fu">summarize</span>(<span class="at">shapiro_p =</span> <span class="fu">shapiro.test</span>(area)<span class="sc">$</span>p.value)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  side  shapiro_p
  &lt;chr&gt;     &lt;dbl&gt;
1 shady     0.338
2 sunny     0.316</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a aria-label="1"></a><span class="co"># Equal spread? -----------------------------------------</span></span>
<span id="cb25-2"><a aria-label="2"></a><span class="fu">leveneTest</span>(area <span class="sc">~</span> side, <span class="at">data =</span> maple_tree_df)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
      Df F value Pr(&gt;F)
group  1  0.4965 0.4926
      14               </code></pre>
</div>
</div>
</div><div class="column" style="width:45%;">
<p><strong>A two-sample t-test needs:</strong></p>
<ul>
<li>each group roughly <strong>normal</strong> → Shapiro <em>p</em> &gt; 0.05 on both sides ✅</li>
<li>(equal spread — Welch’s doesn’t need it, but good to know) → Levene <em>p</em> &gt; 0.05 ✅</li>
</ul>
<p><strong>Decision:</strong> a two-sample t-test is OK. <em>Now</em> we run it.</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>Check → decide → test.</strong> Never the other way round.</p>
</div>
</div>
</div>
</div></div>
</section>

<section id="two-sample-t-test-on-the-tree-means" class="title-slide slide level1 center">
<h1>Two-Sample t-Test on the Tree Means</h1>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>🔮 Predict first:</strong> Shady trees average bigger leaves. With only 8 trees per side, will the two-sample test be significant?</p>
</div>
</div>
</div>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a aria-label="1"></a><span class="co"># Welch's two-sample t-test on the 8 tree means -------</span></span>
<span id="cb27-2"><a aria-label="2"></a>maple_2s_model <span class="ot">&lt;-</span> <span class="fu">t.test</span>(area <span class="sc">~</span> side,</span>
<span id="cb27-3"><a aria-label="3"></a>                         <span class="at">data =</span> maple_tree_df,</span>
<span id="cb27-4"><a aria-label="4"></a>                         <span class="at">var.equal =</span> <span class="cn">FALSE</span>)</span>
<span id="cb27-5"><a aria-label="5"></a>maple_2s_model</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  area by side
t = 2.2017, df = 13.426, p-value = 0.04573
alternative hypothesis: true difference in means between group shady and group sunny is not equal to 0
95 percent confidence interval:
  0.9668576 87.2303924
sample estimates:
mean in group shady mean in group sunny 
           198.3656            154.2669 </code></pre>
</div>
</div>
</div><div class="column" style="width:45%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a aria-label="1"></a><span class="co"># Box plot of the tree means ---------------</span></span>
<span id="cb29-2"><a aria-label="2"></a>maple_tree_df <span class="sc">%&gt;%</span></span>
<span id="cb29-3"><a aria-label="3"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> side, <span class="at">y =</span> area)) <span class="sc">+</span></span>
<span id="cb29-4"><a aria-label="4"></a>  <span class="fu">geom_boxplot</span>(<span class="at">outlier.shape =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb29-5"><a aria-label="5"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.1</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb29-6"><a aria-label="6"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Side"</span>, <span class="at">y =</span> <span class="st">"Mean leaf area (cm²)"</span>) <span class="sc">+</span></span>
<span id="cb29-7"><a aria-label="7"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="t_tests_2_lecture_files/figure-html/maple-box-1.png" alt="Box plot of mean leaf area per tree for shady and sunny sides with the eight tree means as points; the boxes overlap heavily." width="480"></p>
</figure>
</div>
</div>
</div>
<p><strong>Just barely significant</strong> — <em>p</em> only just under 0.05. The boxes still overlap a lot; a couple of different trees and we would have missed it. Is this the best we can do?</p>
</div></div>
</section>

<section id="the-pairing-is-hiding-in-plain-sight" class="title-slide slide level1 center">
<h1>The Pairing Is Hiding in Plain Sight</h1>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a aria-label="1"></a><span class="co"># One line per tree: sunny -&gt; shady ----------------------</span></span>
<span id="cb30-2"><a aria-label="2"></a>maple_tree_df <span class="sc">%&gt;%</span></span>
<span id="cb30-3"><a aria-label="3"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> side, <span class="at">y =</span> area, <span class="at">group =</span> tree)) <span class="sc">+</span></span>
<span id="cb30-4"><a aria-label="4"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb30-5"><a aria-label="5"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb30-6"><a aria-label="6"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="st">"sunny"</span>, <span class="st">"shady"</span>)) <span class="sc">+</span></span>
<span id="cb30-7"><a aria-label="7"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Side"</span>, <span class="at">y =</span> <span class="st">"Mean leaf area (cm²)"</span>) <span class="sc">+</span></span>
<span id="cb30-8"><a aria-label="8"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="t_tests_2_lecture_files/figure-html/slope-plot-1.png" alt="Slope plot with one line per tree joining that tree's sunny mean leaf area to its shady mean leaf area. Every one of the eight lines slopes upward toward the shady side." width="480"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:45%;">
<p>Same 16 numbers — but now each <strong>line is one tree</strong>.</p>
<p><strong>Every line goes up.</strong> On <em>every</em> tree, the shady side has bigger leaves.</p>
<p>So why was the two-sample test such a close call?</p>
<ul>
<li>Some trees just have <strong>big leaves</strong> and some have <strong>small leaves</strong></li>
<li>That <strong>tree-to-tree</strong> difference is large compared with the shade effect</li>
<li>The two-sample test lumps it all into the “noise” — and the signal nearly drowns</li>
</ul>
<p><code>group = tree</code> tells ggplot which points to join with a line. <code>scale_x_discrete(limits = )</code> puts sunny on the left.</p>
</div></div>
</section>

<section id="paired-test-step-1-one-row-per-tree" class="title-slide slide level1 center">
<h1>Paired Test — Step 1: One Row per Tree</h1>
<div class="columns">
<div class="column" style="width:55%;">
<p>A paired test compares the two sides <strong>within each tree</strong>, so tree-to-tree differences cancel out.</p>
<p>First, put each tree on <strong>one row</strong> with a sunny and a shady column, and compute the difference:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a aria-label="1"></a><span class="co"># One row per tree + the shady - sunny difference ------</span></span>
<span id="cb31-2"><a aria-label="2"></a>maple_wide_df <span class="ot">&lt;-</span> maple_tree_df <span class="sc">%&gt;%</span></span>
<span id="cb31-3"><a aria-label="3"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> side, <span class="at">values_from =</span> area) <span class="sc">%&gt;%</span></span>
<span id="cb31-4"><a aria-label="4"></a>  <span class="fu">mutate</span>(<span class="at">diff =</span> shady <span class="sc">-</span> sunny)</span>
<span id="cb31-5"><a aria-label="5"></a>maple_wide_df</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 4
   tree shady sunny  diff
  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     1  136.  106.  30.1
2     2  200.  159.  41.5
3     3  250.  197.  52.5
4     4  191.  165.  26.2
5     5  249.  180.  68.9
6     6  239.  191.  48.0
7     7  159.  114.  45.2
8     8  163.  123.  40.3</code></pre>
</div>
</div>
<p><code>pivot_wider()</code> is a sneak peek — you’ll learn it properly in the Pivoting lecture.</p>
</div><div class="column" style="width:45%;">
<p><strong>Before</strong> (<code>maple_tree_df</code>) — one row per tree <em>and</em> side (16 rows)</p>
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 35%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th>tree</th>
<th>side</th>
<th>area</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>shady</td>
<td>…</td>
</tr>
<tr class="even">
<td>1</td>
<td>sunny</td>
<td>…</td>
</tr>
</tbody>
</table>
<p><strong>After</strong> (<code>maple_wide_df</code>) — one row per tree (8 rows)</p>
<table class="caption-top">
<colgroup>
<col style="width: 20%">
<col style="width: 27%">
<col style="width: 27%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>tree</th>
<th>shady</th>
<th>sunny</th>
<th>diff</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>…</td>
<td>…</td>
<td>…</td>
</tr>
</tbody>
</table>
<ul>
<li><code>names_from = side</code> → the new column names</li>
<li><code>values_from = area</code> → what goes in them</li>
</ul>
<p><strong>Look at <code>diff</code>: every tree is positive.</strong></p>
</div></div>
</section>

<section id="paired-test-step-2-check-the-assumption-first" class="title-slide slide level1 center">
<h1>Paired Test — Step 2: Check the Assumption First</h1>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a aria-label="1"></a><span class="co"># QQ plot of the 8 differences --------------------------</span></span>
<span id="cb33-2"><a aria-label="2"></a>maple_wide_df <span class="sc">%&gt;%</span></span>
<span id="cb33-3"><a aria-label="3"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">sample =</span> diff)) <span class="sc">+</span></span>
<span id="cb33-4"><a aria-label="4"></a>  <span class="fu">stat_qq</span>() <span class="sc">+</span></span>
<span id="cb33-5"><a aria-label="5"></a>  <span class="fu">stat_qq_line</span>() <span class="sc">+</span></span>
<span id="cb33-6"><a aria-label="6"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="t_tests_2_lecture_files/figure-html/diff-qq-1.png" alt="QQ plot of the eight shady-minus-sunny differences in leaf area; the points fall close to the reference line." width="480"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a aria-label="1"></a><span class="co"># Shapiro-Wilk on the differences -----------------------</span></span>
<span id="cb34-2"><a aria-label="2"></a><span class="fu">shapiro.test</span>(maple_wide_df<span class="sc">$</span>diff)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  maple_wide_df$diff
W = 0.95881, p-value = 0.7987</code></pre>
</div>
</div>
</div><div class="column" style="width:45%;">
<p><strong>A paired test needs the differences to be roughly normal</strong> — not each side.</p>
<ul>
<li>QQ plot: dots near the line ✅</li>
<li>Shapiro-Wilk: <em>p</em> &gt; 0.05 ✅</li>
</ul>
<p><strong>No Levene’s test</strong> — there is only one set of numbers (the differences), so there is no second spread to compare.</p>
<p><strong>Decision:</strong> a paired t-test is OK. <em>Now</em> we run it.</p>
</div></div>
</section>

<section id="paired-test-step-3-run-it" class="title-slide slide level1 center">
<h1>Paired Test — Step 3: Run It</h1>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>🔮 Predict first:</strong> Every line went up. Will the paired <em>p</em> be bigger or smaller than the two-sample <em>p</em>?</p>
</div>
</div>
</div>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a aria-label="1"></a><span class="co"># Paired t-test: shady vs. sunny on the SAME tree -------</span></span>
<span id="cb36-2"><a aria-label="2"></a>maple_paired_model <span class="ot">&lt;-</span> <span class="fu">t.test</span>(maple_wide_df<span class="sc">$</span>shady,</span>
<span id="cb36-3"><a aria-label="3"></a>                             maple_wide_df<span class="sc">$</span>sunny,</span>
<span id="cb36-4"><a aria-label="4"></a>                             <span class="at">paired =</span> <span class="cn">TRUE</span>)</span>
<span id="cb36-5"><a aria-label="5"></a>maple_paired_model</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  maple_wide_df$shady and maple_wide_df$sunny
t = 9.3808, df = 7, p-value = 3.255e-05
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
 32.98271 55.21454
sample estimates:
mean difference 
       44.09862 </code></pre>
</div>
</div>
</div><div class="column" style="width:45%;">
<p><strong>Overwhelmingly significant</strong> — <em>p</em> is more than a thousand times smaller. Same trees, same numbers.</p>
<ul>
<li><code>paired = TRUE</code> matches row 1 with row 1, row 2 with row 2 …</li>
<li>The order sets the sign: <strong>shady − sunny</strong>. Positive = shady is bigger.</li>
<li><code>mean difference</code> = the average of the <code>diff</code> column</li>
<li><strong>df = 7</strong> — 8 trees → 8 differences → 8 − 1</li>
</ul>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p><strong>⚠️ Why not <code>area ~ side</code> here?</strong></p>
<p>R does not allow <code>paired = TRUE</code> with a formula. That’s why we made the wide table first.</p>
</div>
</div>
</div>
</div></div>
</section>

<section id="same-data-two-answers-why-pairing-adds-power" class="title-slide slide level1 center">
<h1>Same Data, Two Answers — Why Pairing Adds Power</h1>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a aria-label="1"></a><span class="co"># Put the two results side by side ---------------------</span></span>
<span id="cb38-2"><a aria-label="2"></a><span class="fu">tibble</span>(</span>
<span id="cb38-3"><a aria-label="3"></a>  <span class="at">test =</span> <span class="fu">c</span>(<span class="st">"Two-sample (Welch)"</span>, <span class="st">"Paired"</span>),</span>
<span id="cb38-4"><a aria-label="4"></a>  <span class="at">t    =</span> <span class="fu">c</span>(maple_2s_model<span class="sc">$</span>statistic,</span>
<span id="cb38-5"><a aria-label="5"></a>           maple_paired_model<span class="sc">$</span>statistic),</span>
<span id="cb38-6"><a aria-label="6"></a>  <span class="at">df   =</span> <span class="fu">c</span>(maple_2s_model<span class="sc">$</span>parameter,</span>
<span id="cb38-7"><a aria-label="7"></a>           maple_paired_model<span class="sc">$</span>parameter),</span>
<span id="cb38-8"><a aria-label="8"></a>  <span class="at">p    =</span> <span class="fu">c</span>(maple_2s_model<span class="sc">$</span>p.value,</span>
<span id="cb38-9"><a aria-label="9"></a>           maple_paired_model<span class="sc">$</span>p.value)</span>
<span id="cb38-10"><a aria-label="10"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  test                   t    df         p
  &lt;chr&gt;              &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;
1 Two-sample (Welch)  2.20  13.4 0.0457   
2 Paired              9.38   7   0.0000326</code></pre>
</div>
</div>
</div><div class="column" style="width:45%;">
<p><strong>Same 16 numbers. Same difference in means.</strong></p>
<ul>
<li><strong>Two-sample:</strong> noise = tree-to-tree variation <strong>plus</strong> the shade effect’s wobble → big noise, small <em>t</em></li>
<li><strong>Paired:</strong> subtracting within each tree removes its size, soil, water, age → small noise, big <em>t</em></li>
</ul>
<p>The paired test even has <strong>fewer df</strong> (7 vs.&nbsp;about 13) — and still wins easily, because the noise it removed mattered far more.</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>The design picks the test.</strong> Both sides were measured on the same tree, so the data are paired. The two-sample test answers a question our design never asked.</p>
</div>
</div>
</div>
</div></div>
</section>

<section id="when-is-data-paired" class="title-slide slide level1 center">
<h1>When Is Data Paired?</h1>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Paired ✅</th>
<th>Not paired (two-sample) ❌</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Sunny and shady side of the <strong>same tree</strong></td>
<td>Sunny leaves from some trees, shady from <strong>other</strong> trees</td>
</tr>
<tr class="even">
<td><strong>Before and after</strong> on the same fish</td>
<td>Fish from two different lakes</td>
</tr>
<tr class="odd">
<td>Left and right leg of the same person</td>
<td>Two groups of different people</td>
</tr>
<tr class="even">
<td>Twins split between two treatments</td>
<td>Randomly assigned to two groups</td>
</tr>
</tbody>
</table>
<p><strong>Ask:</strong> does each value in group 1 have a <strong>natural partner</strong> in group 2? If yes → paired.</p>
<p><strong>Our class leaf data</strong> — each team sampled both sides of <strong>their own tree</strong>, so those data are paired too. That is why the paired test was the honest one there as well, once we had averaged each team’s side down to one value.</p>
</section>

<section id="plotting-a-paired-result-build-the-label" class="title-slide slide level1 center">
<h1>Plotting a Paired Result — Build the Label</h1>
<div class="columns">
<div class="column" style="width:58%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a aria-label="1"></a><span class="co"># Label with the paired test result ----------------------</span></span>
<span id="cb40-2"><a aria-label="2"></a>paired_label <span class="ot">&lt;-</span> <span class="fu">paste0</span>(</span>
<span id="cb40-3"><a aria-label="3"></a>  <span class="st">"Paired t-test: t = "</span>,</span>
<span id="cb40-4"><a aria-label="4"></a>  <span class="fu">round</span>(maple_paired_model<span class="sc">$</span>statistic, <span class="dv">2</span>),</span>
<span id="cb40-5"><a aria-label="5"></a>  <span class="st">", df = "</span>, maple_paired_model<span class="sc">$</span>parameter, <span class="st">", "</span>,</span>
<span id="cb40-6"><a aria-label="6"></a>  scales<span class="sc">::</span><span class="fu">pvalue</span>(maple_paired_model<span class="sc">$</span>p.value,</span>
<span id="cb40-7"><a aria-label="7"></a>                 <span class="at">add_p =</span> <span class="cn">TRUE</span>)</span>
<span id="cb40-8"><a aria-label="8"></a>)</span>
<span id="cb40-9"><a aria-label="9"></a>paired_label</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Paired t-test: t = 9.38, df = 7, p&lt;0.001"</code></pre>
</div>
</div>
</div><div class="column" style="width:42%;">
<p>We’ll put the test result <strong>on the figure</strong>, pulled straight from the model — no retyping numbers.</p>
<ul>
<li><code>paste0()</code> glues text and numbers into one piece of text</li>
<li><code>maple_paired_model$statistic</code> → t, <code>$parameter</code> → df</li>
<li><code>scales::pvalue(..., add_p = TRUE)</code> writes “p&lt;0.001” instead of an ugly <code>3.3e-05</code></li>
</ul>
</div></div>
</section>

<section id="plotting-a-paired-result-the-figure" class="title-slide slide level1 center">
<h1>Plotting a Paired Result — the Figure</h1>
<div class="cell columns column-output-location">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a aria-label="1"></a><span class="co"># Each tree in grey + mean ± SE in color -----------------</span></span>
<span id="cb42-2"><a aria-label="2"></a>maple_results_plot <span class="ot">&lt;-</span> maple_tree_df <span class="sc">%&gt;%</span></span>
<span id="cb42-3"><a aria-label="3"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> side, <span class="at">y =</span> area)) <span class="sc">+</span></span>
<span id="cb42-4"><a aria-label="4"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">group =</span> tree), <span class="at">color =</span> <span class="st">"grey70"</span>) <span class="sc">+</span></span>
<span id="cb42-5"><a aria-label="5"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"grey70"</span>) <span class="sc">+</span></span>
<span id="cb42-6"><a aria-label="6"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_se, <span class="at">geom =</span> <span class="st">"errorbar"</span>,</span>
<span id="cb42-7"><a aria-label="7"></a>               <span class="at">width =</span> <span class="fl">0.1</span>, <span class="at">color =</span> <span class="st">"darkgreen"</span>) <span class="sc">+</span></span>
<span id="cb42-8"><a aria-label="8"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">"point"</span>,</span>
<span id="cb42-9"><a aria-label="9"></a>               <span class="at">size =</span> <span class="dv">4</span>, <span class="at">color =</span> <span class="st">"darkgreen"</span>) <span class="sc">+</span></span>
<span id="cb42-10"><a aria-label="10"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="st">"sunny"</span>, <span class="st">"shady"</span>)) <span class="sc">+</span></span>
<span id="cb42-11"><a aria-label="11"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Side of tree"</span>,</span>
<span id="cb42-12"><a aria-label="12"></a>       <span class="at">y =</span> <span class="st">"Mean leaf area (cm²)"</span>,</span>
<span id="cb42-13"><a aria-label="13"></a>       <span class="at">subtitle =</span> paired_label) <span class="sc">+</span></span>
<span id="cb42-14"><a aria-label="14"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb42-15"><a aria-label="15"></a>maple_results_plot</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="t_tests_2_lecture_files/figure-html/results-plot-1.png" alt="Grey lines join each tree's sunny and shady mean leaf area; a large green point with error bars shows the overall mean plus or minus one standard error for each side, higher on the shady side. The subtitle reports the paired t-test result." width="480"></p>
</figure>
</div>
</div>
</div></div>
<p>A box plot hides the pairing. This shows <strong>both</strong>: <strong>grey lines</strong> — every tree’s rise; <strong>green mean ± SE</strong> — the overall answer. <code>aes(group = tree)</code> sits only in <code>geom_line()</code>, so the green layers average over all trees.</p>
</section>

<section id="save-the-figure" class="title-slide slide level1 center">
<h1>Save the Figure</h1>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a aria-label="1"></a><span class="co"># Save the results plot ---------------------------------</span></span>
<span id="cb43-2"><a aria-label="2"></a><span class="fu">ggsave</span>(<span class="st">"figures/maple_paired_plot.png"</span>,</span>
<span id="cb43-3"><a aria-label="3"></a>       <span class="at">plot =</span> maple_results_plot,</span>
<span id="cb43-4"><a aria-label="4"></a>       <span class="at">width =</span> <span class="dv">5</span>, <span class="at">height =</span> <span class="dv">4</span>, <span class="at">dpi =</span> <span class="dv">300</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div><div class="column" style="width:45%;">
<ul>
<li>Goes into your <code>figures/</code> folder</li>
<li><code>dpi = 300</code> is publication quality</li>
<li>The subtitle updates itself if the data change</li>
</ul>
</div></div>
</section>

<section id="reporting-a-paired-result" class="title-slide slide level1 center">
<h1>Reporting a Paired Result</h1>
<div class="columns">
<div class="column" style="width:55%;">
<p><strong>The template:</strong></p>
<blockquote>
<p><em>[Finding] (paired t-test: t(df) = X.XX, p = X.XXX; mean difference = X.X units).</em></p>
</blockquote>
<p><strong>Our sugar maples:</strong></p>
<blockquote>
<p><em>Shady-side leaves were significantly larger than sunny-side leaves on the same tree (paired t-test: t(7) = 9.38, p &lt; 0.001; mean difference = 44.1 cm²).</em></p>
</blockquote>
<p><strong>For the two-sample version</strong>, the test name changes and there’s no “mean difference” — give the two means instead.</p>
</div><div class="column" style="width:45%;">
<p><strong>Where each number comes from:</strong></p>
<table class="caption-top">
<colgroup>
<col style="width: 40%">
<col style="width: 60%">
</colgroup>
<thead>
<tr class="header">
<th>In the sentence</th>
<th>In the output</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>t(7)</td>
<td><code>t =</code> and <code>df =</code></td>
</tr>
<tr class="even">
<td>p &lt; 0.001</td>
<td><code>p-value =</code> (tiny)</td>
</tr>
<tr class="odd">
<td>mean difference</td>
<td><code>mean difference</code> at the bottom</td>
</tr>
</tbody>
</table>
<p><strong>Always say which test</strong> — “t-test” alone doesn’t tell the reader whether the data were paired.</p>
</div></div>
</section>

<section id="backup-plan-rank-based-tests" class="title-slide slide level1 center">
<h1>Backup Plan: Rank-Based Tests</h1>
<div class="columns">
<div class="column" style="width:55%;">
<p>When the QQ plot and Shapiro-Wilk say the data are <strong>clearly not normal</strong>, use a test on <strong>ranks</strong> instead — the smallest value becomes 1, the next 2, and so on.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a aria-label="1"></a><span class="co"># Mann-Whitney U: two-sample partner --------------------</span></span>
<span id="cb44-2"><a aria-label="2"></a><span class="fu">wilcox.test</span>(area <span class="sc">~</span> side, <span class="at">data =</span> maple_tree_df)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon rank sum exact test

data:  area by side
W = 50, p-value = 0.06496
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a aria-label="1"></a><span class="co"># Wilcoxon signed-rank: paired partner ------------------</span></span>
<span id="cb46-2"><a aria-label="2"></a><span class="fu">wilcox.test</span>(maple_wide_df<span class="sc">$</span>shady, maple_wide_df<span class="sc">$</span>sunny,</span>
<span id="cb46-3"><a aria-label="3"></a>            <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon signed rank exact test

data:  maple_wide_df$shady and maple_wide_df$sunny
V = 36, p-value = 0.007813
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div>
</div><div class="column" style="width:45%;">
<ul>
<li>Ranks ignore how far apart values are — an outlier is just “the biggest”</li>
<li>No normality needed</li>
<li>R calls both <code>wilcox.test()</code>; the statistic is <strong>W</strong> or <strong>V</strong>, not <em>t</em></li>
</ul>
<p><strong>Look what happened:</strong></p>
<ul>
<li><strong>Mann-Whitney just misses</strong> (<em>p</em> a little above 0.05) where the two-sample t-test just made it — the power you give up by using ranks</li>
<li><strong>Signed-rank still finds the effect.</strong> V = 36 is the biggest possible for 8 trees — every tree went the same way</li>
</ul>
</div></div>
</section>

<section id="choosing-a-test" class="title-slide slide level1 center scrollable">
<h1>Choosing a Test</h1>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 30%">
<col style="width: 35%">
<col style="width: 35%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Data roughly <strong>normal</strong></th>
<th>Data clearly <strong>not normal</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Two independent groups</strong></td>
<td>Welch’s two-sample t-test</td>
<td>Mann-Whitney U</td>
</tr>
<tr class="even">
<td><strong>Paired</strong> (natural partners)</td>
<td>Paired t-test</td>
<td>Wilcoxon signed-rank</td>
</tr>
</tbody>
</table>
<ol type="1">
<li><strong>Design first:</strong> paired or independent?</li>
<li><strong>Check the assumptions:</strong> each group (two-sample) or the <strong>differences</strong> (paired)</li>
<li><strong>Then</strong> run the test you chose — and say why in your report</li>
</ol>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>Normal enough? Use the t-test.</strong> It uses the actual measurements, so it has more power. Rank tests are the backup, not the default.</p>
</div>
</div>
</div>
</section>

<section id="activity-10-parts-712-then-part-b" class="title-slide slide level1 center">
<h1>→ ACTIVITY 10 Parts 7–12, then Part B</h1>
<div class="activitybanner">
<p><strong>🛑 Do Activity Parts 7–12 now, then start Part B</strong></p>
<p>Average the sugar maple leaves per tree and side, check the assumptions, run the two-sample and the paired t-test, compare them, make the results plot, write the sentences, and run the rank-based tests. Then Part B: the whole workflow on sugar maple <strong>leaf mass</strong> — that is what you hand in.</p>
</div>
</section>

<section id="what-we-learned-today" class="title-slide slide level1 center">
<h1>What We Learned Today</h1>
<div class="columns">
<div class="column" style="width:60%;">
<ul>
<li><strong>Read</strong> <code>t.test()</code> output: t, df, <em>p</em>, CI, means → decide → report</li>
<li><strong>Pseudoreplication:</strong> many leaves from one tree-side are <strong>not</strong> many data points — they inflate <code>df</code>, and with uneven sampling they can flip the difference’s <strong>sign</strong></li>
<li><strong>The fix is one <code>summarize()</code> at the top</strong> — same <code>leaf_df</code>, same <code>mass_g</code>, rerun everything below unchanged</li>
<li><strong>Check → decide → test:</strong> each group for two-sample, the <strong>differences</strong> for paired</li>
<li><strong>Paired vs.&nbsp;two-sample:</strong> the design decides — pairing removes tree-to-tree noise</li>
<li><strong>Show it:</strong> lines per tree + mean ± SE, with the test in the subtitle</li>
<li><strong>Backup:</strong> Mann-Whitney U (two-sample), Wilcoxon signed-rank (paired)</li>
</ul>
</div><div class="column" style="width:40%;">
<p><strong>R skills:</strong></p>
<ul>
<li><code>t.test(y ~ group, data, var.equal = FALSE)</code></li>
<li><code>t.test(a, b, paired = TRUE)</code></li>
<li><code>group_by(id, group) %&gt;% summarize()</code> — kill pseudoreplication</li>
<li><code>pivot_wider(names_from, values_from)</code></li>
<li><code>geom_line(aes(group = tree))</code></li>
<li><code>wilcox.test()</code></li>
</ul>
<p><strong>Up next — Lecture 11:</strong> linear regression</p>
</div></div>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': true,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        // Bounds for smallest/largest possible scale to apply to content
        minScale: 0.2,

        maxScale: 2,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/wlperry\.github\.io\/umd_datasci");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>