<!DOCTYPE html>
<html lang="en"><head>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.36">

  <meta name="author" content="Bill Perry">
  <title>UMD Biostatistics – Lecture 05: Probability and Statistical Inference</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-b88c2fe81f1ff78e74849ca62ba99059.css">
  <link rel="stylesheet" href="../../css/lecture.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
<meta property="og:title" content="Lecture 05: Probability and Statistical Inference – UMD Biostatistics">
<meta property="og:site_name" content="UMD Biostatistics">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Lecture 05: Probability and Statistical Inference</h1>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Bill Perry 
</div>
</div>
</div>

</section>
<section id="lecture-4-review" class="title-slide slide level1 center">
<h1><strong>Lecture 4: Review</strong></h1>
<div class="columns">
<div class="column" style="width:60%;">
<ul>
<li>Introduction to histograms or frequency distributions</li>
<li>Probability Distribution Functions (PDF)
<ul>
<li>Z scores and T scores</li>
</ul></li>
<li>Tests of means using T-Tests
<ul>
<li><p>one sample</p></li>
<li><p>two sample</p></li>
</ul></li>
</ul>
</div><div class="column" style="width:40%;">
<p><img data-src="images/clipboard-536528302.png" width="241" height="330"></p>
</div></div>
<ul>
<li>Tests of means using T-Tests
<ul>
<li>one sample - is the sample mean different from a hypothesized mean?</li>
<li>two sample - are the sample means from two samples the same or different?</li>
</ul></li>
<li>for Two sample T-tests the df = n1+ n2 -2 = 8+8-2=14</li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  side  mean_length sd_length se_length count
  &lt;chr&gt;       &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;int&gt;
1 shady        17.6      2.51     0.886     8
2 sunny        16.2      2.64     0.934     8</code></pre>
</div>
</div>
</section>

<section>
<section id="lecture-5-probability-and-statistical-inference" class="title-slide slide level1 center">
<h1><strong>Lecture 5: Probability and Statistical Inference</strong></h1>

</section>
<div class="columns">
<div class="column" style="width:60%;">
<h3 id="the-goals-for-today"><strong>The goals for today</strong></h3>
<ul>
<li>Statistical inference fundamentals</li>
<li>Hypothesis testing principles</li>
<li>T Distributions</li>
<li>One sample T Test</li>
<li>Two sample T Test</li>
<li>Paired T Test</li>
<li>Assumption tests</li>
</ul>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="05_01_lecture_powerpoint_files/figure-revealjs/unnamed-chunk-2-1.png" width="480"></p>
</figure>
</div>
</div>
</div>
</div>
</div></section>
<section id="lecture-5-probability-and-statistical-inference-1" class="title-slide slide level1 center">
<h1><strong>Lecture 5: Probability and Statistical Inference</strong></h1>
<div class="columns">
<div class="column" style="width:60%;">
<p>The goals for today</p>
<ul>
<li>Statistical inference fundamentals</li>
<li>Hypothesis testing principles</li>
<li>T Distributions</li>
<li>One sample T Test</li>
<li>Two sample T Test</li>
<li>Paired T Test</li>
</ul>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="05_01_lecture_powerpoint_files/figure-revealjs/unnamed-chunk-3-1.png" width="480"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>

<section id="lecture-5-one-tailed-questions" class="title-slide slide level1 center">
<h1><strong>Lecture 5:</strong> One-tailed Questions</h1>
<div class="columns">
<div class="column" style="width:60%;">
<p>One-tailed questions: area of distribution left or (right) of a certain value for a one sample test</p>
<ul>
<li>n=8 (df=7) - 95% of the observations found left</li>
<li>t= 1.895 (5% are outside)</li>
</ul>
<p><img data-src="images/clipboard-1822465473.png" width="267" height="198"></p>
</div><div class="column" style="width:40%;">
<p><img data-src="images/clipboard-4103165911.png" width="609"> xxxx</p>
</div></div>
</section>

<section id="lecture-5-two-tailed-questions" class="title-slide slide level1 center">
<h1><strong>Lecture 5:</strong> Two-tailed Questions</h1>
<div class="columns">
<div class="column" style="width:60%;">
<p>Two-tailed questions refer to area between certain values</p>
<ul>
<li>n= 8 (df=7), 95% of the observations are between</li>
<li>t=-2.365 and t=2.365 (2.5% are outside on each side)</li>
<li>One tailed was t= 1.895 (5% are outside)</li>
</ul>
<p><img data-src="images/clipboard-2234740159.png" width="200" height="150"></p>
</div><div class="column" style="width:40%;">
<p><img data-src="images/clipboard-1746531278.png" width="675"></p>
</div></div>
</section>

<section id="lecture-5-calculating-ci-example" class="title-slide slide level1 center">
<h1><strong>Lecture 5:</strong> Calculating CI Example</h1>
<div class="columns">
<div class="column" style="width:60%;">
<p>Let’s calculate CIs again:</p>
<p>Use two-sided test</p>
<ul>
<li><span class="math inline">\(\text{CI} = \bar{y} \pm t \cdot \frac{s}{\sqrt{n}}\)</span></li>
<li>95% CI Sample A: = 17.6 ± 2.365 * (2.51/(8^0.5)) = +/- 2.098746</li>
<li>The 95% CI is between 15.50 and 19.70</li>
<li>“The 95% CI for the population mean from sample A is 17.6 ± 2.1</li>
</ul>
</div><div class="column" style="width:40%;">
<p><img data-src="images/clipboard-1746531278.png" width="675"></p>
</div></div>
</section>

<section id="lecture-5-applications-of-t-distribution" class="title-slide slide level1 center">
<h1><strong>Lecture 5:</strong> Applications of t-distribution</h1>
<p>So:</p>
<ul>
<li>Can assess confidence that population mean is within a certain range</li>
<li>Can use t distribution to ask questions like:
<ul>
<li>“What is probability of getting sample with mean = ȳ<br>
from population with mean = µ?” (1 sample t-test)</li>
<li>“What is the probability that two samples came from<br>
the same population?” (2 sample t-test)</li>
</ul></li>
</ul>
</section>

<section>
<section id="lecture-5-one-sample-t-test" class="title-slide slide level1 center">
<h1><strong>Lecture 5:</strong> One Sample T-Test</h1>
<p>We want to test if the mean needle length on one side differs from 15mm.</p>
</section>
<h3 id="activity-define-hypotheses-and-identify-assumptions"><strong>Activity: Define hypotheses and identify assumptions</strong></h3>
<p>H₀: μ = 15 (The mean needle length on shade side is 15mm)</p>
<p>H₁: μ ≠ 15 (The mean needle length on shade side is not 240mm)</p>
<h3 id="assumptions-for-t-test">Assumptions for t-test:</h3>
<ol type="1">
<li>Data is normally distributed</li>
<li>Observations are independent</li>
<li>No significant outliers</li>
</ol></section>
<section id="assumptions-in-r---qqplots-from-car" class="title-slide slide level1 center">
<h1>Assumptions in R - qqplots from car</h1>
<div class="cell" data-exercise="true">

<div class="cell-output cell-output-stdout">
<pre><code>[1]  8 11</code></pre>
</div>
</div>
<img data-src="05_01_lecture_powerpoint_files/figure-revealjs/test_assumptions-1.png" width="960" class="r-stretch"></section>

<section>
<section id="statistical-test-of-normality" class="title-slide slide level1 center">
<h1>Statistical Test of Normality</h1>

</section>
<h3 id="shapiro-wilk-test">Shapiro-Wilk test</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  ps_df$length_mm
W = 0.92754, p-value = 0.2228</code></pre>
</div>
</div></section>
<section id="checking-for-outliers" class="title-slide slide level1 center">
<h1>Checking for Outliers</h1>

<img data-src="05_01_lecture_powerpoint_files/figure-revealjs/unnamed-chunk-5-1.png" width="960" class="r-stretch"></section>

<section id="practice-exercise-1-one-sample-t-test" class="title-slide slide level1 center">
<h1>Practice Exercise 1: One-Sample t-Test</h1>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Practice Exercise 1: One-Sample t-Test</strong></p>
</div>
<div class="callout-content">
<p>Let’s perform a one-sample t-test to determine if the mean needle length on the shady side differs from 15 mm:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Mean: 17.6 mm</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  ps_shady_df$length_mm
t = 2.9414, df = 7, p-value = 0.02167
alternative hypothesis: true mean is not equal to 15
95 percent confidence interval:
 15.51092 19.70030
sample estimates:
mean of x 
 17.60561 </code></pre>
</div>
</div>
<p>Interpret this test result by answering these questions:</p>
<ol type="1">
<li>What was the null hypothesis?</li>
<li>What was the alternative hypothesis?</li>
<li>What does the p-value tell us?</li>
<li>Should we reject or fail to reject the null hypothesis at α = 0.05?</li>
<li>What is the practical interpretation of this result for botanists?</li>
</ol>
</div>
</div>
</div>
</section>

<section id="lecture-5-hypothesis-testing-framework" class="title-slide slide level1 center">
<h1><strong>Lecture 5:</strong> Hypothesis Testing Framework</h1>
<div class="columns">
<div class="column" style="width:60%;">
<p>Hypothesis testing is a systematic way to evaluate research questions using data.</p>
<p><strong>Key components:</strong></p>
<ol type="1">
<li><strong>Null hypothesis (Ho)</strong>: Typically assumes “no effect” or “no difference”</li>
<li><strong>Alternative hypothesis (Ha)</strong>: The claim we’re trying to support</li>
<li><strong>Statistical test</strong>: Method for evaluating evidence against H₀</li>
<li><strong>P-value</strong>: Probability of observing our results (or more extreme) if H₀ is true</li>
<li><strong>Significance level (α)</strong>: Threshold for rejecting H₀, typically 0.05</li>
</ol>
<p><strong>Decision rule</strong>: Reject Ho if p-value less than α or shorthand p &lt; 0.05</p>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="05_01_lecture_powerpoint_files/figure-revealjs/unnamed-chunk-7-1.png" width="480"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>

<section id="lecture-5-hypothesis-testing" class="title-slide slide level1 center">
<h1><strong>Lecture 5:</strong> Hypothesis Testing</h1>
<div class="columns">
<div class="column" style="width:60%;">
<p>Hypothesis testing is a systematic way to evaluate research questions using data.</p>
<p><strong>Key components:</strong></p>
<ol type="1">
<li><strong>Null hypothesis (H₀)</strong>: Typically assumes “no effect” or “no difference”</li>
<li><strong>Alternative hypothesis (Hₐ)</strong>: The claim we’re trying to support</li>
<li><strong>Statistical test</strong>: Method for evaluating evidence against H₀</li>
<li><strong>P-value</strong>: Probability of observing our results (or more extreme) if H₀ is true</li>
<li><strong>Significance level (α)</strong>: Threshold for rejecting H₀, typically 0.05</li>
</ol>
<p><strong>Decision rule</strong>: Reject H₀ if p-value &lt; α</p>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="05_01_lecture_powerpoint_files/figure-revealjs/unnamed-chunk-8-1.png" width="480"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>

<section id="lecture-5-interpreting-one-sample-t-test-results" class="title-slide slide level1 center">
<h1>Lecture 5: Interpreting One-Sample T-Test Results</h1>
<p><strong>Activity: Interpret the t-test results</strong></p>
<ul>
<li>What does the p-value tell us?</li>
<li>Should we reject or fail to reject the null hypothesis?</li>
</ul>
<p><strong>How to report this result in a scientific paper:</strong></p>
<p>“A one-sample t-test at α=0.05 showed that the mean needle length (… mm, SD = …) [was/was not] significantly different from the expected 15 mm, t(…) = …, p = …”</p>
</section>

<section id="lecture-5-two-sample-t-tests-introduction" class="title-slide slide level1 center">
<h1><strong>Lecture 5:</strong> Two Sample T-Tests Introduction</h1>
<div class="columns">
<div class="column" style="width:60%;">
<p>For example</p>
<ul>
<li>what is probability that population X is the same as population Y?</li>
<li>How would you assess this question using what we learned?</li>
<li>This is what we will do with the needle length again…</li>
</ul>
</div><div class="column" style="width:40%;">
<p><img data-src="images/two_branches.jpg" width="204"></p>
</div></div>
</section>

<section id="lecture-5-comparing-two-samples" class="title-slide slide level1 center">
<h1><strong>Lecture 5:</strong> Comparing Two Samples</h1>
<div class="columns">
<div class="column" style="width:60%;">
<p>For example</p>
<ul>
<li>what is probability that population X is the same as population Y?</li>
</ul>
<p>How would you assess this question using what we learned?</p>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="05_01_lecture_powerpoint_files/figure-revealjs/unnamed-chunk-9-1.png" width="480"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>

<section id="practice-exercise-2-formulating-hypotheses" class="title-slide slide level1 center">
<h1>Practice Exercise 2: Formulating Hypotheses</h1>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Practice Exercise 2: Formulating Hypotheses</strong></p>
</div>
<div class="callout-content">
<p>For the following research questions about needle lengths write the null and alternative hypotheses:</p>
<ol type="1">
<li>Are needle lengths on shady and sunny sides different?</li>
</ol>
<p>What are the hypotheses?</p>
<p>Ho =</p>
<p>Ha =</p>
</div>
</div>
</div>
</section>

<section>
<section id="lecture-5-two-sample-t-test-framework" class="title-slide slide level1 center">
<h1><strong>Lecture 5:</strong> Two-Sample T-Test Framework</h1>
<p>Now, let’s compare needles lengths from the two sides</p>
<p>Question: <strong>Is there a significant difference in needle length between the sides?</strong></p>
<p>This requires a two-sample t-test.</p>
<p>Two-sample t-test compares means from two independent groups.</p>
</section>
<h3 id="t-fracbarx_1---barx_2s_psqrtfrac1n_1-frac1n_2"><span class="math inline">\(t = \frac{\bar{x}_1 - \bar{x}_2}{S_p\sqrt{\frac{1}{n_1} + \frac{1}{n_2}}}\)</span></h3>
<h3 id="where">where:</h3>
<ul>
<li>x̄₁ and x̄₂: These represent the sample means of the two groups you’re comparing</li>
<li>s²ₚ: This is the pooled variance, calculated as: s²ₚ = [(n₁ - 1)s₁² + (n₂ - 1)s₂²] / (n₁ + n₂ - 2), where s₁² and s₂² are the sample variances of the two groups.</li>
<li><strong>n₁ and n₂:</strong> These are the sample sizes of the two groups.</li>
<li><strong>√(1/n₁ + 1/n₂):</strong> This represents the pooled standard error.</li>
</ul>
<h3 id="t-fracsignalnoise"><span class="math inline">\(t = \frac{SIGNAL}{NOISE}\)</span></h3></section>
<section id="practice-exercise-3-summary-statistics" class="title-slide slide level1 center">
<h1>Practice Exercise 3: Summary Statistics</h1>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Practice Exercise 3: <strong>Calculate summary statistics grouped by lake</strong></strong></p>
</div>
<div class="callout-content">
<p>Before conducting the test, we need to understand the data for each group.</p>
<ol type="1">
<li><p>You need this and the graph to see what is going on ….</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  side  mean_length sd_length     n se_length
  &lt;chr&gt;       &lt;dbl&gt;     &lt;dbl&gt; &lt;int&gt;     &lt;dbl&gt;
1 shady        17.6      2.51     8     0.886
2 sunny        16.2      2.64     8     0.934</code></pre>
</div>
</div></li>
</ol>
</div>
</div>
</div>
</section>

<section id="practice-exercise-4-effect-size" class="title-slide slide level1 center">
<h1>Practice Exercise 4: Effect Size</h1>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Practice Exercise 4: Effect size</strong></p>
</div>
<div class="callout-content">
<p>We could also look at the difference in means… some cool code here</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  difference
       &lt;dbl&gt;
1       1.45</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>

<section id="practice-exercise-5-ggplot-summary-statistics" class="title-slide slide level1 center">
<h1>Practice Exercise 5: ggplot Summary Statistics</h1>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Practice Exercise 5: Using GGPLOT to get summary plot</strong></p>
</div>
<div class="callout-content">
<p>GGplot also has code to make the mean and standard error plots we are interested in along with a lot of others</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="05_01_lecture_powerpoint_files/figure-revealjs/unnamed-chunk-12-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>

<section id="lecture-5-testing-assumptions-for-two-sample-t-test" class="title-slide slide level1 center">
<h1><strong>Lecture 5:</strong> Testing Assumptions for Two-Sample T-Test</h1>
<p>For a two-sample t-test, we need to check:</p>
<ol type="1">
<li>Normality within each group</li>
<li>Equal variances between groups (for standard t-test)</li>
<li>Independent observations</li>
</ol>
<p>If assumptions are violated:</p>
<ul>
<li>Welch’s t-test (unequal variances)</li>
<li>Non-parametric alternatives (Mann-Whitney U test)</li>
</ul>
</section>

<section id="practice-exercise-6-separate-group-data" class="title-slide slide level1 center">
<h1>Practice Exercise 6: Separate Group Data</h1>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Practice Exercise 7: Test normality of sunny pine needle lengths</strong></p>
</div>
<div class="callout-content">
<p>Note you need to test each groups separately…</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
# Groups:   group, tree_no, tree_char [6]
  group                      tree_no tree_char side  length_mm
  &lt;chr&gt;                        &lt;dbl&gt; &lt;chr&gt;     &lt;chr&gt;     &lt;dbl&gt;
1 big_fat_fecund_female_fish       2 tree_2    shady      15.4
2 bill                             3 tree_3    shady      16.7
3 ciabatta                         5 tree_5    shady      19.1
4 fake_data                        8 tree_8    shady      17.4
5 five                             1 tree_1    shady      20.3
6 moose_walkin                     7 tree_7    shady      20.7</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
# Groups:   group, tree_no, tree_char [6]
  group                      tree_no tree_char side  length_mm
  &lt;chr&gt;                        &lt;dbl&gt; &lt;chr&gt;     &lt;chr&gt;     &lt;dbl&gt;
1 big_fat_fecund_female_fish       2 tree_2    sunny      13.2
2 bill                             3 tree_3    sunny      16.0
3 ciabatta                         5 tree_5    sunny      17.7
4 fake_data                        8 tree_8    sunny      13.0
5 five                             1 tree_1    sunny      19.9
6 moose_walkin                     7 tree_7    sunny      18.4</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>

<section id="practice-exercise-8-combined-normality-test" class="title-slide slide level1 center">
<h1>Practice Exercise 8: Combined Normality Test</h1>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Practice Exercise 8: Test Normality at one time</strong></p>
</div>
<div class="callout-content">
<p>There are always a lot of ways to do this in R</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  side  shapiro_stat shapiro_p_value normal_distribution
  &lt;chr&gt;        &lt;dbl&gt;           &lt;dbl&gt; &lt;chr&gt;              
1 shady        0.966           0.868 Normal             
2 sunny        0.900           0.289 Normal             </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>

<section id="practice-exercise-13-test-equal-variances" class="title-slide slide level1 center">
<h1>Practice Exercise 13: Test Equal Variances</h1>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Practice Exercise 13: Test equal variances</strong></p>
</div>
<div class="callout-content">
<p>Levenes test can be done on the original dataframe</p>
<p><strong>Note: the Levenes Test should be NOT SIGNIFICANT - What is the null hypothesis</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Levene's Test for Homogeneity of Variance:"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
      Df F value Pr(&gt;F)
group  1  0.2062 0.6567
      14               </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>

<section id="lecture-5-conducting-the-two-sample-t-test" class="title-slide slide level1 center">
<h1><strong>Lecture 5:</strong> Conducting the Two-Sample T-Test</h1>
<div class="columns">
<div class="column" style="width:60%;">
<p>Now we can compare the mean needle lengths between shady and sunny sides.</p>
<p>Ho: μ₁ = μ₂ (The needle lengths do not differ)</p>
<p>Ha: μ₁ ≠ μ₂ (The mean needle lengths differ - direction is not specified)</p>
<p>Calculate t-statistic manually (optional) - YOUR CODE HERE:</p>
<p>t = (mean1 - mean2) / sqrt((s1^2/n1) + (s2^2/n2))</p>
<p>Deciding between:</p>
<ul>
<li><strong>Standard t-test (equal variances)</strong></li>
<li>Welch’s t-test (unequal variances)</li>
</ul>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Standard two-sample t-test:"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  length_mm by side
t = 1.1279, df = 14, p-value = 0.2783
alternative hypothesis: true difference in means between group shady and group sunny is not equal to 0
95 percent confidence interval:
 -1.309330  4.214005
sample estimates:
mean in group shady mean in group sunny 
           17.60561            16.15328 </code></pre>
</div>
</div>
</div></div>
</section>

<section id="lecture-5-conducting-the-two-sample-t-test-1" class="title-slide slide level1 center">
<h1><strong>Lecture 5:</strong> Conducting the Two-Sample T-Test</h1>
<div class="columns">
<div class="column" style="width:60%;">
<p>Now we can compare the mean needle lengths between shady and sunny sides.</p>
<p>Ho: μ₁ = μ₂ (The needle lengths do not differ)</p>
<p>Ha: μ₁ ≠ μ₂ (The mean needle lengths differ - direction is not specified)</p>
<p>Calculate t-statistic manually (optional) - YOUR CODE HERE:</p>
<p>t = (mean1 - mean2) / sqrt((s1^2/n1) + (s2^2/n2))</p>
<p>Deciding between:</p>
<ul>
<li>Standard t-test (equal variances)</li>
<li><strong>Welches t-test (unequal variances)</strong></li>
</ul>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Welches two-sample t-test:"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  length_mm by side
t = 1.1279, df = 13.96, p-value = 0.2784
alternative hypothesis: true difference in means between group shady and group sunny is not equal to 0
95 percent confidence interval:
 -1.310069  4.214743
sample estimates:
mean in group shady mean in group sunny 
           17.60561            16.15328 </code></pre>
</div>
</div>
</div></div>
</section>

<section>
<section id="lecture-5-difference-between-a-two-sample-t-and-welchs-t-test" class="title-slide slide level1 center">
<h1><strong>Lecture 5:</strong> Difference between a Two-Sample T and Welch’s T Test</h1>

</section>
<section id="standard-t-test-students-t-test" class="slide level2">
<h2>Standard t-test (Student’s t-test)</h2>
<ul>
<li><strong>Assumes equal variances</strong> between the two groups being compared</li>
<li>Uses a <strong>pooled variance estimate</strong> that combines data from both group</li>
<li>Has <strong>higher statistical power</strong> when the equal variance assumption is met</li>
<li><strong>Degrees of freedom</strong> = n₁ + n₂ - 2</li>
</ul>
</section>
<section id="welchs-t-test" class="slide level2">
<h2>Welch’s t-test</h2>
<ul>
<li><strong>Does not assume equal variances</strong> between groups (also called the “unequal variances t-test”)</li>
<li>Uses <strong>separate variance estimates</strong> for each group</li>
<li>More <strong>robust</strong> when group variances are different</li>
<li>Uses a more complex <strong>degrees of freedom calculation</strong> (<strong>Welch-Satterthwaite equation</strong>) and decimal!!!</li>
<li><strong>Degrees of freedom</strong> are typically non-integer and usually smaller than the standard t-test</li>
</ul>
</section></section>
<section id="lecture-5-interpreting-two-sample-t-test-results" class="title-slide slide level1 center">
<h1><strong>Lecture 5:</strong> Interpreting Two-Sample T-Test Results</h1>
<div class="columns">
<div class="column" style="width:60%;">
<p><strong>Interpret the results of the two-sample t-test</strong></p>
<p>What can we conclude about the needle lengths on sunny vs shady sides?</p>
<p><strong>How to report this result in a scientific paper:</strong></p>
<p>“A two-tailed, two-sample t-test at α=0.05 showed [a significant/no significant] difference in needle length between sunny (M = …, SD = …) and shady (M = …, SD = …) sides of pine trees, t(…) = …, p = ….”</p>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="05_01_lecture_powerpoint_files/figure-revealjs/unnamed-chunk-16-1.png" width="480"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>

<section id="lecture-5-now-what-does-a-paired-t-test-tell-us" class="title-slide slide level1 center">
<h1><strong>Lecture 5:</strong> Now what does a paired T test tell us</h1>
<div class="columns">
<div class="column" style="width:60%;">
<p>Paired t-test:</p>
<p>Compares two measurements from the same subjects or matched pairs Tests whether the mean difference between paired observations equals zero Examples: before/after measurements on the same people, left vs right measurements, matched case-control studies Uses the differences between pairs as the data points Generally more powerful because it controls for individual variation</p>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Standard two-sample t-test:"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  ps_wide_df$sunny and ps_wide_df$shady
t = -2.7818, df = 7, p-value = 0.02723
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
 -2.6868652 -0.2178092
sample estimates:
mean difference 
      -1.452337 </code></pre>
</div>
</div>
</div></div>
</section>

<section id="lecture-5-what-is-going-on" class="title-slide slide level1 center">
<h1>Lecture 5: What is going on??</h1>
<p>Note that thee is a lot of variation within trees but the trend is the same</p>

<img data-src="05_01_lecture_powerpoint_files/figure-revealjs/unnamed-chunk-18-1.png" width="960" class="r-stretch"></section>

<section id="lecture-5-assumptions-of-parametric-tests" class="title-slide slide level1 center">
<h1><strong>Lecture 5:</strong> Assumptions of Parametric Tests</h1>
<p><strong>Common assumptions for t-tests:</strong></p>
<ol type="1">
<li>Normality: Data comes from normally distributed populations</li>
<li>Equal variances (for two-sample tests)</li>
<li>Independence: Observations are independent</li>
<li>No outliers: Extreme values can influence results</li>
</ol>
<p>What can we do if our data violates these assumptions?</p>
<p>Alternatives when assumptions are violated:</p>
<ul>
<li>Data transformation (log, square root, etc.)</li>
<li>Non-parametric tests</li>
<li>Robust statistical methods</li>
</ul>
</section>

<section id="lecture-5-summary-and-conclusions" class="title-slide slide level1 center">
<h1><strong>Lecture 5:</strong> Summary and Conclusions</h1>
<p>In this activity, we’ve:</p>
<ol type="1">
<li>Formulated hypotheses about pine needle length</li>
<li>Tested assumptions for parametric tests</li>
<li>Conducted one-sample and two-sample t-tests</li>
<li>Visualized data using appropriate methods</li>
<li>Learned how to interpret and report t-test results</li>
</ol>
<p><strong>Key takeaways:</strong></p>
<ul>
<li>Always check assumptions before conducting tests</li>
<li>Visualize your data to understand patterns</li>
<li>Report results comprehensively</li>
<li>Consider alternatives when assumptions are violated - non parametric tests…</li>
</ul>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/your-site-url\.github\.io");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>