{
  "hash": "e6c78c862d8925d036470eaf032a69d4",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lecture 18 - Class Activity: NMDS and PERMANOVA\"\nauthor: \"Bill Perry\"\nformat:\n  html:\n    output-file: \"18_02_class_activity_nmds_permanova.html\"\n  docx:\n    output-file: \"18_02_class_activity_nmds_permanova.docx\"\n---\n\n\n\n# Lecture 18: Non-metric Multidimensional Scaling (NMDS) and PERMANOVA\n\n## What is NMDS?\n\nNMDS (Non-metric Multidimensional Scaling) is an ordination technique\nthat: - Visualizes dissimilarity between objects in reduced dimensions -\nPreserves rank order of distances, not exact distances - Works well with\nnon-linear ecological relationships - Makes few assumptions about data\nstructure\n\n## When to Use NMDS\n\nUse NMDS when you have: - **Community data**: Species abundance or\npresence/absence matrices - **Non-linear relationships**: When PCA\nassumptions are violated - **Complex ecological gradients**: Multiple\nenvironmental factors affecting communities\n\n## Key Concepts of NMDS\n\n1.  **Dissimilarity matrices** instead of covariance\n2.  **Stress values** measure goodness of fit (\\<0.2 is acceptable)\n3.  **Iterative algorithm** to find optimal configuration\n4.  **No eigenvalues** - axes have no inherent meaning\n5.  **Rank-based** - preserves order, not exact distances\n\n::: {.callout-important appearance=\"simple\"}\n## Critical First Step\n\nAlways check your stress value! Stress \\< 0.1 is excellent, 0.1-0.2 is\ngood, \\> 0.2 is poor representation.\n:::\n\n# Part 1: Data Preparation and Exploration\n\n## Load and Prepare Data\n\nWe'll use the iris dataset for this analysis, treating it as if the\nmeasurements represent abundances of different \"species\" at different\n\"sites\".\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load iris data\niris_df <- read_csv(\"data/iris.csv\") %>%\n  clean_names()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 150 Columns: 5\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (1): species\ndbl (4): sepal_length, sepal_width, petal_length, petal_width\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\n# View data structure\nhead(iris_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  sepal_length sepal_width petal_length petal_width species\n         <dbl>       <dbl>        <dbl>       <dbl> <chr>  \n1          5.1         3.5          1.4         0.2 setosa \n2          4.9         3            1.4         0.2 setosa \n3          4.7         3.2          1.3         0.2 setosa \n4          4.6         3.1          1.5         0.2 setosa \n5          5           3.6          1.4         0.2 setosa \n6          5.4         3.9          1.7         0.4 setosa \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# For NMDS, we need just the numeric columns (our \"species\" data)\n# We'll keep species as our grouping variable\niris_species_df <- iris_df %>%\n  dplyr::select(species)\n\niris_numeric_df <- iris_df %>%\n  dplyr::select(-species)\n\n# Check the structure\nstr(iris_numeric_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [150 × 4] (S3: tbl_df/tbl/data.frame)\n $ sepal_length: num [1:150] 5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...\n $ sepal_width : num [1:150] 3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...\n $ petal_length: num [1:150] 1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...\n $ petal_width : num [1:150] 0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...\n```\n\n\n:::\n:::\n\n\n## Visualize the Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a pairs plot to see relationships\niris_pairs_plot <- iris_df %>%\n  dplyr::select(-species) %>%\n  pairs(main = \"Iris Measurements Relationships\")\n```\n\n::: {.cell-output-display}\n![](18_02_class_activity_files/figure-html/initial_plot-1.png){width=480}\n:::\n:::\n\n\n# Part 2: Running NMDS\n\n## Step 1: Calculate Distance Matrix\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate Bray-Curtis distance (common for ecological data)\n# For iris data, we'll use Euclidean distance since these are measurements\niris_dist <- dist(iris_numeric_df, method = \"euclidean\")\n\n# Check the first few distances\niris_dist[1:5]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5385165 0.5099020 0.6480741 0.1414214 0.6164414\n```\n\n\n:::\n:::\n\n\n## Step 2: Run NMDS\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Run NMDS with 2 dimensions\nset.seed(123)  # For reproducibility\niris_nmds_model <- metaMDS(iris_numeric_df, \n                           distance = \"euclidean\",\n                           k = 2,  # Number of dimensions\n                           trymax = 100)  # Maximum iterations\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRun 0 stress 0.02525035 \nRun 1 stress 0.04045544 \nRun 2 stress 0.03566855 \nRun 3 stress 0.0268287 \nRun 4 stress 0.03695952 \nRun 5 stress 0.03104439 \nRun 6 stress 0.02682881 \nRun 7 stress 0.03962709 \nRun 8 stress 0.03210416 \nRun 9 stress 0.04325555 \nRun 10 stress 0.02525031 \n... New best solution\n... Procrustes: rmse 1.741237e-05  max resid 7.129696e-05 \n... Similar to previous best\nRun 11 stress 0.02525038 \n... Procrustes: rmse 1.217807e-05  max resid 8.876481e-05 \n... Similar to previous best\nRun 12 stress 0.04000578 \nRun 13 stress 0.03552087 \nRun 14 stress 0.0309981 \nRun 15 stress 0.04078306 \nRun 16 stress 0.04008785 \nRun 17 stress 0.03197035 \nRun 18 stress 0.02525033 \n... Procrustes: rmse 5.481604e-06  max resid 2.712782e-05 \n... Similar to previous best\nRun 19 stress 0.02682875 \nRun 20 stress 0.03270101 \n*** Best solution repeated 3 times\n```\n\n\n:::\n\n```{.r .cell-code}\n# Check the results\niris_nmds_model\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nmetaMDS(comm = iris_numeric_df, distance = \"euclidean\", k = 2,      trymax = 100) \n\nglobal Multidimensional Scaling using monoMDS\n\nData:     iris_numeric_df \nDistance: euclidean \n\nDimensions: 2 \nStress:     0.02525031 \nStress type 1, weak ties\nBest solution was repeated 3 times in 20 tries\nThe best solution was from try 10 (random start)\nScaling: centring, PC rotation \nSpecies: expanded scores based on 'iris_numeric_df' \n```\n\n\n:::\n:::\n\n\n**Interpretation**: - Stress value:\n0.025 - This is\nexcellent\nrepresentation\n\n## Step 3: Extract NMDS Scores\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract NMDS scores for plotting\nnmds_scores_df <- as.data.frame(iris_nmds_model$points) %>%\n  rename(nmds1 = MDS1, nmds2 = MDS2) %>%\n  bind_cols(iris_species_df)\n\n# View the scores\nhead(nmds_scores_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      nmds1      nmds2 species\n1 -2.687311  0.2758924  setosa\n2 -2.717262 -0.1705943  setosa\n3 -2.882071 -0.1017541  setosa\n4 -2.746720 -0.2603709  setosa\n5 -2.730486  0.2902002  setosa\n6 -2.311408  0.6625723  setosa\n```\n\n\n:::\n:::\n\n\n## Step 4: Create NMDS Plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Basic NMDS plot\nnmds_basic_plot <- ggplot(nmds_scores_df, aes(x = nmds1, y = nmds2, color = species)) +\n  geom_point(size = 3, alpha = 0.8) +\n  labs(title = \"NMDS Ordination of Iris Data\",\n       subtitle = paste(\"Stress =\", round(iris_nmds_model$stress, 3)),\n       x = \"NMDS1\", \n       y = \"NMDS2\",\n       color = \"Species\") +\n  theme_minimal()\n\nnmds_basic_plot\n```\n\n::: {.cell-output-display}\n![](18_02_class_activity_files/figure-html/nmds_plot-1.png){width=480}\n:::\n:::\n\n\n## Step 5: Add Confidence Ellipses\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# NMDS plot with ellipses\nnmds_ellipse_plot <- ggplot(nmds_scores_df, aes(x = nmds1, y = nmds2, color = species)) +\n  geom_point(size = 3, alpha = 0.8) +\n  stat_ellipse(level = 0.95, size = 1) +\n  labs(title = \"NMDS Ordination with 95% Confidence Ellipses\",\n       subtitle = paste(\"Stress =\", round(iris_nmds_model$stress, 3)),\n       x = \"NMDS1\", \n       y = \"NMDS2\",\n       color = \"Species\") +\n  theme_minimal()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.\nℹ Please use `linewidth` instead.\n```\n\n\n:::\n\n```{.r .cell-code}\nnmds_ellipse_plot\n```\n\n::: {.cell-output-display}\n![](18_02_class_activity_files/figure-html/nmds_ellipse_plot-1.png){width=480}\n:::\n:::\n\n\n## Step 6: Stress Plot (Shepard Diagram)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create stress plot to evaluate fit\nstressplot(iris_nmds_model, main = \"Shepard Diagram: Ordination vs Original Distances\")\n```\n\n::: {.cell-output-display}\n![](18_02_class_activity_files/figure-html/stress_plot-1.png){width=480}\n:::\n:::\n\n\n# Part 3: PERMANOVA Analysis\n\n## What is PERMANOVA?\n\nPERMANOVA (Permutational Multivariate Analysis of Variance) tests\nwhether groups have different multivariate centroids using permutation\ntests.\n\n## Step 1: Run PERMANOVA\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Run PERMANOVA to test if species differ in multivariate space\nset.seed(456)\niris_permanova_model <- adonis2(iris_numeric_df ~ species, \n                                data = iris_df,\n                                method = \"euclidean\",\n                                permutations = 999)\n\n# View results\niris_permanova_model\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPermutation test for adonis under reduced model\nPermutation: free\nNumber of permutations: 999\n\nadonis2(formula = iris_numeric_df ~ species, data = iris_df, permutations = 999, method = \"euclidean\")\n          Df SumOfSqs      R2      F Pr(>F)    \nModel      2   592.07 0.86894 487.33  0.001 ***\nResidual 147    89.30 0.13106                  \nTotal    149   681.37 1.00000                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n**Interpretation**: - F-statistic:\n487.33 - R² (variance explained):\n0.869 - p-value:\n0.001\n\n## Step 2: Check Homogeneity of Dispersions\n\nBefore interpreting PERMANOVA, we need to check if groups have similar\nmultivariate spread.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Test homogeneity of multivariate dispersions\niris_dist_full <- dist(iris_numeric_df)\ndispersion_model <- betadisper(iris_dist_full, iris_df$species)\n\n# Test for differences in dispersion\ndispersion_test <- anova(dispersion_model)\ndispersion_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: Distances\n           Df  Sum Sq Mean Sq F value  Pr(>F)    \nGroups      2  2.9092 1.45458  10.748 4.4e-05 ***\nResiduals 147 19.8941 0.13533                    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n## Step 3: Visualize Dispersions\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot dispersions\nplot(dispersion_model, main = \"Multivariate Dispersion by Species\")\n```\n\n::: {.cell-output-display}\n![](18_02_class_activity_files/figure-html/dispersion_plot-1.png){width=480}\n:::\n:::\n\n\n## Step 4: Pairwise PERMANOVA\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Function for pairwise PERMANOVA comparisons\npairwise_permanova <- function(data_matrix, groups, distance_method = \"euclidean\") {\n  # Get unique group combinations\n  group_levels <- unique(groups)\n  comparisons <- combn(group_levels, 2)\n  \n  # Initialize results\n  results_df <- data.frame(\n    group1 = character(),\n    group2 = character(),\n    f_statistic = numeric(),\n    r_squared = numeric(),\n    p_value = numeric()\n  )\n  \n  # Run pairwise comparisons\n  for(i in 1:ncol(comparisons)) {\n    # Subset data\n    group1 <- comparisons[1, i]\n    group2 <- comparisons[2, i]\n    subset_indices <- which(groups %in% c(group1, group2))\n    \n    subset_data <- data_matrix[subset_indices, ]\n    subset_groups <- groups[subset_indices]\n    \n    # Run PERMANOVA\n    temp_result <- adonis2(subset_data ~ subset_groups, \n                          method = distance_method,\n                          permutations = 999)\n    \n    # Store results\n    results_df <- rbind(results_df, data.frame(\n      group1 = group1,\n      group2 = group2,\n      f_statistic = temp_result$F[1],\n      r_squared = temp_result$R2[1],\n      p_value = temp_result$\"Pr(>F)\"[1]\n    ))\n  }\n  \n  # Adjust p-values for multiple comparisons\n  results_df$p_adjusted <- p.adjust(results_df$p_value, method = \"bonferroni\")\n  \n  return(results_df)\n}\n\n# Run pairwise comparisons\npairwise_results_df <- pairwise_permanova(iris_numeric_df, iris_df$species)\npairwise_results_df\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      group1     group2 f_statistic r_squared p_value p_adjusted\n1     setosa versicolor    551.0039 0.8489994   0.001      0.003\n2     setosa  virginica    943.7992 0.9059320   0.001      0.003\n3 versicolor  virginica     86.7697 0.4696100   0.001      0.003\n```\n\n\n:::\n:::\n\n\n# Part 4: ANOSIM Analysis\n\n## What is ANOSIM?\n\nANOSIM (Analysis of Similarities) tests whether there is a significant\ndifference between groups using rank dissimilarities.\n\n## Step 1: Run ANOSIM\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Run ANOSIM\nset.seed(789)\niris_anosim_model <- anosim(iris_dist_full, iris_df$species, permutations = 999)\n\n# View results\niris_anosim_model\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nanosim(x = iris_dist_full, grouping = iris_df$species, permutations = 999) \nDissimilarity: euclidean \n\nANOSIM statistic R: 0.8794 \n      Significance: 0.001 \n\nPermutation: free\nNumber of permutations: 999\n```\n\n\n:::\n:::\n\n\n**Interpretation**: - R statistic:\n0.879 - p-value:\n0.001 - R close to 1 indicates strong separation\nbetween groups\n\n## Step 2: Plot ANOSIM Results\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot ANOSIM results\nplot(iris_anosim_model, main = \"ANOSIM Results: Distribution of Permuted R Statistics\")\n```\n\n::: {.cell-output-display}\n![](18_02_class_activity_files/figure-html/anosim_plot-1.png){width=480}\n:::\n:::\n\n\n# Part 5: Environmental Fitting (Optional)\n\nIf we had environmental variables, we could fit them to the ordination.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# For demonstration, let's use petal_length as an \"environmental\" variable\nenv_data_df <- data.frame(petal_length = iris_df$petal_length)\n\n# Fit environmental vector\nenv_fit_model <- envfit(iris_nmds_model, env_data_df, permutations = 999)\nenv_fit_model\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n***VECTORS\n\n                NMDS1    NMDS2     r2 Pr(>r)    \npetal_length  0.98205 -0.18862 0.9979  0.001 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\nPermutation: free\nNumber of permutations: 999\n```\n\n\n:::\n:::\n\n\n## Visualize Environmental Vectors\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract vector coordinates\nenv_coords_df <- as.data.frame(env_fit_model$vectors$arrows * 2)  # Scale for visibility\nenv_coords_df$variable <- rownames(env_coords_df)\n\n# NMDS plot with environmental vector\nnmds_env_plot <- ggplot(nmds_scores_df, aes(x = nmds1, y = nmds2, color = species)) +\n  geom_point(size = 3, alpha = 0.8) +\n  stat_ellipse(level = 0.95, size = 1, alpha = 0.3) +\n  geom_segment(data = env_coords_df,\n               aes(x = 0, y = 0, xend = NMDS1, yend = NMDS2),\n               arrow = arrow(length = unit(0.3, \"cm\")),\n               color = \"black\", size = 1) +\n  geom_text(data = env_coords_df,\n            aes(x = NMDS1 * 1.1, y = NMDS2 * 1.1, label = variable),\n            color = \"black\", size = 4) +\n  labs(title = \"NMDS with Environmental Vector\",\n       subtitle = paste(\"Stress =\", round(iris_nmds_model$stress, 3)),\n       x = \"NMDS1\", \n       y = \"NMDS2\",\n       color = \"Species\") +\n  theme_minimal()\n\nnmds_env_plot\n```\n\n::: {.cell-output-display}\n![](18_02_class_activity_files/figure-html/nmds_envfit_plot-1.png){width=480}\n:::\n:::\n\n\n# Summary Checklist for NMDS and PERMANOVA\n\n::: {.callout-tip appearance=\"simple\"}\n## Analysis Checklist\n\n1.  **Prepare your data** - ensure numeric matrix format\n2.  **Choose appropriate distance measure**\n    - Bray-Curtis for abundance data\n    - Euclidean for measurement data\n3.  **Run NMDS** with sufficient iterations\n4.  **Check stress value** - must be \\< 0.2\n5.  **Create ordination plots** with groups identified\n6.  **Test homogeneity of dispersions** before PERMANOVA\n7.  **Run PERMANOVA** to test group differences\n8.  **Consider ANOSIM** as complementary test\n9.  **Fit environmental variables** if available\n:::\n\n## Key Points to Remember\n\n- **NMDS preserves rank order** of distances, not exact values\n- **Stress \\< 0.2** is acceptable, \\< 0.1 is excellent\n- **PERMANOVA tests centroids**, ANOSIM tests overlap\n- **Check dispersion homogeneity** - violated assumption affects\n  interpretation\n- **Multiple comparisons** require p-value adjustment\n- **Axes have no inherent meaning** in NMDS (unlike PCA)\n- **Use appropriate distance measures** for your data type\n\n::: {.callout-important appearance=\"simple\"}\n## Key Takeaways from NMDS/PERMANOVA Analysis\n\n1.  **NMDS is flexible** - works with any distance measure and makes few\n    assumptions\n2.  **Stress indicates fit quality** - always report and check this\n    value\n3.  **PERMANOVA is powerful** but assumes homogeneous dispersions\n4.  **ANOSIM is complementary** - provides different perspective on\n    group separation\n5.  **Visualization is crucial** - always plot your ordination results\n6.  **Environmental fitting** helps interpret ecological patterns\n7.  **Permutation tests** avoid distributional assumptions\n\nRemember: NMDS is iterative and may find different solutions - always\nset a seed for reproducibility!\n:::",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}