<!DOCTYPE html>
<html lang="en"><head>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.36">

  <meta name="author" content="Bill Perry">
  <title>UMD Biostatistics – Lecture 11 - Single factor analysis of variance - ANOVA</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-b88c2fe81f1ff78e74849ca62ba99059.css">
  <link rel="stylesheet" href="../../css/lecture.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
<meta property="og:title" content="Lecture 11 - Single factor analysis of variance - ANOVA – UMD Biostatistics">
<meta property="og:site_name" content="UMD Biostatistics">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Lecture 11 - Single factor analysis of variance - ANOVA</h1>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Bill Perry 
</div>
</div>
</div>

</section>
<section>
<section id="lecture-11-review" class="title-slide slide level1 center">
<h1>Lecture 11: Review</h1>

</section>
<div class="columns">
<div class="column" style="width:60%;">
<h3 id="multiple-regression"><strong>Multiple Regression</strong></h3>
<ul>
<li>MLR model</li>
<li>Regression parameters</li>
<li>Analysis of variance</li>
<li>Null hypotheses</li>
<li>Explained variance</li>
<li>Assumptions and diagnostics</li>
<li>Collinearity</li>
<li>Interactions</li>
<li>Dummy variables</li>
<li>Model selection</li>
<li>Importance of predictors</li>
</ul>
</div><div class="column" style="width:40%;">
<p><img data-src="images/clipboard-2698541257.png" width="400"></p>
</div>
</div></section>
<section>
<section id="lecture-12-overview" class="title-slide slide level1 center">
<h1>Lecture 12: Overview</h1>

</section>
<div class="columns">
<div class="column" style="width:60%;">
<h3 id="anova">ANOVA</h3>
<p>Analysis of variance: single and to come multi-factor designs</p>
<ul>
<li>Predictor variables: fixed</li>
<li>ANOVA model</li>
<li>Analysis and partitioning of variance</li>
<li>Null hypothesis</li>
<li>Assumptions and diagnostics</li>
<li>Post F Tests - Tukey and others</li>
<li>Reporting the results</li>
<li>Mixed Model Anova - random effects</li>
</ul>
</div><div class="column" style="width:40%;">
<p>What if response continuous and predictor(s) categorical?</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Independent variable</th>
<th style="text-align: left;"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Dependent variable</strong></td>
<td style="text-align: left;"><strong>Continuous</strong></td>
<td style="text-align: left;"><strong>Categorical</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Continuous</strong></td>
<td style="text-align: left;">Regression</td>
<td style="text-align: left;">ANOVA</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Categorical</strong></td>
<td style="text-align: left;">Logistic regression</td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
</div>
</div></section>
<section>
<section id="lecture-12-anova-and-regression-connection" class="title-slide slide level1 center">
<h1><strong>Lecture 12:</strong> ANOVA and Regression Connection</h1>

</section>
<div class="columns">
<div class="column" style="width:60%;">
<h3 id="both-regression-and-anova">Both regression and ANOVA:</h3>
<ul>
<li>Partition the total variation in Y</li>
<li>Use F-tests for significance where one MS is divided by another</li>
</ul>
<h3 id="regression">Regression</h3>
<ul>
<li><strong>Form:</strong> <span class="math inline">\(Y = \beta_0 + \beta_1X + \varepsilon\)</span>
<ul>
<li><span class="math inline">\(Y\)</span> = outcome/response variable</li>
<li><span class="math inline">\(\beta_0\)</span> = intercept (value of Y when X = 0)</li>
<li><span class="math inline">\(\beta_1\)</span> = slope (change in Y per unit increase in X)</li>
<li><span class="math inline">\(X\)</span> = predictor/independent variable</li>
<li><span class="math inline">\(\varepsilon\)</span> = error term</li>
</ul></li>
<li><strong>Test:</strong> <span class="math inline">\(H_0: \beta_1 = 0\)</span>
<ul>
<li>Tests whether slope equals zero</li>
<li>Rejecting means X significantly predicts Y</li>
</ul></li>
</ul>
</div><div class="column" style="width:40%;">
<h3 id="anova-1">ANOVA</h3>
<ul>
<li><strong>Form:</strong> <span class="math inline">\(Y_{ij} = \mu + A_i + \varepsilon_{ij}\)</span>
<ul>
<li><span class="math inline">\(Y_{ij}\)</span> = observation for person j in group i</li>
<li><span class="math inline">\(\mu\)</span> = grand mean across all groups</li>
<li><span class="math inline">\(A_i\)</span> = effect of group i</li>
<li><span class="math inline">\(\varepsilon_{ij}\)</span> = error term</li>
</ul></li>
<li><strong>Test:</strong> <span class="math inline">\(H_0: \mu_1 = \mu_2 = ... = \mu_k\)</span>
<ul>
<li>Tests whether all group means are equal</li>
<li>Rejecting means at least one group differs</li>
</ul></li>
</ul>
</div>
</div></section>
<section>
<section id="lecture-12-anova-partitioning" class="title-slide slide level1 center">
<h1><strong>Lecture 12:</strong> ANOVA Partitioning</h1>

</section>
<div class="columns">
<div class="column" style="width:60%;">
<h3 id="general-method-for-partitioning-variation-in-continuous-dependent-variable">General method for partitioning variation in continuous dependent variable</h3>
<ul>
<li>One or more continuous (and categorical) predictors:
<ul>
<li>regression</li>
</ul></li>
<li>One or more categorical predictors:
<ul>
<li>ANOVA</li>
</ul></li>
<li>Categorical predictor variables:
<ul>
<li>groups or experimental treatments</li>
</ul></li>
</ul>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="11_01_lecture_powerpoint_files/figure-revealjs/unnamed-chunk-1-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</div></section>
<section id="lecture-12-anova-as-regression" class="title-slide slide level1 center">
<h1><strong>Lecture 12:</strong> ANOVA as Regression</h1>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>ANOVA as Regression</strong></p>
</div>
<div class="callout-content">
<p>With one categorical variable, ANOVA is equivalent to regression with dummy variables.</p>
<p>In fact when we will run ANOVAs we will use he same code as for regression!</p>
<p>regression: model &lt;- lm(response ~ predictor, data = df)<br>
anova: model &lt;- lm(response ~ factor, data = df)</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="11_01_lecture_powerpoint_files/figure-revealjs/regression-anova-1.png" width="384"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>

<section>
<section id="lecture-12-anova-goals" class="title-slide slide level1 center">
<h1><strong>Lecture 12:</strong> ANOVA Goals</h1>

</section>
<div class="columns">
<div class="column" style="width:60%;">
<h3 id="anova-aims-to-compare-means-of-groups">ANOVA aims to compare means of groups:</h3>
<ul>
<li>Contribution of predictors + “error” to variability</li>
<li>Test H₀ that population (random effects) or group (fixed effects) means are equal</li>
<li>Single factor (1-way) and multifactor (2-, 3-way designs)
<ul>
<li>Single factor: one factor with more than two levels</li>
</ul></li>
<li>Multifactor:
<ul>
<li>two or three factors with two or more levels each</li>
<li>Examines variation due to factors <strong>AND</strong> their interaction</li>
</ul></li>
</ul>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="11_01_lecture_powerpoint_files/figure-revealjs/unnamed-chunk-2-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</div></section>
<section id="lecture-12-analysis-of-variance" class="title-slide slide level1 center">
<h1><strong>Lecture 12:</strong> Analysis of Variance</h1>
<div class="columns">
<div class="column" style="width:60%;">
<p><em>Analysis of variance</em> - the most powerful approach known for simultaneously testing if the means of k groups are equal - works by assessing whether individuals chosen from different groups are, on average, more different than individuals chosen from the same group.</p>
<p>The null hypothesis of ANOVA is that the population means μᵢ are the same for all treatments.</p>
<ul>
<li><strong>H₀</strong>: μ₁ = μ₂ = … = μₖ</li>
<li><strong>H₁</strong>: At least one μᵢ is different from the others.</li>
</ul>
<p>Rejecting H₀ in ANOVA</p>
<ul>
<li>evidence that the mean of at least one group is different from the others<br>
</li>
<li>does not indicate <em>which</em> means differ</li>
</ul>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="11_01_lecture_powerpoint_files/figure-revealjs/unnamed-chunk-3-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>

<section id="lecture-12-anova-logic" class="title-slide slide level1 center">
<h1><strong>Lecture 12:</strong> ANOVA Logic</h1>
<div class="columns">
<div class="column" style="width:60%;">
<p>Even if all groups had the same true mean, the data would likely show different sample means for each group due to sampling error.</p>
<p>The key insight of ANOVA is that we can estimate how much variation among group means ought to be present from sampling error alone if the null hypothesis is true.</p>
<p>ANOVA lets us determine whether there is more variance among the sample means than we would expect by chance alone. If so, then we can infer that there are real differences among the population means.</p>
<p>Two key measures of variation are calculated and compared:</p>
<ol type="1">
<li><strong>Group mean square (MSgroups)</strong> - variation among subjects from different groups</li>
<li><strong>Error mean square (MSerror)</strong> - variation among subjects within the same group</li>
</ol>
<p>The comparison is done with an F-ratio:</p>
<p><span class="math display">\[F = \frac{MS_{groups}}{MS_{error}}\]</span></p>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="11_01_lecture_powerpoint_files/figure-revealjs/unnamed-chunk-4-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>

<section id="lecture-12-partitioning-the-sum-of-squares" class="title-slide slide level1 center">
<h1><strong>Lecture 12:</strong> Partitioning the Sum of Squares</h1>
<div class="columns">
<div class="column" style="width:60%;">
<p>The total variation in Y can be expressed as a sum of squares:</p>
<p><span class="math inline">\(SS_{total} = \sum_{i=1}^{a}\sum_{j=1}^{n}(Y_{ij} - \bar{Y})^2\)</span></p>
<p>This can be partitioned into two components:</p>
<ol type="1">
<li><p><strong>Among Groups (Treatment)</strong>: <span class="math inline">\(SS_{among} = \sum_{i=1}^{a}\sum_{j=1}^{n}(\bar{Y}_i - \bar{Y})^2 = n\sum_{i=1}^{a}(\bar{Y}_i - \bar{Y})^2\)</span></p></li>
<li><p><strong>Within Groups (Error)</strong>: <span class="math inline">\(SS_{within} = \sum_{i=1}^{a}\sum_{j=1}^{n}(Y_{ij} - \bar{Y}_i)^2\)</span></p></li>
</ol>
<p>These components are additive: <span class="math inline">\(SS_{total} = SS_{among} + SS_{within}\)</span></p>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="11_01_lecture_powerpoint_files/figure-revealjs/unnamed-chunk-5-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>

<section id="lecture-12-sum-of-squares-example" class="title-slide slide level1 center">
<h1><strong>Lecture 12:</strong> Sum of Squares Example</h1>
<div class="columns">
<div class="column" style="width:60%;">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = phase_shift ~ treatment, data = circ_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.27857 -0.36125  0.03857  0.61147  1.06571 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)    -0.30875    0.24888  -1.241  0.22988   
treatmentEyes  -1.24268    0.36433  -3.411  0.00293 **
treatmentKnees -0.02696    0.36433  -0.074  0.94178   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.7039 on 19 degrees of freedom
Multiple R-squared:  0.4342,    Adjusted R-squared:  0.3746 
F-statistic: 7.289 on 2 and 19 DF,  p-value: 0.004472</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: phase_shift
          Df Sum Sq Mean Sq F value   Pr(&gt;F)   
treatment  2 7.2245  3.6122  7.2894 0.004472 **
Residuals 19 9.4153  0.4955                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</div><div class="column" style="width:40%;">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Key Connection to Regression</strong></p>
</div>
<div class="callout-content">
<ul>
<li><p>This is the same partitioning we saw in regression analysis:</p>
<ul>
<li><span class="math inline">\(SS_{total} = SS_{regression} + SS_{residual}\)</span></li>
</ul></li>
<li><p>Where:</p>
<ul>
<li><span class="math inline">\(SS_{among}\)</span> in ANOVA = <span class="math inline">\(SS_{regression}\)</span> in regression</li>
<li><span class="math inline">\(SS_{within}\)</span> in ANOVA = <span class="math inline">\(SS_{residual}\)</span> in regression</li>
</ul></li>
<li><p>Both measure how much variation is explained by our model vs. unexplained (error).</p></li>
</ul>
</div>
</div>
</div>
</div></div>
</section>

<section id="lecture-12-anova-tables" class="title-slide slide level1 center">
<h1><strong>Lecture 12:</strong> ANOVA Tables</h1>
<div class="columns">
<div class="column" style="width:60%;">
<p>The ANOVA table organizes all computations leading to a test of the null hypothesis of no differences among population means.</p>
<ul>
<li><strong>Source of variation</strong>: What is being tested</li>
<li><strong>Sum of squares</strong>: Measure of total variation for each source</li>
<li><strong>df</strong>: Degrees of freedom for each source</li>
<li><strong>Mean squares</strong>: Sum of squares divided by df</li>
<li><strong>F-ratio</strong>: Ratio of mean squares, used to test significance</li>
<li><strong>P-value</strong>: Probability of observing our results if H₀ is true</li>
</ul>
<p><strong>Example</strong>: For a one-way ANOVA with 3 groups and 4 replicates per group:</p>
<ul>
<li>df for treatments = (a - 1) = 2</li>
<li>df for error = a(n - 1) = 3(4 - 1) = 9</li>
<li>df total = an - 1 = 11</li>
</ul>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = phase_shift ~ treatment, data = circ_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.27857 -0.36125  0.03857  0.61147  1.06571 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)    -0.30875    0.24888  -1.241  0.22988   
treatmentEyes  -1.24268    0.36433  -3.411  0.00293 **
treatmentKnees -0.02696    0.36433  -0.074  0.94178   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.7039 on 19 degrees of freedom
Multiple R-squared:  0.4342,    Adjusted R-squared:  0.3746 
F-statistic: 7.289 on 2 and 19 DF,  p-value: 0.004472</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: phase_shift
          Df Sum Sq Mean Sq F value   Pr(&gt;F)   
treatment  2 7.2245  3.6122  7.2894 0.004472 **
Residuals 19 9.4153  0.4955                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 4
  treatment   Mean    SD     N
  &lt;fct&gt;      &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;
1 Control   -0.309 0.618     8
2 Eyes      -1.55  0.706     7
3 Knees     -0.336 0.791     7</code></pre>
</div>
</div>
</div></div>
</section>

<section id="lecture-12-anova-vs-regression-tables" class="title-slide slide level1 center">
<h1><strong>Lecture 12:</strong> ANOVA vs Regression Tables</h1>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Comparing ANOVA and Regression Tables</strong></p>
</div>
<div class="callout-content">
<p>An ANOVA table compared to a regression table:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Source</th>
<th>df</th>
<th>SS</th>
<th>MS</th>
<th>F</th>
<th>p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Treatment</td>
<td>a-1</td>
<td>SS_treatment</td>
<td>MS_treatment</td>
<td>F</td>
<td>p</td>
</tr>
<tr class="even">
<td>Error</td>
<td>a(n-1)</td>
<td>SS_error</td>
<td>MS_error</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Total</td>
<td>a*n-1</td>
<td>SS_total</td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>Is equivalent to an ANOVA table from a regression model:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Source</th>
<th>df</th>
<th>SS</th>
<th>MS</th>
<th>F</th>
<th>p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Regression</td>
<td>k</td>
<td>SS_regression</td>
<td>MS_regression</td>
<td>F</td>
<td>p</td>
</tr>
<tr class="even">
<td>Error</td>
<td>n-k-1</td>
<td>SS_residual</td>
<td>MS_residual</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Total</td>
<td>n-1</td>
<td>SS_total</td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<ul>
<li>k = number of predictor / dummy variables = a-1</li>
<li>a = treatment groups/levels of factors</li>
</ul>
</div>
</div>
</div>
</section>

<section>
<section id="lecture-12-f-ratio" class="title-slide slide level1 center">
<h1><strong>Lecture 12:</strong> F ratio</h1>

</section>
<div class="columns">
<div class="column" style="width:60%;">
<h3 id="the-f-ratio-is-calculated-as-f-fracms_amongms_error">The F-ratio is calculated as: <span class="math inline">\(F = \frac{MS_{among}}{MS_{error}}\)</span></h3>
<ul>
<li>Under the null hypothesis (all means equal):
<ul>
<li>The F-ratio should be approximately 1<br>
</li>
<li>Larger F-ratios suggest among-group variance exceeds that expected by chance<br>
</li>
</ul></li>
<li>With the circadian rhythm data:
<ul>
<li>F = 7.29 - p = 0.004<br>
</li>
<li>We reject the null hypothesis<br>
</li>
<li>F-ratio follows F-distribution with (a - 1) and (a(n - 1)) df</li>
</ul></li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  Metric                Value
  &lt;chr&gt;                 &lt;dbl&gt;
1 F-observed             7.29
2 F-critical (α = 0.05)  3.52</code></pre>
</div>
</div>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="11_01_lecture_powerpoint_files/figure-revealjs/f_dist-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</div></section>
<section>
<section id="connection-of-a-f-test-to-t-test" class="title-slide slide level1 center">
<h1>Connection of a F test to T Test</h1>

</section>
<div class="columns">
<div class="column" style="width:60%;">
<h3 id="an-anova-with-two-groups-a-2-is-equivalent-to-a-t-test">An ANOVA with two groups (a = 2) is equivalent to a t-test:</h3>
<ul>
<li>Why <span class="math inline">\(F=t^2\)</span>
<ul>
<li>testing the same hypothesis: are means of two groups different?</li>
</ul></li>
<li><em>Understanding the t-statistic</em>
<ul>
<li><p>The t-statistic for comparing two independent groups is: <span class="math inline">\(t = \frac{\bar{X}_1 - \bar{X}_2}{SE_{\text{difference}}}\)</span></p></li>
<li><p>Measuring # standard errors apart the two means are and can be + / -</p></li>
</ul></li>
<li><em>Understanding the F-statistic</em>
<ul>
<li><p>F-statistic in ANOVA is: <span class="math inline">\(F = \frac{\text{Mean Square Between Groups}}{\text{Mean Square Within Groups}} = \frac{MS_B}{MS_W}\)</span></p></li>
<li><p>ratio of variance <em>between</em> groups to variance <em>within</em> groups</p></li>
<li><p>Unlike <span class="math inline">\(t\)</span>, <span class="math inline">\(F\)</span> is always non-negative (it’s a ratio of squared quantities).</p></li>
</ul></li>
</ul>
</div><div class="column" style="width:40%;">
<ul>
<li><em>The Mathematical Connection (squaring remove sign) of t<sup>2</sup></em>
<ul>
<li><strong>Both measure same signal-to-noise ratio</strong>:
<ul>
<li><p>numerators capture difference between groups (signal)</p></li>
<li><p>denominator captures variability within groups (noise)</p></li>
</ul></li>
</ul></li>
<li><strong>When you have two groups</strong>:
<ul>
<li><p><span class="math inline">\(MS_B\)</span> is directly related to <span class="math inline">\((\bar{X}_1 - \bar{X}_2)^2\)</span></p></li>
<li><p><span class="math inline">\(MS_W\)</span> is related to the pooled variance</p></li>
</ul></li>
<li><em>Degrees of Freedom also match up:</em>
<ul>
<li><p>t-test: <span class="math inline">\(df = n_1 + n_2 - 2\)</span></p></li>
<li><p>F-test (two groups): <span class="math inline">\(df_1 = 1\)</span> (numerator), <span class="math inline">\(df_2 = n_1 + n_2 - 2\)</span> (denominator)</p></li>
<li><p>F-distribution with <span class="math inline">\(df_1 = 1\)</span> is the square of a t-distribution with <span class="math inline">\(df_2\)</span></p></li>
</ul></li>
</ul>
</div>
</div></section>
<section>
<section id="connection-of-a-f-test-to-t-test-1" class="title-slide slide level1 center">
<h1>Connection of a F test to T Test</h1>

</section>
<h3 id="why-this-matters">Why This Matters</h3>
<ul>
<li><p>Shows ANOVA is actually a <em>generalization</em> of the t-test</p></li>
<li><p>When <span class="math inline">\(a = 2\)</span>, you get the same result either way</p></li>
<li><p>but ANOVA extends naturally to comparing three or more groups,</p></li>
<li><p>can’t do that directly with a t-test (without running into multiple comparison problems).</p></li>
</ul>
<h3 id="numerical-example">Numerical Example</h3>
<p>Let’s verify this relationship with a simple example in R:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Using circ_data (Control vs Knees groups):
 t-statistic: 0.0741 
 t^2: 0.0055 
 F-statistic: 0.0055 
 Difference (should be ~0): 0 </code></pre>
</div>
</div></section>
<section id="lecture-12-f-ratio-visualization" class="title-slide slide level1 center">
<h1><strong>Lecture 12:</strong> F ratio Visualization</h1>
<div class="columns">
<div class="column" style="width:60%;">
<p>The F-ratio is calculated as: <span class="math inline">\(F = \frac{MS_{among}}{MS_{error}}\)</span> - Under the null hypothesis (all means equal): - F-ratio should be approximately 1 - Larger F-ratios suggests among-group variance exceeds chance - With the circadian rhythm data: F<sub>2,19</sub> = 7.29, p = 0.004<br>
- We reject the null hypothesis<br>
- F-ratio follows an F-distribution with (a - 1) and (a(n - 1)) df</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = phase_shift ~ treatment, data = circ_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.27857 -0.36125  0.03857  0.61147  1.06571 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)    -0.30875    0.24888  -1.241  0.22988   
treatmentEyes  -1.24268    0.36433  -3.411  0.00293 **
treatmentKnees -0.02696    0.36433  -0.074  0.94178   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.7039 on 19 degrees of freedom
Multiple R-squared:  0.4342,    Adjusted R-squared:  0.3746 
F-statistic: 7.289 on 2 and 19 DF,  p-value: 0.004472</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type II tests)

Response: phase_shift
          Sum Sq Df F value   Pr(&gt;F)   
treatment 7.2245  2  7.2894 0.004472 **
Residuals 9.4153 19                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="11_01_lecture_powerpoint_files/figure-revealjs/unnamed-chunk-11-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>

<section>
<section id="lecture-12-variation-explained-r2" class="title-slide slide level1 center">
<h1><strong>Lecture 12:</strong> Variation Explained: R2</h1>

</section>
<div class="columns">
<div class="column" style="width:60%;">
<p>R² summarizes the contribution of group differences to total variation:</p>
<p><span class="math display">\[R^2 = \frac{SS_{among}}{SS_{total}}\]</span></p>
<p>This is interpreted as the “fraction of the variation in Y that is explained by groups.”</p>
<p>For the circadian rhythm data: <span class="math display">\[R^2 = \frac{7.224}{16.639} = 0.43\]</span></p>
<p>43% of the total variation in phase shift is explained by differences in light treatment, with the remaining 57% being unexplained variation.</p>
<section id="connection-to-regression" class="slide level2">
<h2>Connection to Regression</h2>
<p>This is exactly the same calculation as R² in regression: <span class="math display">\[R^2 = \frac{SS_{regression}}{SS_{total}}\]</span></p>
</section>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="11_01_lecture_powerpoint_files/figure-revealjs/unnamed-chunk-12-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</div></section>
<section id="lecture-12-anova-assumptions" class="title-slide slide level1 center">
<h1><strong>Lecture 12:</strong> ANOVA Assumptions</h1>
<ul>
<li>ANOVA has the same assumptions as the two-sample t-test, but applied to all k groups:
<ul>
<li><strong>Random samples</strong> from corresponding populations</li>
<li><strong>Normality</strong>: Y values are normally distributed in each population</li>
<li><strong>Homogeneity of variance</strong>: variance is the same in all populations</li>
<li><strong>Independence</strong>: observations are independent</li>
</ul></li>
<li><strong>Checking assumptions</strong>:
<ul>
<li>Normality: Q-Q plots, histogram of residuals, Shapiro-Wilk test</li>
<li>Homogeneity: plot residuals vs.&nbsp;predicted values or x-values</li>
<li>Independence: examine experimental design</li>
</ul></li>
<li><strong>If assumptions are violated</strong>:
<ul>
<li><p>Transform Y (e.g., log, square root)</p></li>
<li><p>Use robust or non-parametric alternatives</p></li>
<li><p>Use generalized linear models (GLMs)</p></li>
</ul></li>
</ul>
</section>

<section id="lecture-12-anova-diagnostics" class="title-slide slide level1 center">
<h1><strong>Lecture 12:</strong> ANOVA diagnostics</h1>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="11_01_lecture_powerpoint_files/figure-revealjs/ggplot_diag-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="11_01_lecture_powerpoint_files/figure-revealjs/unnamed-chunk-13-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</section>

<section id="a-newer-way-to-check-with-the-performance-library" class="title-slide slide level1 center">
<h1>A newer way to check with the performance library</h1>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="11_01_lecture_powerpoint_files/figure-revealjs/unnamed-chunk-14-1.png" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p><img data-src="diagnostics_2.png" style="width:80.0%"></p>
</section>

<section id="lecture-12-levenes-test" class="title-slide slide level1 center">
<h1><strong>Lecture 12:</strong> Levene’s Test</h1>
<p>Levene’s test of homogeneity of variance</p>
<ul>
<li>Null Hypothesis is that they are homogeneous</li>
<li>So you want a non significant result here</li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
      Df F value Pr(&gt;F)
group  2  0.1586 0.8545
      19               </code></pre>
</div>
</div>
</section>

<section id="lecture-12-shapiro-wilk-test" class="title-slide slide level1 center">
<h1><strong>Lecture 12:</strong> Shapiro-Wilk Test</h1>
<p>Shapiro-Wilk Normality Test Null Hypothesis is that they are normally distributed So you want a non significant result here</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  residuals(circ_model)
W = 0.95893, p-value = 0.468</code></pre>
</div>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Shared Assumptions with Regression</strong></p>
</div>
<div class="callout-content">
<p>ANOVA and regression share virtually identical assumptions because they are both linear models:</p>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Assumption</th>
<th>ANOVA</th>
<th>Regression</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Linearity</td>
<td>Each group has its own mean; effects are additive (no interaction in one-way ANOVA)</td>
<td>Relationship between X and Y is linear</td>
</tr>
<tr class="even">
<td>Normality</td>
<td>Residuals are normal</td>
<td>Residuals are normal</td>
</tr>
<tr class="odd">
<td>Equal variance</td>
<td>Variance is the same across all groups</td>
<td>Variance is the same across all X values</td>
</tr>
<tr class="even">
<td>Independence</td>
<td>Observations are independent</td>
<td>Observations are independent</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>

<section id="lecture-12-anova-post-hoc-testing-overview" class="title-slide slide level1 center">
<h1><strong>Lecture 12:</strong> ANOVA Post-Hoc Testing Overview</h1>
<div class="columns">
<div class="column" style="width:50%;">
<p>When ANOVA rejects H₀, we need to determine which groups differ</p>
<ul>
<li><strong>Unplanned (post hoc) comparisons</strong>:
<ul>
<li>Used when no specific comparisons were planned</li>
<li>Must adjust for multiple testing</li>
<li><em>Common methods</em>: Tukey-Kramer, Bonferroni, Scheffé, Sidak</li>
</ul></li>
<li><strong>Planned (post hoc) comparisons</strong>:
<ul>
<li>Have strong prior justification</li>
<li>Use pooled variance from all groups</li>
<li>Have higher precision than separate t-tests</li>
</ul></li>
<li><strong>Example</strong>: Using Tukey’s HSD to compare all pairs of treatments in the circadian rhythm data.</li>
</ul>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> contrast        estimate    SE df t.ratio p.value
 Control - Eyes     1.243 0.364 19   3.411  0.0079
 Control - Knees    0.027 0.364 19   0.074  0.9970
 Eyes - Knees      -1.216 0.376 19  -3.231  0.0117

P value adjustment: tukey method for comparing a family of 3 estimates </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> treatment emmean    SE df lower.CL upper.CL .group
 Eyes      -1.551 0.266 19    -2.25   -0.855  a    
 Knees     -0.336 0.266 19    -1.03    0.361   b   
 Control   -0.309 0.249 19    -0.96    0.343   b   

Confidence level used: 0.95 
Conf-level adjustment: sidak method for 3 estimates 
P value adjustment: tukey method for comparing a family of 3 estimates 
significance level used: alpha = 0.05 
NOTE: If two or more means share the same grouping symbol,
      then we cannot show them to be different.
      But we also did not show them to be the same. </code></pre>
</div>
</div>
</div></div>
</section>

<section id="lecture-12-post-hoc-testing-results" class="title-slide slide level1 center">
<h1><strong>Lecture 12:</strong> Post-Hoc Testing Results</h1>
<div class="columns">
<div class="column" style="width:50%;">
<p>When ANOVA rejects H₀, we need to determine which groups differ</p>
<ul>
<li><strong>Unplanned (post hoc) comparisons</strong>:
<ul>
<li>Used when no specific comparisons were planned</li>
<li>Must adjust for multiple testing</li>
<li><em>Common methods</em>: Tukey-Kramer, Bonferroni, Scheffé</li>
</ul></li>
<li><strong>Planned (post hoc) comparisons</strong>:
<ul>
<li>Have strong prior justification</li>
<li>Use pooled variance from all groups</li>
<li>Have higher precision than separate t-tests</li>
</ul></li>
<li><strong>Example</strong>: Using Tukey’s HSD to compare all pairs of treatments in the circadian rhythm data.</li>
</ul>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Control" "Eyes"    "Knees"  </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast         estimate    SE df t.ratio p.value
 control vs eyes     1.243 0.364 19   3.411  0.0029
 control vs knees    0.027 0.364 19   0.074  0.9418</code></pre>
</div>
</div>
</div></div>
</section>

<section id="comparison-of-post-hoc-tests" class="title-slide slide level1 center">
<h1>Comparison of Post-Hoc Tests</h1>
<div class="columns">
<div class="column" style="width:60%;">
<p>The Main Post-Hoc Tests</p>
<ul>
<li>Tukey-Kramer (HSD - Honestly Significant Difference)
<ul>
<li>Compares all possible pairs of group means</li>
<li>Controls family-wise error rate when making multiple comparisons</li>
<li>Most powerful when you want to compare ALL pairwise combinations</li>
</ul></li>
<li>Bonferroni
<ul>
<li>Adjusts α level by dividing by the number of comparisons (e.g., α/k)</li>
<li>Very conservative - reduces power to detect real differences</li>
<li>Best choice for: small number of planned comparisons (not exploratory analyses of all pairs)</li>
</ul></li>
<li>Sidak
<ul>
<li>Similar to Bonferroni but slightly less conservative</li>
<li>Uses multiplicative adjustment: 1-(1-α)^(1/k)</li>
<li>Best choice for: similar situations to Bonferroni, gives slightly more power</li>
</ul></li>
<li>Dunnett’s Test
<ul>
<li>Specifically for comparing treatment groups to control</li>
<li>More powerful than other tests</li>
</ul></li>
</ul>
<p>The key tradeoff is between power (ability to detect real differences) and Type I error control (avoiding false positives). More conservative tests = better error control but less power.</p>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 4
  contrast          Tukey Bonferroni   Sidak
  &lt;chr&gt;             &lt;dbl&gt;      &lt;dbl&gt;   &lt;dbl&gt;
1 Control - Eyes  0.00787    0.00879 0.00877
2 Eyes - Knees    0.0117     0.0132  0.0131 
3 Control - Knees 0.997      1       1.000  </code></pre>
</div>
</div>
</div></div>
</section>

<section id="lecture-12-post-hoc-visualization" class="title-slide slide level1 center">
<h1><strong>Lecture 12:</strong> Post-Hoc Visualization</h1>
<div class="columns">
<div class="column" style="width:50%;">
<p>When ANOVA rejects H₀, we need to determine which groups differ.</p>
<ul>
<li><strong>Unplanned (post hoc) comparisons</strong>:
<ul>
<li>Used when no specific comparisons were planned</li>
<li>Must adjust for multiple testing</li>
<li><em>Common methods</em>: Tukey-Kramer, Bonferroni, Scheffé</li>
</ul></li>
<li><strong>Planned (post hoc) comparisons</strong>:
<ul>
<li>Have strong prior justification</li>
<li>Use pooled variance from all groups</li>
<li>Have higher precision than separate t-tests</li>
</ul></li>
<li><strong>Example</strong>: Using Tukey’s HSD to compare all pairs of treatments in the circadian rhythm data.</li>
</ul>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="11_01_lecture_powerpoint_files/figure-revealjs/unnamed-chunk-20-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>

<section id="lecture-12-significance-groups-plot" class="title-slide slide level1 center">
<h1><strong>Lecture 12:</strong> Significance Groups Plot</h1>
<div class="columns">
<div class="column" style="width:60%;">
<p>When ANOVA rejects H₀, we need to determine which groups differ.</p>
<ul>
<li><strong>Unplanned (post hoc) comparisons</strong>:
<ul>
<li>Used when no specific comparisons were planned</li>
<li>Must adjust for multiple testing</li>
<li><em>Common methods</em>: Tukey-Kramer, Bonferroni, Scheffé</li>
</ul></li>
<li><strong>Planned (post hoc) comparisons</strong>:
<ul>
<li>Have strong prior justification</li>
<li>Use pooled variance from all groups</li>
<li>Have higher precision than separate t-tests</li>
</ul></li>
<li><strong>Example</strong>: Using Tukey’s HSD to compare all pairs of treatments in the circadian rhythm data.</li>
</ul>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="11_01_lecture_powerpoint_files/figure-revealjs/unnamed-chunk-21-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>

<section id="lecture-12-reporting-anova-results" class="title-slide slide level1 center">
<h1><strong>Lecture 12:</strong> Reporting ANOVA Results</h1>
<p><strong>Formal scientific writing example:</strong></p>
<p>“The effect of light treatment on circadian rhythm phase shift was analyzed using a one-way ANOVA. There was a significant effect of treatment on phase shift (F(2, 19) = 7.29, p = 0.004, η² = 0.43). Post-hoc comparisons using Tukey’s HSD test indicated that the mean phase shift for the Eyes treatment (M = -1.55 h, SD = 0.71) was significantly different from both the Control treatment (M = -0.31 h, SD = 0.62) and the Knees treatment (M = -0.34 h, SD = 0.79). However, the Control and Knees treatments did not significantly differ from each other. These results suggest that light exposure to the eyes, but not to the knees, impacts circadian rhythm phase shifts.”</p>
</section>

<section>
<section id="lecture-12-anova-summary" class="title-slide slide level1 center">
<h1><strong>Lecture 12:</strong> ANOVA Summary</h1>

</section>
<h3 id="key-anova-principles">Key ANOVA Principles</h3>
<ol type="1">
<li><strong>Purpose</strong>: ANOVA (Analysis of Variance) compares means across multiple groups simultaneously</li>
<li><strong>Connection to Regression</strong>:
<ul>
<li>Both are special cases of the General Linear Model</li>
<li>ANOVA with categorical predictors = Regression with dummy variables</li>
<li>Both partition variance into explained and unexplained components</li>
</ul></li>
<li><strong>The Analysis of Variance</strong>:
<ul>
<li>Partitions total variation into components</li>
<li>Tests whether differences among groups exceed what would be expected by chance</li>
<li>Uses F-tests to compare variance between groups to variance within groups</li>
</ul></li>
<li><strong>Sum of Squares Partitioning</strong>:
<ul>
<li>SS(Total) = SS(Between Groups) + SS(Within Groups)</li>
<li>Same as SS(Total) = SS(Regression) + SS(Error) in regression</li>
</ul></li>
<li><strong>Fixed vs.&nbsp;Random Effects</strong>:
<ul>
<li>Fixed effects: specific groups of interest (most common)</li>
<li>Random effects: sampling from a larger population</li>
</ul></li>
</ol></section>
<section>
<section id="overview-of-non-parametric-tests" class="title-slide slide level1 center">
<h1>Overview of Non-Parametric Tests</h1>

</section>
<div class="columns">
<div class="column" style="width:60%;">
<h3 id="common-non-parametric-alternatives-to-anova">Common Non-Parametric Alternatives to ANOVA</h3>
<p><strong>Non-parametric tests make fewer assumptions about the data distribution</strong></p>
<ol type="1">
<li><strong>Kruskal-Wallis Test</strong>
<ul>
<li>Non-parametric alternative to one-way ANOVA</li>
<li>Tests for differences in median ranks</li>
<li>Works with ordinal or continuous data</li>
<li>Assumptions: Independent observations, similar distribution shapes</li>
</ul></li>
<li><strong>Mood’s Median Test</strong> not covered here
<ul>
<li>Tests whether medians differ across groups</li>
<li>More robust but less powerful than Kruskal-Wallis</li>
<li>Good for highly skewed data</li>
</ul></li>
</ol>
</div><div class="column" style="width:40%;">
<h3 id="when-to-use-non-parametric-tests">When to Use Non-Parametric Tests</h3>
<p><strong>Consider non-parametric tests when:</strong></p>
<ul>
<li>Sample sizes are small</li>
<li>Data are heavily skewed</li>
<li>Outliers are present and legitimate</li>
<li>Variances are very unequal</li>
<li>Data are ordinal (ranked)</li>
<li>Assumptions checks clearly fail</li>
</ul>
<p><strong>Trade-offs:</strong></p>
<ul>
<li><label><input type="checkbox" checked="">Fewer assumptions</label></li>
<li><label><input type="checkbox" checked="">More robust to outliers</label></li>
<li>✗ Less statistical power</li>
<li>✗ Test medians/ranks, not means</li>
</ul>
</div>
</div></section>
<section>
<section id="kruskal-wallis-test-overview" class="title-slide slide level1 center">
<h1>Kruskal-Wallis Test: Overview</h1>

</section>
<div class="columns">
<div class="column" style="width:60%;">
<h3 id="the-kruskal-wallis-h-test">The Kruskal-Wallis H Test</h3>
<ul>
<li><strong>Most common non-parametric alternative to one-way ANOVA</strong>
<ul>
<li><strong>What it does:</strong>
<ul>
<li>Ranks all observations from smallest to largest</li>
<li>Compares the sum of ranks between groups</li>
<li>Tests if groups come from the same distribution</li>
</ul></li>
<li><strong>Hypotheses:</strong>
<ul>
<li><strong>H₀</strong>: All groups have the same distribution (same median)</li>
<li><strong>H₁</strong>: At least one group has a different distribution</li>
</ul></li>
<li><strong>Test statistic (H):</strong> <span class="math inline">\(H = \frac{12}{N(N+1)} \sum_{i=1}^{k} n_i (\bar{R}_i - \bar{R})^2 - 3(N+1)\)</span></li>
<li>Where:
<ul>
<li>N = total sample size</li>
<li>k = number of groups</li>
<li><span class="math inline">\(\bar{R}_i\)</span> = mean rank for group i</li>
<li><span class="math inline">\(\bar{R}\)</span>= overall mean rank = (N+1)/2</li>
<li>nᵢ = sample size for group i</li>
<li>constant 12 comes from the variance of ranks in a uniform distribution</li>
</ul></li>
<li><strong>Distribution:</strong> Approximated by χ² with (k-1) degrees of freedom</li>
</ul></li>
</ul>
</div><div class="column" style="width:40%;">
<h3 id="assumptions-of-kruskal-wallis">Assumptions of Kruskal-Wallis</h3>
<p><strong>Much more relaxed than parametric ANOVA:</strong></p>
<ul>
<li><strong>Independence</strong>: Observations must be independent
<ul>
<li>Same as parametric ANOVA</li>
<li>Still critical!</li>
</ul></li>
<li><strong>Similar distribution shapes</strong>: Groups should have similar distribution shapes (same spread/variance)
<ul>
<li>If violated, interprets as differences in distributions generally</li>
<li>Not just medians</li>
</ul></li>
<li><strong>Ordinal or continuous data</strong>: Response variable should be at least ordinal</li>
<li><strong>What’s NOT assumed:</strong>
<ul>
<li>✗ Normal distribution</li>
<li>✗ Equal variances (though helps interpretation)</li>
<li>✗ Specific distribution shape</li>
</ul></li>
</ul>
</div>
</div></section>
<section>
<section id="demonstrating-assumption-violations" class="title-slide slide level1 center">
<h1>Demonstrating Assumption Violations</h1>

</section>
<div class="columns">
<div class="column" style="width:60%;">
<h3 id="creating-data-that-violates-assumptions">Creating Data That Violates Assumptions</h3>
<p><strong>Let’s create a modified dataset with clear violations:</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a></a><span class="co"># Create data with outliers and skewness</span></span>
<span id="cb17-2"><a></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb17-3"><a></a>violated_circ_df <span class="ot">&lt;-</span> circ_data <span class="sc">%&gt;%</span></span>
<span id="cb17-4"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb17-5"><a></a>    <span class="at">phase_shift_violated =</span> <span class="fu">case_when</span>(</span>
<span id="cb17-6"><a></a>      treatment <span class="sc">==</span> <span class="st">"Control"</span> <span class="sc">~</span> phase_shift,</span>
<span id="cb17-7"><a></a>      treatment <span class="sc">==</span> <span class="st">"Knees"</span> <span class="sc">~</span> phase_shift <span class="sc">*</span> <span class="fl">3.25</span>,</span>
<span id="cb17-8"><a></a>      treatment <span class="sc">==</span> <span class="st">"Eyes"</span> <span class="sc">~</span> {</span>
<span id="cb17-9"><a></a>        n <span class="ot">&lt;-</span> <span class="fu">length</span>(phase_shift)</span>
<span id="cb17-10"><a></a>        <span class="fu">c</span>(phase_shift[<span class="dv">1</span><span class="sc">:</span>(n<span class="dv">-2</span>)], phase_shift[(n<span class="dv">-1</span>)<span class="sc">:</span>n] <span class="sc">-</span> <span class="dv">7</span>)</span>
<span id="cb17-11"><a></a>      }</span>
<span id="cb17-12"><a></a>    )</span>
<span id="cb17-13"><a></a>  )</span>
<span id="cb17-14"><a></a></span>
<span id="cb17-15"><a></a><span class="co"># Fit model with violated assumptions</span></span>
<span id="cb17-16"><a></a>violated_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(phase_shift_violated <span class="sc">~</span> treatment, </span>
<span id="cb17-17"><a></a>                     <span class="at">data =</span> violated_circ_df)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>What we changed:</strong></p>
<ul>
<li>- Increased variance in Knees group</li>
<li>- Added extreme outliers to Eyes group</li>
<li>- Created unequal variances and non-normality</li>
</ul>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="11_01_lecture_powerpoint_files/figure-revealjs/violated_data_plot-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</div></section>
<section>
<section id="checking-violated-data-assumptions" class="title-slide slide level1 center">
<h1>Checking Violated Data Assumptions</h1>

</section>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="normality-test-on-violated-data">Normality Test on Violated Data</h3>
<p><strong>Clear violation:</strong> p &lt; 0.05, points deviate from line</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  resid(violated_model)
W = 0.89473, p-value = 0.02335</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="11_01_lecture_powerpoint_files/figure-revealjs/violated_normality_plot-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<h3 id="variance-test-on-violated-data">Variance Test on Violated Data</h3>
<ul>
<li>ok having issues making it not homogeoeous</li>
<li><strong>Clear violation:</strong> p &lt; 0.05, unequal variances evident</li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
      Df F value Pr(&gt;F)
group  2  1.5618 0.2355
      19               </code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="11_01_lecture_powerpoint_files/figure-revealjs/violated_variance_plot-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</div></section>
<section>
<section id="performing-the-kruskal-wallis-test" class="title-slide slide level1 center">
<h1>Performing the Kruskal-Wallis Test</h1>

</section>
<div class="columns">
<div class="column" style="width:60%;">
<h3 id="running-kruskal-wallis-on-original-data">Running Kruskal-Wallis on Original Data</h3>
<p><strong>Even though assumptions are met, let’s compare results:</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a></a><span class="co"># Kruskal-Wallis test on original data</span></span>
<span id="cb20-2"><a></a>kruskal_original_result <span class="ot">&lt;-</span> <span class="fu">kruskal.test</span>(</span>
<span id="cb20-3"><a></a>  phase_shift <span class="sc">~</span> treatment, </span>
<span id="cb20-4"><a></a>  <span class="at">data =</span> circ_data)</span>
<span id="cb20-5"><a></a><span class="co"># Display results</span></span>
<span id="cb20-6"><a></a>kruskal_original_result</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  phase_shift by treatment
Kruskal-Wallis chi-squared = 9.4231, df = 2, p-value = 0.008991</code></pre>
</div>
</div>
<p><strong>Interpretation:</strong> - H = test statistic (chi-squared approximation) - df = degrees of freedom (k - 1 = 3 - 1 = 2) - p-value = 0.0135 (significant at α = 0.05) - Conclusion: At least one group differs from others</p>
<p><strong>Compare to parametric ANOVA:</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: phase_shift
          Df Sum Sq Mean Sq F value   Pr(&gt;F)   
treatment  2 7.2245  3.6122  7.2894 0.004472 **
Residuals 19 9.4153  0.4955                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</div><div class="column" style="width:40%;">
<h3 id="rank-visualization">Rank Visualization</h3>
<p><strong>How Kruskal-Wallis works:</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="11_01_lecture_powerpoint_files/figure-revealjs/kruskal_ranks_plot-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
<p><strong>Rank Sums:</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 4
  treatment mean_rank sum_rank     n
  &lt;fct&gt;         &lt;dbl&gt;    &lt;dbl&gt; &lt;int&gt;
1 Control       14.6       117     8
2 Eyes           5.29       37     7
3 Knees         14.1        99     7</code></pre>
</div>
</div>
</div>
</div></section>
<section>
<section id="kruskal-wallis-on-violated-data" class="title-slide slide level1 center">
<h1>Kruskal-Wallis on Violated Data</h1>

</section>
<div class="columns">
<div class="column" style="width:60%;">
<h3 id="non-parametric-test-handles-violations">Non-Parametric Test Handles Violations</h3>
<p><strong>Running Kruskal-Wallis on data with assumption violations:</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a></a><span class="co"># Kruskal-Wallis test on violated data</span></span>
<span id="cb24-2"><a></a>kruskal_violated_result <span class="ot">&lt;-</span> <span class="fu">kruskal.test</span>(</span>
<span id="cb24-3"><a></a>  phase_shift_violated <span class="sc">~</span> treatment, </span>
<span id="cb24-4"><a></a>  <span class="at">data =</span> violated_circ_df)</span>
<span id="cb24-5"><a></a>kruskal_violated_result</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  phase_shift_violated by treatment
Kruskal-Wallis chi-squared = 6.8453, df = 2, p-value = 0.03263</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: phase_shift_violated
          Df  Sum Sq Mean Sq F value Pr(&gt;F)  
treatment  2  41.806 20.9029  2.8361 0.0836 .
Residuals 19 140.037  7.3704                 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<ul>
<li><strong>Key observations:</strong>
<ul>
<li>Both tests still detect differences</li>
<li>Kruskal-Wallis more robust to violations</li>
<li>Parametric test may give misleading results when assumptions violated</li>
<li>Non-parametric test maintains validity</li>
</ul></li>
</ul>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="11_01_lecture_powerpoint_files/figure-revealjs/violated_comparison_plot-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><strong>Why Kruskal-Wallis is robust:</strong>
<ul>
<li>- Uses ranks instead of raw values</li>
<li>- Outliers affect ranks minimally</li>
<li>- Unequal variances less problematic</li>
<li>- No distribution assumptions needed</li>
</ul></li>
</ul>
</div>
</div></section>
<section>
<section id="post-hoc-tests-for-kruskal-wallis" class="title-slide slide level1 center">
<h1>Post-Hoc Tests for Kruskal-Wallis</h1>

</section>
<div class="columns">
<div class="column" style="width:60%;">
<h3 id="pairwise-comparisons-after-significant-kruskal-wallis">Pairwise Comparisons After Significant Kruskal-Wallis</h3>
<p><strong>Just like ANOVA, we need post-hoc tests to identify which groups differ:</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Pairwise comparisons using Wilcoxon rank sum exact test 

data:  nonparam_circ_df$phase_shift and nonparam_circ_df$treatment 

      Control Eyes  
Eyes  0.0037  -     
Knees 1.0000  0.0787

P value adjustment method: bonferroni </code></pre>
</div>
</div>
<ul>
<li><strong>Interpretation of p-values:</strong>
<ul>
<li>- Control vs Eyes: p = 0.024 (significant)</li>
<li>- Control vs Knees: p = 1.000 (not significant)</li>
<li>- Eyes vs Knees: p = 0.078 (not significant)</li>
</ul></li>
<li><strong>Common adjustment methods:</strong>
<ul>
<li>- <code>"bonferroni"</code>: Most conservative</li>
<li>- <code>"holm"</code>: Less conservative than Bonferroni</li>
<li>- <code>"BH"</code>: Benjamini-Hochberg (controls false discovery rate)</li>
<li>- <code>"none"</code>: No adjustment (not recommended)</li>
</ul></li>
</ul>
</div><div class="column" style="width:40%;">
<h3 id="post-hoc-for-violated-data">Post-Hoc for Violated Data</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a></a><span class="co"># Post-hoc tests on violated data</span></span>
<span id="cb28-2"><a></a>pairwise_violated_result <span class="ot">&lt;-</span> <span class="fu">pairwise.wilcox.test</span>(</span>
<span id="cb28-3"><a></a>  <span class="at">x =</span> violated_circ_df<span class="sc">$</span>phase_shift_violated,</span>
<span id="cb28-4"><a></a>  <span class="at">g =</span> violated_circ_df<span class="sc">$</span>treatment,</span>
<span id="cb28-5"><a></a>  <span class="at">p.adjust.method =</span> <span class="st">"bonferroni"</span></span>
<span id="cb28-6"><a></a>)</span>
<span id="cb28-7"><a></a></span>
<span id="cb28-8"><a></a>pairwise_violated_result</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pairwise comparisons using Wilcoxon rank sum exact test 

data:  violated_circ_df$phase_shift_violated and violated_circ_df$treatment 

      Control Eyes  
Eyes  0.0037  -     
Knees 1.0000  1.0000

P value adjustment method: bonferroni </code></pre>
</div>
</div>
<p><strong>Comparison table:</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Original Data Pairwise p-values:
   Control vs Eyes:  0.024 *
   Control vs Knees: 1.000
   Eyes vs Knees:    0.078</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Violated Data Pairwise p-values:
   Control vs Eyes:  0.015 *
   Control vs Knees: 1.000
   Eyes vs Knees:    0.015 *</code></pre>
</div>
</div>
</div>
</div></section>
<section>
<section id="dunns-test-alternative-post-hoc" class="title-slide slide level1 center">
<h1>Dunn’s Test: Alternative Post-Hoc</h1>

</section>
<div class="columns">
<div class="column" style="width:60%;">
<h3 id="dunns-test-for-multiple-comparisons">Dunn’s Test for Multiple Comparisons</h3>
<p><strong>Dunn’s test is specifically designed for Kruskal-Wallis post-hoc comparisons:</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a></a><span class="co"># Dunn's test on original data</span></span>
<span id="cb32-2"><a></a>dunn_original_result <span class="ot">&lt;-</span> <span class="fu">dunnTest</span>(</span>
<span id="cb32-3"><a></a>  phase_shift <span class="sc">~</span> treatment,</span>
<span id="cb32-4"><a></a>  <span class="at">data =</span> circ_data,</span>
<span id="cb32-5"><a></a>  <span class="at">method =</span> <span class="st">"bonferroni"</span>)</span>
<span id="cb32-6"><a></a>dunn_original_result</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       Comparison          Z     P.unadj      P.adj
1  Control - Eyes  2.7789287 0.005453849 0.01636155
2 Control - Knees  0.1434629 0.885924641 1.00000000
3    Eyes - Knees -2.5517789 0.010717452 0.03215236</code></pre>
</div>
</div>
<ul>
<li><strong>Advantages of Dunn’s test:</strong>
<ul>
<li>Designed specifically for Kruskal-Wallis</li>
<li>Provides Z-statistics in addition to p-values</li>
<li>Multiple adjustment methods available</li>
<li>More appropriate than multiple Wilcoxon tests</li>
</ul></li>
<li>Z-statistic is a standardized test statistic that tells you how many standard deviations an observation or difference is from the expected value (usually zero, meaning “no difference”).</li>
</ul>
</div><div class="column" style="width:40%;">
<h3 id="dunns-test-on-violated-data">Dunn’s Test on Violated Data</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a></a><span class="co"># Dunn's test on violated data</span></span>
<span id="cb34-2"><a></a>dunn_violated_result <span class="ot">&lt;-</span> <span class="fu">dunnTest</span>(</span>
<span id="cb34-3"><a></a>  phase_shift_violated <span class="sc">~</span> treatment,</span>
<span id="cb34-4"><a></a>  <span class="at">data =</span> violated_circ_df,</span>
<span id="cb34-5"><a></a>  <span class="at">method =</span> <span class="st">"bonferroni"</span></span>
<span id="cb34-6"><a></a>)</span>
<span id="cb34-7"><a></a></span>
<span id="cb34-8"><a></a>dunn_violated_result</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       Comparison         Z     P.unadj      P.adj
1  Control - Eyes  2.614212 0.008943349 0.02683005
2 Control - Knees  1.126449 0.259975463 0.77992639
3    Eyes - Knees -1.440520 0.149720243 0.44916073</code></pre>
</div>
</div>
<ul>
<li><strong>Interpreting Z-statistics:</strong>
<ul>
<li><p>- Large |Z| values indicate bigger differences</p></li>
<li><p>- Z &gt; 1.96 approximately equivalent to p &lt; 0.05</p></li>
<li><p>- Sign indicates direction of difference</p></li>
</ul></li>
</ul>
</div>
</div></section>
<section>
<section id="reporting-non-parametric-results" class="title-slide slide level1 center">
<h1>Reporting Non-Parametric Results</h1>

</section>
<h3 id="how-to-report-kruskal-wallis-results">How to Report Kruskal-Wallis Results</h3>
<p><strong>Essential elements to include:</strong></p>
<ol type="1">
<li>Test name and purpose</li>
<li>Sample sizes per group</li>
<li>Medians and IQRs (not means and SDs!)</li>
<li>Test statistic (H) and degrees of freedom, P-value, Effect size</li>
<li>Post-hoc test results</li>
<li>Conclusion</li>
</ol>
<p><strong>Example write-up:</strong> “A Kruskal-Wallis test was conducted to compare the effect of light treatment on circadian rhythm phase shift across three groups: Control (n = 8), Knees (n = 7), and Eyes (n = 7). Median phase shifts were -0.48 hours (IQR = 0.84) for Control, -0.29 hours (IQR = 1.04) for Knees, and -1.48 hours (IQR = 0.66) for Eyes. The test revealed a statistically significant difference in phase shift between the groups, H(2) = 8.66, p = 0.013, ε² = 0.37. Post-hoc pairwise comparisons using Dunn’s test with Bonferroni correction indicated that the Eyes treatment differed significantly from Control (p = 0.024), but no other pairwise differences were significant. These results suggest that light exposure to the eyes has a different effect on circadian rhythm than light to other body parts.”</p></section>
<section id="apa-style-reporting" class="title-slide slide level1 center">
<h1>APA Style Reporting</h1>
<p><strong>In-text citation format:</strong></p>
<blockquote>
<p>The Kruskal-Wallis test revealed significant differences between treatment groups, H(2) = 8.66, p = .013.</p>
</blockquote>
<p><strong>Table format:</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Table 1. Descriptive Statistics for Phase Shift by Treatment

 

Note. IQR = interquartile range.
 Kruskal-Wallis H(2) = 8.66, p = .013</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 6
  treatment     n Median   IQR   Min   Max
  &lt;fct&gt;     &lt;int&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 Control       8 -0.485 0.89  -1.27  0.53
2 Eyes          7 -1.48  0.675 -2.83 -0.78
3 Knees         7 -0.29  0.93  -1.61  0.73</code></pre>
</div>
</div>
<p><strong>Common mistakes to avoid:</strong></p>
<ul>
<li>✗ Reporting means instead of medians &amp; Using SD instead of IQR</li>
<li>✗ Not mentioning it’s a non-parametric test</li>
<li>✗ Not justifying why non-parametric test used</li>
</ul>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/your-site-url\.github\.io");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>